### PR TITLE
Fix tree rendering with filters and trails

### LINKED ISSUE #7786: No operations shown on first node that has child nodes in tree view when searching
### Affected version(s)

4.13.x, 5.3.x+

### Description

If you use the search in the _Articles_ tree, the first article in the results will never have any operations.

### Reproduction

1. Log into the back end of the Contao Online Demo.
2. Go to _Articles_.
3. In the _Search_ field leave the default at _Article alias_.
4. Search for `elements`.

This will show the following result:

\
The _Content Elements_ article (which has the alias `content-elements` and thus is part of the search result) does not have any operations.

### PR DESCRIPTION
**Pull request by aschempp**
This is the actually correct fix for https://github.com/contao/contao/pull/7480 (and https://github.com/contao/contao/issues/7366). I have a client which has a `list.sorting.filter` applied by default on the tree, which caused incorrect results, so I had to find a fix.

Trying to explain how it works (copy from whiteboard on my wall 😅):
 - `$dc->root` contains the topmost allowed IDs (`eliminateNestedPages`)
 - `$dc->visibleRootTrails` contains IDs above `$dc->root`
 - `$dc->rootChildren` contains IDs below `$dc->root`
 - when IDs are updated from search results, `$dc->rootChildren` will only contain IDs between `$dc->root` and nested IDs, so we only generate the tree from tomost root until last found node
 - also on search results, `$dc->visibleRootTrails` will contain all IDs that are _between_ nested root nodes, causing their operations not to be rendered (because they are considered root trails).

Initially (`DC_Table::initRoots()`), the arrays will contain the user permissions. `DC_Table::treeView()` will then update `$dc->root` from search results, including the already given permissions. 

Since the original PR was for 4.13, and my client uses 4.13, I had to initially find a fix for their case. This obviously needs to be forward-ported to 5.3 as well, but I guess the same code will run there just fine.

### Admin searching for _slider_, which matches a subpage
Notice how the page `Content elements` does not have operations, because it did not match the search results

Bildschirmfoto 2025-01-14 um 15 20 46

### Admin searching for _elements_, which matches a parent and subpages
Notice how the page `Content elements` now does have operations, because it **did** match the search results, but the _slider_ page is hidden because it does not match

Bildschirmfoto 2025-01-14 um 15 21 02

### Admin searching for _detail_, which matches two pages in separate parent nodes
Only the acutal matches have operations

Bildschirmfoto 2025-01-14 um 15 21 35

### Admin searching for _detail_, while having breadcrumb applied
The _detail_ page of news does not show up because of the breadcrumb menu

Bildschirmfoto 2025-01-14 um 15 25 04

### Fancy search for _news|detail_ (regex) 
Operations are now available on the `News` and `News Detail`, as well as `Event Detail`, but not on `Events`!

Bildschirmfoto 2025-01-14 um 15 27 17

### CODE REVIEW

File: core-bundle/src/Resources/contao/classes/Backend.php [hunk 1]
```diff
@@ -1044,7 +1045,7 @@ public static function addPageIcon($row, $label, ?DataContainer $dc=null, $image
 		}
 
 		// Add the breadcrumb link if you have access to that page
-		if (!$isVisibleRootTrailPage)
+		if ($objUser->hasAccess($row['id'], 'pagemounts'))
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/classes/Backend.php:1048]: Currently, you cannot click on a root trail page in the page tree to create a breadcrumbs from there. However, you can click on the same page if the breadcrumb has previously been set to a nested subpage of it. This change unifies that, I think it makes sense to allow the breadcrumb for any nested level, since I can see this anyways.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -6295,8 +6290,7 @@ protected function formatGroupHeader($field, $value, $mode, $row)
 	 */
 	protected function initRoots()
 	{
-		$table = $this->strTable;
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/drivers/DC_Table.php:6298]: removed `$table` here (and it's usage in the `elseif`below), because it is re-defined in the `if ($this->treeMode)` condition below. Technically would work, but I found the code confusing like this.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php [hunk 3]
```diff
@@ -6335,38 +6329,53 @@ protected function initRoots()
...
+				}
+
+				$this->rootChildren = array_intersect($this->rootChildren, array_merge(...$parents));
+				$this->visibleRootTrails = array_merge($this->visibleRootTrails, array_diff($this->rootChildren, $root));
+			}
 		}
 
-		// Fetch all children of the root
-		if ($this->treeView)
+		// $this->root might not have a correct order here, let's make sure it's ordered by sorting
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/drivers/DC_Table.php:6375]: this now only applies to non-tree modes. In a parent view, we also want to ensure the correct order. But treeView already renders the top nodes from sorted IDs, if `showRootTrail` is enabled (see around line 3783). If `showRootTrail` is not enabled, the root sorting does not have any useful effect anyways, because of the mixing of levels.

**Comment by fritzmg** [comment]
I can confirm that this fixes #7786.

I do not have a reproduction for #7366 unfortunately, so could not test this specifically.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Is this fixed in Contao 5.3 already or does it only affect Contao 4.13?

**Comment by fritzmg** [comment]
It affects 4.13 and 5.3+ and it is not fixed in 5.3. A separate PR for 5.3 is needed.

**Comment by aschempp** [comment]
On a side note, if you filter for pages now, you will not get operations on the filters that do not match the results.

Bildschirmfoto 2025-01-17 um 16 07 29

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
