### PR TITLE
Skip permissions checks for child records

### LINKED ISSUE #7101: Child records are not copied because of permissions
### Affected version(s)

5.3.*

### Description

I could reproduce the problem with forms not having any form fields copied but it's probably also affecting other areas of Contao.

How to reproduce in the Contao Demo:

1. Edit the user group `Editors` as follows:
    a.  Give the users access to the `Forms`
    b. Allow them the form `Search`
    c. Give them the permission to create forms
    d. Add all fields of `tl_form` and `tl_form_field` to the list of fields allowed to edit
2. Switch to the user `j.wilson`
3. Duplicate the form `Search`
4. Save
5. This new form won't have any form fields copied 🐞 

The reason for this is that the newly created form is only added to the permissions in the `oncopy_callback` of `tl_form`. However, [this callback is executed **after** Contao checked for permissions](https://github.com/contao/contao/blob/5.3/core-bundle/contao/drivers/DC_Table.php#L1053-L1070). Which means that when Contao checks for [`CreateAction` in `copyChildren()`](https://github.com/contao/contao/blob/5.3/core-bundle/contao/drivers/DC_Table.php#L1221), the newly created form is not part of the permissions yet.

No idea how to fix that 🤯

### PR DESCRIPTION
**Pull request by aschempp**
This restores the permission handling we had in all previous Contao versions. After discussing with @Toflar, this is the only viable solution to fix our permission issues. Here are two examples that are imho impossible to fix otherwise. They are not a technical issue, but a logical one.

1. If you duplicate a page, its articles will be duplicated as well as its content elements. If you do not have access to some elements, the whole page and articles are duplicated, **but "random" content elements will be missing**.

2. even worse, when deleting a page, DC_Table tries to delete all child records and create an undo record for them. The ones that the user does not have access will not be deleted, **and will not be added to the undo record**. They are however still removed by our reviseTable, and will therefore be lost without the option to undo.

In the same sense we could discuss to adjust the `undo` method instead of what we discussed in https://github.com/contao/contao/pull/7056

FYI @Toflar and me discussed that the same handling will not be possible in a regular REST/CRUD API. It would require special APIs for that, which can always be added if necessary.

- Fixes https://github.com/contao/contao/issues/7101
- Probably also makes https://github.com/contao/contao/pull/7102 obsolete but correctly checking the IDs/updating the cache might still be correct.

### CODE REVIEW

**Comment by leofeyer** [comment]
I ran a quick test to see how Unix behaves in such a case:

```
drwxr-xr-x user:usergroup test
-rw-r----- user:usergroup test/a.txt
-rw-r----- root:root      test/b.txt
```

```bash
$ cp -R test test1
cp: cannot open 'test/b.txt' for reading: Permission denied
```

The new folder `test1` only contains `a.txt` but not `b.txt`.

```bash
$ rm -r test         
rm: remove write-protected regular file 'test/b.txt'?
```

If I confirm this, the folder is deleted.

---

So for us this means:

> If you duplicate a page, its articles will be duplicated as well as its content elements. If you do not have access to some elements, the whole page and articles are duplicated, but "random" content elements will be missing.

This seems logical to me and is consistent with the result of the test above. If you were to duplicate all elements individually, you would not be able to duplicate these elements either.

> will not be deleted, and will not be added to the undo record. They are however still removed by our reviseTable, and will therefore be lost without the option to undo.

This is a bug. Since the user is allowed to delete the parent record, all child records should be deleted and added to the undo record, too. Even if the user does not have access to individual child records.

**Comment by fritzmg** [comment]
This Unix analogy does not apply to Contao completely, as (currently at least) you still have read permissions on content elements that you do not have access to (through the ℹ️ button). In the current state the analogy would be more like this:

```
drwxr-xr-x user:usergroup test
-rw-r--r-- user:usergroup test/a.txt
-rw-r--r-- root:root      test/b.txt
```

And in this case all the files can be copied. Only their _contents_ cannot be changed.

**Comment by leofeyer** [comment]
That is true. 🤔

**Comment by aschempp** [comment]
> And in this case all the files can be copied. Only their _contents_ cannot be changed.

This would equal to what this PR applies. You cannot edit a content element, but it will be copied when you copy the whole article or page.

This opens possibilities to theoretical manipulation, for example you're not allowed to create a module on a page, but you can copy the article from another page including this module and adjust everything around. But I personally would be fine with this limitation, which would apply to Unix filesystem as well.

**Comment by Toflar** [comment]
Also, this has always been like that in Contao 4 and pre Symfony versions as well :)

**Review by fritzmg — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add the same logic for undo operations as well and then merge this pull request.

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -1823,7 +1803,6 @@ public function deleteChildren($table, $id, &$delete)
 		foreach ($ctable as $v)
 		{
 			$this->loadDataContainer($v);
-			$cctable[$v] = $GLOBALS['TL_DCA'][$v]['config']['ctable'] ?? null;
```
Comment (leofeyer) [inline core-bundle/contao/drivers/DC_Table.php:1826]: Why did you remove this?

File: core-bundle/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -1839,36 +1818,12 @@ public function deleteChildren($table, $id, &$delete)
...
-					{
-						continue;
-					}
-
-					$delete[$v][] = $row['id'];
-
-					if (!empty($cctable[$v]))
-					{
-						$this->deleteChildren($v, $row['id'], $delete);
-					}
```
Comment (leofeyer) [inline core-bundle/contao/drivers/DC_Table.php:1871]: Are you absolutely certain that the if condition is not needed? It has been there forever.

Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:1871]: `deleteChildren` does exactly the same check on the first lines, and it (correctly) also checks if the value is an array before doing anything. So this seems completely useless to me.

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php:1871]: You seem to be right. The same code is present in the `copyChildren()` method, so maybe it was just copied from there back then.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
