### PR TITLE
Correctly handle form fields in DC_Folder in "editAll" mode

### LINKED ISSUE #2577: Editing metadata of multiple files causes data loss
**Affected version(s)**
- 4.9.10
- maybe also 4.10.x too (didn't test yet)

**Description**
Edit multiple files and do renaming and adding metadata at the same time, the new meta data would not be saved.

**Steps to reproduce**
1. File manager › Edit multiple > Select 2 or more images
2. Available fields > Select all > Continue
3. Rename file name **AND** change caption field
4. Save and close

**Result:**
File would be renamed, but the new meta data (caption) would not be saved.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2577
| Docs PR or issue | -

Supersedes #2981

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

File: core-bundle/src/Resources/contao/drivers/DC_Folder.php [hunk 1]
```diff
@@ -53,6 +53,12 @@ class DC_Folder extends DataContainer implements \listable, \editable
 	 */
 	protected $strRootDir;
 
+	/**
+	 * Initial ID of the record
+	 * @var integer
+	 */
+	protected $initialId;
```
Comment (m-vo) [inline core-bundle/src/Resources/contao/drivers/DC_Folder.php:60]: Is it really really an integer? :upside_down_face:

**Review by m-vo — DISMISSED** [review]

File: core-bundle/src/Resources/contao/drivers/DC_Folder.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/drivers/DC_Folder.php:60]: Probably as much as `$intId` is an integer in the `DC_Folder` class. 🙈

Comment (leofeyer) [reply core-bundle/src/Resources/contao/drivers/DC_Folder.php:60]: Changed in bc42b3345f7ca3ea6f1df8d514af50f8ee66660d.

File: core-bundle/src/Resources/contao/classes/DataContainer.php [hunk 2]
```diff
@@ -1389,6 +1389,11 @@ public function addCtableTags($strTable, $intId, &$tags)
 		}
 	}
 
+	protected function getFormFieldSuffix()
```
Comment (m-vo) [inline core-bundle/src/Resources/contao/classes/DataContainer.php:1397]: Should this function get a return type hint? Or at least a phpdoc comment? Otherwise you again wouldn't know if you're dealing with an integer or a string.

Comment (leofeyer) [reply core-bundle/src/Resources/contao/classes/DataContainer.php:1397]: Added in eb52224ac0a85237dc9e1b936cb47496ddc2387c.

**Review by m-vo — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by Toflar — APPROVED** [review]
