### PR TITLE
Always render protected pages in the pretty error screen listener

### LINKED ISSUE #4211: Access protection on Website root returns Internal Server Error
### Affected version(s)

4.13.0

### Description

When I use the "Protect page" option on the page type "Website root" a Internal Server Error is returned:

grafik

**Steps to reproduce on demo:**
- Activate "protect page" option on website root.
- Choose a member group which is not "Guests".
- Click on "preview".

In my experience in the prior LTS version with this configurations it redirected to the 401 Page.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/4211

This now force-unprotected **all** error pages, which appears to be what we discussed? 😅 
https://github.com/contao/contao/issues/4211#issuecomment-1064117389

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php [hunk 1]
```diff
@@ -140,6 +140,38 @@ public function getErrorTypes(): \Generator
...
+    public function testUnprotectsErrorPage(): void
+    {
+        $exception = new UnauthorizedHttpException('', '', new InsufficientAuthenticationException());
+
+        $errorPage = $this->mockPageWithProperties([
+            'pid' => 1,
+            'type' => 'error_401',
+            'rootLanguage' => '',
+            'protected' => '1',
+            'groups' => ''
```
Comment (fritzmg) [inline core-bundle/tests/EventListener/PrettyErrorScreenListenerTest.php]:
```suggestion
            'groups' => '',
```

**Review by fritzmg — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]
