### PR TITLE
Prevent argument errors on malicious login attempts

### LINKED ISSUE #6702: Exception triggered by bot on form submit
### Affected version(s)

4.13

### Description

Ein Bot versucht, eine Contao-Installation auf Schwachstellen abzuklopfen und ein Teil der Anfragen triggert die folgende Exception, die dann das PROD-Log sehr schnell sehr unübersichtlich werden lassen.

```
[2024-01-05T13:40:13.605970+01:00] request.INFO: Matched route "tl_page.4.root". {"route":"tl_page.4.root","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.4","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.4.root","_route_object":{"Symfony\\Component\\Routing\\Route":[]}},"request_uri":"https://domain.de/","method":"POST"} []
[2024-01-05T13:40:13.621901+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "preg_match(): Argument #2 ($subject) must be of type string, array given" at /webseiten/domain.de/contao/vendor/contao/core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php line 51 {"exception":"[object] (TypeError(code: 0): preg_match(): Argument #2 ($subject) must be of type string, array given at /webseiten/domain.de/contao/vendor/contao/core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php:51)"} []
```

Damit die Exception nicht getriggert wird, könnte man [hier](https://github.com/contao/contao/blob/6c8856f629b72fb907a12e7ed91d3141700fbcbe/core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php#L47) noch einen weiteren Check einfügen (Danke an @fritzmg für den Code!):

```
protected function requiresAuthentication(Request $request): bool
{
    return $request->isMethod('POST')
        && $request->request->has('FORM_SUBMIT')
        && is_string($request->request->get('FORM_SUBMIT'))
        && preg_match('/^tl_login(_[0-9]+)?$/', $request->request->get('FORM_SUBMIT'));
}  
```

Wenn nichts dagegen spricht, erstelle ich gerne einen PR.

Für 5.x wäre die Stelle [hier](https://github.com/contao/contao/blob/e352dbeab7c0aaa7524fdd1b7db4528736f11909/core-bundle/src/Security/Authenticator/ContaoLoginAuthenticator.php#L107).

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #6702

This also makes the `ContaoLoginAuthenticationListener` of Contao 4.13 consistent with the `ContaoLoginAuthenticator` of Contao 5 (there the cast already exists).

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

File: core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php [hunk 1]
```diff
@@ -48,7 +48,7 @@ protected function requiresAuthentication(Request $request): bool
     {
         return $request->isMethod('POST')
             && $request->request->has('FORM_SUBMIT')
-            && preg_match('/^tl_login(_[0-9]+)?$/', $request->request->get('FORM_SUBMIT'));
+            && preg_match('/^tl_login(_[0-9]+)?$/', (string) $request->request->get('FORM_SUBMIT'));
```
Comment (leofeyer) [inline core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]: Is it really wise to just cast the value and ignore the error? There is a similar discussion in https://github.com/contao/contao/pull/6567#pullrequestreview-1750226004 where I suggested to throw an exception instead.

Comment (fritzmg) [reply core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]: The [issue](https://github.com/contao/contao/issues/6702) is that malicious login attempts flood the log with errors. Either we prevent that error and thus avoid flooding the log - or we don't. There is not really another way, is there?

Comment (fritzmg) [reply core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]: And in any case: in Symfony 5 `InputBag::get` can return `string|int|float|bool|null`, so casting to `(string)` makes sense anyway, does it not? (i.e. defensive programming)
Presumably that's why we have this cast in Contao 5 already.

Comment (fritzmg) [reply core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]: #6567 is a different case anyway. There you cannot cause the error by flooding the server with invalid requests. It is caused in the back end and presumably has a specific reproduction.

Comment (leofeyer) [reply core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]: The question is whether we should ignore hacking attempts or not. I find it more defensive to throw "bad request" exceptions in such cases than to just cast the value and hope that the application will handle the attack later on.

The "log flooding" is just a symptom. We should fix the root cause IMHO.

Comment (ausi) [reply core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]:
```suggestion
            && \is_string($request->request->get('FORM_SUBMIT'));
            && preg_match('/^tl_login(_[0-9]+)?$/', $request->request->get('FORM_SUBMIT'));
```

File: core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php [hunk 2]
```diff
@@ -48,6 +48,7 @@ protected function requiresAuthentication(Request $request): bool
     {
         return $request->isMethod('POST')
             && $request->request->has('FORM_SUBMIT')
+            && \is_string($request->request->get('FORM_SUBMIT'));
```
Comment (ausi) [inline core-bundle/src/Security/Authentication/ContaoLoginAuthenticationListener.php]:
```suggestion
            && \is_string($request->request->get('FORM_SUBMIT'))
```

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by de-es** [comment]
Danke @fritzmg
