### PR TITLE
Unwrap response exceptions thrown while rendering a template

### LINKED ISSUE #5977: Twig interprets a redirect exception as an error
### Affected version(s)

5.1.x

### Description

It seems that Twig will catch the `Contao\CoreBundle\Exception\RedirectResponseException` and will throw type `Twig\Error\RuntimeError` error. The issue happens only with the content elements / frontend modules that use the new Twig templates (like Unfiltered HTML content element).

Steps to reproduce on demo.contao.org:

1. Create a content element of "Unfiltered HTML" type with the following content:

```
{{insert_module::17}}
```

It will display the "lost password" frontend module.

2. Go to the frontend and enter `d.evans` and `d.evans@example.com` respectively and submit the form.
3. Error.

CleanShot 2023-04-21 at 17 14 54

CleanShot 2023-04-21 at 17 15 24

/cc @Toflar

### PR DESCRIPTION
**Pull request by m-vo**
Tries to fix #5977 

Here is an attempt at fixing #5977. There is no extension point for the exception handling in Twig (it happens in the `Template` base class), but we can convert the exception in a kernel exception listener. It's not ideal but the effort to do so, is also very minimal.

If we agree on the concept - which exceptions should we "unwrap"?

/cc @qzminski

### CODE REVIEW

File: core-bundle/src/EventListener/UnwrapTwigExceptionListener.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+     * will wrap the exception in a Twig\Error\RuntimeError. For cases that we
+     * want the exception to bubble, we need to unwrap the original exception
+     * again.
+     */
+    public function __invoke(ExceptionEvent $event): void
+    {
+        if (
+            !($throwable = $event->getThrowable()) instanceof RuntimeError ||
+            ($previous = $throwable->getPrevious()) === null ||
+            !\in_array(\get_class($previous), self::$exceptionsToUnwrap, true)
```
Comment (ausi) [inline core-bundle/src/EventListener/UnwrapTwigExceptionListener.php]: Should we iterate over the array and use a `$previous instanceof $exceptionToUnwrap` check instead? This way we would also detect child classes which is the expected behaviour I think.

Comment (m-vo) [reply core-bundle/src/EventListener/UnwrapTwigExceptionListener.php]: Changed in 0ccd80afb08f4f239919a56b9681eb93582631b5.

**Comment by ausi** [comment]
> which exceptions should we "unwrap"?

How about checking for the parent `Contao\CoreBundle\Exception\ResponseException` as we probably want all response exceptions to not be ignored?

**Review by Toflar — COMMENTED** [review]
👍 for the concept. We really need a fix here because we cannot ignore `{{insert_*::..}}` insert tags not working properly in Twig.

I agree with @ausi that we should use `is_a()` on `ResponseException` though 😊

**Comment by m-vo** [comment]
> I agree with @ausi that we should use is_a() on ResponseException though blush

Me too. :smile: The code is updated, now.

File: core-bundle/src/EventListener/UnwrapTwigExceptionListener.php [hunk 2]
```diff
@@ -12,39 +12,27 @@
...
+     * will wrap the exception in a Twig\Error\RuntimeError. In case of our
+     * response exceptions, we need them to bubble, though. Therefore, we
+     * unwrap them again, here.
      */
     public function __invoke(ExceptionEvent $event): void
     {
         if (
             !($throwable = $event->getThrowable()) instanceof RuntimeError ||
-            ($previous = $throwable->getPrevious()) === null
+            !is_a($previous = $throwable->getPrevious(), ResponseException::class)
```
Comment (ausi) [inline core-bundle/src/EventListener/UnwrapTwigExceptionListener.php]:
```suggestion
            !($previous = $throwable->getPrevious()) instanceof ResponseException
```
As using `instanceof` in the first check and `is_a()` in the second looks confusing (to me ☺️)

**Review by Toflar — APPROVED** [review]

File: core-bundle/src/EventListener/UnwrapTwigExceptionListener.php [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+     * If an exception is encountered while rendering a Twig template, Twig
+     * will wrap the exception in a Twig\Error\RuntimeError. In case of our
+     * response exceptions, we need them to bubble, though. Therefore, we
+     * unwrap them again, here.
+     */
+    public function __invoke(ExceptionEvent $event): void
+    {
+        if (
+            !($throwable = $event->getThrowable()) instanceof RuntimeError ||
+            !($previous = $throwable->getPrevious()) instanceof ResponseException
```
Comment (leofeyer) [inline core-bundle/src/EventListener/UnwrapTwigExceptionListener.php:31]: So now `instanceof` instead of `is_a()` after all?

Comment (m-vo) [reply core-bundle/src/EventListener/UnwrapTwigExceptionListener.php:31]: It's the same outcome (https://3v4l.org/Cb1bs) but now we're not mixing two different ways in one condition.

**Comment by leofeyer** [comment]
Thank you @m-vo.
