### PR TITLE
Skip the initializeSystem hook if the temp folder does not yet exist

### LINKED ISSUE #929: Filesystem tools may access invalid paths during initializeSystemHook
**Affected version(s)**
4.4 / 4.8

**Description**  
Using `File->write()` during the `initializeSystem` hook can fail because the [`tmp` subdirectory](https://github.com/contao/contao/blob/2d5832fa11753aea0b0511721c35a88f83d17502/core-bundle/src/Resources/contao/library/Contao/File.php#L844) inside `/system` might not yet exist. 

Effectively this leads to an error in [madeyourday/contao-rocksolid-custom-elements](https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/114) during installation.

**Fix**
We should probably check the path before writing.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #929
| Docs PR or issue | -

### CODE REVIEW

File: core-bundle/src/Framework/ContaoFramework.php [hunk 1]
```diff
@@ -427,10 +427,12 @@ private function setTimezone()
      */
     private function triggerInitializeSystemHook()
     {
-        if (isset($GLOBALS['TL_HOOKS']['initializeSystem']) && \is_array($GLOBALS['TL_HOOKS']['initializeSystem'])) {
-            foreach ($GLOBALS['TL_HOOKS']['initializeSystem'] as $callback) {
-                System::importStatic($callback[0])->{$callback[1]}();
-            }
+        if (empty($GLOBALS['TL_HOOKS']['initializeSystem']) || !is_dir($this->rootDir.'/system/tmp')) {
+            return;
```
Comment (fritzmg) [inline core-bundle/src/Framework/ContaoFramework.php:431]: This would always return when no `initializeSystem` hook is present and thus the `initconfig.php` will never be loaded in that case for example.

**Review by fritzmg — CHANGES_REQUESTED** [review]

File: core-bundle/src/Framework/ContaoFramework.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:431]: That's intended as discussed in the last Mumble call (see https://github.com/contao/contao/issues/929#issuecomment-611531123). We do not want to execute any logic unless the system is fully installed.

Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:431]: @ausi @aschempp /cc

Comment (fritzmg) [reply core-bundle/src/Framework/ContaoFramework.php:431]: Yes, but this way the `initconfig.php` is _never_ executed, regardless of whether the system is fully installed or not, when no hook is registered.

Comment (fritzmg) [reply core-bundle/src/Framework/ContaoFramework.php:431]: To be clear: I mean
```php
if (empty($GLOBALS['TL_HOOKS']['initializeSystem']) || …) {
    return;
}
```

If no `intializeSystem` hooks is registered, the function returns early, meaning that the `initconfig.php` for example, which would be included later on, is never included.

Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:431]: You are absolutely right. My bad. 🤦‍♂️

Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:431]: Changed in f1de5eb44130701bdefb63e6f37aefdf43d17de6.

Comment (bytehead) [reply core-bundle/src/Framework/ContaoFramework.php:431]: LGTM.

**Review by bytehead — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

File: core-bundle/src/Framework/ContaoFramework.php [hunk 2]
```diff
@@ -427,6 +427,10 @@ private function setTimezone()
      */
     private function triggerInitializeSystemHook()
     {
+        if (!is_dir($this->rootDir.'/system/tmp')) {
+            return;
+        }
+
         if (isset($GLOBALS['TL_HOOKS']['initializeSystem']) && \is_array($GLOBALS['TL_HOOKS']['initializeSystem'])) {
```
Comment (aschempp) [inline core-bundle/src/Framework/ContaoFramework.php:434]:
```suggestion
        if (isset($GLOBALS['TL_HOOKS']['initializeSystem']) && \is_array($GLOBALS['TL_HOOKS']['initializeSystem']) && is_dir($this->rootDir.'/system/tmp')) {
```

**Review by aschempp — CHANGES_REQUESTED** [review]
We discussed that we should not check for the file, if no hook is registered, to prevent unnecessary file operations.

File: core-bundle/src/Framework/ContaoFramework.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:434]: Actually, I am not sure about this. Right now, we are not including the `initialize.php` script if the temp folder has not yet been installed. If we moved the check inside the first if condition, the `initialize.php` file would be included even if the temp folder does not yet exist, wouldn't it?

Comment (aschempp) [reply core-bundle/src/Framework/ContaoFramework.php:434]: That's correct. However, I would assume there's most likely no such file in an application that's just being installed. But it's possible/likely that there are extensions that use the hook. Also, removing/renaming/disabling the file is easy, removing the extension to circumvent an issue is tedious.

Comment (leofeyer) [reply core-bundle/src/Framework/ContaoFramework.php:434]: See #1690.
