### PR TITLE
Fix deleting multiple records

### LINKED ISSUE #5839: Deleting children with parent records in "delete all" mode throws an error
### Affected version(s)

5.1.x

### Description

When trying to delete the children records with parent record, Contao will throw an exception:

CleanShot 2023-03-06 at 10 36 31

The problem happens exactly at this place:

https://github.com/contao/contao/blob/5.x/core-bundle/contao/drivers/DC_Table.php#L1534

The first deleted record is the parent record, which also deleted its children. Then, Contao tries to edit the next record in the queue (the child), but this record no longer exists.

I am not sure how to fix this one exactly though.

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/contao/issues/5839

In `deleteAll()` we delete all the IDs that have been selected. If you select a parent and its child, you will get a `NotFoundException` for the child record. This is, because the parent already deleted the child during the first `delete()` and its respective `deleteChilds()` call. So by the time the second ID wants to be deleted in `deleteAll()`, it's already gone.

Fix is simple: We don't need to throw a `NotFoundException` at all. If a record is already gone then that's good, why would there be any error? :)

### CODE REVIEW

**Review by qzminski — DISMISSED** [review]

**Review by leofeyer — DISMISSED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
just returning here seems wrong to me, because the method by default redirects back to the referrer. Can you please also explain how `deleteChild()` could already been executed? The `delete()` method is executed from `act=delete` and never recursively as far as I know?

**Comment by Toflar** [comment]
> Can you please also explain how `deleteChild()` could already been executed? The `delete()` method is executed from `act=delete` and never recursively as far as I know?

We're talking about `deleteAll()` which contains an array of multiple IDs that have been selected in the back end. We loop over those and call `delete()` for them all. `delete()` itself calls `deleteChilds()`. Which means that if the IDs you selected initially are in a parent->child relelation, the second call of `delete()` within `deleteAll()` will run on the child already deleted by the previous call.

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -1531,7 +1531,8 @@ public function delete($blnDoNotRedirect=false)
 
 		if (null === $currentRecord)
 		{
-			throw new NotFoundException('Cannot load record "' . $this->strTable . '.id=' . $this->intId . '".');
+			// Already deleted (can happen if e.g. deleteChilds() already took care of a specifc ID).
+			return;
```
Comment (aschempp) [inline core-bundle/contao/drivers/DC_Table.php]:
```suggestion
			if ($blnDoNotRedirect)
			{
				return;
			}

			throw new NotFoundException('Cannot load record "' . $this->strTable . '.id=' . $this->intId . '".');
```

**Review by aschempp — CHANGES_REQUESTED** [review]
I see. I would suggest to handle that case explicitly then.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.
