### PR TITLE
Fix the impersonation message

### LINKED ISSUE #4170: Logging leaving user impersonation
### Affected version(s)

4.13.0

### Description

Leaving user impersonation (user menu -> ``Back to A``) creates a missleading system log entry (``User "B" has switched to user "A"``). But in fact A has quit the impersonation to B.

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Fixes #4170

Explanation of the behaviour:

## Simple case

- "A" is logged in
- switches to "B" ... the log entry is `User "A" has switched to user "A"`
- switches back to itself ... the log entry is `User "A" has quit the impersonation of user "B"`

## Complex case

- "A" is logged in
- switches to "B" ... the log entry is `User "A" has switched to user "A"`
- switches directly to "C" ... the log entries are `User "A" has quit the impersonation of user "B"` and `User "A" has switched to user "C"`
- switches back to itself ... the log entry is `User "A" has quit the impersonation of user "C"`

I think, that is the right way, because it is alway user "A" who is the origin user.

### CODE REVIEW

File: core-bundle/src/EventListener/SwitchUserListener.php [hunk 1]
```diff
@@ -59,9 +60,25 @@ public function __invoke(SwitchUserEvent $event): void
...
+
+        if ($originalUser === $targetUser) {
+            $this->logger->info(
+                sprintf('User "%s" has quit the impersonation of user "%s"', $originalUser, $sourceUser),
+                ['contao' => new ContaoContext(__METHOD__, ContaoContext::ACCESS, $originalUser)]
+            );
+        } else {
+            if (!empty($originalUser)) {
+                $sourceUser = $originalUser;
+            }
```
Comment (leofeyer) [inline core-bundle/src/EventListener/SwitchUserListener.php:72]:
```suggestion
            }

```

@cliffparnitzky If you would allow edits from the maintainers, I could have fixed this myself. 🙈

Comment (cliffparnitzky) [reply core-bundle/src/EventListener/SwitchUserListener.php:72]: I have currently no clue how allow edits of maintainers. I've added the new line after line 77 from the suggestion. But this runs into an "Cody styling error" in the checks.

File: core-bundle/src/EventListener/SwitchUserListener.php [hunk 2]
```diff
@@ -59,9 +60,25 @@ public function __invoke(SwitchUserEvent $event): void
...
+        if ($token instanceof SwitchUserToken) {
+            $originalUser = $token->getOriginalToken()->getUser()->getUsername();
+        }
+
+        if ($originalUser === $targetUser) {
+            $this->logger->info(
+                sprintf('User "%s" has quit the impersonation of user "%s"', $originalUser, $sourceUser),
+                ['contao' => new ContaoContext(__METHOD__, ContaoContext::ACCESS, $originalUser)]
+            );
+        } else {
```
Comment (bytehead) [inline core-bundle/src/EventListener/SwitchUserListener.php:69]: I personally would combine the `else` and following `if` here: 
```suggestion
        } elseif (!empty($originalUser)) {
```

**Review by bytehead — CHANGES_REQUESTED** [review]

File: core-bundle/src/EventListener/SwitchUserListener.php [hunk 3]
```diff
@@ -59,9 +60,25 @@ public function __invoke(SwitchUserEvent $event): void
...
+            if (!empty($originalUser)) {
```
Comment (bytehead) [inline core-bundle/src/EventListener/SwitchUserListener.php:70]: Is there a special reason to use `!empty` instead of checking for `null !== $originalUser`?

Comment (cliffparnitzky) [reply core-bundle/src/EventListener/SwitchUserListener.php:70]: No, I think both is good. The `empty` is more or less my general choice of sting comparing, because it includes `null` and empty sting.

File: core-bundle/src/EventListener/SwitchUserListener.php (hunk 2 above)
Comment (cliffparnitzky) [reply core-bundle/src/EventListener/SwitchUserListener.php:69]: I think that is not good, because the `if` is only used to reduce the number of loggings. @bytehead How should this look?

Comment (bytehead) [reply core-bundle/src/EventListener/SwitchUserListener.php:69]: Sorry, nevermind. I got distracted with the code view and the conversations 🙈

File: core-bundle/src/EventListener/SwitchUserListener.php (hunk 3 above)
Comment (bytehead) [reply core-bundle/src/EventListener/SwitchUserListener.php:70]: 👍

File: core-bundle/src/EventListener/SwitchUserListener.php (hunk 1 above)
Comment (bytehead) [reply core-bundle/src/EventListener/SwitchUserListener.php:72]: There's a checkbox on the lower right. After the closing bracket of the `if` and before `$this->logger->info` there should be an empty line.

**Review by bytehead — CHANGES_REQUESTED** [review]

**Review by bytehead — DISMISSED** [review]
👍

File: core-bundle/src/EventListener/SwitchUserListener.php [hunk 4]
```diff
@@ -59,9 +60,26 @@ public function __invoke(SwitchUserEvent $event): void
...
         }
 
-        $this->logger->info(
-            sprintf('User "%s" has switched to user "%s"', $sourceUser, $targetUser),
-            ['contao' => new ContaoContext(__METHOD__, ContaoContext::ACCESS, $sourceUser)]
-        );
+        $originalUser = null;
+
+        if ($token instanceof SwitchUserToken) {
+            $originalUser = $token->getOriginalToken()->getUser()->getUsername();
```
Comment (aschempp) [inline core-bundle/src/EventListener/SwitchUserListener.php]:
```suggestion
            $originalUser = $token->getOriginalToken()->getUsername();
```

File: core-bundle/src/EventListener/SwitchUserListener.php [hunk 5]
```diff
@@ -59,9 +60,26 @@ public function __invoke(SwitchUserEvent $event): void
             $targetUser = $targetUser->getUsername();
```
Comment (aschempp) [inline core-bundle/src/EventListener/SwitchUserListener.php]: `$targetUser` is always `instanceof UserInterface`, not sure why this check is here.

**Review by aschempp — COMMENTED** [review]
By looking at the Symfony code, I think this could be a bit simplified. If `$token instanceof SwitchUserToken`, we don't need the `$sourceUser` etc. at all. So maybe that could be the first check in the method and log appropriately? 😊

**Comment by leofeyer** [comment]
@cliffparnitzky What about @aschempp‘s suggestions above? Can you please resolve the conversations, so we can eventually merge this PR?

File: core-bundle/src/EventListener/SwitchUserListener.php (hunk 5 above)
Comment (cliffparnitzky) [reply core-bundle/src/EventListener/SwitchUserListener.php]: Yes, this seems to be right. I will remove the check.

File: core-bundle/src/EventListener/SwitchUserListener.php (hunk 4 above)
Comment (cliffparnitzky) [reply core-bundle/src/EventListener/SwitchUserListener.php]: This works. I will change it.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @cliffparnitzky.
