### PR TITLE
Use the class name as cache key in System::import()

### LINKED ISSUE #2152: System::import() may return unexpected instances
**Affected version(s)**

- `^4.9.4`

**Description**

Since #1840 a `System#import()` or `System::importStatic()` may return an unexpected instance. This is the case for the `User` import in Contao. How to reproduce it:

```php

class CallbackA extends \Contao\System
{
    public function __invoke()
    {
        $this->import('Frontenduser', 'User');
        var_dump(get_class($this->User));
    }
}

class CallbackB extends \Contao\System
{
    public function __invoke()
    {
        $this->import('BackendUser', 'User');
        var_dump(get_class($this->User));
    }
}

(new CallbackA())();
(new CallbackB())();
```

If a third party extension imports the backend user before the frontend user is imported (e.g. through a hook), the frontend user is not used in all legacy classes. Which might lead to an invalid upload folder path in the `FormFileUpload` form field.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2152
| Docs PR or issue | -

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/System.php [hunk 1]
```diff
@@ -193,7 +193,7 @@ protected function import($strClass, $strKey=null, $blnForce=false)
 			}
 			elseif (\in_array('getInstance', get_class_methods($strClass)))
 			{
-				static::$arrStaticObjects[$strKey] = static::$arrSingletons[$strKey] = $this->arrObjects[$strKey] = \call_user_func(array($strClass, 'getInstance'));
+				static::$arrStaticObjects[$strKey] = static::$arrSingletons[$strClass] = $this->arrObjects[$strKey] = \call_user_func(array($strClass, 'getInstance'));
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/library/Contao/System.php]: I think we should not write to `static::$arrStaticObjects[$strKey]` in this case either.

**Review by aschempp — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/library/Contao/System.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/System.php]: I agree. It should not really matter, though, because the classes are singletons anyway.

Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/System.php]: Ah, it does matter. If we remove it, we have to add an `elseif (isset(static::$arrSingletons[$strClass]))` branch in the `importStatic()` method.

Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/System.php]: Adjusted in 02fd655f61a2902aff5444062a68fdf6242815a7.

**Review by dmolineus — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Review by bytehead — APPROVED** [review]
