### PR TITLE
Fix the missing `Vary` header in the CAPTCHA controller

### LINKED ISSUE #9716: Add Vary Header to _contao/captcha/ Route
### Affected version(s)

5.7.3

### Description

As discussed in slack. The captcha route sends JSON or Javascript depending on HTTP Header. In some caching environments there are issues because if missing vary header. The vary header with value "X-Requested-With" should be added.

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/contao/issues/9716

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Review by zoglo — DISMISSED** [review]

File: core-bundle/src/Controller/CaptchaController.php [hunk 1]
```diff
@@ -33,19 +33,25 @@ public function __construct(private readonly ContaoFramework $framework)
...
 
         $captcha = new FormCaptcha();
 
-        return new JsonResponse([
+        $response = new JsonResponse([
             'question' => html_entity_decode($captcha->question, ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML5),
             'sum' => $captcha->sum,
             'hash' => $captcha->sum.$captcha->hash,
         ]);
+        $response->setVary('X-Requested-With');
```
Comment (ausi) [inline core-bundle/src/Controller/CaptchaController.php:54]:
```suggestion
        $response->headers->set('Cache-Control', 'no-cache, no-store');
        $response->setVary('X-Requested-With');
```
We should also never cache the JSON response as the captcha hash is time sensitive.

Comment (fritzmg) [reply core-bundle/src/Controller/CaptchaController.php:54]: We typically only set `no-cache, no-store` for non-cachable responses (`private` would indicate it being only cacheable in a private cache).

Comment (ausi) [reply core-bundle/src/Controller/CaptchaController.php:54]: Suggested code updated :+1:

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Controller/CaptchaController.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/src/Controller/CaptchaController.php:54]: If the response is never cached, why would it need a `Vary` header?

Comment (Toflar) [reply core-bundle/src/Controller/CaptchaController.php:54]: The whole point of this PR is to add the vary header because the response **is** cached...

Comment (aschempp) [reply core-bundle/src/Controller/CaptchaController.php:54]: Yes, because it also didn't have the `no-cache` option, but it is now added here?

Comment (Toflar) [reply core-bundle/src/Controller/CaptchaController.php:54]: There are two possible responses for the same URL here - hence both should have the `Vary` header just to be sure, imho.

Comment (aschempp) [reply core-bundle/src/Controller/CaptchaController.php:54]: Ah I didn't realize it's the same URL where one response is cacheable and one is not. Then I would keep `Very` as well 👍

**Review by aschempp — DISMISSED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.
