### PR TITLE
Additionally check the `disablePermissionsChecks` flag for back end modules

### LINKED ISSUE #8753: Non-admin users cannot create favorites anymore
### Affected version(s)

5.3.38

### Description

Since updating from Contao 5.3.34 to 5.3.38, non-admin backend users are no longer able to create favorites.

Clicking on “Save URL as favorite” results in the following error message:

Not enough permissions to create [Subject: Source: tl_favorites].

In 5.3.34 this worked as expected.
Admin users are not affected.

Steps to reproduce:

1. Create a backend user who is not an administrator.

2. Log in with this user.

3. Open any page/view in the backend.

4. Click “Save URL as favorite” in the header menu.

Current behavior:
An error message is shown:

Not enough permissions to create [Subject: Source: tl_favorites].

Expected behavior:
The URL should be saved as a favorite, as it did in Contao 5.3.34.

### LINKED ISSUE #8767: User cannot access their profile
### Affected version(s)

5.6.1

### Description

Contao 5.6.1: the user cannot access/edit their profile. Error page:
Forbidden 
Not enough permissions to read [Subject: Source: tl_user; ID: *].

It works when downgrading to 5.6.0.

Image

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #8753

This adds a check for `disablePermissionChecks` in our `BackendAccessVoter` which will also have an effect on the `TableAccessVoter` when it checks for the back end module access.

### CODE REVIEW

File: core-bundle/src/Security/Voter/BackendAccessVoter.php [hunk 1]
```diff
@@ -129,6 +129,29 @@ private function hasAccess(mixed $subject, string $field, BackendUser $user): bo
...
+
+            foreach ($subject as $module) {
+                foreach ($GLOBALS['BE_MOD'] as $modules) {
+                    foreach ($modules as $name => $config) {
+                        if ($name === $module) {
+                            $hasModuleAccess = $config['disablePermissionChecks'] ?? false;
+                        }
+
+                        if (false === $hasModuleAccess) {
+                            break 3;
```
Comment (m-vo) [inline core-bundle/src/Security/Voter/BackendAccessVoter.php]: Wouldn't it be easier to just use an early return here (or even better L140)?

Comment (fritzmg) [reply core-bundle/src/Security/Voter/BackendAccessVoter.php]: My thinking was that I do not want to return early here as it should just skip to the next check (which there currently is none of course), if not all of the back end modules have `disablePermissionsCheck` enabled.

But I think this solution is may be not the correct one anyway.

Comment (fritzmg) [reply core-bundle/src/Security/Voter/BackendAccessVoter.php]: Check is now simplified 👍

Comment (m-vo) [reply core-bundle/src/Security/Voter/BackendAccessVoter.php]: If there are multiple checks they should probably each go in a separate function, so you can easily grasp it at the higher level/main function. 👍

**Review by aschempp — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]
