### PR TITLE
Fix BC for `TL_LANG.LNG` and `TL_LANG.CNT`

### LINKED ISSUE #4035: Fix backwards compatibility for TL_LANG.LNG and TL_LANG.CNT
### Affected version(s)

4.12

### Description

Additionally to #3716 we should also fix access to the `$GLOBALS['TL_LANG']['LNG']` and `$GLOBALS['TL_LANG']['CNT']` globals array after calling `System::loadLanguageFile('languages')` and `System::loadLanguageFile('countries')`

### PR DESCRIPTION
**Pull request by ausi**
Fixes #4035

`->trans('CNT.de', [], 'contao_countries')`, `->trans('LNG.de', [], 'contao_languages')` and `System::loadLanguageFile('languages')` as well as `System::loadLanguageFile('countries')` works now as it did before.

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

File: core-bundle/src/Resources/contao/library/Contao/System.php [hunk 1]
```diff
@@ -536,6 +536,30 @@ public static function loadLanguageFile($strName, $strLanguage=null, $blnNoCache
 			$GLOBALS['TL_LANG']['MSC']['textDirection'] = (\ResourceBundle::create($strLanguage, 'ICUDATA', true)['layout']['characters'] ?? null) === 'right-to-left' ? 'rtl' : 'ltr';
 		}
 
+		// Backwards compatibility
+		if ('languages' === $strName)
+		{
+			foreach (self::getContainer()->get(Locales::class)->getLocales($strLanguage) as $strLocale => $strLabel)
+			{
+				if (!isset($GLOBALS['TL_LANG']['LNG'][$strLocale]))
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/library/Contao/System.php]: This will not work if a different language is loaded. I think you should move this before loading the actual language file and not check for `$GLOBALS` existence.

**Review by aschempp — CHANGES_REQUESTED** [review]

**Comment by aschempp** [comment]
Also, can we maybe add a unit tests for the translator stuff? I know the translator can check/checks whether a message domain exists, not sure `contao_languages` and `contao_countries` do exist with this?

**Comment by ausi** [comment]
> Also, can we maybe add a unit tests for the translator stuff?

Will do. @leofeyer can you merge the 4.9 upstream so that I have the changes from https://github.com/contao/contao/pull/4013 available.

File: core-bundle/src/Resources/contao/library/Contao/System.php (hunk 1 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/System.php]: Fixed in 6629909f483ebfab00d6d189128f95d411c6ed86

**Comment by leofeyer** [comment]
Done.

**Review by fritzmg — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
