### PR TITLE
Fix the stop time in the DB queries

### LINKED ISSUE #2231: Time control wrong / counter-intuitive
**Affected version(s)**
Contao 4.4.24 (maybe other versions too)

**Description**
Time control of the elements to the minute is counter-intuitive. The value in the "From" field is OK, the value in the "To" field is intuitively "-2 minutes".

**What I've found out:**
If you want to show elements to the second, the system behaves strangely. E.g. if you want to display an element from "10:00:00" to "10:00:59", you have to add "10:00" in the field "From", but the value "10:02" in the field "To". Even if you argue that the "To"-field contains the first second of the minute the element should not be visible anymore, the value described does not make much sense. Same behaviour, if you define time-strings to contain seconds - the seconds seem to be ignored.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2231
| Docs PR or issue | -

### CODE REVIEW

File: calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php [hunk 1]
```diff
@@ -207,7 +207,7 @@ public static function findPublishedByParentAndIdOrAlias($varId, $arrPids, array
 		if (!static::isPreviewMode($arrOptions))
 		{
 			$time = \Date::floorToMinute();
-			$arrColumns[] = "($t.start='' OR $t.start<='$time') AND ($t.stop='' OR $t.stop>'" . ($time + 60) . "') AND $t.published='1'";
+			$arrColumns[] = "$t.published='1' AND ($t.start='' OR $t.start<='$time') AND ($t.stop='' OR $t.stop>'$time')";
```
Comment (leofeyer) [inline calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php:210]: Just in case you wonder, I have adjusted the order to be forward compatible with Contao 4.10.

**Review by ausi — APPROVED** [review]
