### PR TITLE
Fix generating error pages by name

### LINKED ISSUE #2809: Routing debug issues
**Affected version(s)**

Contao 4.9

**Description**

I tried to debug some routes with `vendor/bin/contao-console route:match` but get following errors:

`vendor/bin/contao-console route:match /preview.php/_wdt/205c80`
```
In RouteProvider.php line 115:
                                                                                                                                                   
  Return value of Contao\CoreBundle\Routing\RouteProvider::getRouteByName() must be an instance of Symfony\Component\Routing\Route, null returned                                        
```

I locally fixed it with following condition, I'm able to select a route:
```php
if (!isset($routes[$name])) {
    throw new RouteNotFoundException('Route name does not match a page ID');
}
```

```
 [OK] Route "tl_page.893.error_404" matches                                                                             
                                                                                                                        
 Select one of the matching routes:
  [0] tl_page.893.error_404.locale
  [1] tl_page.893.error_404
```

If I select any I get another error now:

```
  The route "tl_page.893.error_404" does not exist.  
```

### PR DESCRIPTION
**Pull request by aschempp**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2809

### CODE REVIEW

File: core-bundle/src/Routing/RouteProvider.php [hunk 1]
```diff
@@ -338,7 +338,8 @@ private function getPageIdsFromNames(array $names): array
         $ids = [];
 
         foreach ($names as $name) {
-            if (0 !== strncmp($name, 'tl_page.', 8)) {
+            $parts = explode('.', $name);
```
Comment (bytehead) [inline core-bundle/src/Routing/RouteProvider.php:341]: CS (newline)?

**Review by bytehead — CHANGES_REQUESTED** [review]

File: core-bundle/src/Routing/RouteProvider.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/src/Routing/RouteProvider.php:341]: already fixed 😊

File: core-bundle/src/Routing/Route404Provider.php [hunk 2]
```diff
@@ -56,17 +56,24 @@ public function getRouteCollectionForRequest(Request $request): RouteCollection
...
-        // Support console and web inspector profiling
+        $routes = $this->getRoutes();
+
         if (null === $names) {
-            return $this->getRoutes();
+            return $routes;
         }
 
-        return [];
+        return array_intersect_key($routes, array_flip($names));
```
Comment (leofeyer) [inline core-bundle/src/Routing/Route404Provider.php:76]: Do we need to cast `(array) $names` here? Because even though the phpDoc says `array|null`, the type is not enforced and `$names` could be anything (except `null` of course).

File: core-bundle/src/Routing/RouteProvider.php [hunk 3]
```diff
@@ -338,7 +338,9 @@ private function getPageIdsFromNames(array $names): array
...
+
+            if ('tl_page' !== ($parts[0] ?? '') || 'error_404' === ($parts[2] ?? '')) {
```
Comment (leofeyer) [inline core-bundle/src/Routing/RouteProvider.php]:
```suggestion
            if ('tl_page' !== $parts[0] || 'error_404' === ($parts[2] ?? '')) {
```

`$parts[0]` will always be set, even if the string is empty or does not contain the split character (see https://3v4l.org/O2Qvv).

File: core-bundle/src/Routing/Route404Provider.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/src/Routing/Route404Provider.php:76]: if the interface would enforce it, you would get an error. Now you get an error as well if you don't follow the docs…

**Review by leofeyer — APPROVED** [review]
