### PR TITLE
Fix a regression with icons in dark mode

### LINKED ISSUE #7018: `Image::getHtml()` not considering dark-mode images anymore
### Affected version(s)

5.3.1

### Description

#6982 reverted #6880 so the the same issue got reintroduced

https://github.com/contao/contao/pull/6982/files#r1523305209

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #7018 

#6982 reverted #6880 so the logic was reintroduced within the new getHtml method

### CODE REVIEW

File: core-bundle/contao/library/Contao/Image.php [hunk 1]
```diff
@@ -159,10 +159,21 @@ public static function getHtml($src, $alt='', $attributes='')
...
+
+		foreach (array('data-icon', 'data-icon-disabled') as $icon)
+		{
+			if (isset($darkAttributes[$icon]))
+			{
+				$pathinfo = pathinfo($darkAttributes[$icon]);
+				$darkAttributes[$icon] = $pathinfo['filename'] . '--dark.' . $pathinfo['extension'];
+			}
+		}
+
```
Comment (leofeyer) [inline core-bundle/contao/library/Contao/Image.php]: This should probably be moved inside the `if (str_contains($template, '{darkAttributes}'))` condition, so the code is not run unnecessarily.

Comment (zoglo) [reply core-bundle/contao/library/Contao/Image.php]: @leofeyer Adjusted it in https://github.com/contao/contao/pull/7019/commits/15b8634934b7b3cf673021aa7b68a492ed5e93d7 and also tested that already

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.
