### PR TITLE
Fix the back end pagination

### LINKED ISSUE #9035: Bottom pagination is still/again broken
### Affected version(s)

5.7

### Description

Image

I can click on the pagination icons or the next/prev button, but it does not show the current page. It also looks like the grey container is not correctly placed.

Problably related to https://github.com/contao/contao/issues/8979
/cc @m-vo

### PR DESCRIPTION
**Pull request by fritzmg**
This PR fixes two issues:

* The old back end pagination received its current page parameter via `Input::setGet()` in `DC_Table`, which the new one obviously does not, as we only check the regular request object. This causes #9035 - and is fixed by introducing a new `withCurrentPage()` config, so that you can override the current page from the outside.
* The old back end pagination also had a `.pagination-lp` (and `.pagination-vp`) CSS class, which was missing for the new pagination. This PR re-introduces that class for the back end pagination, fixing the styling of the pagination.

I have also updated an existing test so that it verifies that existing parameters are retained in the pagination URLs (unrelated to these 2 issues).

### CODE REVIEW

**Review by leofeyer — APPROVED** [review]

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -5848,14 +5848,14 @@ protected function paginationMenu()
 			$this->redirect(preg_replace('/&(amp;)?lp=[^&]+/i', '', Environment::get('requestUri')));
 		}
 
+		$paginationConfig = (new PaginationConfig('lp', (int) $this->total, (int) $limit))->withIgnoreOutOfBounds();
+
 		if ($limit)
 		{
-			Input::setGet('lp', $offset / $limit + 1); // see #6923
+			$paginationConfig = $paginationConfig->withCurrentPage($offset / $limit + 1);
```
Comment (Toflar) [inline core-bundle/contao/drivers/DC_Table.php:5855]: That's exactly why I wanted to have the `PaginationConfig` 🥳
