### PR TITLE
Handle `%` characters in the SERP preview

### LINKED ISSUE #3420: "Internal Server Error: 3 arguments are required, 2 given" when having a "%" char in the site name of the website startpoint
**Affected version(s)**
Contao 4.9.20 running on PHP v.8.0.10

I was not able to replicate the issue on the demo site so it might be only with PHP 8.0.
I do not know on which version the demo site runs though.

**Description**
After a fresh installation while trying to set up my site structure I noticed this issue.
When adding the website startpoint with a "%" char in the site name I can not add a site inside that start point.
It fails with "Internal Server Error: 3 arguments are required, 2 given".
After I rename the start point to something without % it works just fine.

### PR DESCRIPTION
**Pull request by fritzmg**
If you use a `%` character in your website root title, the following warning will occur when trying to insert a new page or editing a page within that website root:

```
ErrorException:
Warning: sprintf(): Too few arguments

  at vendor\contao\contao\core-bundle\src\Resources\contao\widgets\SerpPreview.php:73
  at Contao\SerpPreview->generate()
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Widget.php:651)
  at Contao\Widget->generateWithError(true)
     (vendor\contao\contao\core-bundle\src\Resources\contao\templates\backend\be_widget.html5:3)
  at include('vendor/contao/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateInheritance.php:100)
  at Contao\Widget->inherit()
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Widget.php:598)
  at Contao\Widget->parse()
     (vendor\contao\contao\core-bundle\src\Resources\contao\classes\DataContainer.php:668)
  at Contao\DataContainer->row('{title_legend},title,alias,type;{meta_legend},pageTitle,robots,description,serpPreview;{protected_legend:hide},protected;{layout_legend:hide},includeLayout;{cache_legend:hide},includeCache;{chmod_legend:hide},includeChmod;{expert_legend:hide},cssClass,sitemap,hide,noSearch,guests,requireItem;{tabnav_legend:hide},tabindex,accesskey;{publish_legend},published,start,stop')
     (vendor\contao\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php:1985)
  at Contao\DC_Table->edit()
     (vendor\contao\contao\core-bundle\src\Resources\contao\classes\Backend.php:644)
  at Contao\Backend->getBackendModule('page', null)
     (vendor\contao\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor\contao\contao\core-bundle\src\Controller\BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\index.php:31)
  at require('web/index.php')
     (web\app.php:4)         
```

This PR fixes this by escaping any `%` character with another `%` character for `sprintf`.

### CODE REVIEW

File: core-bundle/src/Resources/contao/widgets/SerpPreview.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function generate()
 
 		if ($titleTag = $this->getTitleTag($model))
 		{
-			$title = StringUtil::substr(sprintf($titleTag, $title), 64);
+			$title = StringUtil::substr(sprintf(str_replace('%', '%%', $titleTag), $title), 64);
```
Comment (ausi) [inline core-bundle/src/Resources/contao/widgets/SerpPreview.php]: Wouldn’t this stop the `sprintf()` from working for the expected `%s` placeholder?

Comment (ausi) [reply core-bundle/src/Resources/contao/widgets/SerpPreview.php]: I think the correct place for this fix is in https://github.com/contao/contao/blob/465dc7457491fa9066806def5f73e6dbdfac2b99/core-bundle/src/Resources/contao/dca/tl_page.php#L1021 (and in the same method of the other DCAs)

Comment (fritzmg) [reply core-bundle/src/Resources/contao/widgets/SerpPreview.php]: True, didn't think about this part of code enough.

Comment (fritzmg) [reply core-bundle/src/Resources/contao/widgets/SerpPreview.php]: I am using `preg_replace('/%(?!s)/', '%%', $titleTag)` now, which should replace all occurrences of `%` with `%%`, except `%s`. wdyt?

Replacing the `%` with `%%` before `%s` gets added is otherwise a bit cumbersome, as it might look like this for example:

```php
// Replace page title with a placeholder and any other insert tags with its actual value
$strTitleTag = self::replaceInsertTags(str_replace('{{page::pageTitle}}', '[[PAGETITLE]]', $layout->titleTag ?: '{{page::pageTitle}} - {{page::rootPageTitle}}'));

// Escape any "%" characters and then replace page title placeholder with a sprintf placeholder
$strTitleTag = str_replace('[[PAGETITLE]]', '%s', str_replace('%', '%%', $strTitleTag));

return $strTitleTag;
```

Comment (ausi) [reply core-bundle/src/Resources/contao/widgets/SerpPreview.php]: This would still break with `%s` in the page title. How about something like this?

```php
return implode(
	'%s', 
	array_map(
		function($strVal) {
			return str_replace('%', '%%', self::replaceInsertTags(strVal));
		},
		explode('{{page::pageTitle}}', $layout->titleTag ?: '{{page::pageTitle}} - {{page::rootPageTitle}}', 2)
	)
);
```

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
