### PR TITLE
Fix issues with MooTools' `domready` event

### LINKED ISSUE #8239: Collapsed action select dropdown on small screens doesn't work anymore
### Affected version(s)

5.5.8

### Description

On small screens (narrow browser window):

A click on the arrow to expand the select list doesn't work anymore, you can't select any of the hidden action options.

Can be reproduced at demo.contao.org

For example when you want to edit multiple content elements:

Image

Nothing happens when you click on the select field arrow at the bottom right.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #8239 - and other things that I noticed for which no GitHub issues were created yet (e.g. the mobile menu button not working, DropZone not working - and more).

First of all this changes the `window.removeEvents()` back to `Element.Events.removeEvents()`.

This would then create issues for our inline `<script>`s  that use `domready` - however, all of these do not actually _need_ `domready` since their HTML element is already _before_ the `<script>`.

The PR also removes `Turbo.cache.exemptPageFromCache()` from `Contao.SerpPreview.initialize()` as I found it not to be necessary anymore.

This still of course lacks one BC issue: extensions or App adjustments that use MooTools `domready` within `<body>` - for that we have no solution as of yet. But this PR won't make this any worse than in previous 5.5 versions.

_Note:_ use **Hide whitespace** to review the changes on GitHub.

### CODE REVIEW

**Review by m-vo — DISMISSED** [review]
Reviewed and tested manually by a vigorous beserk-like back-and-forth clicking though the back end without encountering any errors. :tada:

**Review by zoglo — DISMISSED** [review]
Am gonna approve this with the remark that this introduces a console error for tinymce instances when any mooTools widget is initialized on the same page when navigating back and forth.

As discussed, this is most likely a race condition that is caused by MooTools intervening into event listeners.

The TinyMCE JS however is not affected by the error thrown within the console and this PR does fix the other bugs.

File: core-bundle/assets/backend.js [hunk 1]
```diff
@@ -49,8 +49,8 @@ const mooDomready = () => {
     if (!document.body.mooDomreadyFired) {
         document.body.mooDomreadyFired = true;
 
-        if (window.removeEvents) {
-            window.removeEvents();
+        if (Element.Events.removeEvents) {
```
Comment (leofeyer) [inline core-bundle/assets/backend.js]: This condition is never `true` on my system (Safari and Firefox on macOS). I added `console.log(Element.Events.removeEvents);` above this line and it is always `undefined`.

Since this PR also fixes #8227 by removing `window.addEvent("domready", …)` in the other files, I'm all for merging it. But are we sure that we want to ignore that?

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — DISMISSED** [review]

File: core-bundle/assets/backend.js (hunk 1 above)
Comment (leofeyer) [reply core-bundle/assets/backend.js]: Besides that, anything that would work such as `Element.removeEvents()`, `window.removeEvents()` or `document.body.removeEvents()` will remove the `domready` event and break all MooTools related stuff (like it is currently in Contao 5.5.8). So this basically only works because it is never executed.

**Review by leofeyer — DISMISSED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Review by leofeyer — APPROVED** [review]
