### PR TITLE
Do not use load callbacks to set default values

### LINKED ISSUE #8340: Do not use load callbacks to set default values
As discussed in the call, the current behavior is unexpected but correct. Maybe we can use a callback for the `default` field instead of a load_callback as we do here:

https://github.com/contao/contao/blob/de4b81a11ef416ca1d7553bbf642121d24541aa8/core-bundle/contao/dca/tl_article.php#L140

_Originally posted by @leofeyer in https://github.com/contao/contao/issues/8313#issuecomment-2863162364_

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #8340

### CODE REVIEW

File: core-bundle/contao/dca/tl_module.php [hunk 1]
```diff
@@ -502,22 +502,16 @@
 		),
 		'reg_text' => array
 		(
+			'default'                 => static fn (): string => (is_array($GLOBALS['TL_LANG']['tl_module']['emailText'] ?? null) ? $GLOBALS['TL_LANG']['tl_module']['emailText'][1] : ($GLOBALS['TL_LANG']['tl_module']['emailText'] ?? null)),
```
Comment (aschempp) [inline core-bundle/contao/dca/tl_module.php]: this doesn't really need to be a callback?

File: newsletter-bundle/contao/dca/tl_module.php [hunk 2]
```diff
@@ -58,23 +58,17 @@
 
 $GLOBALS['TL_DCA']['tl_module']['fields']['nl_subscribe'] = array
 (
+	'default'                 => static fn(): string => $GLOBALS['TL_LANG']['tl_module']['text_subscribe'][1],
```
Comment (aschempp) [inline newsletter-bundle/contao/dca/tl_module.php]: this doesn't really need to be a callback, but should probably null-check the label

File: newsletter-bundle/contao/dca/tl_module.php [hunk 3]
```diff
@@ -58,23 +58,17 @@
...
-	(
-		array('tl_module_newsletter', 'getSubscribeDefault')
-	),
+	'eval'                    => array('style'=>'height:120px', 'decodeEntities'=>true),
 	'sql'                     => "text NULL"
 );
 
 $GLOBALS['TL_DCA']['tl_module']['fields']['nl_unsubscribe'] = array
 (
+	'default'                 => static fn(): string => $GLOBALS['TL_LANG']['tl_module']['text_unsubscribe'][1],
```
Comment (aschempp) [inline newsletter-bundle/contao/dca/tl_module.php]: this doesn't really need to be a callback, but should probably null-check the label

**Review by aschempp — CHANGES_REQUESTED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
