### PR TITLE
Make sure the parent directory exists when writing files

### LINKED ISSUE #3582: Check if system is installed when loading language files
Btw. booting the Contao Framework and then using a Model method will cause the `loadLanguageFile` Hook to be executed, which in turn can have other unintended consequences that may even cause `cache:warmup --env=prod` on the console to fail. For example if your Contao instance uses `madeyourday/contao-rocksolid-custom-elements` and the `system/` folder is missing (as it usually is during a deployment), the following error will occur:

```
$ vendor/bin/contao-console cache:warmup -vvv

In Files.php line 159:

  [ErrorException]
  Warning: fopen(system/tmp/7ba9a9e97772f43b365094323d38535d): failed to open stream: No such file or directory  


Exception trace:
  at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php:159
 Contao\Files->fopen() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php:829
 Contao\File->fputs() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php:461
 Contao\File->write() at vendor\madeyourday\contao-rocksolid-custom-elements\src\CustomElements.php:1556
 MadeYourDay\RockSolidCustomElements\CustomElements::loadConfig() at vendor\madeyourday\contao-rocksolid-custom-elements\src\CustomElements.php:1633
 MadeYourDay\RockSolidCustomElements\CustomElements->loadLanguageFileHook() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\System.php:545
 Contao\System::loadLanguageFile() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:376
 Contao\DcaExtractor->createExtract() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:128        
 Contao\DcaExtractor->__construct() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:150
 Contao\DcaExtractor::getInstance() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model\QueryBuilder.php:33     
 Contao\Model\QueryBuilder::find() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:1215
 Contao\Model::buildFindQuery() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:1053
 Contao\Model::find() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:967
 Contao\Model::findAll() at vendor\contao\core-bundle\src\Framework\Adapter.php:44
 Contao\CoreBundle\Framework\Adapter->__call() at vendor\contao\core-bundle\src\Twig\Loader\TemplateLocator.php:76
 Contao\CoreBundle\Twig\Loader\TemplateLocator->findThemeDirectories() at vendor\contao\core-bundle\src\Twig\Loader\ContaoFilesystemLoaderWarmer.php:55
 Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoaderWarmer->warmUp() at vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php:98
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at vendor\symfony\http-kernel\Kernel.php:584
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:323    
 Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() at vendor\symfony\http-kernel\Kernel.php:786
 Symfony\Component\HttpKernel\Kernel->preBoot() at vendor\symfony\http-kernel\Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at vendor\symfony\framework-bundle\Console\Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at vendor\symfony\framework-bundle\Console\Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at vendor\bin\contao-console(21) : eval()'d code:36
 eval() at vendor\bin\contao-console:21
```

_Originally posted by @fritzmg in https://github.com/contao/contao/issues/3576#issuecomment-943415123_

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/3582

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Files.php [hunk 1]
```diff
@@ -156,6 +159,8 @@ public function fopen($strFile, $strMode)
 	{
 		$this->validate($strFile);
 
+		$this->mkdir($this->strRootDir);
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Files.php]:
```suggestion
		$this->mkdir(\dirname($strFile));
```
Did you mean something like this?

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: But `$this->mkdir()` is not recursive so maybe better to use something like this?
```suggestion
		(new Filesystem())->mkdir(\dirname($this->strRootDir . '/' . $strFile));
```

Comment (fritzmg) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: Yes, definitely use the `Filesystem` component for mkdir.

File: core-bundle/src/Resources/contao/library/Contao/Files.php [hunk 2]
```diff
@@ -156,6 +156,14 @@ public function fopen($strFile, $strMode)
...
 		$this->validate($strFile);
 
+		$filesystem = System::getContainer()->get('filesystem');
+		$parentDir = \dirname($this->strRootDir . '/' . $strFile);
+
+		if (!$filesystem->exists($parentDir))
+		{
+			$filesystem->mkdir($parentDir);
+		}
+
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Files.php]: No need to check for existence or ask the container IMO.

```suggestion
		(new Filesystem())->mkdir(\dirname($this->strRootDir . '/' . $strFile));
```

**Review by ausi — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/library/Contao/Files.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: but that will make it impossible to mock …

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: Mocking is not needed here, see the `fopen()` in the next line.

Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: Changed in 0e37183f2689cd33c2c6b7df34e02c57b197423e

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
I think we should check `$strMode` to actually know if a file is being written or just read. In the latter case, we should not create the folder.

Also, you should probably use the `Files::mkdir()` method instead of the Symfony `Filesystem` class to generate the folder.

**Comment by fritzmg** [comment]
> Also, you should probably use the `Files::mkdir()` method instead of the Symfony `Filesystem` class to generate the folder.

`Files::mkdir()` does not create the directories recursively though.

**Comment by leofeyer** [comment]
We should set this flag to `true` in line 92.

**Comment by aschempp** [comment]
> I think we should check `$strMode` to actually know if a file is being written or just read. In the latter case, we should not create the folder.

If we don't create the parent directory, wouldn't still break if we are running a `fopen` call on a non-existing file & directory?

**Comment by leofeyer** [comment]
> If we don't create the parent directory, wouldn't still break if we are running a `fopen` call on a non-existing file & directory?

Yes, probably. Just like when you enter a wrong filename, therefore I’d expect this behavior.

The point is that I don’t want `fopen('i/do/not/exist.pdf', 'r')` to create an orphan `i/do/not` folder in case the path is invalid. And your changes would do exactly this.

File: core-bundle/src/Resources/contao/library/Contao/Files.php [hunk 3]
```diff
@@ -156,6 +158,8 @@ public function fopen($strFile, $strMode)
 	{
 		$this->validate($strFile);
 
+		(new Filesystem())->mkdir(\dirname($this->strRootDir . '/' . $strFile));
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Files.php]:
```suggestion
		if ($strMode[0] !== 'r')
		{
			(new Filesystem())->mkdir(\dirname($this->strRootDir . '/' . $strFile));
		}
```

File: core-bundle/src/Resources/contao/library/Contao/Files.php [hunk 4]
```diff
@@ -156,6 +156,11 @@ public function fopen($strFile, $strMode)
 	{
 		$this->validate($strFile);
 
+		if ($strMode[0] !== 'r')
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Files.php]:
```suggestion
		if ($strMode[0] !== 'r' && \dirname($strFile) && \dirname($strFile) !== '.')
```

Otherwise files from the root directory could cause problems I think `->fopen('foo.txt')`.
_(A reason why I’d prefer using Symfony Filesystem ☺️)_

Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: what would that "attack" look like? `./file.php`?

Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: also, wouldn't that be catched by `is_dir` in `mkdir`?

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: `Files::getInstance()->fopen('test.txt', 'w')` results in `$this->mkdir('.')` and `'.'` is an insecure path (I hope).

Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php:159]: changed in 8209e66dbc84d36c41db05dafebb797a00980c55

Comment (aschempp) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: changed in 8209e66dbc84d36c41db05dafebb797a00980c55

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Resources/contao/library/Contao/Files.php [hunk 5]
```diff
@@ -156,6 +156,11 @@ public function fopen($strFile, $strMode)
 	{
 		$this->validate($strFile);
 
+		if ($strMode[0] !== 'r' && \dirname($strFile) && \dirname($strFile) !== '.')
+		{
+			$this->mkdir(\dirname($strFile));
+		}
+
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Files.php]:
```suggestion
		if ($strMode[0] != 'r' && ($strPath = \dirname($strFile)) && $strPath != '.')
		{
			$this->mkdir($strPath);
		}

```

This might not be a problem at all due to the stat cache, but since `dirname()` calls are potentially expensive, it seems better to store the result in a variable.

Comment (Toflar) [reply core-bundle/src/Resources/contao/library/Contao/Files.php]: They are free in case of disabled open_basedir but we should change it anyway 👍

**Review by leofeyer — APPROVED** [review]

**Review by Toflar — APPROVED** [review]
