### PR TITLE
Do not add request attributes to forward URLs

### LINKED ISSUE #9691: Wrong redirect with intern 301 redirect
### Affected version(s)

5.7.3

### Description

If you create a page with type "intern redirect" and select another page as redirect-target, you'll get redirected correctly but with Contao params in the URL.
Sth like this:
`http://my-site./redirect-target?_controller=Contao%5CCoreBundle%5CController%5CPage%5CForwardPageController&_canonical_route=tl_page.24&_route=tl_page.24&_route_params%5B_scope%5D=frontend&_route_params%5B_locale%5D=de&_route_params%5B_format%5D=html&_route_params%5B_canonical_route%5D=tl_page.24&_firewall_context=security.firewall.map.context.contao_frontend&_security_firewall_run=_security_contao_frontend`

### PR DESCRIPTION
**Pull request by lukasbableck**
Fixes https://github.com/contao/contao/issues/9691

Currently the requests attributes are added to the forward URL in the ForwardPageController, which produces forward URLs like this:
```
http://my-site./redirect-target?_controller=Contao%5CCoreBundle%5CController%5CPage%5CForwardPageController&_canonical_route=tl_page.24&_route=tl_page.24&_route_params%5B_scope%5D=frontend&_route_params%5B_locale%5D=de&_route_params%5B_format%5D=html&_route_params%5B_canonical_route%5D=tl_page.24&_firewall_context=security.firewall.map.context.contao_frontend&_security_firewall_run=_security_contao_frontend
```

This is fixed by this PR while also simplifying the query param handling, as those can just be passed in the `generateContentUrl` method call instead of using `http_build_query` and appending them to the URL.

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Review by fritzmg — DISMISSED** [review]

**Review by Toflar — COMMENTED** [review]
I think @aschempp should review this. Because the code looks like it does not pass the query parameters as parameters for url generation on purpose (missing a comment though.....).
I think this was very likely done on purpose because otherwise a parameter would also be used for a path placeholder.

**Review by aschempp — CHANGES_REQUESTED** [review]
This approach would no longer include URL parameters (e.g. `auto_item` stuff) when generating the forward page.

What we would need to do is something like this (untested):

```php
$route = $this->pageRegistry->getRoute($forwardPage);
$parameters = [
    array_intersect_key($route->compile()->getVariables(), $request->attributes->all()),
    $request->query->all()
];

$this->generateContentUrl($forwardPage, $parameters, …);
```

It might be simpler (and possibly better due to naming conflicts) to keep the qurey stuff and only use the compiled route variables for the url generator.

**Comment by lukasbableck** [comment]
Good point, didn't event know that's supported tbh 😅 
Should be fine now

File: core-bundle/src/Controller/Page/ForwardPageController.php [hunk 1]
```diff
@@ -27,13 +28,16 @@
 #[AsPage(contentComposition: false)]
 class ForwardPageController extends AbstractController implements DynamicRouteInterface
 {
-    public function __construct(private readonly LoggerInterface|null $logger = null)
-    {
+    public function __construct(
+        private readonly LoggerInterface|null $logger = null,
+        private readonly PageRegistry|null $pageRegistry = null,
```
Comment (aschempp) [inline core-bundle/src/Controller/Page/ForwardPageController.php:33]: The page registry can never be `null`, it always exists in Contao.

File: core-bundle/src/Controller/Page/ForwardPageController.php [hunk 2]
```diff
@@ -42,7 +46,7 @@ public function __invoke(Request $request, PageModel $pageModel): RedirectRespon
         }
 
         return $this->redirect(
-            $this->generateContentUrl($forwardPage, $request->attributes->all(), UrlGeneratorInterface::ABSOLUTE_URL).$queryString,
+            $this->generateContentUrl($forwardPage, array_intersect_key($request->attributes->all(), array_flip($route?->compile()->getVariables() ?? [])), UrlGeneratorInterface::ABSOLUTE_URL).$queryString,
```
Comment (aschempp) [inline core-bundle/src/Controller/Page/ForwardPageController.php:49]: The page registry will always return a route (the method return definition requires it), so there is no need for `$route?...`

**Review by aschempp — CHANGES_REQUESTED** [review]
Almost good! 🙃

File: core-bundle/src/Controller/Page/ForwardPageController.php (hunk 1 above)
Comment (lukasbableck) [reply core-bundle/src/Controller/Page/ForwardPageController.php:33]: True, but then we would need 3 additional, basically useless, mocks in 7 tests, that's why I made it optional. 😅
Or is there another way I'm missing?

Comment (leofeyer) [reply core-bundle/src/Controller/Page/ForwardPageController.php]: @aschempp /ping

Comment (aschempp) [reply core-bundle/src/Controller/Page/ForwardPageController.php]: I don't think we ever allow a service to be null that cannot be null just to make tests simpler… so I would suggest empty mocks.

Comment (lukasbableck) [reply core-bundle/src/Controller/Page/ForwardPageController.php]: Ok, updated in [c877fd7](https://github.com/contao/contao/pull/9692/commits/c877fd76d6e24966f3aae10980ccdbcb3becd5d6) 😊

**Comment by lukasbableck** [comment]
CI failures are unrelated

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @lukasbableck.
