### PR TITLE
Handle ampersands in the alt attribute of the picture insert tag

### LINKED ISSUE #7754: The picture insert tag fails if the alt attribute contains '&'
### Affected version(s)

5.3.x

### Description

Generating a picture with the picture insert tag fails with an undefined array key error if the alt attribute contains '&' .
The error occurs even if the alt value has been url encoded.

```
{{picture::path/to/image.jpeg?size=2&alt=Foo & Bar}} // fails
{{picture::path/to/image.jpeg?size=2&alt=Foo &amp; Bar}} // fails
{{picture::path/to/image.jpeg?size=2&alt=Foo%20%26%20Bar}} // fails
```

### PR DESCRIPTION
**Pull request by markocupic**
Fixes https://github.com/contao/contao/issues/7754

When using the picture insert tag, an error message appears if the ALT attribute contains the ampersand. Even if this url was encoded. 

This fix should resolve the error by url decoding the string slightly later. 

But I would be glad if someone could review my fix.

### CODE REVIEW

File: core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php [hunk 1]
```diff
@@ -501,12 +501,12 @@ public function __invoke(ResolvedInsertTag $insertTag): InsertTagResult
...
                 // Take arguments
                 if (str_contains($insertTag->getParameters()->get(0), '?')) {
-                    $arrChunks = explode('?', urldecode($insertTag->getParameters()->get(0)), 2);
+                    $arrChunks = explode('?', $insertTag->getParameters()->get(0), 2);
                     $strSource = StringUtil::decodeEntities($arrChunks[1]);
                     $arrParams = explode('&', $strSource);
 
                     foreach ($arrParams as $strParam) {
-                        [$key, $value] = explode('=', $strParam);
+                        [$key, $value] = explode('=', urldecode($strParam));
```
Comment (ausi) [inline core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php]:
```suggestion
                        [$key, $value] = explode('=', urldecode($strParam), 2);
```
Otherwise encoded `=` in the value part would not be supported.

**Review by ausi — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @markocupic.
