### PR TITLE
Fix a possible CSRF cookie race condition

### LINKED ISSUE #5772: CSRF cookie race condition
### Affected version(s)

4.9

### Description

We currently have two extra requests for pages that are always served from cache, `/_contao/check_cookies` and `/_contao/request_token_script`. In some cases this can lead to a race condition because both routes try to set a different CSRF cookie.

I think the best fix would be to never set a CSRF cookie in the `/_contao/check_cookies` route.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5772

### CODE REVIEW

File: core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php [hunk 1]
```diff
@@ -49,7 +49,13 @@ public function onKernelRequest(RequestEvent $event): void
...
         }
 
-        $this->tokenStorage->initialize($this->getTokensFromCookies($event->getRequest()->cookies));
+        $request = $event->getRequest();
+
+        if (false === $request->attributes->get('_token_check')) {
+            return;
+        }
+
+        $this->tokenStorage->initialize($this->getTokensFromCookies($request->cookies));
```
Comment (ausi) [inline core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php]:
```suggestion
        $this->tokenStorage->initialize($this->getTokensFromCookies($event->getRequest()->cookies));
```

I think we should only skip the response event, not the token storage initialization.

Comment (leofeyer) [reply core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php]: Changed in faaa63dfa1172b9e39ee7659df837cd5ea4d6de5.

**Review by ausi — APPROVED** [review]
