### PR TITLE
Fix the picker for child tables without PID

### LINKED ISSUE #2046: Content element selector doesn't let you select elements, only pages and articles
**Affected version(s)**

Contao 4.9.2

**Description**

The content element selector in backend doesn't let you pick an element. Only lets you pick pages or articles.

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2046

A picker that picks elements from a child table like the one used in the include content element currently creates links like `?do=article&table=tl_content` which show an empty page because the pid (`id=`) is missing.

If there is a `CURRENT_ID` in the session, an arbitrary page might show up instead of an empty page, or it causes a permission error as in #2046.

This pull request fixes this by only adding the `table=` parameter if there is a valid pid.

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]
Tested and confirmed 👍

File: core-bundle/src/Picker/AbstractTablePickerProvider.php [hunk 1]
```diff
@@ -226,36 +231,29 @@ protected function getPtableAndPid(string $table, string $value): array
...
 
-        if (false === $data) {
-            return [null, null];
+            $data = $qb->execute()->fetch();
         }
 
-        $pid = (int) $data['pid'];
-
         if ($dynamicPtable) {
             $ptable = $data['ptable'] ?: $ptable;
```
Comment (leofeyer) [inline core-bundle/src/Picker/AbstractTablePickerProvider.php]: IIRC, `$data` can be `false` at this point. Should we replace `?:` with `??`?

Comment (fritzmg) [reply core-bundle/src/Picker/AbstractTablePickerProvider.php]: In Contao 4.9, `ptable` can be an empty string: https://github.com/contao/contao/blob/2bc452ebc042a476285243a3c2371c1fa0203a9b/core-bundle/src/Resources/contao/dca/tl_content.php#L18

Comment (ausi) [reply core-bundle/src/Picker/AbstractTablePickerProvider.php]:
```suggestion
            if (!empty($data['ptable'])) {
                $ptable = $data['ptable'];
            }
```

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
