### PR TITLE
Do not render the SERP preview on POST requests

### LINKED ISSUE #8587: Changing the `pagetype` of an error page to `regular` throws an error
### Affected version(s)

5.3.*

### Reproducer

1. Login into the contao demo
2. Change the pagetype of the 404 to regular

### Description

Due to the limitation of not being able to copy error pages, I tried to change the page type to type `regular` and then copy it. This however ends up in an error due to not being able to generate a content URL due to a missing url_callback for the SERP Widget.

<details>
<summary>Stacktrace 2/2 - LogicExeption</summary>

```
LogicException:
Unable to generate a content URL for the SERP widget, please provide the url_callback.

  at vendor/contao/core-bundle/contao/widgets/SerpPreview.php:176
  at Contao\SerpPreview->getUrl(object(PageModel))
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:54)
  at Contao\SerpPreview->generate()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:652)
  at Contao\Widget->generateWithError(true)
     (vendor/contao/core-bundle/contao/templates/backend/be_widget.html5:3)
  at include('/html/contao/vendor/contao/core-bundle/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/contao/library/Contao/TemplateInheritance.php:109)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:600)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:789)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2208)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:462)
  at Contao\Backend->getBackendModule('page', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)
```
</details>

<details>
<summary>Stacktrace 1/2 - LogicExeption</summary>

```
Symfony\Component\Routing\Exception\RouteNotFoundException:
This route is not routable

  at vendor/contao/core-bundle/src/Routing/Page/UnroutablePageRouteCompiler.php:23
  at Contao\CoreBundle\Routing\Page\UnroutablePageRouteCompiler::compile(object(PageRoute))
     (vendor/symfony/routing/Route.php:410)
  at Symfony\Component\Routing\Route->compile()
     (vendor/contao/core-bundle/src/Routing/ContentUrlGenerator.php:92)
  at Contao\CoreBundle\Routing\ContentUrlGenerator->generate(object(PageModel), array(), 0)
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:172)
  at Contao\SerpPreview->getUrl(object(PageModel))
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:54)
  at Contao\SerpPreview->generate()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:652)
  at Contao\Widget->generateWithError(true)
     (vendor/contao/core-bundle/contao/templates/backend/be_widget.html5:3)
  at include('/html/contao/vendor/contao/core-bundle/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/contao/library/Contao/TemplateInheritance.php:109)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:600)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:789)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2208)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:462)
  at Contao\Backend->getBackendModule('page', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)                
```
</details>

### PR DESCRIPTION
**Pull request by aschempp**
Fixes #8587

The SERP preview should never be generated for post request to prevent issues with inconsistent data. The only case where the post-generated SERP widget would show up is if the form has errors and the page is not reloaded.

### CODE REVIEW

File: core-bundle/contao/widgets/SerpPreview.php [hunk 1]
```diff
@@ -34,6 +34,11 @@ class SerpPreview extends Widget
 	 */
 	public function generate()
 	{
+		if (Input::isPost())
+		{
+			return '<div class="serp-preview"><p class="tl_gerror">' . $GLOBALS['TL_LANG']['MSC']['noSerpPreviewPost'] . '</p></div>';
```
Comment (leofeyer) [inline core-bundle/contao/widgets/SerpPreview.php]:
```suggestion
			return '<div class="serp-preview"><p class="tl_info">' . $GLOBALS['TL_LANG']['MSC']['noSerpPreviewPost'] . '</p></div>';
```

I don't know if we need this feature at all, but if we want to add it, it should be an info message and not an error message.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
