### PR TITLE
Catch exceptions to prevent the resize images command from failing

### LINKED ISSUE #2176: Issue with subprocesses in ResizeImagesCommand
**Affected version(s)**

4.9

**Description**

Stacktrace:

```
Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "11".
#11 /vendor/symfony/process/Process.php(428): Symfony\Component\Process\Process::wait
#10 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(355): Contao\CoreBundle\Command\ResizeImagesCommand::finishSubProcess
#9 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(286): Contao\CoreBundle\Command\ResizeImagesCommand::executeConcurrent
#8 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(196): Contao\CoreBundle\Command\ResizeImagesCommand::resizeImages
#7 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(160): Contao\CoreBundle\Command\ResizeImagesCommand::execute
#6 /vendor/symfony/console/Command/Command.php(255): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/console/Application.php(1018): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application::run
#0 /vendor/contao/manager-bundle/bin/contao-console(38): null
```

`11` is segfault. I think we should catch those because if one subprocess fails all that happens is that the respective image is not created which is no big deal. However, right now it stops the parent process from continuing to work on all the other images. I think we should try-catch-wrap those.
However, I'm not sure if we should somehow check the number of failures and compare it with the total number of processes executed. If all of them fail, something might be wrong. If one out of 100 fails, it's no big deal...

/cc @ausi

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2176

### CODE REVIEW

**Review by Toflar — COMMENTED** [review]
Are you sure we should only catch them and not have some threshold as to where we consider the main command to fail?

**Comment by ausi** [comment]
I can’t think a good threshold. If such errors occur for specific images there might be many consecutive failures.

How about remembering the errors and exit the command with status code `1` if one of the subcommands failed?

**Comment by Toflar** [comment]
The problem is that failing will be quite common so that command would always fail. I don't think that's a good default.
I think we should allow failure but if all of the image resizes fail then likely there is an issue.

**Comment by ausi** [comment]
> I think we should allow failure but if all of the image resizes fail then likely there is an issue.

Makes sense 👍. I will update the pull request.

**Comment by ausi** [comment]
Done in e895a000400395a60d8cf2493414777504487f7f.

File: core-bundle/src/Command/ResizeImagesCommand.php [hunk 1]
```diff
@@ -325,14 +329,30 @@ private function executeConcurrent(float $timeLimit, float $concurrent): int
...
+
+        if ($failedCount > 0) {
+            $this->io->writeln('Resizing of '.$failedCount.' images failed.');
+        }
+
+        if (0 !== $failedCount && $count - $failedCount <= 0) {
+            $this->io->error('No image could be resized successfully.');
+
+            return 1;
+        }
```
Comment (m-vo) [inline core-bundle/src/Command/ResizeImagesCommand.php:355]: Shouldn't this condition be in line 345? If everything fails this will now output:
```
Resized 0 Images successfully.
Resizing of n images failed.
No image could be resized successfully.
```

File: core-bundle/src/Command/ResizeImagesCommand.php [hunk 2]
```diff
@@ -325,14 +329,30 @@ private function executeConcurrent(float $timeLimit, float $concurrent): int
...
             unset($processes[$index]);
             $this->updateOutput($processes, $counts, $paths);
         }
 
         $this->tableOutput->clear();
 
-        $this->io->writeln('Resized '.array_sum($counts).' Images.');
+        $count = array_sum($counts);
+
+        $this->io->writeln('Resized '.($count - $failedCount).' Images successfully.');
```
Comment (m-vo) [inline core-bundle/src/Command/ResizeImagesCommand.php]:
```suggestion
        $this->io->writeln('Resized '.($count - $failedCount).' images successfully.');
```

File: core-bundle/src/Command/ResizeImagesCommand.php (hunk 1 above)
Comment (ausi) [reply core-bundle/src/Command/ResizeImagesCommand.php:355]: I think the output is OK this way. The error is formatted differently to the info messages:
Bildschirmfoto 2020-08-24 um 15 36 58

**Review by Toflar — DISMISSED** [review]

**Review by m-vo — DISMISSED** [review]

**Review by m-vo — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
