### PR TITLE
Correctly check if the core modules are installed for comments

### LINKED ISSUE #8408: AddCommentFieldsListener to creedy
### Affected version(s)

5.3.33

### Description

The AddCommentFieldsListener of comments bundle may lead to an exception is some edge cases.

My scenario: 
- FAQ bundle not installed
- Comments bundle installed
- an external extension has an tl_faq.php file
- an other bundle adds a callback listener to all dca's that are loaded through the loadDataContainer hook

Result when trying to delete something in the contao backend:

Image

Solution as discussed in [slack](https://contao.slack.com/archives/CK4J0KNDB/p1749200662076569):
Check if palette exist in AddCommentFieldsListener

I will try to provide an PR in the next days.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes #8408

Checking for bundles is already present in that listener, just not executed for the parent and child fields.

The tests are still exactly the same, I just refactored them to use a `dataProvider` instead of a private teste function (which I think is "more correct").

### CODE REVIEW

File: comments-bundle/src/EventListener/DataContainer/AddCommentFieldsListener.php [hunk 1]
```diff
@@ -134,6 +145,18 @@ private function applyParentFields(string $table): void
 
     private function applyChildFields(string $table): void
     {
+        $isInstalled = match ($table) {
+            'tl_news' => isset($this->bundles['ContaoNewsBundle']),
+            'tl_calendar_events' => isset($this->bundles['ContaoCalendarBundle']),
+            'tl_faq' => isset($this->bundles['ContaoFaqBundle']),
+            default => throw new \RuntimeException('Unsupported table '.$table),
+        };
+        dump($table, $this->bundles, $isInstalled);
```
Comment (fritzmg) [inline comments-bundle/src/EventListener/DataContainer/AddCommentFieldsListener.php]:
```suggestion
```

**Review by leofeyer — APPROVED** [review]

**Review by zoglo — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]
