### PR TITLE
Fix the base path for canonical URLs

### LINKED ISSUE #7606: Canonical URLs are incorrectly generated
### Affected version(s)

4.13.49

### Description

I have a multilingual website with several page trees. If I now manually select another page from another page tree in the page structure, the URL is generated incorrectly.
The prefix is also added to the URL. (See screenshot)

screen-20241007_sURaup2h

### PR DESCRIPTION
**Pull request by fritzmg**
Same as #7767 for Contao 4.13.

### CODE REVIEW

File: core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php [hunk 1]
```diff
@@ -101,7 +101,7 @@ public function createContaoWebpageResponseContext(PageModel $pageModel): Respon
                     throw new \RuntimeException('The request stack did not contain a request');
                 }
 
-                $url = UrlUtil::makeAbsolute($url, $request->getUri());
+                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().'/'.$request->getBasePath());
```
Comment (ausi) [inline core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php]:
```suggestion
                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().$request->getBasePath().'/');
```

**Review by ausi — CHANGES_REQUESTED** [review]

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
