### PR TITLE
Fix several Turbo issues

### LINKED ISSUE #7391: tinyMCE/ace not restored after Turbo page transition
### Affected version(s)

5.4

### Description

With the changes from #7387 there now are two issues after saving a record with a tinyMCE/ace field:

* The tinyMCE Editor is gone (gets destroyed somehow/not reinitialized).
* The ace editor loses its size and only restores it after clicking into it.
 
Sidenote: For ace, we're currently using some rather complicated init stuff to make it use its full height. This could probably simplified to something like that (maybe already fixing the issue):
```js
const editor = ace.edit(element, {
    theme: document.documentElement.dataset.colorScheme === 'dark' ? 'ace/theme/twilight' : 'ace/theme/clouds',
    mode: 'ace/mode/foo',
    maxLines: 100, // >= lines from content
    wrap: true,
    useSoftTabs: false,
    autoScrollEditorIntoView: true,
});

editor.container.style.lineHeight = '1.45';
whitespace.detectIndentation(editor.getSession());
``` 

/cc @zoglo

### LINKED ISSUE #7399: Page layout - Custom JavaScript code multiple lines
### Affected version(s)

5.4.0-RC2

### Description

there are 1 or more Custom JavaScript code lines - all numbered with #1 
Click `Save` » the next one will added. Numbered with #1 too
Click `Save and close` and reopen » the number of lines plus one more will be shown

local Installation Laragon, Windows 11
php82

### LINKED ISSUE #7402: Unable to submit / save new elements with tinyMCE
### Affected version(s)

5.4.0-RC2

### Description

When trying to save a new `text-element`, you can't save / submit the form due to following validation error in the developer console:
```js
An invalid form control with name='text' is not focusable.
```
The textarea for `text` is required but is set to `display: none`, thus not being focusable.

There's also an issue on trying to update mandatory fields using TinyMCE

Related issue on TinyMCE:
https://github.com/tinymce/tinymce/issues/2584

Related commit of a former fix:
https://github.com/Probesys/bileto/commit/5d1e324fc87082be6fcc20286c06fa1a8fea43ef
> This commit also explains that it may be a side effect of turbo in their case and it removes the required attribute

/cc @m-vo

### LINKED ISSUE #7403: Delayed "confirm to leave"
### Affected version(s)

5.4.x

### Description

Unfortunately there is one additional (somewhat cosmetic) issue that arises with Turbo: the JavaScript pop-up to confirm that you want to leave the page will be "delayed". Try the following:

* Create a new `text` content element.
* Enter some text in the **Text** TinyMCE, but don't save.
* Hover over Content » Forms (to prefetch), then click on Content » Forms (issue might also arise without prefetch).
* Click to edit a form or its form fields.

The JavaScript pop-up to confirm to leave the page (originating from entering a text in the TinyMCE of the `text` content element from before) will now show.

### PR DESCRIPTION
**Pull request by m-vo**
This PR tries to fix several Turbo related issues.

#### Callbacks
See #7391 for the original issue. In #7394 we're using a Stimulus controller and JSON serialized the config. But this
broke callbacks. In 07ca6e9561b9bf8a300b49ce32f737f6f99a77a4 I therefore switched to an expando property instead, which also removes the need to serialize/deserialize. This should resolve #7402 since now the `setup` callback is run again, which - in our case - removes the `required` attribute. In the future we could move those "technical" things out of the template into the controller - for now I wanted to have the fewest possible changes to the template.

#### Event order (Webkit)
Another problem with the tinyMCE only appeared in Webkit browsers: There, the connect event in our Stimulus controller was run before the disconnect event of the previous element with the same id. And because tinyMCE creates editor ids based on element ids, initializing the respective editor failed (because the same id still existed). I solved this in 802506362a62000582225298c37eb96b745c271d by forcing tinyMCE to create unique ids and only reference editors by the created id.

#### Caching
I disabled caching for pages having the tinyMCE editor on them (0c1933da6524ef44317b59a636888095b83ea88b), otherwise snapshots don't work correctly. They are made using `cloneNode` and while I got attached properties to work, there were other weird side effects, likely caused by the way the tinyMCE editor is built.

#### Delayed "confirm to leave"
See #7403. Normally, when leaving a page, the `BeforeUnloadEvent` gets dispatched. TinyMCE's autosave plugin listens to this event and - if the editor is "dirty" - sets a message. The browser then displays that message in a  nativeconfirm dialog. In order to restore this behavior even on Turbo visits, we're now listening to the `turbo:before-visit` event, dispatch our own `BeforeUnloadEvent` and use the set `returnValue` in a programmatic confirm dialog (8ae1c905c282a5eb16bac44f6a6e427d406ffcc1). Unfortunately, I had to use the old way of initializing events (`createEvent`/`initEvent` instead of event constructors), because otherwise the returned value would not be accessible. Not sure if there is any other way to accomplish this.

### Chosen
Since we're basically invoking chosen (`<el>.chosen()`) for all selects with a class `tl_chosen` on `domready`, this leads to issues described in #7399 if the event gets executed over again. The chosen library actually checks for the existence of a class `chzn-done` before creating an instance but this class does not get set, apparently. So it's another Stimulus controller again.

### ace
You guessed it: Stimulus controller. This should fix #7399.

### Other stuff
I disabled Turbo Drive in the SerpWidget for now. Otherwise it's also broken after submitting the form.

### CODE REVIEW

File: core-bundle/assets/backend.js [hunk 1]
```diff
@@ -22,6 +22,23 @@ application.load(context.keys().map((key) => {
...
+                }
+            })
+        }
+    }
+}).observe(document, {
+    attributes: false,
+    childList: true,
+    subtree: true
+});
+
```
Comment (fritzmg) [inline core-bundle/assets/backend.js]: Hm, can't we add the attribute via the data container output?

Comment (m-vo) [reply core-bundle/assets/backend.js]: We should do this, yes, but I thought it's very likely people are relying on the mechanism (just adding a class).

Comment (fritzmg) [reply core-bundle/assets/backend.js]: Hm, I guess so, yeah.

Comment (m-vo) [reply core-bundle/assets/backend.js]: I replaced all occurrences where we output `tl_chosen` with the respective `data-controller` attribute in 28f00e7a795ec43e2679608b1a7c569871c6ba58. I think would be fine with removing the BC layer then. Wdyt?

**Comment by m-vo** [comment]
Here is some background information for why some things were failing:

When Turbo caches a page, it will create a so-called _snapshot_. This is done by using `cloneNode(true)` which will effectively remove all attached data and event listeners. If there are any things on the page, that were dynamically built and don't clean up after themselves (e.g. an open popup), they need to be reset in a `turbo:before-cache` event, so that the snapshot has a clean baseline. Alternatively, things can be annotated with `data-turbo-temporary` and are then automatically excluded from the snapshots as well.

For making the mootools stuff work, we have a `turbo:render` listener, that fires `domready` and then sets a marker property on the `body` element - as long as the marker is there, subsequent invocations of the listener won't fire the `domready` event again. This works for page transitions but not for caching. So when you navigated back, the restored snaphot would still contain the ("dead") HTML of e.g. chosen , the marker property would be gone and then `domready` would fire again. As a result, you would see another chosen select and so on. 

The beauty of Stimulus is, that it's easy to support the full life cycle of adding/removing dynamic things to/from the DOM with the `connect` and `disconnect` events. So that's why I used it over custom code in a `turbo:before-cache` listener to solve the issues as it will also improve things when using Turbo Streams in the future. That does not mean we can't utilize such a listener for other edge cases should they come up.

**Review by fritzmg — CHANGES_REQUESTED** [review]
Unfortunately the whole ACE editor configuration needs to stay adjustable. People have created custom `be_ace` templates in order to disable autocomplete for example, as this makes the editor slow in some browsers.

**Comment by m-vo** [comment]
> Unfortunately the whole ACE editor configuration needs to stay adjustable. 

Addressed in 523d6791c2487902e4c1c092f5f25a2bca2729a8 - now there is a config callback using the same object property strategy as with the tinyMCE controller.

File: core-bundle/assets/controllers/tinymce-controller.js [hunk 2]
```diff
@@ -1,15 +1,59 @@
...
+        // Move the config to a member variable to prevent memory leaks.
+        this.config = {
+            ...this.element.tinymceConfig,
+            ...{
+                target: this.element
+            }
+        };
+
+        delete this.element.tinymceConfig;
+
```
Comment (m-vo) [inline core-bundle/assets/controllers/tinymce-controller.js]: We could probably omit this part (now that I know how snapshots work), because it will never leak and then use `element.tinymceConfig` in L33 instead of `this.config`.

Comment (leofeyer) [reply core-bundle/assets/controllers/tinymce-controller.js]: Then let‘s omit this 👍

File: core-bundle/assets/backend.js (hunk 1 above)
Comment (leofeyer) [reply core-bundle/assets/backend.js]: Yes, let‘s remove it then.

Comment (fritzmg) [reply core-bundle/assets/backend.js]: Not sure. I also have projects where I simply added the `chosen` class. I mean it's fine for me as I will know to change this to `data-controller="contao--chosen"` when upgrading to 5.4, but I guess it's still a BC break?

**Review by zoglo — COMMENTED** [review]
I just tested everything that this PR tries to solve:

**Working**
https://github.com/contao/contao/issues/7391 ✅
https://github.com/contao/contao/issues/7399 ✅ 
https://github.com/contao/contao/issues/7403 ✅ 

**Partially working**
This one works on first save, however doesn't work on the second save after *saving* once
https://github.com/contao/contao/issues/7402

File: core-bundle/assets/backend.js (hunk 1 above)
Comment (m-vo) [reply core-bundle/assets/backend.js]: I removed it for now. We can still re-add it later on if we decide it'S necessary.

**Comment by m-vo** [comment]
> Partially working
> This one works on first save, however doesn't work on the second save after saving once
> https://github.com/contao/contao/issues/7402

It's working for me in Chrome/Firefox/Epiphany (Webkit). Can you try to find out what's causing the problem and then open up a new issue? I think we should get this package going for now.

**Comment by zoglo** [comment]
> Can you try to find out what's causing the problem and then open up a new issue? I think we should get this package going for now.

As much as I tested, this might be related to some form submit issue on chromium (and windows) - Works fine with firefox tho

I agree with merging this - didn't find anything else

> and then open up a new issue? 

@m-vo will do - might be some form validation issue on windows (chrome), this doesn't stop merging this tbh

**Review by zoglo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Comment by zoglo** [comment]
@leofeyer @m-vo 

https://github.com/contao/contao/issues/7402 is fully working on chrome (windows) with a clean install using the newest release candidate
