### PR TITLE
Filter empty entries during validation for multi-file upload fields

### LINKED ISSUE #9370: Error message on multiple upload field when no file is uploaded
### Affected version(s)

5.7.x-dev

### Description

When a form is submitted without uploading a file, an error occurs if the upload field is optional but has multiple upload enabled.

**Steps to Reproduce:**

1. Create form field type: File Upload
2. Set "Mandatory field": No
3. Enable "Allow multiple files"
4. Use default settings for all other options
5. Submit form in frontend without uploading a file

**Expected Result:**

Form submits successfully (field is optional).

**Actual Result:**

Error message appears:
```
The name of at least one uploaded file contains invalid characters or exceeds the maximum length of 255 characters!
```

### PR DESCRIPTION
**Pull request by lukasbableck**
Fixes #9370 

Before checking if the `name` array of `$_FILES` is empty, it has to be passed through `array_filter` to remove empty entries, which are present if no files are selected and the field is not mandatory.

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Review by zoglo — DISMISSED** [review]

File: core-bundle/contao/forms/FormUpload.php [hunk 1]
```diff
@@ -116,7 +116,7 @@ public function __get($strKey)
 	public function validate()
 	{
 		// No file specified
-		if (!isset($_FILES[$this->strName]) || empty($_FILES[$this->strName]['name']))
+		if (!isset($_FILES[$this->strName]) || (\is_array($_FILES[$this->strName]['name']) ? empty(array_filter($_FILES[$this->strName]['name'])) : empty($_FILES[$this->strName]['name'])))
```
Comment (leofeyer) [inline core-bundle/contao/forms/FormUpload.php]:
```suggestion
		if (!isset($_FILES[$this->strName]) || empty($_FILES[$this->strName]['name']) || (\is_array($_FILES[$this->strName]['name']) && empty(array_filter($_FILES[$this->strName]['name']))))
```

This way `$_FILES[$this->strName]['name']` isn't passed to `is_array()` if it's empty. Does this make more sense?

Comment (lukasbableck) [reply core-bundle/contao/forms/FormUpload.php]: Theoretically the `is_array()` could be dropped entirely by casting to an array, that makes it way simpler IMO. 
Just found out that casting a string to an array returns an array with that string at position 0. 😄 

```php
if (!isset($_FILES[$this->strName]) || empty(array_filter((array) $_FILES[$this->strName]['name'])))
```
WDYT?

(This could then of course also be used here to drop the `is_array()` https://github.com/contao/contao/pull/9373/changes#diff-1ef1c840705db9a70cd578e1e2fce406f178f909ff0e177cca45059e0d16b245R138)

Comment (leofeyer) [reply core-bundle/contao/forms/FormUpload.php]: Even better 😄

Comment (lukasbableck) [reply core-bundle/contao/forms/FormUpload.php]: I've updated the PR 🙂

**Review by leofeyer — APPROVED** [review]
