### PR TITLE
Fix some context menu quirks

### LINKED ISSUE #7908: Context menu UX issues
### Affected version(s)

5.5.x

### Description

Minor UX issue: if you first open the context menu by right-clicking - and then click on ⋯, the context menu (under ⋯) will briefly open but then immediately close again. The document click listener probably needs an additional check whether the `event.currentTarget` is also not the ⋯.

### PR DESCRIPTION
**Pull request by m-vo**
This fixes some of the UX issues mentioned in https://github.com/contao/contao/issues/7908#issuecomment-2603118759:

* [x] When opening the context menu using the keyboard, the position is where it was last opened (using the mouse) - not always near the button like it is the case when reloading the page.
* [x] Hitting `Esc` should IMHO close the menu. At least this is how every application I use is handling this.
* [x] Using the keyboard to open the context menu doesn't close the previous instances. I.e. you can open multiple context menus.
* [x] Clicking inside an open menu, dragging the mouse to another `…` button and then releasing the mouse will open a second menu.

### CODE REVIEW

**Comment by m-vo** [comment]
@zoglo, @aschempp Feel free to directly push to this PR if you want to change things.

**Comment by zoglo** [comment]
This also fixes #7908 @m-vo am I right?

I could not reproduce this anymore:
> the context menu (under ⋯) will briefly open but then immediately close again. The document click listener probably needs an additional check whether the event.currentTarget is also not the ⋯.

File: core-bundle/assets/controllers/operations-menu-controller.js [hunk 1]
```diff
@@ -16,13 +19,17 @@ export default class extends Controller {
         document.addEventListener('pointerdown', this.close);
```
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js]: This could be:
```data-action="pointerdown@document->contao--operations-menu#close"```

File: core-bundle/assets/controllers/operations-menu-controller.js [hunk 2]
```diff
@@ -33,6 +40,7 @@ export default class extends Controller {
 
     disconnect () {
         document.removeEventListener('pointerdown', this.close);
+        document.removeEventListener('keydown', this.closeOnEscape);
     }
```
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js]: We can completeley remove it if we use the data-actions in controller initializations

File: core-bundle/assets/controllers/operations-menu-controller.js [hunk 3]
```diff
@@ -62,12 +70,18 @@ export default class extends Controller {
...
+        if (this.$menu) {
             this.$menu.elements.controller.close();
         }
     }
 
+    closeOnEscape(event) {
+        if (event.key === 'Escape') {
+            this.close();
+        }
+    }
```
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js]: I'd rather go with something like this data-action and remove this completely
```data-action="keydown.esc@document->contao--operations-menu#close"```

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/assets/controllers/operations-menu-controller.js [hunk 4]
```diff
@@ -1,11 +1,14 @@
...
 import AccessibleMenu from 'accessible-menu';
 
-export default class extends Controller {
+export default class OperationsMenuController extends Controller {
+    static instances = [];
     static targets = ['menu', 'controller', 'title'];
 
     initialize () {
         this.close = this.close.bind(this);
+        this.closeOnEscape = this.closeOnEscape.bind(this);
```
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js]: Could remove those if we got with the data actions

File: core-bundle/assets/controllers/operations-menu-controller.js (hunk 2 above)
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js]: Same here 😀

**Comment by fritzmg** [comment]
Yes, that one is fixed as well as far as I tested.

**Review by zoglo — CHANGES_REQUESTED** [review]
/cc @aschempp 

We are actually creating our own listeners here whilst we could use data-actions for the controller initialization and let Stimulus handle the disconnects and the event listeners.

We could get rid of the disconnect method, the bind within initialize + the closeOnEscape if we simply add the following data-actions to the controller:

```
data-action="keydown.esc@document->contao--operations-menu#close pointerdown@document->contao--operations-menu#close"
```

Is there a reason we are not doing it that way?

**Comment by zoglo** [comment]
/cc @m-vo
/cc @aschempp 

See https://github.com/m-vo/contao/pull/9 for https://github.com/contao/contao/pull/7979#pullrequestreview-2584757634

TL;DR:
Refactored the manually added event listeners into data-actions.
And one day it's just a component and it'll be changed in just one place I hope 🙈

**Comment by m-vo** [comment]
I thought about adding events in "stimulus notation" as well. The one downside is, that reusability only comes once we've got templates for that. Maybe we should make a feature request over at Stimulus, to declare events, that are tightly coupled to the controllers (i.e. where it does not make sense to ever leave them out for an element), in the controllers themselves.

@zoglo I'll merge your PR in a minute, so that we can progress here.

**Comment by m-vo** [comment]
> I thought about adding events in "stimulus notation" as well. The one downside is, that reusability only comes once we've got templates for that.

For the record - I left a feature request about this, here: https://github.com/hotwired/stimulus/issues/811

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

File: core-bundle/assets/controllers/operations-menu-controller.js [hunk 5]
```diff
@@ -62,8 +58,8 @@ export default class extends Controller {
         this.setFixedPosition(event);
     }
 
-    close (event) {
-        if (this.$menu && !this.menuTarget.contains(event.target) && !this.controllerTarget?.contains(event.target)) {
```
Comment (zoglo) [inline core-bundle/assets/controllers/operations-menu-controller.js:66]: https://github.com/contao/contao/issues/7997 Removing this does lead to the actions not working as the close event should take this into consideration
