### PR TITLE
Fix the module wizard and section wizard scripts

### LINKED ISSUE #8129: Choices Select-Box nach Duplizieren nicht initialisiert
### Affected version(s)

5.5.1

### Description

Wenn ich in einem **Layout** unter **Frontend-Module** eine Zeile mit einem eingebundenen Modul dupliziere, lässt sich direkt danach das Modul nicht über die Select Box auswählen. Die Select Box ist nicht anklickbar.

In der Browser-Console wird folgender Fehler angezeigt:

`Trying to initialise Choices on element already initialised`

Image

Nach dem ersten Speichern funktioniert die Select Box wieder.

Getestet mit Safari 18.3

### LINKED ISSUE #8141: Eigene Layoutbereiche - Reihe dupliziert doppelt
### Affected version(s)

5.3.x, 5.5.x

### Description

mir bekannte Versionen: 5.3.26 und Online Demo 5.5.0

Beim Duplizieren 'Eigene Layoutbereiche' wird beim ersten duplizieren nur 1x (wie gewünscht) dupliziert. Ab dem zweiten mal duplizieren jeweils 2x,
Dies betrifft aber nur das Duplizieren, ab dem zweiten Icon. Dupliziert man weiter mit dem 1. Icon, wird wieder nur jeweils 1 neues item hinzugefügt.

Ist in der Online Demo nachvollziehbar

Windows 11
Browser Firefox 135.0.1

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #8129

This PR introduces templates for the `ModuleWizard` and `SectionWizard`, migrates the corresponding new-old vanilla JS to a Stimulus controller (`row-wizard`) and introduces template snapshots<sup>*)</sup> for each of the wizards rows.

*) The issue from #8129 shows a nasty problem: When clicking on "copy", we basically duplicated the `<tr>` element with all its children. This included things like choices instances that were already in their "wrapped" state (Choices modifies the DOM), so when inserting these, the respective controller connected, tried to init and failed (in the case of Choices, because the Choices script finds a certain data-attribute indicating an "active" instance). 

The new solution wraps the rows in `<template>` elements and lets the controller unwrap them. When doing so, a snapshot of the original HTML is created and stored. This snapshot is both used when copying a row and when restoring the original state before a cache entry is made.

### CODE REVIEW

File: core-bundle/assets/controllers/module-wizard-controller.js [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+        // We need to queue a micro task here, so that Stimulus will fire
+        // rowTargetConnected().
+        queueMicrotask(() => {this._unwrap(template)});
+    }
+
+    rowTargetConnected() {
+        this._makeSortable();
+    }
+
+    rowTargetDisconnected() {
```
Comment (m-vo) [inline core-bundle/assets/controllers/module-wizard-controller.js]:
```suggestion
    rowTargetDisconnected(row) {
```

Comment (m-vo) [reply core-bundle/assets/controllers/module-wizard-controller.js]: Assets need to be rebuilt.

**Review by zoglo — DISMISSED** [review]

File: core-bundle/assets/controllers/module-wizard-controller.js (hunk 1 above)
Comment (zoglo) [reply core-bundle/assets/controllers/module-wizard-controller.js]: Did that in 19f7e966d648532d02c7e4a0c4917f8c80359980 :)

File: core-bundle/assets/controllers/module-wizard-controller.js [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+        const newRow = row.nextElementSibling;
+        this.rowSnapshots.set(newRow, snapshot);
+
+        this._syncSelects(row, newRow);
+    }
+
+    delete(event) {
+        const row = this._getRow(event);
+
+        row.remove();
```
Comment (leofeyer) [inline core-bundle/assets/controllers/module-wizard-controller.js]:
```suggestion
        this._getRow(event).remove();
```

File: core-bundle/assets/controllers/module-wizard-controller.js [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+    }
+
+    enable(event) {
+        event.target.previousElementSibling.checked ^= 1;
```
Comment (leofeyer) [inline core-bundle/assets/controllers/module-wizard-controller.js]: Is `^=` correct here?

Comment (zoglo) [reply core-bundle/assets/controllers/module-wizard-controller.js]: Had to look it up as well, it's a bitwise XOR that toggles the checkbox:
true => false
false => true

Comment (leofeyer) [reply core-bundle/assets/controllers/module-wizard-controller.js]: 🦊

**Review by zoglo — DISMISSED** [review]

**Comment by m-vo** [comment]
This PR now includes the same changes for the `SectionWizard´ - I updated the PR title and initial description.

As both the `ModuleWizard` and the `SectionWizard` behave in a very similar way, instead of duplicating a lot of code, I implemented a `row-wizard` Stimulus controller that is used in both.

**Review by leofeyer — CHANGES_REQUESTED** [review]
Unfortunately, the module wizard does not work in Safari:

https://github.com/user-attachments/assets/13f8e1d4-52e0-472c-abf6-76e621ca51d8

The section wizard runs fine. Both run fine in Firefox.

**Comment by m-vo** [comment]
Time for some BrowserStack action. I'll try to fix this...

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
