### PR TITLE
Harden hyperlink controller against URLs that are null

### LINKED ISSUE #5761: CE Hyperlink - Internal Server Error "Argument #1 ($input) must be of type string, null given..."
### Affected version(s)

5.0.9

### Description

In Contao 5.0.9, if you create a content element "Hyperlink" and the just klick the back button, an Internal Server Error occurs. I could reproduce this in the online demo. Error message is:

`Contao\CoreBundle\InsertTag\InsertTagParser::replaceInline(): Argument #1 ($input) must be of type string, null given, called in .../contao/core-bundle/src/Controller/ContentElement/HyperlinkController.php on line 35`

After that you cannot approach any content element of that article any more.

How to reproduce:
in an article create a content element hyperlink. Don't fill in any of the forms, just klick the "back" button on top right.

In debug mode I get the following stacl trace:

```
TypeError:
Contao\CoreBundle\InsertTag\InsertTagParser::replaceInline(): Argument #1 ($input) must be of type string, null given, called in /.../vendor/contao/core-bundle/src/Controller/ContentElement/HyperlinkController.php on line 35

  at vendor/contao/core-bundle/src/InsertTag/InsertTagParser.php:35
  at Contao\CoreBundle\InsertTag\InsertTagParser->replaceInline(null)
     (vendor/contao/core-bundle/src/Controller/ContentElement/HyperlinkController.php:35)
  at Contao\CoreBundle\Controller\ContentElement\HyperlinkController->getResponse(object(FragmentTemplate), object(ContentModel), object(Request))
     (vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php:39)
  at Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController->__invoke(object(Request), object(ContentModel), 'main', null)
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2, false)
     (vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php:86)
  at Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(object(HttpKernel), object(Request), 2, false)
     (vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php:78)
  at Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render('/_fragment?_path=_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.content_element.hyperlink', object(Request), array('ignore_errors' => false))
     (vendor/symfony/http-kernel/Fragment/FragmentHandler.php:81)
  at Symfony\Component\HttpKernel\Fragment\FragmentHandler->render(object(ContentElementReference), 'forward', array('ignore_errors' => false))
     (vendor/contao/core-bundle/src/Fragment/FragmentHandler.php:70)
  at Contao\CoreBundle\Fragment\FragmentHandler->render(object(ContentElementReference))
     (vendor/contao/core-bundle/contao/elements/ContentProxy.php:65)
  at Contao\ContentProxy->generate()
     (vendor/contao/core-bundle/contao/library/Contao/Controller.php:570)
  at Contao\Controller::getContentElement(object(ContentModel))
     (vendor/contao/core-bundle/contao/dca/tl_content.php:1257)
  at tl_content->addCteType(array('id' => 54, 'type' => 'hyperlink', 'addImage' => 0, 'showPreview' => 0, 'inline' => 0, 'overwriteMeta' => 0, 'fullsize' => 0, 'thead' => 0, 'tfoot' => 0, 'tleft' => 0, 'sortable' => 0, 'target' => 0, 'overwriteLink' => 0, 'useImage' => 0, 'useHomeDir' => 0, 'metaIgnore' => 0, 'splashImage' => 0, 'sliderContinuous' => 0, 'protected' => 0, 'invisible' => 0, 'com_moderate' => 0, 'com_bbcode' => 0, 'com_disableCaptcha' => 0, 'com_requireLogin' => 0, 'pid' => 8, 'ptable' => 'tl_article', 'sorting' => 128, 'tstamp' => 1675788603, 'headline' => 'a:2:{s:4:"unit";s:2:"h2";s:5:"value";s:0:"";}', 'text' => null, 'singleSRC' => null, 'alt' => '', 'imageTitle' => '', 'size' => '', 'imageUrl' => null, 'caption' => '', 'floating' => 'above', 'html' => null, 'unfilteredHtml' => null, 'listtype' => '', 'listitems' => null, 'tableitems' => null, 'summary' => '', 'sortIndex' => 0, 'sortOrder' => 'ascending', 'mooHeadline' => '', 'mooStyle' => '', 'mooClasses' => '', 'highlight' => '', 'markdownSource' => 'sourceText', 'code' => null, 'url' => null, 'titleText' => '', 'linkTitle' => '', 'embed' => '', 'rel' => '', 'multiSRC' => null, 'perRow' => 4, 'perPage' => 0, 'numberOfItems' => 0, 'sortBy' => '', 'galleryTpl' => '', 'customTpl' => '', 'playerSRC' => null, 'youtube' => '', 'vimeo' => '', 'posterSRC' => null, 'playerSize' => '', 'playerOptions' => null, 'playerStart' => 0, 'playerStop' => 0, 'playerCaption' => '', 'playerAspect' => '', 'playerPreload' => '', 'playerColor' => '', 'youtubeOptions' => null, 'vimeoOptions' => null, 'sliderDelay' => 0, 'sliderSpeed' => 300, 'sliderStartSlide' => 0, 'data' => null, 'cteAlias' => 0, 'articleAlias' => 0, 'article' => 0, 'form' => 0, 'module' => 0, 'groups' => null, 'cssID' => 'a:2:{i:0;s:0:"";i:1;s:0:"";}', 'start' => '', 'stop' => '', 'com_order' => 'ascending', 'com_perPage' => 0, 'com_template' => '', 'nodes' => null, 'nodesWrapper' => ''))
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:4806)
  at Contao\DC_Table->parentView()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:374)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/contao/classes/Backend.php:547)
  at Contao\Backend->getBackendModule('article', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:149)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:184)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:44)
```

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #5761

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

File: core-bundle/contao/models/ContentModel.php [hunk 1]
```diff
@@ -53,7 +53,7 @@
  * @property string            $highlight
  * @property string            $markdownSource
  * @property string|null       $code
- * @property string            $url
+ * @property string|null       $url
```
Comment (aschempp) [inline core-bundle/contao/models/ContentModel.php:56]: Since this is a varchar field with empty string default, can it really be null or would it just be an empty string?

Comment (fritzmg) [reply core-bundle/contao/models/ContentModel.php:56]: @aschempp `tl_content.url` is `text NULL`, not a varchar.

**Comment by leofeyer** [comment]
Thank you @m-vo.
