### PR TITLE
Revert #2476 + work around for PHPStan

### LINKED ISSUE #2570: Registering callbacks/hooks/picker providers with a priority via annotations is broken
**Affected version(s)**

Contao 4.10

**Description**
This [commit](https://github.com/contao/contao/commit/e68ed7fbf66d2c6d1cfa3a880f96fc3501592b2b) from #2476 breaks defining callbacks, hooks and picker providers with a priority. This will fail silently and the elements won't be registered at all. :scream: 

Here is an example:
```
[Type Error] Attribute "priority" of @Callback declared on method Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener::generateArticleForPage() expects a(n) int|null, but got integer.
```

This is because of this check in the doc parser that now fails because `'int' !== 'int|null'`: https://github.com/doctrine/annotations/blob/984d7dc8d61c3566768379fe25aa531b54b8130d/lib/Doctrine/Common/Annotations/DocParser.php#L902

Doctrine Annotations should probably handle this but we should imo fix this asap as this renders lots of things unusable in the current 4.10.

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2570
| Docs PR or issue | -

This works around the issue in #2570. Besides that we should probably investigate if `doctrine/annotations` has a bug and/or check  our default values.

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

File: core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php [hunk 1]
```diff
@@ -26,16 +26,12 @@ public function testAnnotatedCallbacks(): void
         $listener = $this->createListener();
 
         $annotationReader = new AnnotationReader();
+
+        /** @var callback $annotation */
```
Comment (m-vo) [inline core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php]: Just in case you're wondering as well: I just noticed that the CS fixer's `PhpCsFixer\Fixer\Phpdoc\PhpdocTypesFixer` transforms `Callback` to `callback` :man_facepalming:. It doesn't really matter though, because the annotation still works.

Comment (leofeyer) [reply core-bundle/tests/EventListener/DataContainer/DisableAppConfiguredSettingsListenerTest.php]: I have adjusted this in contao/easy-coding-standard@251e23cf9435e7e9dfd867f5606024df5424ca32.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
