### PR TITLE
Fix and improve route debugging

### LINKED ISSUE #2044: Return value of RouteProvider::getRouteByName() must be an instance of Route
**Affected version(s)**

Contao 4.10

**Description**

```
vendor/bin/contao-console debug:router tl_page.64.locale                  
11:31:37 ERROR     [console] Error thrown while running command "debug:router 'tl_page.64.locale'". Message: "Return value of Contao\CoreBundle\Routing\RouteProvider::getRouteByName() must be an instance of Symfony\Component\Routing\Route, null returned" ["exception" => TypeError { …},"command" => "debug:router 'tl_page.64.locale'","message" => "Return value of Contao\CoreBundle\Routing\RouteProvider::getRouteByName() must be an instance of Symfony\Component\Routing\Route, null returned"]

In RouteProvider.php line 113:
                                                                                                                                                   
  Return value of Contao\CoreBundle\Routing\RouteProvider::getRouteByName() must be an instance of Symfony\Component\Routing\Route, null returned  
                                                                                                                                                   
debug:router [--show-controllers] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command> [<name>]
```

This is the output of `debug:router`:

```
 tl_page.64.locale                      ANY      https    managed-edition.wip   /user{!parameters}.html       
```

### PR DESCRIPTION
**Pull request by aschempp**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2044

### CODE REVIEW

File: core-bundle/src/Routing/AbstractPageRouteProvider.php [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+        foreach ($names as $name) {
+            if (0 !== strncmp($name, 'tl_page.', 8)) {
+                continue;
+            }
+
+            [, $id] = explode('.', $name);
+
+            if (!is_numeric($id)) {
+                continue;
+            }
```
Comment (leofeyer) [inline core-bundle/src/Routing/AbstractPageRouteProvider.php:108]:
```suggestion
            [$table, $id] = explode('.', $name);

            if ('tl_page' !== $table || !is_numeric($id)) {
                continue;
            }
```

This would save the `strncmp()` call.

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]
