### PR TITLE
Handle arrays when converting basic entities

### LINKED ISSUE #8183: Eval basicEntities does not work for serialized fields/widgets (like keyValueWizard)
### Affected version(s)

5.5.x

### Description

example: (if a add this code)
`$GLOBALS['TL_DCA']['tl_content']['fields']['data']['eval']['basicEntities'] = true;`

I will get an error:

```
ErrorException:
Warning: Array to string conversion

  at vendor/contao/core-bundle/contao/library/Contao/StringUtil.php:231
  at Contao\StringUtil::convertBasicEntities(array(array('key' => 'LOHNSCHNITT', 'value' => 'Präzise und individuell nach Deinen Vorgaben'), array('key' => 'OBST[-]BAUM[-]SCHNITT', 'value' => 'Exakte Verarbeitung für hochwertige Produkte'), array('key' => 'LAMELLEN SCHNEIDEN', 'value' => 'Perfekt für Verleimungen oder Spezialanfertigungen'), array('key' => 'INDIVIDUELLE WÜNSCHE?', 'value' => 'Kein Problem – sprich uns an!')))
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:1270)
  at Contao\Widget::getAttributesFromDca(array('inputType' => 'keyValueWizard', 'sql' => 'text NULL', 'eval' => array('basicEntities' => true, 'required' => false), 'attributes_callback' => array(array('contao.listener.data_container.description_list_label', '__invoke')), 'label' => array('Template-Daten', 'Sie können über <code>$this->keys</code> auf die Werte im Template zugreifen.')), 'data', 'a:4:{i:0;a:2:{s:3:"key";s:11:"LOHNSCHNITT";s:5:"value";s:45:"Präzise und individuell nach Deinen Vorgaben";}i:1;a:2:{s:3:"key";s:21:"OBST[-]BAUM[-]SCHNITT";s:5:"value";s:45:"Exakte Verarbeitung für hochwertige Produkte";}i:2;a:2:{s:3:"key";s:18:"LAMELLEN SCHNEIDEN";s:5:"value";s:51:"Perfekt für Verleimungen oder Spezialanfertigungen";}i:3;a:2:{s:3:"key";s:22:"INDIVIDUELLE WÜNSCHE?";s:5:"value";s:31:"Kein Problem – sprich uns an!";}}', 'data', 'tl_content', object(DC_Table))
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:498)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2169)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:467)
  at Contao\Backend->getBackendModule('article', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:183)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)   
```

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #8183

### CODE REVIEW

**Comment by ausi** [comment]
Should we support arrays in `StringUtil::restoreBasicEntities()` for consistency too?

**Comment by leofeyer** [comment]
Yes, we have to. The phpDoc says `string|array` there, too.

File: core-bundle/contao/library/Contao/StringUtil.php [hunk 1]
```diff
@@ -228,7 +228,19 @@ public static function decodeEntities($strString, $strQuoteStyle=ENT_QUOTES)
 	 */
 	public static function convertBasicEntities($strBuffer)
 	{
-		return str_replace(array('&amp;', '&lt;', '&gt;', '&nbsp;', '&shy;', '&ZeroWidthSpace;'), array('[&]', '[lt]', '[gt]', '[nbsp]', '[-]', '[zwsp]'), $strBuffer);
+		$search = array('&amp;', '&lt;', '&gt;', '&nbsp;', '&shy;', '&ZeroWidthSpace;');
+		$replace = array('[&]', '[lt]', '[gt]', '[nbsp]', '[-]', '[zwsp]');
+
+		if (\is_array($strBuffer))
+		{
+			array_walk_recursive($strBuffer, static fn(&$value) => $value = str_replace($search, $replace, $value));
```
Comment (ausi) [inline core-bundle/contao/library/Contao/StringUtil.php]:
```suggestion
			array_walk_recursive($strBuffer, static fn(&$value) => $value = \is_string($value) ? str_replace($search, $replace, $value) : $value);
```

Comment (leofeyer) [reply core-bundle/contao/library/Contao/StringUtil.php]: See d42d207edc5c7ddc8011c4369afeff7c56209aa0

**Comment by leofeyer** [comment]
Might be a bit over-engineered now but it sure works 🙈

File: core-bundle/contao/library/Contao/StringUtil.php [hunk 2]
```diff
@@ -228,7 +228,24 @@ public static function decodeEntities($strString, $strQuoteStyle=ENT_QUOTES)
...
+		{
+			if (\is_string($value))
+			{
+				$value = str_replace(array('&amp;', '&lt;', '&gt;', '&nbsp;', '&shy;', '&ZeroWidthSpace;'), array('[&]', '[lt]', '[gt]', '[nbsp]', '[-]', '[zwsp]'), $value);
+			}
+		};
+
+		if (\is_array($strBuffer))
+		{
+			array_walk_recursive($strBuffer, static fn(&$value) => $replace($value));
```
Comment (ausi) [inline core-bundle/contao/library/Contao/StringUtil.php]:
```suggestion
			array_walk_recursive($strBuffer, $replace);
```

File: core-bundle/contao/library/Contao/StringUtil.php [hunk 3]
```diff
@@ -240,7 +257,24 @@ public static function convertBasicEntities($strBuffer)
...
+		{
+			if (\is_string($value))
+			{
+				$value = str_replace(array('[&]', '[&amp;]', '[lt]', '[gt]', '[nbsp]', '[-]', '[zwsp]'), array('&amp;', '&amp;', '&lt;', '&gt;', '&nbsp;', '&shy;', '&ZeroWidthSpace;'), $value);
+			}
+		};
+
+		if (\is_array($strBuffer))
+		{
+			array_walk_recursive($strBuffer, static fn(&$value) => $replace($value));
```
Comment (ausi) [inline core-bundle/contao/library/Contao/StringUtil.php]:
```suggestion
			array_walk_recursive($strBuffer, $replace);
```

**Review by ausi — DISMISSED** [review]

**Review by ausi — APPROVED** [review]

**Comment by aschempp** [comment]
maybe a good time to reopen https://github.com/contao/contao/pull/7372 now? 🙄

**Comment by leofeyer** [comment]
Yes, the first commit https://github.com/contao/contao/pull/7372/commits/687d71619da8478b2b391a2becb0ac04da199290 was actually correct (apart from @ausi's remarks). But the PR needs to be rebased on the `5.3` branch.
