### PR TITLE
Change the newsletter recipient icon according to the start/stop date

### LINKED ISSUE #951: Member that is deactivated by date still gets newsletters
**Affected version(s)**
Tested on Contao 4.4.43 and 4.8.4

**Description**  
Members can be deactivated by setting the checkbox "Deactivate" or by setting the "Deactivate on" date. The checkbox also disables the member as newsletter recipient, but when the date is passed the newsletter recipient is still active.

**How to reproduce**  

1. Create a newletter channel
2. Create a member and assign the newsletter channel
3. Set a future date for "Deactivate on" for the member
4. Wait until the date is passed
5. In member overview, the member is inactive
6. In newsletter channel recipients list the member is still active

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #951

This changes at least the member icon on the left according to the start/stop date, making it more clear, that the recipient is actually inactive, even though `tl_newsletter_recipient.active` is still enabled.

See also https://github.com/contao/contao/blob/fbc4d759bd7975722c25842503ac9c80c7fe5089/newsletter-bundle/contao/classes/Newsletter.php#L199 (note that `$objRecipients` is a `JOIN` with `tl_member` on `email`).

### CODE REVIEW

File: newsletter-bundle/contao/dca/tl_newsletter_recipients.php [hunk 1]
```diff
@@ -210,6 +211,21 @@ public function listRecipient($row)
 		$icon = Image::getPath('member');
 		$icond = Image::getPath('member_');
 
+		// Change icon according to start/stop of associated member (#951)
+		if ($member = MemberModel::findOneByEmail($row['email']))
```
Comment (aschempp) [inline newsletter-bundle/contao/dca/tl_newsletter_recipients.php]: if you "show all" pages of the view, this would potentially lead to 500 quers for the member emails. Maybe we could do one cache query joining the pid of the row?

Comment (fritzmg) [reply newsletter-bundle/contao/dca/tl_newsletter_recipients.php]: Changed in f4b8ee743c

**Review by aschempp — DISMISSED** [review]
this would be nicer as a service that can implement the `ResetInterface`, but I'll guess it'll do 🙃

**Comment by fritzmg** [comment]
Agreed - however, I am planning a modern rewrite of this bundle anyway and thus decided to keep the legacy callback for now.

**Review by leofeyer — APPROVED** [review]
