### PR TITLE
Cast `$alexf` data to array

### LINKED ISSUE #7432: Fehler beim Wechsel vom Admin zum Redakteur im Backend
### Affected version(s)

5.3.12

### Description

Beim Wechsel im Backend vom Admin zum Redakteur wird folgende Fehlermeldung ausgegeben:

`array_search(): Argument #2 ($haystack) must be of type array, null given`

Hier der Stack-Trace:
```
TypeError:
array_search(): Argument #2 ($haystack) must be of type array, null given

  at vendor/contao/core-bundle/contao/classes/BackendUser.php:316
  at array_search('tl_user::admin', null)
     (vendor/contao/core-bundle/contao/classes/BackendUser.php:316)
  at Contao\BackendUser->setUserFromDb()
     (vendor/contao/core-bundle/contao/library/Contao/User.php:345)
  at Contao\User::loadUserByIdentifier('Redakteur')
     (vendor/contao/core-bundle/src/Framework/Adapter.php:38)
  at Contao\CoreBundle\Framework\Adapter->__call('loadUserByIdentifier', array('Redakteur'))
     (vendor/contao/core-bundle/src/Security/User/ContaoUserProvider.php:50)
  at Contao\CoreBundle\Security\User\ContaoUserProvider->loadUserByIdentifier('Redakteur')
     (vendor/symfony/security-http/Firewall/SwitchUserListener.php:159)
  at Symfony\Component\Security\Http\Firewall\SwitchUserListener->attemptSwitchUser(object(Request), 'Redakteur')
     (vendor/symfony/security-http/Firewall/SwitchUserListener.php:117)
  at Symfony\Component\Security\Http\Firewall\SwitchUserListener->authenticate(object(RequestEvent))
     (vendor/symfony/security-bundle/Debug/WrappedLazyListener.php:46)
  at Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate(object(RequestEvent))
     (vendor/symfony/security-http/Firewall/AbstractListener.php:26)
  at Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke(object(RequestEvent))
     (vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:83)
  at Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners(object(RequestEvent), object(Generator))
     (vendor/symfony/security-http/Firewall.php:95)
  at Symfony\Component\Security\Http\Firewall->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42) 
```

Und die dev-error.log:
```
[2024-08-12T08:49:09.943506+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","method":"GET"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.946798+02:00] security.DEBUG: Read existing security token from the session. {"key":"_security_contao_backend","token_class":"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.979521+02:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Contao\\CoreBundle\\Security\\User\\ContaoUserProvider","username":"Frankadmin"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.981108+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"contao_backend","authenticators":2} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.981147+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"contao_backend","authenticator":"Contao\\CoreBundle\\Security\\Authenticator\\ContaoLoginAuthenticator"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.981168+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"contao_backend","authenticator":"Contao\\CoreBundle\\Security\\Authenticator\\ContaoLoginAuthenticator"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.981182+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"contao_backend","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\LoginLinkAuthenticator"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:09.981198+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"contao_backend","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\LoginLinkAuthenticator"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.056411+02:00] security.DEBUG: Stored the security token in the session. {"key":"_security_contao_backend"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.083984+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\Cron::updateMinutelyCliCron" [] {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.084241+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\SuperviseWorkersCron" [] {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.086583+02:00] messenger.INFO: Sending message Contao\CoreBundle\Messenger\Message\SearchIndexMessage with contao_prio_low sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"class":"Contao\\CoreBundle\\Messenger\\Message\\SearchIndexMessage","alias":"contao_prio_low","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.135471+02:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: proc_open(): posix_spawn() failed: Permission denied" at Terminal.php line 220 {"exception":"[object] (ErrorException(code: 0): Warning: proc_open(): posix_spawn() failed: Permission denied at /www/htdocs/w1234567/verzeichnis/vendor/symfony/console/Terminal.php:220)"} {"request_uri":"https://domain.de/contao?do=user&ref=YEegZQmI","request_method":"GET"}
[2024-08-12T08:49:10.209542+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"97ccb0"},"request_uri":"https://domain.de/_wdt/97ccb0","method":"GET"} {"request_uri":"https://domain.de/_wdt/97ccb0","request_method":"GET"}
[2024-08-12T08:49:10.364749+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\Cron::updateMinutelyCliCron" [] {"request_uri":"https://domain.de/_wdt/97ccb0","request_method":"GET"}
[2024-08-12T08:49:10.365072+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\SuperviseWorkersCron" [] {"request_uri":"https://domain.de/_wdt/97ccb0","request_method":"GET"}
[2024-08-12T08:49:10.366629+02:00] messenger.INFO: Sending message Contao\CoreBundle\Messenger\Message\SearchIndexMessage with contao_prio_low sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"class":"Contao\\CoreBundle\\Messenger\\Message\\SearchIndexMessage","alias":"contao_prio_low","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} {"request_uri":"https://domain.de/_wdt/97ccb0","request_method":"GET"}
[2024-08-12T08:49:10.369591+02:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: proc_open(): posix_spawn() failed: Permission denied" at Terminal.php line 220 {"exception":"[object] (ErrorException(code: 0): Warning: proc_open(): posix_spawn() failed: Permission denied at /www/htdocs/w1234567/verzeichnis/vendor/symfony/console/Terminal.php:220)"} {"request_uri":"https://domain.de/_wdt/97ccb0","request_method":"GET"}
[2024-08-12T08:49:12.478705+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://domain.de/contao?_switch_user=Redakteur","method":"GET"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.481112+02:00] security.DEBUG: Read existing security token from the session. {"key":"_security_contao_backend","token_class":"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.508616+02:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Contao\\CoreBundle\\Security\\User\\ContaoUserProvider","username":"Frankadmin"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.509437+02:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"contao_backend","authenticators":2} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.509470+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"contao_backend","authenticator":"Contao\\CoreBundle\\Security\\Authenticator\\ContaoLoginAuthenticator"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.509489+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"contao_backend","authenticator":"Contao\\CoreBundle\\Security\\Authenticator\\ContaoLoginAuthenticator"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.509504+02:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"contao_backend","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\LoginLinkAuthenticator"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.509519+02:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"contao_backend","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\LoginLinkAuthenticator"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.512063+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "array_search(): Argument #2 ($haystack) must be of type array, null given" at BackendUser.php line 316 {"exception":"[object] (TypeError(code: 0): array_search(): Argument #2 ($haystack) must be of type array, null given at /www/htdocs/w1234567/verzeichnis/vendor/contao/core-bundle/contao/classes/BackendUser.php:316)"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.526061+02:00] security.DEBUG: Stored the security token in the session. {"key":"_security_contao_backend"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.578668+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\Cron::updateMinutelyCliCron" [] {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.578928+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\SuperviseWorkersCron" [] {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.601162+02:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: proc_open(): posix_spawn() failed: Permission denied" at Terminal.php line 220 {"exception":"[object] (ErrorException(code: 0): Warning: proc_open(): posix_spawn() failed: Permission denied at /www/htdocs/w1234567/verzeichnis/vendor/symfony/console/Terminal.php:220)"} {"request_uri":"https://domain.de/contao?_switch_user=Redakteur","request_method":"GET"}
[2024-08-12T08:49:12.673230+02:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8a64fa"},"request_uri":"https://domain.de/_wdt/8a64fa","method":"GET"} {"request_uri":"https://domain.de/_wdt/8a64fa","request_method":"GET"}
[2024-08-12T08:49:12.730386+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\Cron::updateMinutelyCliCron" [] {"request_uri":"https://domain.de/_wdt/8a64fa","request_method":"GET"}
[2024-08-12T08:49:12.730647+02:00] app.DEBUG: Executing cron job "Contao\CoreBundle\Cron\SuperviseWorkersCron" [] {"request_uri":"https://domain.de/_wdt/8a64fa","request_method":"GET"}
[2024-08-12T08:49:12.732056+02:00] messenger.INFO: Sending message Contao\CoreBundle\Messenger\Message\SearchIndexMessage with contao_prio_low sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"class":"Contao\\CoreBundle\\Messenger\\Message\\SearchIndexMessage","alias":"contao_prio_low","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} {"request_uri":"https://domain.de/_wdt/8a64fa","request_method":"GET"}
[2024-08-12T08:49:12.734503+02:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: proc_open(): posix_spawn() failed: Permission denied" at Terminal.php line 220 {"exception":"[object] (ErrorException(code: 0): Warning: proc_open(): posix_spawn() failed: Permission denied at /www/htdocs/w1234567/verzeichnis/vendor/symfony/console/Terminal.php:220)"} {"request_uri":"https://domain.de/_wdt/8a64fa","request_method":"GET"}
```

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7432

Removing the `$alexf` member variable in #7365 turns out to be overzealous. The member variable needs to stay in order to ensure that it is always an array.

### CODE REVIEW

File: core-bundle/contao/classes/BackendUser.php [hunk 1]
```diff
@@ -132,6 +138,9 @@ public function __get($strKey)
 
 			case 'fop':
 				return \is_array($this->arrData['fop']) ? $this->arrData['fop'] : ($this->arrData['fop'] ? array($this->arrData['fop']) : false);
+
+			case 'alexf':
+				return $this->alexf;
```
Comment (ausi) [inline core-bundle/contao/classes/BackendUser.php]:
```suggestion
			case 'alexf':
				return (array) ($this->arrData['alexf'] ?? null);
```
Can’t we use something like this instead of reintroducing the member variable?

Or do we need to use `StringUtil::deserialize()`?

Comment (fritzmg) [reply core-bundle/contao/classes/BackendUser.php]: What is the downside of having the member variable?

**Comment by aschempp** [comment]
I'm not sure this is the correct solution. It applies to any other public field of the member. If the variable in Contao is empty, it will not be an array. If there is data, it will be. If we want to force arrays for them, we should use the `__get` method instead. Or we could fix the place where we use the data instead.

**Comment by fritzmg** [comment]
No, we need to revert it, as this is a BC break. The removal was a completely unrelated change.

**Comment by aschempp** [comment]
That is not true. We fixed the magic setters from setting object properties if they existed, which is exactly the case here.

File: core-bundle/contao/classes/BackendUser.php (hunk 1 above)
Comment (ausi) [reply core-bundle/contao/classes/BackendUser.php]: Since `$this->$k = …` was replaced with `$this->arrData[$k] = …` in #7365 your change would not work as expected because the data would get stored in `$this->arrData` but read from `$this->alexf`

**Comment by fritzmg** [comment]
Hm, yes I see what you mean now. I guess @ausi 's proposal is the correct way then 👍

File: core-bundle/contao/classes/BackendUser.php [hunk 2]
```diff
@@ -132,6 +132,9 @@ public function __get($strKey)
 
 			case 'fop':
 				return \is_array($this->arrData['fop']) ? $this->arrData['fop'] : ($this->arrData['fop'] ? array($this->arrData['fop']) : false);
+
+			case 'alexf':
+				return (array) ($this->arrData['alexf'] ?? null);
```
Comment (aschempp) [inline core-bundle/contao/classes/BackendUser.php]: This would return an empty array for an empty string value.

```suggestion
				return empty($this->arrData['alexf']) ? array(): $this->arrData['alexf'];
```

File: core-bundle/contao/classes/BackendUser.php [hunk 3]
```diff
@@ -132,6 +132,9 @@ public function __get($strKey)
 
 			case 'fop':
 				return \is_array($this->arrData['fop']) ? $this->arrData['fop'] : ($this->arrData['fop'] ? array($this->arrData['fop']) : false);
+
+			case 'alexf':
```
Comment (aschempp) [inline core-bundle/contao/classes/BackendUser.php]: Should we add all other array-like properties (see class annotations)?

File: core-bundle/contao/classes/BackendUser.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/contao/classes/BackendUser.php]: wouldn't ensure an array though 🤔  maybe this is better?
```suggestion
				return \is_array($this->arrData[$strKey] ?? null) ? $this->arrData[$strKey] : array();
```

File: core-bundle/contao/classes/BackendUser.php (hunk 3 above)
Comment (fritzmg) [reply core-bundle/contao/classes/BackendUser.php]: @leofeyer wdyt? We already do it for some of the properties, but not all.

Comment (leofeyer) [reply core-bundle/contao/classes/BackendUser.php]: If we are certain that it does not cause more issue, then yes.

Comment (ausi) [reply core-bundle/contao/classes/BackendUser.php]: As a bugfix I’d only handle the `alexf` case. The other properties can be done in 5.5 IMO.

Comment (fritzmg) [reply core-bundle/contao/classes/BackendUser.php]: I am not sure. Furthermore, for some of these properties we return `false` instead of an empty array. So it is inconsistent right now, not matter what. And I don't think we should change that as a bugfix - I think we should just fix the original issue.

**Comment by fritzmg** [comment]
For `groups` we use

```php
return \is_array($this->arrData['groups']) ? $this->arrData['groups'] : ($this->arrData['groups'] ? array($this->arrData['groups']) : array());
```

i.e. if the value is not an array and not empty, but the value into an array. Should we do the same for `alexf`?

**Comment by ausi** [comment]
> Should we do the same for `alexf`?

I think we should just use `StringUtil::deserialize($this->arrData['alexf'] ?? null, true)`. This already handles the empty string and null case and also works with simple strings and with serialized strings.

**Comment by aschempp** [comment]
We currently `StringUtil::deserialize` **all** values, assuming that if it is a serialized array it will automatically be unserialized, otherwise it will return the original value. So we would need a special handling for alexf (as we have with groups).

**Comment by aschempp** [comment]
Btw, none of this makes sense to me, why it would be different now that we don't use an object property 🙈

**Comment by fritzmg** [comment]
> Btw, none of this makes sense to me, why it would be different now that we don't use an object property 🙈

`alexf` is not part of `tl_user` and thus will **not** be set here:

https://github.com/contao/contao/blob/69e7e4b56df2e7f40544a15c001e3a74f2fbdcf2/core-bundle/src/Resources/contao/classes/BackendUser.php#L406-L413

It will only be set later on in `setUserFromDb()` here:

https://github.com/contao/contao/blob/69e7e4b56df2e7f40544a15c001e3a74f2fbdcf2/core-bundle/src/Resources/contao/classes/BackendUser.php#L455-L465

But if the field is `null` in `tl_user_group`, nothing will be set. Before #7365 this meant that the default value of the `$alexf` member variable was in effect, i.e. an empty array. After #7365 the default value of `alexf` is `null`.

**Comment by ausi** [comment]
> Before #7365 this meant that the default value of the `$alexf` member variable was in effect, i.e. an empty array. After #7365 the default value of `alexf` is `null`.

In this case we can just restore the original behavor using `return $this->arrData['alexf'] ?? array();`.

**Comment by fritzmg** [comment]
Reverted back to the original version of the PR.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by aschempp** [comment]
I'm sorry but I think that's wrong. I missed that `alexf` is not a property on the user but only of groups. It should not be in `arraData`, because we would try to save it if you save the user. We should restore the original behaviour of a class property (with special handling accordingly).

**Comment by leofeyer** [comment]
Ah, that was probably the reason why `$alexf` was a class property 😄
