### PR TITLE
Auto-generate and dump the APP_SECRET during contao-setup

### LINKED ISSUE #5693: Key provided is shorter than 256 bits, only 240 bits provided
### Affected version(s)

4.13.14, 4.9.37

### Description

Mit Login ins Backend kommt die Fehlermeldung: `Key provided is shorter than 256 bits, only 240 bits provided`. Wenn man die Seite im Anschluss neu lädt, kommt die Fehlermeldung: `The key "username" must be a string, "NULL" given`. Sobald ich in der URL alles nach `../contao/` entferne und die Seite neu lade, gelange ich ins Backend. Zur Info: 2-Faktor-Authentifizierung ist aktiviert. Das Problem ist mir bereits bei verschiedenen Installationen aufgefallen, ich kann aber leider nicht nachvollziehen, woran es liegt.

Der Systemlog gibt folgende Meldung aus:

```
[2023-01-17T07:31:51.550507+01:00] request.INFO: Matched route "contao_backend_login". {"route":"contao_backend_login","route_parameters":{"_route":"contao_backend_login","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::loginAction"},"request_uri":"https://****.de/contao/login?_hash=***&redirect=https%3A%2F%2F***.de%2Fcontao%3Fdo%3Dlog%26ref%3DlTby2xKP","method":"POST"} []
[2023-01-17T07:31:51.671316+01:00] security.INFO: User has been authenticated successfully. {"username":"hendrik.bengs"} []
[2023-01-17T07:31:51.732548+01:00] request.CRITICAL: Uncaught PHP Exception Lcobucci\JWT\Signer\InvalidKeyProvided: "Key provided is shorter than 256 bits, only 240 bits provided" at /***/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php line 39 {"exception":"[object] (Lcobucci\\JWT\\Signer\\InvalidKeyProvided(code: 0): Key provided is shorter than 256 bits, only 240 bits provided at /***/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php:39)"} []
```

### PR DESCRIPTION
**Pull request by m-vo**
This backports #5066, so that a secret also gets automatically created in Contao 4.13 if not set (or set to the default).

Related to #5693, where we discussed that this backport would be worthwhile.

### CODE REVIEW

File: manager-bundle/src/Command/ContaoSetupCommand.php [hunk 1]
```diff
@@ -94,7 +120,7 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             $this->executeCommand(array_merge($php, [$this->consolePath], $command, $commandFlags), $output);
         }
 
-        $output->writeln('<info>Done! Please open the Contao install tool or run contao:migrate on the command line to make sure the database is up-to-date.</info>');
+        $io->info('Done! Please run the contao:migrate command to make sure the database is up-to-date.');
```
Comment (ausi) [inline manager-bundle/src/Command/ContaoSetupCommand.php]: Did you change the text on purpose?
```suggestion
        $io->info('Done! Please open the Contao install tool or run contao:migrate on the command line to make sure the database is up-to-date.');
```

**Review by ausi — DISMISSED** [review]

File: manager-bundle/src/Command/ContaoSetupCommand.php (hunk 1 above)
Comment (leofeyer) [reply manager-bundle/src/Command/ContaoSetupCommand.php]: In Contao 4.13, the install tool still exists, so these changes should be reverted (as @ausi suggested) IMHO.

Comment (m-vo) [reply manager-bundle/src/Command/ContaoSetupCommand.php]: Ah yes, accidentally cherry picked this. It's fixed now in 66f94d777974007872bd762d387fb305de61a8ad.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
