### PR TITLE
Fix deferred images in HTML emails

### LINKED ISSUE #680: C 4.8.1 {{image::*}} im Newsletter Template erzeugt keine Bilder mehr
**Affected version(s)**
Contao 4.8.1

**Description**  
Ich verwende im Newsletter Template ein Logo via replaceInsertTags

`<?= $this->replaceInsertTags( '{{image::fa971c31-7300-11e8-8b83-74d02bcb043d?width=450&height=150&mode=crop}}' ); ?>`

Bisher hat das auch super funktioniert. Seit Contao 4.8.1 ist das Bild im Newsletter nicht mehr vorhanden.

**How to reproduce / Workaround**  
Erzeuge ich via Inhaltselement "Text" und dem Inserttag selbst {{image::fa971c31-7300-11e8-8b83-74d02bcb043d?width=450&height=150&mode=crop}} das Bild und rufe es im Frontend einmalig auf, funktioniert auch die Grafik im Newsletter.

Ändere ich die Größeneinstellung im Template ist die Grafik wieder nicht verfügbar. Erst wenn ich die Grafik mit den neuen Einstellungen wieder einmalig im Frontend via Inserttag aufrufe, funktioniert sie auch wieder im Newsletter.

Ich gehe also davon aus das {{image::*}}  im Template keine Bildversionen mehr erzeugt. Vermutlicher Zusammenhand mit Deferred Image Creation.

VG Frank

### PR DESCRIPTION
**Pull request by ausi**
Fixes #680

Better name for `$objFile->generateIfDeferredImage()`?
`createDeferredImage()`, `generateDeferredImage()`, `createImageIfDeferred()` ?

### CODE REVIEW

**Comment by leofeyer** [comment]
I'd go with `createDeferredImage()`.

File: core-bundle/src/Resources/contao/library/Contao/Email.php [hunk 1]
```diff
@@ -407,7 +407,7 @@ public function sendTo()
 						$src = rawurldecode($src); // see #3713
 
 						// Embed the image if the URL is now relative
-						if (!preg_match('@^https?://@', $src) && file_exists($this->strImageDir . $src))
+						if (!preg_match('@^https?://@', $src) && ($objFile = new File(StringUtil::stripRootDir($this->strImageDir . $src))) && ($objFile->exists() || $objFile->createDeferredImage()))
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Email.php]:
```suggestion
						if (!preg_match('@^https?://@', $src) && ($objFile = new File(StringUtil::stripRootDir($this->strImageDir . $src))) && $objFile->createDeferredImage())
```

Because `File::createDeferredImage()` already calls `$this->exists()`.

BTW, from using the method here, it could also be called `createIfDeferred()` analogous to `createIfNotExists()`.

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Email.php]: But `createDeferredImage()` would return false, so the `exists()` check is needed here too.
👍 for `createIfDeferred()`

**Comment by leofeyer** [comment]
Thank you @ausi.
