### PR TITLE
Also export the media type(s) when exporting style sheets

### LINKED ISSUE #842: CSS Medientypen werden nicht exportiert.
**Affected version(s)**
4.8.x und vermutlich auch alle älteren

**Description**  
Beim Exportieren des CSS Stylesheets eines Themes werden die Medientypen nicht mit exportiert (sofern nicht mit Mediaqueries verbunden)

**How to reproduce**  
Stylesheet mit Medientyp "print" anlegen und exportieren.
Die exportierte Datei enthält keinen `@print {}`- Block.

Das erschwert Nutzern des internen Editors die Umstellung und sollte vor einem Entfernen des Editors behoben werden.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #842

### CODE REVIEW

File: core-bundle/src/Resources/contao/classes/StyleSheets.php [hunk 1]
```diff
@@ -1387,10 +1387,18 @@ public function exportStyleSheet(DataContainer $dc)
...
 
+		$blnClose = false;
+
 		// Add the media query (see #7560)
 		if ($objStyleSheet->mediaQuery != '')
 		{
 			$objFile->append('@media ' . $objStyleSheet->mediaQuery . ' {');
+			$blnClose = true;
+		}
+		elseif (\is_array(($tmp = \StringUtil::deserialize($objStyleSheet->media))) && (\count($tmp) > 1 || $tmp[0] != 'all'))
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/classes/StyleSheets.php:1398]: How can this ever happen if the previous `if` condition checks for a non-empty field?

Comment (leofeyer) [reply core-bundle/src/Resources/contao/classes/StyleSheets.php:1398]: The previous condition checks for `->mediaQuery`, which is the text field where you can enter a media query. The second condition checks for `->media`, which is the checkbox wizard where you can pick one or more media types.

**Review by Toflar — APPROVED** [review]

**Review by ausi — APPROVED** [review]
