### PR TITLE
Return early in the Search::indexPage() method if nothing has changed

### LINKED ISSUE #2235: Search indexer performance penalty/glitches
**Affected version(s)**

(only tested with current master so far, probably at least 4.10)

**Description**

The search indexer locks and updates the search tables on every call even if nothing has changed (case A) with the exception of one scenario where the page was visited in preview mode first and therefore contains the wrong url (case B). When fixing this we should also make sure the lock only ever occurs after the checksum check/early return if possible.

**How to reproduce case A**
1. Make sure the search indexer runs in the FE
1. Open a page &rarr; will be indexed
1. Open the same page again without changing the content &rarr; `tl_search` and `tl_search_term` will be updated again<sup>*)</sup>

**How to reproduce case B**
1. Make sure the search indexer runs in the FE
1. Truncate the search tables
1. Open a page in the preview mode &rarr; the stored url will contain `preview.php/` 
1. Open the same page through the regular entry point &rarr; no change happens to the url or any associated record<sup>**)</sup>

--------
<sup>*)</sup> because there is no early return in the case of matching checksums and urls

<sup>**)</sup> because this first condition https://github.com/contao/contao/blob/fab8317d8f06000b8977987fb9dd71ee3d66415d/core-bundle/src/Resources/contao/library/Contao/Search.php#L188-L192 evaluates to `true` and the following to `false` resulting in a `return` in line 220.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2235
| Docs PR or issue | -

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Search.php [hunk 1]
```diff
@@ -181,9 +181,15 @@ public static function indexPage($arrData)
...
 								->execute($arrSet['checksum'], $arrSet['pid']);
 
-		// Update the URL if the new URL is shorter or the current URL is not canonical
-		if ($objIndex->numRows && $objIndex->url != $arrSet['url'])
+		if ($objIndex->numRows)
 		{
+			// The page has already been indexed and has not changed (see #2235)
+			if ($objIndex->url == $arrSet['url'])
+			{
+				return true;
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Search.php]:
```suggestion
				return false;
```
The doccomment says `@return boolean True if a new record was created`

Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Search.php]: Good catch. 👍🏻

**Review by ausi — APPROVED** [review]

**Review by ausi — APPROVED** [review]
