### PR TITLE
Do not trigger warnings for fractions with rounding errors

### LINKED ISSUE #927: Rundungsfehler für Important Part bei Bildern nach Update von 4.7 auf 4.8
**Affected version(s)**
Update von 4.7 auf 4.8

**Description**  
Nach dem Update erhalte ich im Systemlog diverse Fehlermeldungen folgender Art:
```html
Invalid important part x=0.00117647058824, y=0.506172839506, width=0.998823529412, height=0.479717813051 for image "/www/htdocs/XXX/www.XXX.de/files/mein-bild.jpg".
```

**How to reproduce**  
Ich kann es nicht genau reproduzieren, aber lt. Slack-Thread mit @ausi sind wir zum Entschluss eines Rundungsfehlers gekommen. In der Datenbank mit 4.7 stehen folgende Werte beim Bild mit der Größe 850 x 567px:

```html
importantPartX = 1
importantPartY = 287
importantPartWidth = 849
importantPartHeight = 272
```

nach dem Update stehen dann folgende Werte in der DB:

```html
importantPartX = 0.00117647058824
importantPartY = 0.506172839506
importantPartWidth = 0.998823529412
importantPartHeight = 0.479717813051
```

Wenn man jetzt `importantPartX = 0.00117647058824` und `importantPartWidth = 0.998823529412` zusammenrechnet, kommt man auf `1.0000000000002`

### PR DESCRIPTION
**Pull request by ausi**
Fixes #927

### CODE REVIEW

File: core-bundle/src/Image/ImageFactory.php [hunk 1]
```diff
@@ -326,8 +326,8 @@ private function createImportantPart(ImageInterface $image): ?ImportantPart
         }
 
         if (
-            (float) $file->importantPartX + (float) $file->importantPartWidth > 1
-            || (float) $file->importantPartY + (float) $file->importantPartHeight > 1
+            (float) $file->importantPartX + (float) $file->importantPartWidth >= 2
+            || (float) $file->importantPartY + (float) $file->importantPartHeight >= 2
```
Comment (m-vo) [inline core-bundle/src/Image/ImageFactory.php:334]: You could probably also check if all values are integers to avoid the constant. :smile: 
```php
$isWholeNumber = function($number): bool { return (int) $number == (float) $number; };

if(
  $isWholeNumber($file->importantPartX) && $isWholeNumber($file->importantPartY) &&
  $isWholeNumber($file->importantPartWidth) && $importantPartHeight($file->importantPartX)
) {
  // ...
}
```

Comment (ausi) [reply core-bundle/src/Image/ImageFactory.php:334]: The `>= 2` check should work for all cases and is simpler IMO so I’d vote for keeping it as it is.

Comment (m-vo) [reply core-bundle/src/Image/ImageFactory.php:334]: Yeah, agree. :smile:  

But for the sake of completeness I'm also throwing [bcadd](https://www.php.net/manual/en/function.bcadd.php) + [bccomp](https://www.php.net/manual/de/function.bccomp.php) in the ring. :monkey:  (&larr; ok noone will ever have this extension, but imo that's the only right way to deal with floats).

**Review by leofeyer — DISMISSED** [review]

**Review by Toflar — CHANGES_REQUESTED** [review]
Can we add at least a comment in the code? I don't think anyone reading that will understand this comparison otherwise.

**Comment by ausi** [comment]
> Can we add at least a comment in the code?

Done in 43374c37d1722d467e10bdb26577e8d38c2dceca.

**Comment by ausi** [comment]
Better now?

I also added a deprecation warning so that we can remove this code in version 5.0.

**Review by m-vo — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
