### PR TITLE
Remove files of multiple uploads properly

### LINKED ISSUE #9696: File upload field (multiple mode) triggers is_file(): Argument #1 must be of type string, array given when one file fails validation
### Affected version(s)

5.7.3

### Description
When using a file upload field in multiple mode inside a Contao 5.7 form, submitting several files at once causes an error if at least one of the uploaded files fails validation (e.g., file too large).

Instead of gracefully cleaning up the temporary files, Contao throws the following PHP error:

```PHP
is_file(): Argument #1 ($filename) must be of type string, array given
```
This happens during the cleanup phase in Contao\Form, lines 308–323, where the system attempts to remove uploaded files when the form has errors.

### Steps to Reproduce
1. Create a form with a file upload field configured as:
    - multiple = true
    - with a file size limit (e.g., 2 MB)
2. Submit the form with several files, including:
    - at least one valid file
    - at least one file exceeding the allowed size
3. Submit the form
4. Observe the error

### Actual Behavior
A PHP warning/error is thrown:
``` PHP
is_file(): Argument #1 ($filename) must be of type string, array given
```
This occurs because $upload['tmp_name'] may be an array when multiple files are uploaded, but the cleanup code assumes it is always a string.

### Relevant Code (Contao\Form, lines 308–323)
``` PHP
// Remove any uploads, if form did not validate (#1185)
if (($doNotSubmit || $this->hasErrors()) && $hasUpload)
{
    foreach ($arrFiles as $upload)
    {
        if (!empty($upload['uuid']) && null !== ($file = FilesModel::findById($upload['uuid'])))
        {
            $file->delete();
        }

        if (isset($upload['tmp_name']) && is_file($upload['tmp_name']))
        {
            unlink($upload['tmp_name']);
        }
    }
}

```
When multiple = true, $upload['tmp_name'] can be an array, causing is_file() and unlink() to fail.

### Environment
Contao version: 5.7.3
PHP version: 8.3
Environment: local
Extensions installed: none relevant (contao-manager edition)

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #9696

### CODE REVIEW

File: core-bundle/contao/forms/FormUpload.php [hunk 1]
```diff
@@ -133,23 +133,12 @@ public function validate()
 			return;
 		}
 
-		$files = $_FILES[$this->strName];
+		$files = array_map(static fn ($value): array => (array) $value, $_FILES[$this->strName]);
```
Comment (fritzmg) [inline core-bundle/contao/forms/FormUpload.php:136]: @lukasbableck this is unrelated, but we could save a few lines of code here by simply always casting the properties to an array - instead of checking for `$fileCount == 1` and then using `foreach`. wdyt?

**Review by lukasbableck — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
