### PR TITLE
Do not boot Contao framework in DefaultIndexer::delete()

### LINKED ISSUE #5426: SearchIndexListener causing potential `Failed to start the session because headers have already been sent`
### Affected version(s)

all

### Description

The issue can be best reproduced by calling `assets/images/foobar-image-that-does-not-exist.jpg`.

The `ImagesController` is one that does not require the `ContaoFramework` to be initialized. So what happens in this case is that you'll end up in a 404 and thus the `SearchIndexListener` will try to `delete()` on the `IndexerInterface $indexer` in the `kernel.terminate` event. So **after** the response (and thus the headers) have already been sent to the client.

The used indexer, by default, is our `DefaultSearchIndexer` which accesses the "old" `Search` library that supports hooks and thus, has to make sure, the `ContaoFramework` is initialized.
Hence, [it initializes the framework](https://github.com/contao/contao/blob/4.9/core-bundle/src/Search/Indexer/DefaultIndexer.php#L119). Normally, this is no problem because in 99% of all cases, it has already been initialized and so nothing happens. However, for more modern routes like our `ImagesController`, it is not.
So effectively, it will now initialize the `ContaoFramework` in the `kernel.terminate` environment. It will call hooks like the ones listening to `initializeSystem` and they potentially access the session causing `Failed to start the session because headers have already been sent` issues. But essentially, it could be anything.

I'm not quite sure how to fix this so marking `up for discussion`.

### PR DESCRIPTION
**Pull request by Toflar**
Same as https://github.com/contao/contao/pull/5440 for 4.13

### CODE REVIEW

**Comment by Toflar** [comment]
@fritzmg I did change the typehint here because `->delete()` shortcuts etc. are not part of the interface and we use it anywhere else. I did not bother changing it in 4.9 though because there we use DBAL 2 and there's no difference.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by ausi** [comment]
This breaks in my setup, I get an error `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':url' at line 1`

File: core-bundle/src/Resources/contao/library/Contao/Search.php [hunk 1]
```diff
@@ -782,33 +783,31 @@ public static function query(string $strKeywords, bool $blnOrSearch=false, array
...
+		$connection = $connection ?? System::getContainer()->get('database_connection');
 
-		$objResult = $objDatabase->prepare("SELECT id FROM tl_search WHERE url=?")
-								 ->execute($strUrl);
+		$result = $connection
+			->prepare('SELECT id FROM tl_search WHERE url=:url')
+			->executeQuery(array('url' => $strUrl));
 
-		while ($objResult->next())
+		foreach ($result->fetchAllAssociativeIndexed() as $id)
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Search.php:794]: This doesn’t seem to work

```suggestion
		foreach ($result->fetchFirstColumn() as $id)
```

File: core-bundle/src/Resources/contao/library/Contao/Search.php [hunk 2]
```diff
@@ -782,33 +783,31 @@ public static function query(string $strKeywords, bool $blnOrSearch=false, array
...
 		{
 			// Decrement document frequency counts
-			$objDatabase
+			$connection
 				->prepare("
 					UPDATE tl_search_term
-					INNER JOIN tl_search_index ON tl_search_term.id = tl_search_index.termId AND tl_search_index.pid = ?
+					INNER JOIN tl_search_index ON tl_search_term.id = tl_search_index.termId AND tl_search_index.pid = :id
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Search.php:800]:
```suggestion
					INNER JOIN tl_search_index ON tl_search_term.id = tl_search_index.termId AND tl_search_index.pid = ?
```

Using `?` instead of the named parameters fixed it in my setup.

File: core-bundle/src/Resources/contao/library/Contao/Search.php [hunk 3]
```diff
@@ -782,33 +783,31 @@ public static function query(string $strKeywords, bool $blnOrSearch=false, array
...
-	public static function removeEntry($strUrl)
+	public static function removeEntry($strUrl, Connection $connection = null)
 	{
-		$objDatabase = Database::getInstance();
+		$connection = $connection ?? System::getContainer()->get('database_connection');
 
-		$objResult = $objDatabase->prepare("SELECT id FROM tl_search WHERE url=?")
-								 ->execute($strUrl);
+		$result = $connection
+			->prepare('SELECT id FROM tl_search WHERE url=:url')
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Search.php:791]:
```suggestion
			->prepare('SELECT id FROM tl_search WHERE url=?')
```
same here

File: core-bundle/src/Resources/contao/library/Contao/Search.php [hunk 4]
```diff
@@ -782,33 +783,31 @@ public static function query(string $strKeywords, bool $blnOrSearch=false, array
...
+			->executeQuery(array('url' => $strUrl));
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Search.php:792]:
```suggestion
			->executeQuery('SELECT id FROM tl_search WHERE url=:url', array('url' => $strUrl));
```

This way, named parameters would work. Not sure which style we prefer.
