### PR TITLE
Fix the front end preview URLs in the back end

### LINKED ISSUE #1224: FE preview redirect for pages inconsistent
**Affected version(s)**

4.9 RC1

**Description**

The FE preview URL when clicking on the icon in the page tree looks as follows: `/contao?do=feRedirect&page=299`. That looks like the old format because when you edit a page and click on preview, you get to `/contao/preview?page=299`.
This should be unified. Imho the `do=feRedirect` is the old way and can be replaced.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #1224

### CODE REVIEW

File: core-bundle/src/Resources/contao/classes/Backend.php [hunk 1]
```diff
@@ -932,7 +932,7 @@ public static function addPageIcon($row, $label, DataContainer $dc=null, $imageA
 		$label = '<a href="' . self::addToUrl('pn=' . $row['id']) . '" title="' . StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['selectNode']) . '">' . $label . '</a>';
 
 		// Return the image
-		return '<a href="contao/main.php?do=feRedirect&amp;page=' . $row['id'] . '" title="' . StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['view']) . '" target="_blank">' . Image::getHtml($image, '', $imageAttribute) . '</a> ' . $label;
+		return '<a href="contao/preview.php?page=' . $row['id'] . '" title="' . StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['view']) . '" target="_blank">' . Image::getHtml($image, '', $imageAttribute) . '</a> ' . $label;
```
Comment (bytehead) [inline core-bundle/src/Resources/contao/classes/Backend.php:935]: There is actually a config value for `/preview.php`: `contao.previewScript`.

File: core-bundle/src/Resources/contao/dca/tl_article.php [hunk 2]
```diff
@@ -548,7 +548,7 @@ public function addIcon($row, $label)
 			$image .= '_';
 		}
 
-		return '<a href="contao/main.php?do=feRedirect&amp;page=' . $row['pid'] . '&amp;article=' . ($row['alias'] ?: $row['id']) . '" title="' . Contao\StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['view']) . '" target="_blank">' . Contao\Image::getHtml($image . '.svg', '', 'data-icon="' . ($unpublished ? $image : rtrim($image, '_')) . '.svg" data-icon-disabled="' . rtrim($image, '_') . '_.svg"') . '</a> ' . $label;
+		return '<a href="contao/preview.php?page=' . $row['pid'] . '&amp;article=' . ($row['alias'] ?: $row['id']) . '" title="' . Contao\StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['view']) . '" target="_blank">' . Contao\Image::getHtml($image . '.svg', '', 'data-icon="' . ($unpublished ? $image : rtrim($image, '_')) . '.svg" data-icon-disabled="' . rtrim($image, '_') . '_.svg"') . '</a> ' . $label;
```
Comment (bytehead) [inline core-bundle/src/Resources/contao/dca/tl_article.php:551]: There is actually a config value for `/preview.php`: `contao.previewScript`.

**Review by bytehead — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/classes/Backend.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/classes/Backend.php:935]: That's the old legacy URL, which will be replaced automatically in the `Controller::replaceOldBePaths()` method:

https://github.com/contao/contao/blob/68b47c6ccab103c8fd205bc1c9a7f105c293d86b/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1116-L1127

It has nothing to do with the `preview.php` entry point.

File: core-bundle/src/EventListener/PreviewUrlConvertListener.php [hunk 3]
```diff
@@ -16,6 +16,7 @@
 use Contao\CoreBundle\Event\PreviewUrlConvertEvent;
 use Contao\CoreBundle\Framework\ContaoFramework;
 use Contao\PageModel;
+use Symfony\Component\HttpFoundation\Request;
```
Comment (Toflar) [inline core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: Are these changes related in any way or is that just CS? If there are changes then the tests should reflect those and otherwise I'm confused why this is in this PR (not saying you have to do another one but for next time...I just don't know what this is doing here).

Comment (bytehead) [reply core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: They are, see `private function getParams(Request $request): ?string`: https://github.com/contao/contao/pull/1286/files#diff-3ce6d6db43287783796b3f1f09f1f81fR62

Comment (ausi) [reply core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: I think he means all changes in this file. For me most of it looks like CS or rather restructuring, but it seems that `$article->id` got changed to `$article->alias`.

Comment (leofeyer) [reply core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: The PR does not include CS fixes. I have fixed and refactored the `__invoke()` method though; it used `$article->id` although it should have used `$article->alias` to be in line with the `Controller::redirectToFrontendPage()` method:

https://github.com/contao/contao/blob/68b47c6ccab103c8fd205bc1c9a7f105c293d86b/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1359-L1363

Comment (Toflar) [reply core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: What I‘m saying is that if it‘s CS, it doesn‘t belong here. If it‘s a bugfix, tests need to reflect the changes😊 So apparently the tests are missing which might cause a future regression.

File: core-bundle/src/Resources/contao/classes/Backend.php (hunk 1 above)
Comment (richardhj) [reply core-bundle/src/Resources/contao/classes/Backend.php:935]: Why do you use the legacy URL in favor of generating the `contao_backend_preview` route URL?

Comment (leofeyer) [reply core-bundle/src/Resources/contao/classes/Backend.php:935]: Because when we start replacing the old BE URLs in the legacy code (which we should do at some point), we should replace them all instead of just one now.

Comment (aschempp) [reply core-bundle/src/Resources/contao/classes/Backend.php:935]: We should really stop that behavior of *don't refactor because we can't refactor it all just now* 🙈 🤷‍♂

Comment (leofeyer) [reply core-bundle/src/Resources/contao/classes/Backend.php:935]: I disagree, because consistency is way more important IMHO.

**Review by bytehead — DISMISSED** [review]

**Review by Toflar — CHANGES_REQUESTED** [review]
LGTM apart from the missing test for the article handling.

**Comment by leofeyer** [comment]
Unit test added in 7dfad9c2f022a5fb50a28f8d3b90f833bc68137b.

File: core-bundle/src/EventListener/PreviewUrlConvertListener.php (hunk 3 above)
Comment (leofeyer) [reply core-bundle/src/EventListener/PreviewUrlConvertListener.php:19]: Unit test added in 7dfad9c2f022a5fb50a28f8d3b90f833bc68137b.

**Review by bytehead — APPROVED** [review]

**Review by Toflar — APPROVED** [review]
👍
