### PR TITLE
Fix the Stimulus color picker preview

### LINKED ISSUE #8504: All-letter hex value in colorpicker not working for background of colorpicker icon
### Affected version(s)

5.5

### Description

I developed a custom backend module with a colorpicker.
Entering an all-letter hex value in the input field and saving the module would not change the background color of the colorpicker icon.

Reproducible in demo.contao.org backend:
1. create a new content element of type "Vimeo"
2. in "controls color" enter "ffffff"
3. save the record
--> the background of the colorpicker icon is incorrectly set to black (clicking on the color picker icon the shown value is #000000).
(4. entering "ffff00" in "controls color" and saving the record sets the background of the colorpicker icon to ffff00 and also the shown value in the small colorpicker window is shown as #FFFF00)

I can't tell if this is just a quirk regarding the background color of the colorpicker icon and which value is actually saved. The color of the Vimeo controls never change, regardless of which hex value is entered (which would be a different issue).

### PR DESCRIPTION
**Pull request by zoglo**
### Description

- fixes #8504

The root cause of the issue is stripping the rhombus to comply to our own input field with eval color and initializing the default with `ffffff`. The used library expects hex colors with the rhombus prepended (see value on [input type color](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/color)), in this specific case it did work without the rhombus (`#`) but not for `ffffff` so allowing other values is more of a feature than a bug.

#### Explanation for the fix

Since our color picker allows different values than hex (depending on eval), I check whether the value matches the HEX format first, then _temporarily_ prepend a `#` for the `connect` method that builds the picker as seen here:
https://github.com/stimulus-components/stimulus-components/blob/c44e23a93c469ed41b4d1088fa4639b94f639443/components/color-picker/src/index.ts#L23-L30

I simply strip the attached rhombus again afterwards

#### Disclaimer

I know there is the `inputTargetConnected` that I could have used for that but there was no need as we simply have to handle it just right before the init of the `Pickr` library.

### CODE REVIEW

**Review by aschempp — COMMENTED** [review]
Does not having the `#` only cause issues when the widget is initialized? Asking because we also string `#` when the value is saved. And maybe we want to apply the same logic (`'#' === value.charAt(0)`) instead of storing if we added the prefix?

If `#` is mandatory for the widget, maybe we should use a save and load callback that adds/strips the `#` on the DCA side instead?

File: core-bundle/assets/controllers/color-picker-controller.js [hunk 1]
```diff
@@ -1,6 +1,21 @@
 import ColorPicker from '@stimulus-components/color-picker';
 
 export default class extends ColorPicker {
+    connect() {
+        let hexValueLoaded = false;
+
+        if (this.inputTarget.value && /^[0-9a-f]{6}$/i.test(this.inputTarget.value)) {
```
Comment (leofeyer) [inline core-bundle/assets/controllers/color-picker-controller.js]: Do we also have to handle shortened values like `#fff`?

Comment (zoglo) [reply core-bundle/assets/controllers/color-picker-controller.js]: We have to, yes

Comment (zoglo) [reply core-bundle/assets/controllers/color-picker-controller.js]: See b492c85690b9ae369f71e62ca239a769bae17c2b

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.
