### PR TITLE
Delete uploaded files if a form does not validate

### LINKED ISSUE #1185: Residual file via frontend upload when server-side form validation fails because of other field
**Affected version(s)**
4.4, 4.8

**Description**
If a file is uploaded via a frontend form, the upload is completed and the file is retained even when server-side form validation fails because of another field in the form.

**How to reproduce**
* Create a new form in the form generator.
* Create a file upload field. Check "Store uploaded files" and select a directory.
* Create a text field. For "Input validation", select "Alphabetic characters".
* Add a send field.
* In the frontend, select a valid file, but type `123` into the text field. Send the form.

**Result:** You get an error message for the "Alphabetic characters" field, but the file from the other field is uploaded anyway.

This produces a greater issue if you also select "Preserve existing files" in the file upload field settings: A user initially selects a file, but enters something invalid in another field. They send the form. Once they get the validation error, they enter something correct and re-send the form, again with the file. Their initially-validated and already-uploaded file is now uploaded a second time and given a suffix.

**Expected result:** Ideally, the file would not be uploaded or not be moved to the selected directory if the form does not pass validation.

### PR DESCRIPTION
**Pull request by fritzmg**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1185
| Docs PR or issue | -

This is an alternative, less invasive approach to #3600 in order to fix #1185. Instead of introducing a new mechanic for the legacy framework, this PR instead fixes the specific, original problem by making sure the `Form` removes any uploaded files, if the form itself did not validate. `Form` already purges `$_SESSION['FILES']` when the form did not validate here:

https://github.com/contao/contao/blob/ba5f1ba905f54918641267f2e90965d3d1153df0/core-bundle/src/Resources/contao/forms/Form.php#L262-L271

so the `Form` might as well also properly delete the uploads.

### CODE REVIEW

**Review by aschempp — APPROVED** [review]
I like that a lot more than the other PR. It will automatically work for any upload widget without requiring adjustments (e.g. our fineuploader I would assume).

**Comment by leofeyer** [comment]
> I like that a lot more than the other PR.

So do I.

File: core-bundle/src/Resources/contao/forms/Form.php [hunk 1]
```diff
@@ -259,6 +259,30 @@ protected function compile()
 			$this->processFormData($arrSubmitted, $arrLabels, $arrFields);
 		}
 
+		// Remove any uploads, if form did not validate (#1185)
+		if ($doNotSubmit && $hasUpload && !empty($_SESSION['FILES']))
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/forms/Form.php:263]: Do we not need the `&& !Environment::get('isAjaxRequest')` check here as well?

Comment (fritzmg) [reply core-bundle/src/Resources/contao/forms/Form.php:263]: I don't think so. It looks like a bug to me that `$_SESSION['FILES']` was not purged in the past when the form was sent via AJAX. Or conversely: it should not matter whether the form was sent via AJAX or not. If the form does not validate, any uploaded file should be deleted, regardless of the type of request, should it not?

**Comment by leofeyer** [comment]
Thank you @fritzmg.
