### PR TITLE
Only use the VFS in `DC_Folder` when writing into "files"

### LINKED ISSUE #9563: Internal Server Error when editing legacy templates
### Affected version(s)

5.7.1

### Description

In 5.7.1, when I try to edit any legacy template, I get an internal server error.

Error message is:
`"Virtual filesystem path "../templates/mein-theme/mod_article.html5" must not escape the filesystem boundary."`

Stack Trace in Debug mode:

```
OutOfBoundsException:
Virtual filesystem path "../templates/mein-theme/mod_article.html5" must not escape the filesystem boundary.

  at vendor/contao/core-bundle/src/Filesystem/VirtualFilesystem.php:384
  at Contao\CoreBundle\Filesystem\VirtualFilesystem->resolve('../templates/mein-theme/mod_article.html5')
     (vendor/contao/core-bundle/src/Filesystem/VirtualFilesystem.php:89)
  at Contao\CoreBundle\Filesystem\VirtualFilesystem->write('../templates/mein-theme/mod_article.html5', '<?php if ($this->teaserOnly): ?>  <?php $this->block(\'alias\'); ?>    <article class="<?= $this->class ?> block test"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>      <div class="tce_text block">        <h2><?= $this->headline ?></h2>        <div class="teaser">          <?= $this->cspInlineStyles($this->teaser) ?>          <p class="more"><a href="<?= $this->href ?>" title="<?= $this->readMore ?>"><?= $this->more ?> <span class="invisible"><?= $this->headline ?></span></a></p>        </div>      </div>    </article>  <?php $this->endblock(); ?><?php elseif ($this->noMarkup): ?>  <?php $this->block(\'content\'); ?>    <?= implode(\'\', $this->elements) ?>  <?php $this->endblock(); ?><?php else: ?>  <div class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>  	<div class="article-wrapper">    <?php if ($this->printable): ?>      <?php $this->block(\'syndication\'); ?>        <!-- indexer::stop -->        <div class="syndication">          <?php if ($this->printButton): ?>            <a href="<?= $this->print ?>" class="print" title="<?= $this->printTitle ?>" onclick="window.print();return false" data-skip-search-index><?= Contao\\Image::getHtml(\'assets/contao/images/print.svg\') ?></a>          <?php endif; ?>          <?php if ($this->pdfButton): ?>            <a href="<?= $this->href ?>" class="pdf" title="<?= $this->pdfTitle ?>" data-skip-search-index><?= Contao\\Image::getHtml(\'assets/contao/images/pdf.svg\') ?></a>          <?php endif; ?>          <?php if ($this->facebookButton): ?>            <a href="<?= $this->route(\'contao_frontend_share\', [\'p\' => \'facebook\', \'u\' => $this->encUrl]) ?>" class="facebook" rel="nofollow" title="<?= $this->facebookTitle ?>" onclick="var w=window.open(this.href,\'\',\'width=640,height=380,modal=yes,left=100,top=50,location=no,menubar=no,resizable=yes,scrollbars=yes,status=no,toolbar=no\');w.opener=null;return false"><?= Contao\\Image::getHtml(\'assets/contao/images/facebook.svg\') ?></a>          <?php endif; ?>          <?php if ($this->twitterButton): ?>            <a href="<?= $this->route(\'contao_frontend_share\', [\'p\' => \'twitter\', \'u\' => $this->encUrl, \'t\' => $this->encTitle]) ?>" class="twitter" rel="nofollow" title="<?= $this->twitterTitle ?>" onclick="var w=window.open(this.href,\'\',\'width=640,height=380,modal=yes,left=100,top=50,location=no,menubar=no,resizable=yes,scrollbars=yes,status=no,toolbar=no\');w.opener=null;return false"><?= Contao\\Image::getHtml(\'assets/contao/images/twitter.svg\') ?></a>          <?php endif; ?>        </div>        <!-- indexer::continue -->      <?php $this->endblock(); ?>    <?php endif; ?>    <?php $this->block(\'content\'); ?>      <?= implode(\'\', $this->elements) ?>    <?php $this->endblock(); ?>    <?php if ($this->backlink): ?>      <?php $this->block(\'backlink\'); ?>        <!-- indexer::stop -->        <p class="back"><a href="<?= $this->backlink ?>" title="<?= $this->back ?>"><?= $this->back ?></a></p>        <!-- indexer::continue -->      <?php $this->endblock(); ?>    <?php endif; ?>    </div>  </div><?php endif; ?>')
     (vendor/contao/core-bundle/contao/drivers/DC_Folder.php:2145)
  at Contao\DC_Folder->source()
     (vendor/contao/core-bundle/contao/classes/Backend.php:463)
  at Contao\Backend->getBackendModule('tpl_editor', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:143)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/Backend/BackendController.php:45)
  at Contao\CoreBundle\Controller\Backend\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:183)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:193)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)
```

How to reproduce:
- Create a *.html5 template in "LAYOUT -> Templates"
- Try to edit the source text of the template and click "Save" or "Save and close"

Regards
Mathias

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #9563

@mdollde Can you test if this fixes your issue?

### CODE REVIEW

**Review by lukasbableck — DISMISSED** [review]

File: core-bundle/contao/drivers/DC_Folder.php [hunk 1]
```diff
@@ -2139,11 +2139,19 @@ public function source()
 					$strSource = gzencode($strSource);
 				}
 
-				// Write the file using the VFS (see #9450)
-				System::getContainer()
-					->get('contao.filesystem.virtual.files')
-					->write(Path::makeRelative($objFile->path, 'files'), $strSource)
-				;
+				// Write the file using the VFS if possible (see #9450)
+				if (Path::isBasePath('files', $objFile->path))
```
Comment (ausi) [inline core-bundle/contao/drivers/DC_Folder.php]: Should we check for `%contao.upload_path%` here instead of hardcoded `files` ?

Comment (m-vo) [reply core-bundle/contao/drivers/DC_Folder.php]: see 35bba85da6079d76ff47d46815c3786065121359

**Review by lukasbableck — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Review by ausi — APPROVED** [review]
