### PR TITLE
Use ClockMock for time sensitive test

### LINKED ISSUE #3226: Use ClockMock in AuthenticationProviderTest
For reference, see this failing CI job: https://github.com/contao/contao/pull/3219/checks?check_run_id=3191509596

### PR DESCRIPTION
**Pull request by bytehead**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3226
| Docs PR or issue | n/a

Use ClockMock for this time sensitive test.

### CODE REVIEW

File: core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php [hunk 1]
```diff
@@ -120,6 +121,8 @@ public function testLocksUserOnInvalidTwoFactorCode(int $initialAttempts, int $l
         $provider = $this->createTwoFactorProvider($authProvider, $userChecker);
         $hasException = false;
 
+        ClockMock::withClockMock(true);
```
Comment (m-vo) [inline core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: I think this also needs to be registered - either by calling `ClockMock::register()` or by adding the `@time-sensitive` annotation on the method/in the `phpunit.xml`. You test can with `sleep(1000);` for instance - this should pass instantly.

**Review by m-vo — CHANGES_REQUESTED** [review]

File: core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: Just noticed, that we have already got some classes in the `phpunit.xml`:

https://github.com/contao/contao/blob/2ca2e45476e5a98aba8644093551a6576fa37261/phpunit.xml.dist#L63-L70

Comment (bytehead) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: This are whole directories. I'd rather register the `ClockMock` in the test, what do you think?

Comment (m-vo) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: Sounds sensible to me!

I'm personally in favor of the method annotation, but not sure what @leofeyer thinks about this?

Comment (bytehead) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: annotation is also fine for me :)

Comment (ausi) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: It’s not about directories but about namespaces, ClockMock works by creating a function in the registered namespaces so that the classes in these namespaces use the moked functions instead of the native php functions.

We have to register the namespaces in the phpunit xml file because registering it in the tests can be too late (if the class was already loaded by a different test).

Comment (bytehead) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: Thanks for the clarification. I'll adjust it.

Comment (bytehead) [reply core-bundle/tests/Security/Authentication/Provider/AuthenticationProviderTest.php:124]: Added to the list in b5486f939.

File: phpunit.xml.dist [hunk 2]
```diff
@@ -63,6 +63,8 @@
                             <element key="1"><string>Contao\CoreBundle\Tests\Command</string></element>
                             <element key="2"><string>Contao\CoreBundle\Cron\Command</string></element>
                             <element key="3"><string>Contao\CoreBundle\Tests\Cron</string></element>
+                            <element key="4"><string>Contao\CoreBundle\Security\Authentication\Provider</string></element>
+                            <element key="4"><string>Contao\CoreBundle\Tests\Security\Authentication\Provider</string></element>
```
Comment (ausi) [inline phpunit.xml.dist]:
```suggestion
                            <element key="5"><string>Contao\CoreBundle\Tests\Security\Authentication\Provider</string></element>
```

Comment (bytehead) [reply phpunit.xml.dist]: ups 🙈

**Review by ausi — APPROVED** [review]

**Review by m-vo — APPROVED** [review]
:heart:

**Comment by leofeyer** [comment]
Thank you @bytehead.
