### PR TITLE
Fix external news targets not opening in a new window

### LINKED ISSUE #2947: respect news redirect target
**Affected version(s)**

Tested in demo (4.9.12)

**Description**

News-Item:
Redirect target->Custom URL->Open in new window
The link does **not** open in new window (neither layout_simple nor layout_short).
It works for events though.

image

### PR DESCRIPTION
**Pull request by fritzmg**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2947
| Docs PR or issue | -

The implementation for opening external target URLs for news articles in a new window was erroneously removed in https://github.com/contao/contao/pull/2615. This PR fixes that.

### CODE REVIEW

File: news-bundle/src/Resources/contao/modules/ModuleNews.php [hunk 1]
```diff
@@ -369,9 +369,10 @@ protected function generateLink($strLink, $objArticle, $blnAddArchive=false, $bl
 		$strArticleUrl = News::generateNewsUrl($objArticle, $blnAddArchive);
 
 		return sprintf(
-			'<a href="%s" title="%s" itemprop="url">%s%s</a>',
+			'<a href="%s" title="%s"%s itemprop="url">%s%s</a>',
 			$strArticleUrl,
 			StringUtil::specialchars(sprintf($strReadMore, $blnIsInternal ? $objArticle->headline : $strArticleUrl), true),
+			($objArticle->target && !$blnIsInternal ? ' target="_blank" rel="noreferrer noopener"' : ''),
```
Comment (m-vo) [inline news-bundle/src/Resources/contao/modules/ModuleNews.php:375]: Shouldn't `rel="noreferrer noopener"` be added to each external link (independent of the target)?

Comment (fritzmg) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php:375]: That's how it was previously. I assume the thought behind it that there is no real reason to add `noreferrer noopener` for links that point to your own site, as it is not an untrusted link.

Comment (m-vo) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php:375]: You could also add an external link and not set it to open in a new window, could you? This is probably what you want for UX anyway.

I know it was like this before but IMHO we should change it. :slightly_smiling_face:

**Review by leofeyer — APPROVED** [review]

File: news-bundle/src/Resources/contao/modules/ModuleNews.php (hunk 1 above)
Comment (leofeyer) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php:375]: @contao/developers WDYT?

Comment (ausi) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php:375]: AFAIK `noopener` only makes sense for `target=_blank` links as links in the same page don’t get an opener reference anyway. I would keep it as it is now.

**Comment by leofeyer** [comment]
Thank you @fritzmg.
