### PR TITLE
Handle empty label fields in the picker

### LINKED ISSUE #6181: Widget Picker - Fehler bei DCA -> list -> label -> fields -> leeres value (vgl. tl_member.php)
### Affected version(s)

4.13.25

### Description

Hallo zusammen:

In der tl_member.php wird das Label für die Erste Spalte auf Nichts (leer) gesetzt - Siehe hier:
https://github.com/contao/contao/blob/27f0144d05b2acffed7f493ca929d9a6649495c2/core-bundle/src/Resources/contao/dca/tl_member.php#L56-L61

Möchte man aber jetzt zum Beispiel das Widget Picker verwenden (z.B. wegen der Sortiermöglichkeiten) und versucht auf die Tabelle **tl_member.php** zu zugreifen, tritt eine Exception auf.

Die Exception tritt auf, weil die Variable $f als Key leer ist:
https://github.com/contao/contao/blob/27f0144d05b2acffed7f493ca929d9a6649495c2/core-bundle/src/Resources/contao/widgets/Picker.php#L149-L151

Hintergrund ist zwar, dass in dieser Zeile geprüft wird, ob es sich um ein Array handelt, allerdings wird im ELSE-Teil auf einen nicht existenden Key $f zugegriffen, der dann die Exception auslöst.

Vorschlag wäre die Zeilen L149-L151 gegen folgendes auszutauschen:

```
// Leeres Label (vgl. tl_member)
if ($f == '') {
	$return .= '<th class="tl_folder_tlist col_empty">&nbsp;</th>';
}

else {
	$return .= '<th class="tl_folder_tlist col_' . $f . '">' . (\is_array($GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label']) ? $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label'][0] : $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label']) . '</th>';
}
```

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6181

As suggested by @ausi in https://github.com/contao/contao/issues/6181#issuecomment-1611114172.

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by ausi — APPROVED** [review]

File: core-bundle/src/Resources/contao/widgets/Picker.php [hunk 1]
```diff
@@ -147,7 +147,7 @@ public function generate()
 				}
 
 				$return .= '
-    <th class="tl_folder_tlist col_' . $f . '">' . (\is_array($GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label']) ? $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label'][0] : $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label']) . '</th>';
+    <th class="tl_folder_tlist col_' . $f . '">' . (\is_array($GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label'] ?? null) ? $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label'][0] : $GLOBALS['TL_DCA'][$strRelatedTable]['fields'][$f]['label'] ?? '') . '</th>';
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/widgets/Picker.php:150]: shouldn't we use `$f` (the field name) as a fallback for the label here?

Comment (leofeyer) [reply core-bundle/src/Resources/contao/widgets/Picker.php:150]: No, an empty string is correct.
