### PR TITLE
Drop the schema filter and adjust the schema generator

### LINKED ISSUE #1664: Consider dropping or modifying doctrine schema filter
In 22ebe459273a85843be441cc43c614f48224fba6 we added a schema filter to the installer so that only tables starting with `tl_` are processed. I'd like to discuss that decision again or vote for the implementation of configurable exceptions. 

**Consider this scenario:**

There is a Symfony bundle that brings along some entities and a Contao extension wrapping this bundle so that users can easily install and use it (providing a ContaoManagerPlugin, configuration + so on). 

Now the table for the bundle's entities won't get created when calling `contao:migrate` or using the InstallTool. So in order to get things working for Contao users the only way (I can currently think of) is to manipulate the entities name in a `loadClassMetadata` event to include the prefix. This is imo too hacky and could possibly break references.

**Possible solutions**

1. Remove the filter again and simply handle all tables.
2. Allow defining exceptions (e.g. via prepended config) - as the filter can be a function (and not only regex like pre version 2.9) this shouldn't be too hard.

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Closes #1664 
| Docs PR or issue | todo

This drops the default `tl_` prefix schema filter. I also removed the obsolete `DcaSchemaProvider:createFromDca` code path and moved the schema creation into its own service (because SOC).

The schema generation process looks like this: 

1) The `Installer` creates a `$fromSchema` from the database and a `$toSchema` from our `SchemaProvider`.
2) The `SchemaProvider` asks the `SchemaTool` to create a schema from the manager's class meta data.
3) This will trigger the `contao.listener.doctrine_schema` listener that listens on doctrine's `postGenerateSchema` event and calls `DcaSchemaProvider#appendToSchema` which will add the DCA definitions.

If you want to alter the schema, e.g. to add another table that's neither defined via DCA definitions or entity metadata (see https://github.com/contao/contao/issues/1664#issuecomment-635566159) you can add your own schema listener on the `postGenerateSchema` event like in 2) + a priority <0/>0 if you want to run after/before the core.

E.g. to create a table `foo` with an `id INT` column you could add a listener like this:

```php
// Doctrine\ORM\Tools\ToolEvents::postGenerateSchema
public function postGenerateSchema(GenerateSchemaEventArgs $event)
{
    $schema = $event->getSchema();

    $table = $schema->createTable('foo');
    $table->addColumn('id', 'integer');
}
```

@discordier Would that fit your needs?

todo:
* [x] adjust + drop tests

### CODE REVIEW

**Comment by discordier** [comment]
> @discordier Would that fit your needs?

Looks fine so far. This way I can adjust the whole Schema to my needs, good job. :+1:

**Comment by m-vo** [comment]
Tests are adjusted now. That was quite a hassle...

The new `SchemaProvider` now optionally allows injecting the `SchemaTool`. However, this is only needed for the unit tests to allow mocking it (otherwise we would test doctrine's code and couple the tests to their internals which imo is the wrong way). If someone has an idea how to solve this in a nicer way, please let me know :smile:. btw.: Making it a service instead and always injecting it looks like the wrong solution to me as well.

**Comment by ausi** [comment]
> The new `SchemaProvider` now optionally allows injecting the `SchemaTool`. However, this is only needed for the unit tests to allow mocking it

The `SchemaProvider::createSchema()` method is only two lines of code. I think I would prefer to test the output of the real `SchemaTool` instead of mocking it.

**Comment by m-vo** [comment]
>The SchemaProvider::createSchema() method is only two lines of code. I think I would prefer to test the output of the real SchemaTool instead of mocking it.

I went yet another route and also used a "real" entity manager now. This way there is no mocking needed and it still tests that the implementation creates a schema from the entity manager's class metadata. 

(The code for that which now lives in our `DoctrineTestCase` is heavily inspired by Symfony's `DoctrineTestHelper`.)

**Review by aschempp — COMMENTED** [review]
Why did you create a new class instead of just adding the new code to the existing one?

**Comment by m-vo** [comment]
> Why did you create a new class instead of just adding the new code to the existing one?

Separation of concerns:
-  The `DcaSchemaProvider` enhances the schema with tables from the DCA definitions - IMO it should really be called `DcaSchemaListener` but the name (and deprecated `createSchema` method) must be kept for BC.
- The new `SchemaProvider` actually creates a schema from metadata.

Before these two things were somewhat intertwined, likely due to the fact that we did not always have ORM in the beginning and needed two different strategies (that are now unified).

**Comment by aschempp** [comment]
But either class is only necessary because we **do** have/add schema from DCA?

**Comment by m-vo** [comment]
> But either class is only necessary because we **do** have/add schema from DCA?

No, these are orthogonal concepts. The `SchemaProvider` is there to provide data for our schema tooling and doesn't know anything about the DCA (or any other listeners that might alter the schema).

**Comment by aschempp** [comment]
🤷 that hasn't changed, it has been like this since the `DcaSchemaProvider` was added. I (personally) just think we shouldn't add another class without improving anything other than *class naming*. It just requires another BC layer for zero reasons.

**Comment by m-vo** [comment]
I don't get it. Why should these two things be in the same class? 

> It just requires another BC layer for zero reasons

Which BC layer are you referring to? Do you mean the deprecated method that few people (if any) will have used in their code?

**Comment by aschempp** [comment]
> Do you mean the deprecated method that few people (if any) will have used in their code?

Yes. You moved the `createSchema` method into a new class, which does the same thing (with different code) that it already did in the old class, and add a BC layer so the old class uses the new class 🤷

**Comment by m-vo** [comment]
Nobody should call `DcaSchemaProvider#createSchema` and neither does any of the production code in this class use the new `SchemaProvider`. The method is just a leftover from previous usage/implementation where schema creation and appending was mixed together.

**Comment by aschempp** [comment]
I'm not sure what we're talking here about. The code in https://github.com/contao/contao/pull/2049/files#diff-241e59c1f0c35337477b3df6f6f2ef87L140-L153 is (almost) the same as your new code in https://github.com/contao/contao/pull/2049/files#diff-ce2cdf2eac0620c62fb09db9643db272R34-R43. So you basically copied that code to a new class, with the same (public) method name. I don't see why that would be useful.

**Comment by m-vo** [comment]
The code that you referenced (https://github.com/contao/contao/pull/2049/files#diff-241e59c1f0c35337477b3df6f6f2ef87L140-L153) is dead/never executed because we *always* have ORM enabled. And the other bit (`createSchemaFromOrm`) simply doesn't belong in this class. It has nothing todo with the DCA?!

**Comment by m-vo** [comment]
This PR is rebased against the current master, now + should be ready to go. Resolving the conflicts from the tests was pita and unfortunately the diff is quite large now. I'm not really happy with this, but well...

The failing test seem unrelated.

File: core-bundle/tests/Doctrine/DoctrineTestCase.php [hunk 1]
```diff
@@ -12,256 +12,61 @@
...
-    }
-
-    /**
-     * Mocks a Doctrine registry with database connection and ORM.
+     * @param Connection|MockObject|null $connection
      *
      * @return Registry&MockObject
      */
-    protected function mockDoctrineRegistryWithOrm(array $metadata = [], string $filter = null): Registry
+    protected function mockDoctrineRegistry($connection = null): Registry
```
Comment (leofeyer) [inline core-bundle/tests/Doctrine/DoctrineTestCase.php:41]: Changing the method signature is a BC break. Not sure if our BC promise applies to test class, but since it is an abstract class, we must assume that people are using it. @contao/developers WDYT?

Comment (m-vo) [reply core-bundle/tests/Doctrine/DoctrineTestCase.php:41]: Imho tests should never be part of the BC promise because they mostly/only make sense in context of the tested code. Otherwise you would end up introducing abstractions and BC layers that shouldn't exist in test code.

Symfony exludes them as well (see [docs](https://symfony.com/doc/current/contributing/code/bc.html#using-our-classes)):
> Classes, properties and methods that bear the tag @internal as well as the classes located in the various *\Tests\ namespaces are an exception to this rule. They are meant for internal use only and should not be accessed by your own code.

Comment (Toflar) [reply core-bundle/tests/Doctrine/DoctrineTestCase.php:41]: See https://github.com/contao/docs/pull/648

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
