### PR TITLE
Fix subpalette toggling

### LINKED ISSUE #5779: SubmitOnChange not triggering save_callback
### Affected version(s)

4.13

### Description

Follow up for #3246

### PR DESCRIPTION
**Pull request by aschempp**
The `toggleSubpalette` currently modifies the database directly, without `save_callback` or thelike. It also does not check for `notEditable` on the DCA or thelike. In Contao 5, it does not apply the `onbeforesubmit_callback` or `UpdateAction` permissions.

This can all be "easily" solved by using the `toggle()` operation in `DC_Table`. It only required minimal adjustments to allow for this case.

There is only one caveat we might want to discuss: the field value is now **toggled**, whereas the request previously submitted the new desiered `state`. However, this is/was also the case for all toggle operations in the DCA – they previously submitted a state but the toggle operation does no longer handle them. 

PS: you might want to look at the two commits separately for easier understanding of the changes.

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
I'm okay with the changes. I don't see why `toggleSubpalette` would be needed for anything else than a checkbox state. If you want to have anything else (in which case it would not be "toggling" anyway) you should use your own ajax operation.

**Comment by aschempp** [comment]
> I don't see why `toggleSubpalette` would be needed for anything else than a checkbox state. If you want to have anything else (in which case it would not be "toggling" anyway) you should use your own ajax operation.

It is not meant for anything else but checkboxes and never was. But you currently could set the state of a field to `1` even though the state was already `1` (so nothing really happened). That's no longer the case since we're now **actually toggling**.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -2738,9 +2738,9 @@ public function toggle($intId=null)
 			$this->intId = $intId;
 		}
 
-		$this->strField = Input::get('field');
+		$this->strField = $strSelectorField ?: Input::get('field');
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/drivers/DC_Table.php]: Can we use `Input::post('field') ?? Input::get('field')` instead? Then we would not need the method argument.

Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: If `$strSelectorField` is set, we do not check for the `toggle` permission on the field (because the field is explicitly set, and selectors do not toggle). I also think "hardcoding" this is better than using "random" input that just works for the Ajax class but no other likely use case.

Comment (leofeyer) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: Agreed. But then we should always pass `$strSelectorField` and not fall back on `Input::get('field')`, either.

Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: that won't work, for two reasons:
 1. this is a DC action that is called via `act=toggle`, noone is passing arguments
 2. if `$strSelectorField` is set, we don't check for the toggle permission (`toggle=true` on the field), which is necessary for `act=toggle` but not for manually calling the method.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -2770,7 +2772,7 @@ public function toggle($intId=null)
 		}
 
 		// Check the field access
-		if (!System::getContainer()->get('security.helper')->isGranted(ContaoCorePermissions::USER_CAN_EDIT_FIELD_OF_TABLE, $this->strTable . '::' . $this->strField))
+		if (!DataContainer::isFieldExcluded($this->strTable, $this->strField) && !System::getContainer()->get('security.helper')->isGranted(ContaoCorePermissions::USER_CAN_EDIT_FIELD_OF_TABLE, $this->strTable . '::' . $this->strField))
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/drivers/DC_Table.php]: There seems to be no `DataContainer::isFieldExcluded()` method:

**Review by leofeyer — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/drivers/DC_Table.php [hunk 3]
```diff
@@ -2855,7 +2858,12 @@ public function toggle($intId=null)
 
 		$this->invalidateCacheTags();
 
-		$this->redirect($this->getReferer());
+		Input::setPost('FORM_SUBMIT', $prevSubmit);
+
+		if (!$blnDoNotRedirect)
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/drivers/DC_Table.php:2865]:
```suggestion
		if (!Environment::get('isAjaxRequest'))
```

How about using this instead? It would save us the third method argument.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: ah you're right, this is Contao 5 only. What's the best approach to remove this and make sure it gets re-added in Contao 5?

File: core-bundle/src/Resources/contao/drivers/DC_Table.php (hunk 3 above)
Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php:2865]: I don't think that would be a good idea.
 1. we have this argument on a few other DC actions with exactly the same behaviour
 2. I would no longer be able to toggle a field when not being an ajax request (e.g. implementing my own toggling behaviour)

Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php:2865]: a possible option would be to not redirect when `$strSubmittedField` is given, but that's kind of some magic behavour to me.

File: core-bundle/src/Resources/contao/drivers/DC_Table.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php:2775]: Can we simply add the method in Contao 4.13, too?

Comment (leofeyer) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: I can handle this when I merge the PR, however, are you sure that `!DataContainer::isFieldExcluded()` is correct? It should be `DataContainer::isFieldExcluded()` (without the `!`) IMHO.

Comment (aschempp) [reply core-bundle/src/Resources/contao/drivers/DC_Table.php]: you're right!

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
