### PR TITLE
Use `data-turbo-track="dynamic"` instead of reloading

### LINKED ISSUE #8514: `data-turbo-track="reload"` does not work with dynamically added assets
### Affected version(s)

5.5

### Description

If you use an extension like Changelanguage, which dynamically adds assets like this,

```php
$GLOBALS['TL_CSS'][] = 'bundles/terminal42changelanguage/backend.css';
```

there will be a lot of full page reloads due to `data-turbo-track="reload"`. Even different views within the same module will trigger a full reload, such as `?do=news` (news archive overview) and `?do=news&table=tl_news` (news overview inside an archive). This makes navigating the back end noticeably slower.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #8514 

Currently we have the following in our `be_main`:

https://github.com/contao/contao/blob/30966535b69e6bedf680e695ec13420395fa6094/core-bundle/contao/templates/backend/be_main.html5#L59-L60

This ensures that Turbo reloads the page completely if new stylesheets or scripts are added to the `<head>` dynamically via `$GLOBALS['TL_CSS']` or `$GLOBALS['TL_JAVASCRIPT']`.

This however has caused some issues in the past, most notably https://github.com/contao/contao/issues/8182. And if a back end module adds an assets dynamically like this, prefetching is moot as well - and there were other issues like https://github.com/contao/contao/issues/8430

While the latter has been alleviated by always loading those assets in the back end, we are still loading some assets dynamically in some back end view in some of our bundles, e.g.:

https://github.com/contao/contao/blob/23f615f83a6582b0067cc2e68f498f9233adac79/comments-bundle/contao/config/config.php#L26

https://github.com/contao/contao/blob/23f615f83a6582b0067cc2e68f498f9233adac79/newsletter-bundle/contao/config/config.php#L27

So when navigating to _Comments_ or to _Newsletters_ or navigating away from these, there will always be a full reload.

I propose we do not do a full reload and instead employ [`data-turbo-track="dynamic"`](https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change) for these assets. This PR applies this attribute to all stylesheets and scripts added to the back end via `$GLOBALS['TL_CSS']` and `$GLOBALS['TL_JAVASCRIPT']`. As far as I tested this works without any issues, with the added benefit of prefetching now always working as well.

There is one caveat: if you add assets to `$GLOBALS['TL_CSS']` or `$GLOBALS['TL_JAVASCRIPT']` globally for every back end request (as shown [here](https://docs.contao.org/dev/guides/adding-back-end-assets/#adding-assets-globally)), those assets will still get `data-turbo-track="dynamic"`, even though they are not actually dynamic.

This applies to the following stylesheets of the core bundles as well:

https://github.com/contao/contao/blob/23f615f83a6582b0067cc2e68f498f9233adac79/faq-bundle/contao/config/config.php#L33-L37

https://github.com/contao/contao/blob/30966535b69e6bedf680e695ec13420395fa6094/calendar-bundle/contao/config/config.php#L40-L44

https://github.com/contao/contao/blob/30966535b69e6bedf680e695ec13420395fa6094/faq-bundle/contao/config/config.php#L33-L37

I am not sure what negative implications there could be by having assets removed and added on every request by Turbo.

### CODE REVIEW

File: core-bundle/contao/classes/BackendTemplate.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ private function compile()
 			foreach (array_unique($GLOBALS['TL_JAVASCRIPT']) as $javascript)
 			{
 				$options = StringUtil::resolveFlaggedUrl($javascript);
-				$strJavaScripts .= Template::generateScriptTag($this->addStaticUrlTo($javascript), $options->async, $options->mtime);
+				$strJavaScripts .= preg_replace('/>$/', ' data-turbo-track="dynamic">', Template::generateScriptTag($this->addStaticUrlTo($javascript), $options->async, $options->mtime));
```
Comment (m-vo) [inline core-bundle/contao/classes/BackendTemplate.php]: This cannot work I think as removing scripts won't unload them/remove their listeners/free their memory etc.

**Review by m-vo — CHANGES_REQUESTED** [review]

File: core-bundle/contao/classes/BackendTemplate.php (hunk 1 above)
Comment (zoglo) [reply core-bundle/contao/classes/BackendTemplate.php]:
```suggestion
				$strJavaScripts .= Template::generateScriptTag($this->addStaticUrlTo($javascript), $options->async, $options->mtime);
```

Imo that change is not needed as we are only talking about Styles in the Issue. We would not need to add the attribute to any JS.

**Review by zoglo — CHANGES_REQUESTED** [review]
To quote the documentation: `Typically used to [remove style and link elements](https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change) during navigation.`

https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change

I do think it's the right fix but we should not add `dynamic` to JS.

File: core-bundle/contao/classes/BackendTemplate.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/contao/classes/BackendTemplate.php]: > as we are only talking about Styles in the Issue

However, the problem is triggered by dynamic scripts, too.

**Comment by fritzmg** [comment]
@m-vo wdyt about my concern though that this will add `data-turbo-track="dynamic"` to assets, that are actually not dynamic?

File: core-bundle/contao/classes/BackendTemplate.php (hunk 1 above)
Comment (fritzmg) [reply core-bundle/contao/classes/BackendTemplate.php]: > This cannot work I think as removing scripts won't unload them/remove their listeners/free their memory etc.

But that does not really matter, does it? In Contao 5.4+ your JavaScript needs to be compatible with this fact in any case. It does not matter whether you add a JavaScript [globally](https://docs.contao.org/dev/guides/adding-back-end-assets/#adding-assets-globally) or just in a [specific DCA](https://docs.contao.org/dev/guides/adding-back-end-assets/#adding-assets-for-a-dca) - in both cases your JavaScript needs to be compatible with the fact that Turbo will only render the `body` for example. You cannot rely on our `data-turbo-track` hash. The JavaScript cannot rely that listeners will automatically be removed when switching to another page, it cannot rely on `DOMContentLoaded` etc.

`data-turbo-track="dynamic"` on `<script>` makes sure that, if you have 100 extensions who add 100 different JavaScripts under 100 different URLs and you visit those 100 different URLs, you won't end up with the `<head>` being populated constantly with 100 different `<script>` tags in your DOM.

Comment (fritzmg) [reply core-bundle/contao/classes/BackendTemplate.php]: > To quote the documentation: `Typically used to [remove style and link elements](https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change) during navigation.`
> 
> https://turbo.hotwired.dev/handbook/drive#removing-assets-when-they-change
> 
> I do think it's the right fix but we should not add `dynamic` to JS.

@zoglo it says "typically used". The Turbo documentation just makes you aware how JavaScript needs to work with Turbo Drive and wants to make sure that you don't get a misconception about this.

File: core-bundle/contao/library/Contao/Template.php [hunk 2]
```diff
@@ -442,13 +443,14 @@ public function minifyHtml($strHtml)
...
-	 * @param mixed  $mtime The file mtime
+	 * @param string      $href  The script path
+	 * @param string|null $media The media type string
+	 * @param mixed       $mtime The file mtime
+	 * @param string|null $track The data-turbo-track attribute
 	 *
 	 * @return string The markup string
 	 */
-	public static function generateStyleTag($href, $media=null, $mtime=false)
+	public static function generateStyleTag($href, $media=null, $mtime=false, $track=null)
```
Comment (m-vo) [inline core-bundle/contao/library/Contao/Template.php:453]: Should we use an enum for `$track` or don't we care because of _legacy code base_?

**Review by m-vo — APPROVED** [review]

File: core-bundle/contao/library/Contao/Template.php (hunk 2 above)
Comment (fritzmg) [reply core-bundle/contao/library/Contao/Template.php:453]: Since it's just an HTML attribute where technically anything will be valid I think it's fine to keep it simple.

File: core-bundle/contao/classes/BackendTemplate.php [hunk 3]
```diff
@@ -88,7 +88,7 @@ private function compile()
 			foreach (array_unique($GLOBALS['TL_JAVASCRIPT']) as $javascript)
 			{
 				$options = StringUtil::resolveFlaggedUrl($javascript);
-				$strJavaScripts .= Template::generateScriptTag($this->addStaticUrlTo($javascript), $options->async, $options->mtime);
+				$strJavaScripts .= Template::generateScriptTag($this->addStaticUrlTo($javascript), $options->async, $options->mtime, track: 'dynamic');
```
Comment (Toflar) [inline core-bundle/contao/classes/BackendTemplate.php:91]: Why does this call use named arguments but the other one does not?

Comment (fritzmg) [reply core-bundle/contao/classes/BackendTemplate.php:91]: Because in the other one it is not necessary. `Template::generateStyleTag` has the following arguments:

* `$href`
* `$media`
* `$mtime`
* `$track`

Out of these 4 we use all of them here.

`Template::generateScriptTag` on the other hand has the following arguments:

* `$src`
* `$async`
* `$mtime`
* `$hash`
* `$crossorigin`
* `$referrerpolicy`
* `$defer`
* `$track`

Out of these, we only use the first 3 here - plus the new `$track` argument. Hence the named argument for the new one.

**Review by Toflar — APPROVED** [review]

**Review by zoglo — APPROVED** [review]
