### PR TITLE
Fix possible null value access in BackupCodeManager

### LINKED ISSUE #1243: 4.9.0-RC1: Two-factor authentication - error when entering wrong authentication-code
**Affected version(s)**
4.9.0-RC1

**Description**
1. set up two-factor authentication (works fine)
2. login with username/pw
3. in the "two-factor-authentication" window enter a wrong confirmation code
--> a contao error-page is shown ("Es ist ein Fehler aufgetreten...")
--> the contao log file in /var/logs displays an error:

`[2020-01-23 11:20:34] request.INFO: Matched route "contao_backend_login". {"route":"contao_backend_login","route_parameters":{"_route":"contao_backend_login","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::loginAction"},"request_uri":"https://url.tl/contao/login","method":"POST"} []
[2020-01-23 11:20:34] request.CRITICAL: Uncaught PHP Exception TypeError: "json_decode() expects parameter 1 to be string, null given" at /var/www/xyz/vendor/contao/core-bundle/src/Security/TwoFactor/BackupCodeManager.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): json_decode() expects parameter 1 to be string, null given at /var/www/xyz/vendor/contao/core-bundle/src/Security/TwoFactor/BackupCodeManager.php:29)"} []`

Note: test was done on a fresh and naked contao 4.9.0-RC1 installation

### PR DESCRIPTION
**Pull request by bytehead**
Fixes #1243

### CODE REVIEW

**Review by leofeyer — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by aschempp — DISMISSED** [review]

File: core-bundle/src/Security/TwoFactor/BackupCodeManager.php [hunk 1]
```diff
@@ -23,6 +23,10 @@ public function isBackupCode($user, string $code): bool
             return false;
         }
 
+        if (null === $user->backupCodes) {
+            return false;
+        }
+
         return \in_array($code, json_decode($user->backupCodes, true), true);
```
Comment (aschempp) [inline core-bundle/src/Security/TwoFactor/BackupCodeManager.php]: Should we handle `json_decode` errors (returning `null` value) as well?

Comment (bytehead) [reply core-bundle/src/Security/TwoFactor/BackupCodeManager.php]: Fixed in 60836e491.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.
