### PR TITLE
Fix the parent record loading in the dynamic parent table voter

### LINKED ISSUE #7488: Type error in the `AbstractDynamicPtableVoter`
I´m sorry, some element groups works perfectly, but others no longer work for unknown reasons, even with an admin account. here is the error:

`Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter::getParentTableAndId(): Return value must be of type array, bool returned`

Stack Trace:
```
TypeError:
Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter::getParentTableAndId(): Return value must be of type array, bool returned

  at vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:91
  at Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter->getParentTableAndId(1)
     (vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:88)
  at Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter->getParentTableAndId(2705)
     (vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:65)
  at Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter->hasAccessToParent(object(PostAuthenticationToken), array('pid' => 2705, 'ptable' => 'tl_content'))
     (vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:38)
  at Contao\CoreBundle\Security\Voter\DataContainer\AbstractDynamicPtableVoter->hasAccess(object(PostAuthenticationToken), object(ReadAction))
     (vendor/contao/core-bundle/src/Security/Voter/DataContainer/AbstractDataContainerVoter.php:47)
  at Contao\CoreBundle\Security\Voter\DataContainer\AbstractDataContainerVoter->vote(object(PostAuthenticationToken), object(ReadAction), array('contao_dc.tl_content'))
     (vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php:38)
  at Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter->vote(object(PostAuthenticationToken), object(ReadAction), array('contao_dc.tl_content'))
     (vendor/symfony/security-core/Authorization/AccessDecisionManager.php:70)
  at Symfony\Component\Security\Core\Authorization\AccessDecisionManager->collectResults(object(PostAuthenticationToken), array('contao_dc.tl_content'), object(ReadAction))
     (vendor/symfony/security-core/Authorization/Strategy/PriorityStrategy.php:37)
  at Symfony\Component\Security\Core\Authorization\Strategy\PriorityStrategy->decide(object(Generator))
     (vendor/contao/core-bundle/src/Security/Authentication/ContaoStrategy.php:45)
  at Contao\CoreBundle\Security\Authentication\ContaoStrategy->decide(object(Generator))
     (vendor/symfony/security-core/Authorization/AccessDecisionManager.php:59)
  at Symfony\Component\Security\Core\Authorization\AccessDecisionManager->decide(object(PostAuthenticationToken), array('contao_dc.tl_content'), object(ReadAction), false)
     (vendor/symfony/security-core/Authorization/TraceableAccessDecisionManager.php:60)
  at Symfony\Component\Security\Core\Authorization\TraceableAccessDecisionManager->decide(object(PostAuthenticationToken), array('contao_dc.tl_content'), object(ReadAction))
     (vendor/symfony/security-core/Authorization/AuthorizationChecker.php:48)
  at Symfony\Component\Security\Core\Authorization\AuthorizationChecker->isGranted('contao_dc.tl_content', object(ReadAction))
     (vendor/symfony/security-bundle/Security.php:94)
  at Symfony\Bundle\SecurityBundle\Security->isGranted('contao_dc.tl_content', object(ReadAction))
     (vendor/contao/core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php:200)
  at Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener->Contao\CoreBundle\EventListener\DataContainer\{closure}(object(DataContainerOperation))
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:934)
  at Contao\DataContainer->generateButtons(array('id' => 2705, 'type' => 'cp_grid_start', 'addImage' => 0, 'showPreview' => 0, 'inline' => 0, 'overwriteMeta' => 0, 'fullsize' => 0, 'thead' => 0, 'tfoot' => 0, 'tleft' => 0, 'sortable' => 0, 'target' => 0, 'overwriteLink' => 0, 'useImage' => 0, 'useHomeDir' => 0, 'metaIgnore' => 0, 'splashImage' => 0, 'sliderContinuous' => 0, 'protected' => 0, 'invisible' => 0, 'pid' => 2703, 'ptable' => 'tl_content', 'sorting' => 256, 'tstamp' => 1723645868, 'headline' => 'a:2:{s:4:"unit";s:2:"h2";s:5:"value";s:0:"";}', 'text' => null, 'singleSRC' => null, 'alt' => '', 'imageTitle' => '', 'size' => '', 'imageUrl' => null, 'caption' => '', 'floating' => 'above', 'html' => null, 'unfilteredHtml' => null, 'listtype' => '', 'listitems' => null, 'tableitems' => null, 'summary' => '', 'sortIndex' => 0, 'sortOrder' => 'ascending', 'mooHeadline' => '', 'mooStyle' => '', 'mooClasses' => '', 'highlight' => '', 'markdownSource' => 'sourceText', 'code' => null, 'url' => null, 'titleText' => '', 'linkTitle' => '', 'embed' => '', 'rel' => '', 'multiSRC' => null, 'perRow' => 4, 'perPage' => 0, 'numberOfItems' => 0, 'sortBy' => '', 'galleryTpl' => '', 'customTpl' => '', 'playerSRC' => null, 'youtube' => '', 'vimeo' => '', 'posterSRC' => null, 'playerSize' => '', 'playerOptions' => null, 'playerStart' => '0', 'playerStop' => '0', 'playerCaption' => '', 'playerAspect' => '', 'playerPreload' => '', 'playerColor' => '', 'youtubeOptions' => null, 'vimeoOptions' => null, 'sliderDelay' => 7000, 'sliderSpeed' => 700, 'sliderStartSlide' => 0, 'data' => null, 'cteAlias' => 0, 'articleAlias' => 0, 'article' => 0, 'form' => 0, 'module' => 0, 'groups' => null, 'cssID' => 'a:2:{i:0;s:0:"";i:1;s:0:"";}', 'start' => '', 'stop' => '', 'cp_grid_desktop' => 'grid_50_50', 'cp_grid_tablet' => 'grid_50_50', 'cp_grid_mobile' => 'grid_100', 'cp_grid_valign' => 'items-center', 'cp_grid_halign' => 'justify-items-center', 'rsce_data' => null, 'styleManager' => 'a:5:{s:16:"fcjg_ausrichtung";s:0:"";s:9:"fcjg_grid";s:0:"";s:13:"fcjg_overflow";s:0:"";s:15:"plakart_margins";s:0:"";s:16:"plakart_paddings";s:0:"";}', 'faq' => null, 'picked_news' => null, 'eventArchive' => null, 'eventCount' => 3, 'service' => null, 'mode' => 0, 'iconColor' => '', 'iconPicker' => '', 'closeSections' => 0, 'sectionHeadline' => 'a:2:{s:5:"value";s:0:"";s:4:"unit";s:2:"h2";}', 'sliderSpaceBetween' => 0, 'sliderSlidesPerView' => '1', 'sliderEffect' => 'slide', 'sliderWrapperClass' => '', 'sliderButtons' => '', 'sliderScrollbar' => '', 'sliderPagination' => '', 'sliderPaginationType' => 'bullets', 'sliderBreakpoints' => null, 'sliderAutoheight' => '', 'sliderCenteredSlides' => '', 'sliderCustomOptions' => null, 'stats' => null, 'importantInfos' => null, 'iconWidth' => '', 'logoWidth' => '', 'ticketPrices' => null, 'ticketInfos' => null, 'personName' => '', 'personDescription' => '', 'hosted_button_id' => '', 'accountDetails' => null, 'donateRecipient' => '', 'buttons' => null), 'tl_content', array(), false, null, null, 2708)
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:4966)
  at Contao\DC_Table->parentView()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:468)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/contao/classes/Backend.php:546)
  at Contao\Backend->getBackendModule('article', null)
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)        
```

Database has been updated. 

**Edit 2:** Now the above error also appears in some articles. seems to be in articles that do not have an element group

_Originally posted by @jaynoe in https://github.com/contao/contao/issues/7217#issuecomment-2311972123_

### PR DESCRIPTION
**Pull request by aschempp**
The previous query could result in incorrect parent records being loaded. 

@Toflar can you check if this fixes your performance issues?

### CODE REVIEW

**Comment by Toflar** [comment]
I can confirm this reduces the time needed to load a regular CE list from 13 seconds (yes, 13 seconds - lots of content elements in my case...) to about 1s. Still not perfect but according to my profiles this is also due to other queries not related to Contao but my app - so I guess this fix is good 🥳

**Comment by m-vo** [comment]
Maybe the function declaration could look like this to make it a bit easier to understand what it does:

```php
/**
 * Recursively follow the pid of the given id and return a sparse record ([id, pid, ptable])
 * for the topmost parent entry of the current table.
 */
private function getTopmostParentRecord(int $id): array
{
   // …
}
```

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php [hunk 1]
```diff
@@ -78,16 +78,33 @@ private function getParentTableAndId(int $id): array
...
+        // element nested), $records will only have one result, and we can directly use it.
+        if ($last['ptable'] !== $table) {
+            return $this->parents[$id] = $last;
+        }
+
         // Trigger recursion in case our query returned exactly 10 records in which case
         // we might have higher parent records
         if (10 === \count($records)) {
-            $records = array_merge($records, $this->getParentTableAndId((int) end($records)['pid']));
+            return $this->getParentTableAndId((int) $last['pid']);
```
Comment (m-vo) [inline core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: IMHO recursion on a function level should be avoided as much as possible, so that we can switch to/dynamically use a non-recursive version (like `WITH RECURSIVE` for MySQL 8.0+) later on. The recursion - for now - could also happen inside the function with an anonymous function. 

As briefly discussed on Slack, the logic could also be put into a utility class as it is also used in `Database::getChildRecords()`.

Just noting these two things. We can add or change bot of this in a followup PR.

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php [hunk 2]
```diff
@@ -78,16 +78,33 @@ private function getParentTableAndId(int $id): array
 
         // Limit to a nesting level of 10
         $records = $this->connection->fetchAllAssociative(
-            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=?".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid", 9),
-            [$id],
+            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=?".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid AND ptable=?", 9),
+            [$id, ...array_fill(0, 9, $table)],
```
Comment (Toflar) [inline core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: This should use named parameters, no?

Comment (m-vo) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: Not possible for table names. But the identifier should be quoted.

Comment (Toflar) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: Why does `?` work but `:table` wouldn't?

Comment (m-vo) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: Ah sorry, misunderstood your comment. Yes, that would work of course.

Comment (m-vo) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: But `$table` in L81/106 should still be quoted using `quoteIdentifiers()`, IMHO.

File: calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php [hunk 3]
```diff
@@ -64,8 +64,8 @@ public function testChecksElementAccessPermission(CreateAction|DeleteAction|Read
 
         foreach ($parentRecords as $id => $records) {
             $fetchAllAssociativeMap[] = [
-                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid', 9),
-                [$id],
+                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable=?', 9),
+                [$id, ...array_fill(0, 9, 'tl_content')],
```
Comment (leofeyer) [inline calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php]:
```suggestion
                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable='tl_content'", 9),
                [$id],
```

File: core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php [hunk 4]
```diff
@@ -64,8 +64,8 @@ public function testChecksElementAccessPermission(CreateAction|DeleteAction|Read
 
         foreach ($parentRecords as $id => $records) {
             $fetchAllAssociativeMap[] = [
-                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid', 9),
-                [$id],
+                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable=?', 9),
+                [$id, ...array_fill(0, 9, 'tl_content')],
```
Comment (leofeyer) [inline core-bundle/tests/Security/Voter/DataContainer/ArticleContentVoterTest.php]:
```suggestion
                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable='tl_content'", 9),
                [$id],
```

File: news-bundle/tests/Security/Voter/NewsContentVoterTest.php [hunk 5]
```diff
@@ -64,8 +64,8 @@ public function testChecksElementAccessPermission(CreateAction|DeleteAction|Read
 
         foreach ($parentRecords as $id => $records) {
             $fetchAllAssociativeMap[] = [
-                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid', 9),
-                [$id],
+                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(' UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable=?', 9),
+                [$id, ...array_fill(0, 9, 'tl_content')],
```
Comment (leofeyer) [inline news-bundle/tests/Security/Voter/NewsContentVoterTest.php]:
```suggestion
                'SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=?'.str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM tl_content WHERE id=@pid AND ptable='tl_content'", 9),
                [$id],
```

File: calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php (hunk 3 above)
Comment (aschempp) [reply calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php]: That would be wrong. The test must have the same arguments that we give to the method, otherwise the return-map wouldn't match.

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: changed in e102bfda6eeb09f9906f8bbcbe1653eb301dc507

**Review by Toflar — DISMISSED** [review]

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php [hunk 6]
```diff
@@ -78,16 +78,33 @@ private function getParentTableAndId(int $id): array
...
         // Limit to a nesting level of 10
         $records = $this->connection->fetchAllAssociative(
-            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=?".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid", 9),
-            [$id],
+            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=:id".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid AND ptable=:ptable", 9),
+            ['id' => $id, 'ptable' => $table],
         );
 
+        if (!$records) {
+            throw new \RuntimeException(\sprintf('Parent record of %s.%s not found', $table, $id));
```
Comment (m-vo) [inline core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:96]: This should IMHO be a `LogicException` or an `InvalidArgumentException` (depending on if the `$id` argument is believed to exist in the code path calling the function or not).

Comment (aschempp) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:96]: I don't think that's true. A record is missing in the database, which is a runtime error. This is never supposed to happen because you cannot be viewing such a thing in the back end in the first place.

Comment (m-vo) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:96]: But then the voter should never be executed, no? (which would be a logic error)

File: calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php (hunk 3 above)
Comment (leofeyer) [reply calendar-bundle/tests/Security/Voter/CalendarContentVoterTest.php]: True 👍

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php (hunk 6 above)
Comment (aschempp) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:96]: its a parent record that is missing. The voter tries to vote on a record, but a parent record (which is necessary to vote) is not found at runtime.

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php]: Yes, that is planned for Contao 5.5 already (see #6682).

File: core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php [hunk 7]
```diff
@@ -78,16 +88,39 @@ private function getParentTableAndId(int $id): array
 
         // Limit to a nesting level of 10
         $records = $this->connection->fetchAllAssociative(
-            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=?".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid", 9),
-            [$id],
+            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=:id".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid AND ptable=:ptable", 9),
+            ['id' => $id, 'ptable' => $table],
```
Comment (leofeyer) [inline core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:92]:
```suggestion
            "SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=:id AND ptable=:ptable".str_repeat(" UNION SELECT id, @pid:=pid AS pid, ptable FROM $table WHERE id=@pid AND ptable=:ptable", 9),
            ['id' => $id, 'ptable' => $table],
```

Do we not need the `AND ptable=:ptable` in the first SELECT?

Comment (aschempp) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:92]: we could, but it does not make sense because the method is only called if that statement is already true.

Comment (aschempp) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:92]: it would allow us to use the first record a few lines below

Comment (leofeyer) [reply core-bundle/src/Security/Voter/DataContainer/AbstractDynamicPtableVoter.php:92]: You are right, the first query uses `id=:id` and not `id=@pid`, so it is not necessary to add this.

**Review by Toflar — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
