### PR TITLE
Fix non-normalized file extension comparisons when building lightboxes

### LINKED ISSUE #2358: Fehler bei der Verarbeitung der Galerie
**Affected version(s)**

ab Contao 4.10.0

**Description**

**Fehler in der Galerie:**
Vorschaubilder werden korrekt angezeigt, aber die "Großansicht" wird nicht eingebunden, wenn die Dateiendung .JPG Großgeschrieben ist (kein link). 
Änderung der Dateiendung auf Kleinschreibung und Synchronisierung behebt (als Soforthilfe) das Problem.

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2358
| Docs PR or issue | -

### CODE REVIEW

File: core-bundle/tests/Image/Studio/FigureBuilderTest.php [hunk 1]
```diff
@@ -693,10 +696,14 @@ public function provideLightboxResourcesOrUrls(): \Generator
             $relativeFilePathWithInvalidExtension, [null, $relativeFilePathWithInvalidExtension], false,
         ];
 
-        yield 'external url/path with valid extension' => [
+        yield 'external url/path with valid extension (1)' => [
```
Comment (leofeyer) [inline core-bundle/tests/Image/Studio/FigureBuilderTest.php]: I generally do not like the `(1)` and `(2)` suffixes. The titles should say "external url/path with a valid lowercase extension" and "external url/path with a valid uppercase extension", so when a test fails, you do not have to look up the source code to see what `(1)` and `(2)` refers to.

Comment (m-vo) [reply core-bundle/tests/Image/Studio/FigureBuilderTest.php]: see 0f44d5452060f5dca2362af76fa3b525311a1d11

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
