### PR TITLE
Respect the label field order in the picker

### LINKED ISSUE #2853: Universal picker renders label fields in wrong order
**Affected version(s)**

Contao 4.9

**Description**

Hello, I use the Universal Picker in a custom data container array. I use it with two label fields and a custom format:

```php
// tl_my_dca.php
// ...
'fields' => ['title', 'type'],
'format' => '%s <span class="tl_gray">(%s)</span>'
// ...
```

The universal picker however applies the fields to the placeholders in reverse order. 

The formatting should be the other way around: `local` is the `type` and should be in light gray.

This happens due to the [flipping and intersecting in the widget](https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/widgets/Picker.php#L265): After `array_intersect_key` the resulting array contains the label field keys in the order of appearance in `$arrRow`, rather than the order provided by my dca config. 

I'll look into this and provide a fix 👍

### PR DESCRIPTION
**Pull request by bezin**
| Q                | A
| -----------------| ---
| Fixed issues     | #2853
| Docs PR or issue | -

Maintains the order of the keys in the picker label generator function.

### CODE REVIEW

File: core-bundle/src/Resources/contao/widgets/Picker.php [hunk 1]
```diff
@@ -262,7 +262,13 @@ protected function renderLabel(array $arrRow, DataContainer $dc)
 		}
 
 		$labelConfig = &$GLOBALS['TL_DCA'][$dc->table]['list']['label'];
-		$label = vsprintf($labelConfig['format'], array_intersect_key($arrRow, array_flip($labelConfig['fields'])));
+		$labelValues = [];
+
+		foreach ($labelConfig['fields'] as $field) {
+			$labelValues[] = $arrRow[$field];
```
Comment (ausi) [inline core-bundle/src/Resources/contao/widgets/Picker.php]: Could the field be missing?

```suggestion
			$labelValues[] = $arrRow[$field] ?? '';
```

File: core-bundle/src/Resources/contao/widgets/Picker.php [hunk 2]
```diff
@@ -262,7 +262,13 @@ protected function renderLabel(array $arrRow, DataContainer $dc)
 		}
 
 		$labelConfig = &$GLOBALS['TL_DCA'][$dc->table]['list']['label'];
```
Comment (ausi) [inline core-bundle/src/Resources/contao/widgets/Picker.php:271]:
```suggestion
		$labelConfig = $GLOBALS['TL_DCA'][$dc->table]['list']['label'];
```

I think this reference needs to be removed, but this might be out of scope for this PR :)

File: core-bundle/src/Resources/contao/widgets/Picker.php (hunk 1 above)
Comment (bezin) [reply core-bundle/src/Resources/contao/widgets/Picker.php]: Yes, it could. However, the previous implementation did not care for this either so I kinda went along with it 😂 
But I will improve this!

**Comment by bezin** [comment]
What's with the code style errors? Is this because the widget classes are legacy and that is why I should use `array()` rather than `[]` and have the curly brace on a new line for the `foreach` statement?

File: core-bundle/src/Resources/contao/widgets/Picker.php (hunk 2 above)
Comment (bezin) [reply core-bundle/src/Resources/contao/widgets/Picker.php:271]: Yeah, I was wondering the same but yet I felt I should not touch this ;-)

**Comment by ausi** [comment]
Yes, you can run `composer run cs-fixer` locally to fix these issues automatically.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bezin.
