### PR TITLE
Reload translations if the language changes

### LINKED ISSUE #4008: Using translator to access different languages at once fails
### Affected version(s)

`>= 4.9`

### Description

We're working on a project where we need the same translation in different languages. We saw that this is a known limitation in 4.9 since the `locale` parameter is ignored for everything Contao related:

https://github.com/contao/contao/blob/20cbb7fa7cd4714649d12de6239ccd0584cba773/core-bundle/src/Translation/Translator.php#L44-L50

But it seems like this could've been fixed in 4.12 since the according comment is missing and the whole loading of language files seems to be reworked:

https://github.com/contao/contao/blob/9e0dceaa6660feddeb36608035ad79cd6e6ba136/core-bundle/src/Translation/Translator.php#L55-L75

Unfortunately right after updating to 4.12 the issue still seems to be the same:

```php
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "In neuem Fenster öffnen"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Open in new window"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Ouvrir dans une nouvelle fenêtre"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
```

It seems like Contao is still stuck to the language that was loaded in last (which was the problem in <=4.9 due to `$GLOBALS['TL_LANG']` being overwritten only if a new language was loaded).

### PR DESCRIPTION
**Pull request by ausi**
Fixes #4008

I kept the existing structure of `System::$arrLanguageFiles` for better backwards compatibility.

@bennyborn can you test if the two changes from _core-bundle/src/Resources/contao/library/Contao/System.php_ fix your issue in Contao 4.12?

### CODE REVIEW

File: core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php [hunk 1]
```diff
@@ -20,7 +20,7 @@ class ContentElementReferenceTest extends TestCase
 {
     public function testCreatesTheControllerNameFromTheModelType(): void
     {
-        $model = new ContentModel();
+        $model = (new \ReflectionClass(ContentModel::class))->newInstanceWithoutConstructor();
```
Comment (ausi) [inline core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php]: `new ContentModel()` executes the constructor of the `DcaExtractor` which loads the default language file. So this test previously had a hidden dependency on a test that preloads the language file.

**Comment by bennyborn** [comment]
> @bennyborn can you test if the two changes from _core-bundle/src/Resources/contao/library/Contao/System.php_ fix your issue in Contao 4.12?

Seems to do the job!

Doing this now works as expected:

```php
System::loadLanguageFile('default', 'de'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "In neuem Fenster öffnen"
System::loadLanguageFile('default', 'en'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Open in new window"
System::loadLanguageFile('default', 'fr'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Ouvrir dans une nouvelle fenêtre"
System::loadLanguageFile('default', 'it'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Si apre in una nuova finestra"
System::loadLanguageFile('default', 'de'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "In neuem Fenster öffnen"
System::loadLanguageFile('default', 'en'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Open in new window"
System::loadLanguageFile('default', 'fr'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Ouvrir dans une nouvelle fenêtre"
System::loadLanguageFile('default', 'it'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]); // "Si apre in una nuova finestra"
```

Also doing this works:

```php
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "In neuem Fenster öffnen"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Open in new window"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Ouvrir dans une nouvelle fenêtre"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "In neuem Fenster öffnen"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Open in new window"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Ouvrir dans une nouvelle fenêtre"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
```

The only thing failing seems to be using `$this->trans` within templates but that seems due to the missing lang parameter in `Contao\Template`.

**Comment by ausi** [comment]
> The only thing failing seems to be using `$this->trans` within templates but that seems due to the missing lang parameter in `Contao\Template`.

How did you set the language in this case? Or how can this be reproduced?

**Comment by bennyborn** [comment]
> How did you set the language in this case? Or how can this be reproduced?

Reproducing is simple. Take any template (e.g. `fe_page.html5`) and add the following dumps:

```php
dump( $this->trans('MSC.target.0', [], 'contao_default','de') );
dump( $this->trans('MSC.target.0', [], 'contao_default','en') );
dump( $this->trans('MSC.target.0', [], 'contao_default','fr') );
dump( $this->trans('MSC.target.0', [], 'contao_default','it') );
dump( $this->trans('MSC.target.0', [], 'contao_default','de') );
dump( $this->trans('MSC.target.0', [], 'contao_default','en') );
dump( $this->trans('MSC.target.0', [], 'contao_default','fr') );
dump( $this->trans('MSC.target.0', [], 'contao_default','it') );
```
As I said this not working comes down to the fact that the trans method of the Template class just lacks the 4th parameter

https://github.com/contao/contao/blob/9e0dceaa6660feddeb36608035ad79cd6e6ba136/core-bundle/src/Resources/contao/library/Contao/Template.php#L382-L394

**Comment by ausi** [comment]
> As I said this not working comes down to the fact that the trans method of the Template class just lacks the 4th parameter

That would be a feature then. If you like to see that implemented please open a feature request via https://github.com/contao/contao/issues/new?labels=feature&template=2_Feature_request.yml

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php]: You should use `mockClassWithProperties` for this

File: core-bundle/src/Resources/contao/library/Contao/System.php [hunk 2]
```diff
@@ -460,7 +460,7 @@ public static function loadLanguageFile($strName, $strLanguage=null, $blnNoCache
 		}
 
 		// Return if the language file has been loaded already
-		if (!$blnNoCache && isset(static::$arrLanguageFiles[$strName][$strLanguage]))
+		if (!$blnNoCache && array_key_last(static::$arrLanguageFiles[$strName] ?? array()) === $strLanguage)
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/library/Contao/System.php:463]: `array_key_last` is only available in PHP 7.3, but Contao 4.9 supports lower versions

**Review by aschempp — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/library/Contao/System.php (hunk 2 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/System.php:463]: Fixed in a2171c6ff1afe09db87c81fd8bf141f08e7b60ad

File: core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php (hunk 1 above)
Comment (ausi) [reply core-bundle/tests/Fragment/Reference/ContentElementReferenceTest.php]: fixed in bf16286cbe1a894bc06be4f2e1e56f9aa7d4b701

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
