### PR TITLE
Parse the markup of HTML operations

### LINKED ISSUE #8105: Paste Button Callback broken if multiple operations are returned
### Affected version(s)

Contao 5.5

### Description

If a `paste_button_callback` returns two or more operations, all will be added to one list element in the context menu. This will also break some styling and the buttons are not correctly spaced.

I noticed it because the label was not visible, but loaded
Image

I think the callback now implicitly only supports one operation coming from the callback
https://github.com/contao/contao/blob/477f309086d7a6872cfdc49fb3c77e070358d438/core-bundle/contao/drivers/DC_Table.php#L3867-L3877

But it always has supported mulitple in the past.

A local quickfix was to split up individual `a` tags and add each seperately. But that's definetly not a good solution:
```php
  // Call paste_button_callback(&$dc, $row, $table, $blnCircularReference, $arrClipboard, $children, $previous, $next)
  if (\is_array($GLOBALS['TL_DCA'][$this->strTable]['list']['sorting']['paste_button_callback'] ?? null))
  {
    $strClass = $GLOBALS['TL_DCA'][$this->strTable]['list']['sorting']['paste_button_callback'][0];
    $strMethod = $GLOBALS['TL_DCA'][$this->strTable]['list']['sorting']['paste_button_callback'][1];

    $html = System::importStatic($strClass)->$strMethod($this, $currentRecord, $table, $blnCircularReference, $arrClipboard, $children, $previous, $next);
    $anchors = explode('<a ', $html);
    $anchors = array_filter($anchors);
    $anchors = array_map(function($a) {
      return '<a '.$a;
    }, $anchors);

  foreach( $anchors as $anchor ) {
    $operations->append(array('primary' => true, 'html'=>$anchor));
  }
}
```
of course this must also be added to the `is_callable` part.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/8105

~We still need to come up with a better way to generate multiple operations per callback to prevent DOM parsing.~
Added in 77b0e6ff1b6452129bdd1d425acc73a9a357803f

### CODE REVIEW

**Comment by leofeyer** [comment]
Can you explain what the changes do?

File: core-bundle/src/DataContainer/DataContainerOperationsBuilder.php [hunk 1]
```diff
@@ -158,14 +155,66 @@ public function append(array $operation): self
...
+     */
+    private function parseOperationsHtml(array $operation): array
+    {
+        if (!isset($operation['html']) || '' === trim((string) $operation['html'])) {
+            return [$operation];
+        }
+
+        $xml = new \DOMDocument();
+        $xml->preserveWhiteSpace = false;
+        $xml->loadHTML($operation['html']);
```
Comment (michb) [inline core-bundle/src/DataContainer/DataContainerOperationsBuilder.php]: I think we have to use `UTF-8` otherwise some characters will not be handled properly like `ä`, `ö`, or `ü`.
Something like this: `$xml->loadHTML('<?xml encoding="UTF-8">'.$operation['html']);`

**Comment by aschempp** [comment]
> Can you explain what the changes do?

It parses the HTML markup generated by callbacks, and splits them into separate operations. Best example can be seen in the tests. It basically splits by `a`-Tag or by any other element, optionally followed by a text element (e.g. `<span>foo</span> test`.

File: core-bundle/src/DataContainer/DataContainerOperationsBuilder.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/src/DataContainer/DataContainerOperationsBuilder.php]: does DOMDocument not use UTF-8 by default?

Comment (Toflar) [reply core-bundle/src/DataContainer/DataContainerOperationsBuilder.php]: No, there's all sorts of quirks. Also, PHP never had proper support for HTML5. `DomDocument` should in theory support HTML 4, but it even isn't really HTML 4 compliant either. This only changed with [PHP 8.4 and the new DOM API](https://www.php.net/releases/8.4/en.php#dom_additions_html5).
So you might want to add a test for UTF-8 data.

**Comment by ausi** [comment]
If we __really__ want to use HTML parsing to fix this issue we should IMO:

1. Change the return type of the `paste_button_callback` to `string|array` and trigger a deprecation if `string` gets returned.
2. Only parse the HTML code if the deprecated `string` type was returned.
3. Remove the HTML parsing again in Contao 6.

It would also be great if we could check the possibility to get the character position out of the `DOM` library to just split the original string without reserializing it again (as the libxml parser/serializer has several issues AFAIR).

**Comment by leofeyer** [comment]
As discussed in the call, we only want to enable this for the paste button callback and not in general. For the future, we want to have a solution that works without HTML parsing.

File: core-bundle/src/DataContainer/DataContainerOperationsBuilder.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/src/DataContainer/DataContainerOperationsBuilder.php]: fixed in 81326e768261e1bac2a6344d3ac709aa50cb34ef

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
