### PR TITLE
Fix the "Loading data …" box styling issues

### LINKED ISSUE #9003: Loading overlay for subpalettes obscured by TinyMCE
### Affected version(s)

5.3+

### Description

If you create a new `text` content element for example and click on **Add image**, the "Loading" overlay while loading the new subpalette might be obscured by TinyMCE's panels above, depending on your scroll position.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #9003

The "Loading data …" overlay that is displayed when loading a sub-palette (and now also when [applying a `fileTree` selection](https://github.com/contao/contao/pull/9108)) currently has a few styling issues:

In Contao 4.13 the overlay covered everything. Since the introduction of the sticky submit actions in Contao 5, the submit actions are not overlayed anymore:

\
When you scroll down, the background overlay doesn't stretch across the whole viewport:

\
The overlay is obscured by TinyMCE (https://github.com/contao/contao/issues/9003):

\
This PR fixes that by:

* Using `position: fixed` for the overlay background.
* Removing the `top` position set by the JavaScript for the overlay background, as it is now `fixed`.
* Applying an appropriate `z-index` to the overlay background and the box itself.

Btw. should we also set the box itself to fixed and simply always display it in the centre of the viewport? wdyt?

### CODE REVIEW

File: core-bundle/assets/scripts/core.js [hunk 1]
```diff
@@ -452,7 +452,6 @@ window.AjaxRequest =
 		overlay.set({
 			'styles': {
 				'display': 'block',
```
Comment (leofeyer) [inline core-bundle/assets/scripts/core.js:454]: Do we need the `'display': 'block'` at all? DIVs are block elements by default.

Comment (fritzmg) [reply core-bundle/assets/scripts/core.js:454]: The overlay is `display: none` by default.

**Review by leofeyer — APPROVED** [review]
