### PR TITLE
Prevent endless recursion when copying elements with children

### LINKED ISSUE #7360: 504 Gateway Timeout when copy/paste Pages with childs
### Affected version(s)

5.3.11

### Description

Case scenario:
When you try to copy/paste a Page which has child-pages the error accrue. When you copy/paste a page without child-pages it works ok.
image

```
[22-Jul-2024 16:34:24 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/lalala/vendor/doctrine/dbal/src/Connection.php on line 1104
[22-Jul-2024 16:37:06 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/lalala/vendor/doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php on line 138
[22-Jul-2024 16:45:59 UTC] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /home/lalala/vendor/contao/core-bundle/contao/library/Contao/Database.php on line 114
```

### PR DESCRIPTION
**Pull request by ausi**
Attempt to fix #7360

### CODE REVIEW

**Comment by Toflar** [comment]
I can confirm this fixes the issue 🥳

**Comment by ausi** [comment]
Looks like this bug was introduced in https://github.com/contao/contao/commit/8ed8a059ef8e4ea3b420dccde595f5f5973e6750#diff-d435f42f940856c7253fdef43ab51701ac38816414b06b80fc042acaabb3101f so I’m not sure if this is the right fix (and if it still works with nested content elements)

See also: https://github.com/contao/contao/pull/6521#discussion_r1706049574

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -1130,7 +1130,7 @@ protected function copyChildren($table, $insertID, $id, $parentId)
 			$children = Input::get('childs');
 		}
 
-		if ($children && $db->fieldExists('pid', $table) && $db->fieldExists('sorting', $table))
+		if ($children && ($GLOBALS['TL_DCA'][$table]['list']['sorting']['mode'] ?? null) == self::MODE_TREE)
```
Comment (ausi) [inline core-bundle/contao/drivers/DC_Table.php]:
```suggestion
		if (!($GLOBALS['TL_DCA'][$table]['config']['ptable'] ?? null) && $children && $db->fieldExists('pid', $table) && $db->fieldExists('sorting', $table))
```
This would be an alternative that just reverts the change from https://github.com/contao/contao/pull/6521#pullrequestreview-1777396112

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php]: @Toflar Does this also fix the issue?

Comment (Toflar) [reply core-bundle/contao/drivers/DC_Table.php]: Yes, that also works - but I am not using any nested elements just yet so I don't know how it affects those. But copying the entire page tree with children works with both fixes.

Comment (ausi) [reply core-bundle/contao/drivers/DC_Table.php]: I tested the new fix for copying nested elements and it worked :+1:

**Review by Toflar — APPROVED** [review]

**Review by bytehead — APPROVED** [review]
Tested as well - works like a charm!

**Comment by leofeyer** [comment]
Thank you @ausi.
