### PR TITLE
Check for a successful response in `LegacyRouteParametersListener`

### LINKED ISSUE #9746: `Unused arguments: auto_item` on protected news detail page after authentication
### Affected version(s)

5.7.3 (was fine in 5.7.2)

### Description

I encountered an issue with protected news detail pages in Contao 5.7.3 when using a custom 401 page with a login module.

**Steps to reproduce:**

1. Set up a protected page with a news reader (accessible only to specific member groups).
2. Configure a custom 401 page that includes a login module.
3. As a non-authenticated user, open a news detail page (e.g. /news/some-article).
4. The system correctly shows the 401 page (URL remains the same).
5. Log in using the login form on the 401 page.

**Expected behavior:**
After login, the user should be able to see the requested news detail page.

**Actual behavior:**
After login:

- The user is authenticated.
- A 404 error is returned instead of the news detail page.

According to the Symfony profiler:

- The request is no longer handled by the 401 page, but by the news reader page.
- However, an exception is thrown: `Unused arguments: auto_item`

If the user manually reloads the page, the news detail page is displayed correctly.

The issue can be reproduced in the Contao demo installation and does not occur on 5.7.2

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #9746

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

File: core-bundle/tests/EventListener/LegacyRouteParametersListenerTest.php [hunk 1]
```diff
@@ -138,4 +138,42 @@ public function testThrowsUnusedArgumentsExceptionWithUnusedRoutParameters(): vo
         $listener = new LegacyRouteParametersListener($scopeMatcher, $framework);
         $listener($responseEvent);
     }
+
+    public function testDoesNotThrowUnusedArgumentsExceptionWithUnusedRoutParametersOnUnsuccessfulResponses(): void
```
Comment (lukasbableck) [inline core-bundle/tests/EventListener/LegacyRouteParametersListenerTest.php]:
```suggestion
    public function testDoesNotThrowUnusedArgumentsExceptionWithUnusedRouteParametersOnUnsuccessfulResponses(): void
```

File: core-bundle/tests/EventListener/LegacyRouteParametersListenerTest.php
Comment (lukasbableck) [inline core-bundle/tests/EventListener/LegacyRouteParametersListenerTest.php]:
```suggestion
    public function testThrowsUnusedArgumentsExceptionWithUnusedRouteParameters(): void
```

**Review by lukasbableck — DISMISSED** [review]
LGTM, only noticed a typo in the test names 😅

**Review by lukasbableck — APPROVED** [review]

**Comment by fritzmg** [comment]
> LGTM, only noticed a typo in the test names 😅

For anyone else taking a long time to figure out what was not right: I originally wrote `Rout` instead of `Route` in the tests' names 😄

**Comment by leofeyer** [comment]
Thank you @fritzmg.
