### PR TITLE
Do not use exponential notation for float values

### LINKED ISSUE #5294: Selecting an important part close to the edges might result in an CoordinatesOutOfBoundsException
### Affected version(s)

4.9+

### Description

We frequently get the following error via Sentry:

```
Contao\Image\Exception\CoordinatesOutOfBoundsException: The X coordinate plus the width must not be greater than 1
#19 /vendor/contao/image/src/ImportantPart.php(49): Contao\Image\ImportantPart::__construct
#18 /vendor/contao/core-bundle/src/Image/ImageFactory.php(363): Contao\CoreBundle\Image\ImageFactory::createImportantPart
#17 /vendor/contao/core-bundle/src/Image/ImageFactory.php(161): Contao\CoreBundle\Image\ImageFactory::create
#16 /vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php(635): Contao\DataContainer::row
#15 /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php(1426): Contao\DC_Folder::edit
#14 /vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(642): Contao\Backend::getBackendModule
#13 /vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php(169): Contao\BackendMain::run
#12 /vendor/contao/core-bundle/src/Controller/BackendController.php(48): Contao\CoreBundle\Controller\BackendController::mainAction
#11 /vendor/symfony/http-kernel/HttpKernel.php(159): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#10 /vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\Component\HttpKernel\HttpKernel::handle
#9 /vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\Kernel::handle
#8 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#7 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#6 /vendor/symfony/framework-bundle/HttpCache/HttpCache.php(62): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward
#5 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(269): Symfony\Component\HttpKernel\HttpCache\HttpCache::pass
#4 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(285): Symfony\Component\HttpKernel\HttpCache\HttpCache::invalidate
#3 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(126): Contao\ManagerBundle\HttpKernel\ContaoCache::invalidate
#2 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(213): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#1 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): Contao\ManagerBundle\HttpKernel\ContaoCache::handle
#0 /web/index.php(31): null
```

i.e. the customer created an invalid important part - which then breaks the whole file manager. The reason for this is: if you create an important part very close to the edge of the image (but not fully on the edge), the JavaScript might create values like this:

```
importantPartHeight: 0.5086042065009561
importantPartWidth: 0.9999999975671574
importantPartX: 2.4328426438934947e-9
importantPartY: 0.10742604709720065
```

(these are the values sent in the POST body) i.e. the `importantPartX` is depicted with an exponent component, instead of `0.0000000024328426438934947`. This number is then apparently ignored when saving it and so the old database value remains - and thus `importantPartX` + `importantPartWidth` can be greater than `1`.

The Browser in this case was Safari 14.1.2.

/cc @ausi

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5294

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Widget.php [hunk 1]
```diff
@@ -230,6 +230,11 @@ public function __set($strKey, $varValue)
 				break;
 
 			case 'value':
+				if (\is_float($varValue))
+				{
+					$varValue = StringUtil::numberToString($varValue);
+				}
+
 				$this->varValue = StringUtil::deserialize($varValue);
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Widget.php]: Can we not put this in an `else` condition? Because if the `if` condition matches, `$varValue` can no longer be a serialized string.

**Review by leofeyer — DISMISSED** [review]

File: core-bundle/src/Resources/contao/library/Contao/Widget.php (hunk 1 above)
Comment (Toflar) [reply core-bundle/src/Resources/contao/library/Contao/Widget.php]: What if the serialized array contains a collection of floats? Wouldn't we want to convert them to strings then too? 🤔

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Widget.php]: As the scalar values inside serialized arrays are not converted by the database, I’d not interfere with them here.

File: core-bundle/src/Resources/contao/library/Contao/Widget.php [hunk 2]
```diff
@@ -232,10 +232,12 @@ public function __set($strKey, $varValue)
 			case 'value':
 				if (\is_float($varValue))
 				{
-					$varValue = StringUtil::numberToString($varValue);
+					$this->varValue = StringUtil::numberToString($varValue);
```
Comment (fritzmg) [inline core-bundle/src/Resources/contao/library/Contao/Widget.php:236]:
```suggestion
					// Prevent exponential notations (see #5296)
					$this->varValue = StringUtil::numberToString($varValue);
```

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
