### PR TITLE
Use `<turbo-frame>` for `DataContainer::edit()` and fix other Turbo issues

### LINKED ISSUE #7413: Simultaneous edit mishap
### Affected version(s)

5.4

### Description

Assume you're editing the same element in two browsers. When trying to save the externally modified element, a JS error will appear: `Form responses must redirect to another location`. 

(Probably because we're sending the wrong response code in that case for Turbo to pick it up correctly.)

### PR DESCRIPTION
**Pull request by fritzmg**
Proposal to fix #7413

This changes the behavior of `DC_Table::edit` though: Turbo scrolls to the top after submitting regular forms. With framed forms you will stay in place by default (might be advantageous?).

If we agree on this approach, I would apply this to `DC_Folder::edit` as well - for consistency.

### CODE REVIEW

**Comment by leofeyer** [comment]
> With framed forms you will stay in place by default (might be advantageous?).

Is there any confirmation that the form has been submitted and the data has been saved then?

**Comment by fritzmg** [comment]
No (well except that the button will be available again), but we could add [`autoscroll="true" data-autoscroll-block="start"`](https://turbo.hotwired.dev/reference/frames#html-attributes) to the frame, then it will scroll to the start of the frame after submitting.

**Comment by zoglo** [comment]
> No, but we could add the data-autoscroll-block="start" to the frame, then it will scroll to the start of the frame after submitting.

Wouldn't that work against the data-scroll-offset then? Imho, you want to see the field you were at after reloading.

**Comment by fritzmg** [comment]
> Wouldn't that work against the data-scroll-offset then? Imho, you want to see the field you were at after reloading.

Hm, not sure what you mean? In Contao 5.3 you will always be at the top. And currently in Contao 5.4 as well.

**Comment by fritzmg** [comment]
Oh, you mean when using the Keyboard Shortcuts. Well that's another can of worms I suppose 😁

**Comment by zoglo** [comment]
~~I mean the scroll offset controller that handles the last position of a field you clicked.~~

Nvm @fritzmg :)

**Comment by leofeyer** [comment]
> No (well except that the button will be available again)

That would suffice for me. So IMHO the page must not be scrolled to the top after submitting a form.

**Comment by zoglo** [comment]
There is one issue with this approach:
The `Version conflict` doesn't show up anymore, it would just overwrite it 🤔 
___
*Edit*

Guess this might need to be another Stimulus Controller again?
Similar problem has been discussed [here](https://discuss.hotwired.dev/t/how-to-redirect-from-a-form-that-is-inside-a-turbo-frame/4164)

**Comment by fritzmg** [comment]
> There is one issue with this approach:
The Version conflict doesn't show up anymore, it would just overwrite it 🤔

No, it should be shown, at least I have tested it. Keep in mind that #7408 needs to be merged as well.

**Comment by fritzmg** [comment]
> The `Version conflict` doesn't show up anymore, 

Hm, yeah, with the latest merges this PR does not actually fix #7413 anymore, though I don't understand why.

> it would just overwrite it 🤔

That is always true, i.e. the last submit always wins. Contao only tells you, that someone else also would have made some changes before you - but at that point those changes are already overwritten by your changes.

**Comment by fritzmg** [comment]
Ah, not related to the merges - while testing I set the status code of the `be_conflict` response to 422/500, which I removed later on, thinking it wasn't actually needed. But it is needed after all.

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -2170,7 +2171,11 @@ public function edit($intId=null, $ajaxId=null)
 				$objTemplate->href = Environment::get('requestUri');
 				$objTemplate->button = $GLOBALS['TL_LANG']['MSC']['continue'];
 
-				throw new ResponseException($objTemplate->getResponse());
+				// We need to set the status code to either 422 or 500 in order for Turbo to render this response.
+				$response = $objTemplate->getResponse();
+				$response->setStatusCode(Response::HTTP_INTERNAL_SERVER_ERROR);
```
Comment (zoglo) [inline core-bundle/contao/drivers/DC_Table.php]:
```suggestion
				$response->setStatusCode(Response::HTTP_UNPROCESSABLE_ENTITY);
```
Could use 422 here since that one describes the problem the best

File: core-bundle/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -2388,13 +2393,14 @@ public function edit($intId=null, $ajaxId=null)
 </script>';
 		}
 
-		// Begin the form (-> DO NOT CHANGE THIS ORDER -> this way the onsubmit attribute of the form can be changed by a field)
+		// Begin the form (-> DO NOT CHANGE TH"IS ORDER -> this way the onsubmit attribute of the form can be changed by a field)
```
Comment (zoglo) [inline core-bundle/contao/drivers/DC_Table.php]:
```suggestion
		// Begin the form (-> DO NOT CHANGE THIS ORDER -> this way the onsubmit attribute of the form can be changed by a field)
```
Might have been a typo that you added

**Review by zoglo — DISMISSED** [review]
Works as expected now. I'd however throw the 422 error as it's more descriptive.
 (There is also a small typo that got in)

File: core-bundle/contao/drivers/DC_Table.php (hunk 1 above)
Comment (fritzmg) [reply core-bundle/contao/drivers/DC_Table.php]: Neither really fits. The entity was in fact processed at this point. Turbo just forces us to use either one.

**Comment by fritzmg** [comment]
It turns out having the 422/500 response with `<meta name="turbo-visit-control" content="reload">` is enough - no `<turbo-frame>` needed. 

The advantage of a `<turbo-frame>` would be, that the scroll position upon saving is not changed (irrespective of the `scroll-offset-controller` - which currently would not work anyway). @leofeyer @m-vo wdyt, should we wrap the edit form in a frame anyway?

**Comment by leofeyer** [comment]
Probably yes but we have to remove the `data-turbo-frame="_top"` again, don‘t we?

**Comment by fritzmg** [comment]
> Probably yes but we have to remove the `data-turbo-frame="_top"` again, don‘t we?

If we don't want the `<turbo-frame>` on the edit form, all the `data-turbo-frame` attributes are superfluous, yes.

**Comment by leofeyer** [comment]
No, I mean keep the frame but don't scroll to the top after submitting the form.

**Comment by fritzmg** [comment]
Ah, the `data-turbo-frame="_top"` attribute is not what that does. That just tells the link or form which frame to target (in this case the `_top` frame). This must be added on the "Save and Close" and "Save and Back" buttons as they redirect to somewhere else where the frame will not be present anymore.

A frame request not causing any scrolling is the default behavior.

**Comment by leofeyer** [comment]
Ah, I see 👍

File: core-bundle/contao/drivers/DC_Table.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php]: I think `422` is more appropriate in this case.

Comment (fritzmg) [reply core-bundle/contao/drivers/DC_Table.php]: But did the user mess up? It's not their fault that another user happened to edit the record at the same time 😁

Comment (zoglo) [reply core-bundle/contao/drivers/DC_Table.php]: I agree with @fritzmg because of this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
> Clients that receive a `422` response should expect that repeating the request without modification will fail with the same error.

Since Turbo only allows either `422` and `500` to handle this error, the `500` is more correct considering it's our fault for *allowing* to edit an entry whilst someone else is within edit-mode.

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php]: > But did the user mess up? It's not their fault that another user happened to edit the record at the same time 😁

True, but it certainly is not a server error. The server and the software both work just fine, don‘t they?

> Clients that receive a `422` response should expect that repeating the request without modification will fail with the same error.

Which is the case, isn‘t it?

Comment (fritzmg) [reply core-bundle/contao/drivers/DC_Table.php]: Yes, resending the same exact request would result in the same response.

**Comment by fritzmg** [comment]
Oooph, `DC_Table` is so confusing, I had the `</turbo-frame>` end tag in the completely wrong position 🙈
I really wish we went ahead with the Twig implementation by @m-vo back then.

File: core-bundle/contao/drivers/DC_Table.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/contao/drivers/DC_Table.php]: Wouldn't it be best if the `be_conflict` screen would appear every time with the identical POST data until some extra flag (confirming the action) was set? Then the outcome would be reproducible and also 422 would be correct. 

If that's too complicated, I would go with 422. The status code is not _that_ important in this case. It's only the API for our own front end, there will never be an additional layer.

**Comment by m-vo** [comment]
Thanks @fritzmg for checking this out! I'm not that familiar working with Turbo frames, yet, so I can't really tell if it's best to wrap the the form. But the changes look logical to me and are quite minimal, so :+1:.

File: core-bundle/contao/drivers/DC_Table.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/contao/drivers/DC_Table.php]: Judging by the [code](https://github.com/hotwired/turbo/blob/f88bfe45ed44abb6ea9140a8ba138dfe68aa2730/src/http/fetch_response.js#L16-L18), any 4xx status code should work. So what about [409](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409)?

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php]: I like 409 👍

Comment (fritzmg) [reply core-bundle/contao/drivers/DC_Table.php]: Changed to 409 👍

**Comment by fritzmg** [comment]
I noticed another issue: our `be_diff` form would not update with Turbo either, as the `POST` request responds with `200`. Thus I disabled Turbo for that form in 5e9cf6b098c30d45e875e26bbb23dca349423d30 (similar to https://github.com/contao/contao/pull/7378).

**Comment by fritzmg** [comment]
I have integrated the scroll to error functionality into the `scroll-offset-controller` in c4dad5a44c51325189d62d7edf58f9086f0d8084.

However, there is a race condition issue with the initialisation of TinyMCE. With the Stimulus controller the scrolling would happen before TinyMCE is initialized. I have added a `setTimeout` to compensate, but this is not ideal of course.

**Comment by m-vo** [comment]
> However, there is a race condition issue with the initialisation of TinyMCE. With the Stimulus controller the scrolling would happen before TinyMCE is initialized. I have added a `setTimeout` to compensate, but this is not ideal of course.

Instead of having a timeout set (which was too small in my case btw), the editor could itself signal the change. This can either be done by listening to the `load` event or - probably a lot simpler - by adding the following code when the init promise resolves (L27) in the `tinymce` controller. 

This bit will only be executed once the editor was fully loaded and directly calls the other controller's function (could also be done with events, but I think it's OK to do it like this, here):
```js
if(this.element.closest('*[data-contao--scroll-offset-target="widgetError"]')) {
    this.application
        .getControllerForElementAndIdentifier(document.documentElement, 'contao--scroll-offset')
        .widgetErrorTargetConnected();
}
```

**Comment by fritzmg** [comment]
Done. Though I think a custom event might be nicer after all. Then we could do something like

```js
document.addEventListener('tinymce-init', () => {
    if (null !== this.hasWidgetErrorTarget) {
        this.widgetErrorTargetConnected();
    }
});
```

within `contao--scroll-offset#connect`. Other controllers might also want to listen to this. wdyt?

**Comment by m-vo** [comment]
We could maybe even utilize Stimulus events, then: https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events. This would probably look something like this:
```js
// when the init promise has resolved
this.dispatch("editor-loaded", { detail: { content: editors[0] } });
```

```html
<html […] data-action="contao--tinymce:editor-loaded->contao--scroll-offset#widgetErrorTargetConnected">
```
(or rather a distinct method, so that the event argument could be used)

**Comment by fritzmg** [comment]
Ah yes, I like this 👍

**Comment by fritzmg** [comment]
Alright, so here are the changes:

*General changes:*

* The `be_conflict` response now has a `409` status code, as per the previous discussion (this fixes #7413).
* Turbo is disabled for the the `be_diff` form, as it generates regular 200 responses.
* Scrolling to a widget with an error is now handled by the `scroll-offset` controller. The old `Backend.vScrollTo` calls have been removed and `Backend.vScrollTo` has thus been deprecated accordingly (it is not used anywhere else in the core anymore). _Note:_ this only works if the form is wrapped in a Turbo Frame, as Turbo otherwise always scrolls to the top, overriding any custom scrolling behavior.

*Turbo Frame related changes:*

* The `edit()` forms of all core DC drivers now use a `<turbo-frame>`.
* The MooTools `domready` event is now also fired when rendering a Turbo Frame, for compatibility with the legacy JS framework.
* The frame wraps the whole content, including the jump-to-navigation and the version form. It is important to include the jump-to-navigation, as it can change when the palette changes.
* All forms within the frame target the `_self` frame (including the versions form).
* The `saveNclose` and `saveNback` action target the `_top` frame, as they redirect to somewhere else.

File: core-bundle/contao/drivers/DC_File.php [hunk 3]
```diff
@@ -329,22 +329,11 @@ public function edit()
...
-<script>
-  window.addEvent(\'domready\', function() {
-    Backend.vScrollTo(($(\'' . $this->strTable . '\').getElement(\'label.error\').getPosition().y - 20));
-  });
-</script>';
-		}
-
 		$return = '
-<div data-controller="contao--jump-targets">
+<turbo-frame id="tl_edit_form_frame" target="_top" data-turbo-action="forward" data-controller="contao--jump-targets">
```
Comment (m-vo) [inline core-bundle/contao/drivers/DC_File.php]: Did you mean `data-turbo-action="advance"`? (same in `DC_Table`)

Comment (fritzmg) [reply core-bundle/contao/drivers/DC_File.php]: Yes 🙈

**Review by m-vo — DISMISSED** [review]

**Comment by fritzmg** [comment]
One more change: rather than setting `data-turbo-frame="_self"` on the `<form>` itself I decided to only set it on the `save` button. All the other buttons should either scroll to the top - or respond with a redirect to somewhere else. Additionally, any buttons added via the `buttons_callback` will thus also target the `_top` frame (the frame's default) rather than `_self`, unless specifically set this way. This ensures that buttons added from extension will always work, even when they do not render the form again.

**Review by m-vo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
