### PR TITLE
Fix the metadata for breadcrumbs

### LINKED ISSUE #7274: Incorrect structured data for navigation paths breadcrumblist generated: ‘@id’: false
### Affected version(s)

5.3.8

### Description

An incorrect entry for the breadcrumb list is generated for the start page of a website:
```
        {
            ‘@type’: ‘BreadcrumbList’,
            ‘itemListElement’: [
                {
                    ‘@type’: ‘ListItem’,
                    ‘item’: {
                        ‘@id’: ‘\/’,
                        ‘name’: ‘Scheuermatthof’
                    },
                    ‘position’: 1
                },
                {
                    ‘@type’: ‘ListItem’,
                    ‘item’: {
                        ‘@id’: false,    <=== *** HERE ***
                        ‘name’: ‘Homepage’
                    },
                    ‘position’: 2
                }
            ]
        }
```
The @id cannot be "false".

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7274

* The `index` page will not be output in the schema.org metadata (_note:_ we need to check for `isActive` in addition to alias is `index` because the root entry also has `index` as its alias).
* The URL for the last breadcrumb entry (the active page) is now fixed and also uses a forward slash.

### CODE REVIEW

File: core-bundle/contao/modules/ModuleBreadcrumb.php [hunk 1]
```diff
@@ -186,7 +188,7 @@ protected function compile()
 				'isRoot'   => false,
 				'isActive' => true,
 				// Use the current request without query string for the current page (see #3450)
-				'href'     => strtok(Environment::get('request'), '?'),
+				'href'     => $request->getBasePath().$request->getPathInfo(),
```
Comment (ausi) [inline core-bundle/contao/modules/ModuleBreadcrumb.php]:
```suggestion
				'href'     => $request->getBaseUrl().$request->getPathInfo(),
```

**Review by ausi — CHANGES_REQUESTED** [review]

File: core-bundle/contao/modules/ModuleBreadcrumb.php [hunk 2]
```diff
@@ -83,7 +85,7 @@ protected function compile()
 			(
 				'isRoot'   => true,
 				'isActive' => false,
-				'href'     => (($objFirstPage !== null) ? $this->generateContentUrl($objFirstPage) : Environment::get('base')),
+				'href'     => (($objFirstPage !== null) ? $this->generateContentUrl($objFirstPage) : $request->getBasePath()),
```
Comment (leofeyer) [inline core-bundle/contao/modules/ModuleBreadcrumb.php]: What if `$request` is `null`? `Environment::get('base')` falls back to the current URL in this case I think.

Comment (fritzmg) [reply core-bundle/contao/modules/ModuleBreadcrumb.php]: `Environment::getRequest()` would use `new Request(server: $_SERVER)` in that instance (which is also deprecated).

Comment (leofeyer) [reply core-bundle/contao/modules/ModuleBreadcrumb.php]: You still have to handle the case, otherwise there will be a fatal error 🤷‍♂️

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
