### PR TITLE
Also apply cache headers in Twig layouts

### LINKED ISSUE #8718: Shared Cache not working in Twig layouts
### Affected version(s)

5.6.0

### Description

It seems like the Shared Cache is not working when using a Twig layout. 
Every response has `Contao-Cache: miss` and `Cache-Control: no-cache, private`, even when the page does not have any content at all.
I'm not logged in, no cookies set, etc. It's also working fine with HTML5 layouts.

Image

Image

Image

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #8718

### CODE REVIEW

**Review by Toflar — COMMENTED** [review]
LGTM just checking: did you double check that fragments can also affect the page response. This only works if `SubrequestCacheSubscriber::MERGE_CACHE_HEADER` is set to `1` (or `true` or anything) on the response headers. See `AbstractFragmentController::markResponseForInternalCaching()`.

**Comment by m-vo** [comment]
Good call! We indeed need to enable the `Contao-Merge-Cache-Control` header - `PageRegular` does the same. Updated in 7fe7d72.

File: core-bundle/src/Controller/Page/AbstractLayoutPageController.php [hunk 1]
```diff
@@ -55,6 +56,10 @@ public function __invoke(Request $request): Response
         $response = $this->getResponse($template, $layout, $request);
         $this->container->get('contao.routing.response_context_accessor')->finalizeCurrentContext($response);
 
+        // Set cache headers
+        $response->headers->set(SubrequestCacheSubscriber::MERGE_CACHE_HEADER, '1');
```
Comment (Toflar) [inline core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: Couldn't we just move and re-use the `markResponseForInternalCaching()` from the `AbstractFragmentController` to the `AbstractController` and also use it here? Then it would be unified? 🤔

Comment (m-vo) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: Hmm, `markResponseForInternalCaching()` also removes any existing `Cache-Control`. That's a bit weird on the main request, no? I mean, it would not hurt if it comes before the `setCacheHeaders()` call, but I wonder if its correct?

Comment (Toflar) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: I think every page controller has to configure this itself. Just like this is the case in the content elements and frontend modules. It's just that when you use the default `createTemplate()` etc. it will be done for you automatically. 
So I think we should try to achieve the same here - if you use some default methods when extending from `AbstractLayoutController` the caching will be done automatically for you. But if you want to not have that you should be able to. See what I mean?

Comment (m-vo) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: Sure, we can move the `markResponseForInternalCaching` to the `AbstractController` and call this method instead of setting the `MERGE_CACHE_HEADER` directly. But would you still have the second call that removes any previous cache control headers in there, too? Or should we override the method for fragments and only re-add this part there?

Comment (Toflar) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: Can't we replicate the logic from the fragments for consistency? There, the `$onGetResponse` callback does this.

Comment (m-vo) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: > There, the $onGetResponse callback does this. 

No, that's only the case for legacy templates, when the response comes from the old engine - we set `markResponseForInternalCaching()` when rendering the template.

Comment (m-vo) [reply core-bundle/src/Controller/Page/AbstractLayoutPageController.php:60]: I moved `markResponseForInternalCaching()` in the `AbstractController` in 95b030fd83f96d0d6d268405aba2661c865f9298. If you want to affect which cache headers are set in your specific controller, you can adjust what's done by default in `markResponseForInternalCaching()` as well as `setCacheHeaders()`.

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
