### PR TITLE
Fix an undefined array key warning in the `AbstractLayoutPageController`

### LINKED ISSUE #8649: Undefined array key within AbstracLayoutPageController
https://github.com/m-vo/contao/blob/1a2ff4352e452d39a15ebae24f7451d27ae4e649/core-bundle/src/Controller/Page/AbstractLayoutPageController.php#L136

This one will throw an undefined array key warning and should be 
```php
if ($definition['enable'] ?? null) {
```

(Not related to this PR but related to the functionality ☺️)

_Originally posted by @zoglo in https://github.com/contao/contao/pull/8645#pullrequestreview-3102944987_

### PR DESCRIPTION
**Pull request by zoglo**
### Description

- Fixes #8649

### CODE REVIEW

File: core-bundle/src/Controller/Page/AbstractLayoutPageController.php [hunk 1]
```diff
@@ -146,7 +146,7 @@ public function all(): \Generator
         $moduleIdsBySlot = [];
 
         foreach (StringUtil::deserialize($layout->modules, true) as $definition) {
-            if ($definition['enable']) {
+            if ($definition['enable'] ?? null) {
```
Comment (Toflar) [inline core-bundle/src/Controller/Page/AbstractLayoutPageController.php]:
```suggestion
            if ($definition['enable'] ?? false) {
```

**Review by Toflar — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]
