### PR TITLE
Do not auto-link images in the newsreader

### LINKED ISSUE #5477: News images in reader are linked when no content elements
### Affected version(s)

4.9.35, 4.13.12

### Description

Images (through singleSRC field) in news are always get linked to the news reader page. This also happens in the news reader (detail page) when no content element are available for the news article and fullsize is not set. Since we are already on the detail page, the images is linked to the current page, which is not ideal.

The problematic code: https://github.com/contao/contao/blob/a1bcee403a4fd2c6bddfcbd5106c97be66ef420c/news-bundle/src/Resources/contao/modules/ModuleNews.php#L189

Steps to reproduce:
1. Create a news reader
2. Create a news article without content elements and do not check option "fullsize" 
3. Open the news article in reader view -> the image is linked to the current page

Also discussed on slack: https://contao.slack.com/archives/CK4J0KNDB/p1667486480300469

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5477

### CODE REVIEW

File: news-bundle/src/Resources/contao/modules/ModuleNews.php [hunk 1]
```diff
@@ -184,7 +184,7 @@ protected function parseArticle($objArticle, $blnAddArchive=false, $strClass='',
 			if (null !== ($figure = $figureBuilder->buildIfResourceExists()))
 			{
 				// Rebuild with link to news article if none is set
-				if (!$figure->getLinkHref())
+				if (!$figure->getLinkHref() && $objTemplate->link != Environment::get('request'))
```
Comment (ausi) [inline news-bundle/src/Resources/contao/modules/ModuleNews.php]:
```suggestion
				if (!$figure->getLinkHref() && $intCount !== 0)
```
`$intCount` is zero for the reader module and `1` or higher for the list module AFAIK.

File: calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php [hunk 2]
```diff
@@ -401,7 +401,7 @@ protected function compile()
 				if (null !== $figure)
 				{
 					// Rebuild with link to event if none is set
-					if (!$figure->getLinkHref())
+					if (!$figure->getLinkHref() && $event['href'] != Environment::get('request'))
```
Comment (ausi) [inline calendar-bundle/src/Resources/contao/modules/ModuleEventlist.php]: This is only executed for the list module, right?
The reader module has its own code for the figure without the auto-link already: https://github.com/contao/contao/blob/f0bb2fd04dffad786828dd55c8ca592de3579c9d/calendar-bundle/src/Resources/contao/modules/ModuleEventReader.php#L324-L336

So I think this change is not needed.

```suggestion
					if (!$figure->getLinkHref())
```

File: news-bundle/src/Resources/contao/modules/ModuleNews.php (hunk 1 above)
Comment (leofeyer) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php]: Not sure about this. At least with `link !== requestUri` you can kind of see what the code does ("do not link to the page I am already on") but `count !== 0` is not comprehensible without further knowledge.

And `count !== 0` will not work if the `event_full` template is used in a news list module.

Comment (ausi) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php]: > but `count !== 0` is not comprehensible without further knowledge.

Agree, we could use a descriptive comment, or maybe another parameter for the method like `$blnForReader`?

> And `count !== 0` will not work if the `event_full` template is used in a news list module.

I thought this is exactly what we want. No auto-link in the reader module, but still auto-link in the list module (even if the full template is used). This already works that way for events, see my other comment: https://github.com/contao/contao/pull/5851#discussion_r1133995625

To my understanding, only the news reader module behaves wrong currently, not the events reader.

Comment (leofeyer) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php]: You are right.

Comment (leofeyer) [reply news-bundle/src/Resources/contao/modules/ModuleNews.php]: I still think `$objTemplate->link != Environment::get('request')` is the better choice, because it does what we actually want to do, which is not link to the page we are already on.

This way no one needs to know about `$intCount` and that is has to be set to link news images to the reader page, which is kind of a weird DX in my opinion. @contao/developers WDYT?

**Comment by leofeyer** [comment]
As discussed in the call, we want to abuse the `$intCount` variable.

```
// Explaining comment
$blnIsReader = !$intCount;
```

**Review by ausi — APPROVED** [review]
