### PR TITLE
Fix some autofocus quirks

### LINKED ISSUE #8842: Clicking an action autofocuses to the first input element
### Affected version(s)

5.x / 5.6

### Description

When clicking any action such as a button on an edit view, the first focusable field will get focus, leading to a jump.

This is ~~most likely~~ a regression caused by https://github.com/contao/contao/pull/8715, thus most likely affecting 5.6 as well.

### PR DESCRIPTION
**Pull request by zoglo**
### Description

* fixes #8842
* fixes an issue of jumping to the first target when creating a new target / disconnecting

This one was tricky, there are 2 things that are being fixed with this PR:

1. When clicking an action that causes the scroll-offset-controller to trigger (the autofocus part), it may jump to the autofocus target
    - this has been fixed in 14ab2d4e2277b15d0521c373734f46c39e26d4a2 /cc @aschempp -> hint: row-wizard

2. The autofocus on Safari
    - This is actually same as outlined in https://github.com/contao/contao/issues/8842#issuecomment-3528123887 but due to the autofocus selecting everything. Safari jumps to the selection (even without the autofocus-controller -> I removed it in the tests to confirm the issue), hence the changes in 4804ed95f2738fdfd475a5e8716dddc72dca4c2c that remove the `selection`

___

Unrelated but still happening (imho something that is not part of this PR: https://github.com/contao/contao/issues/8934), the scrolling effect even happens without the scroll-offset-controller activated.

### CODE REVIEW

File: core-bundle/assets/controllers/scroll-offset-controller.js [hunk 1]
```diff
@@ -125,10 +125,11 @@ export default class extends Controller {
...
         this.#autoFocus = true;
         input.focus();
-    }
 
-    autoFocusTargetDisconnected() {
-        this.#autoFocus = false;
+        requestAnimationFrame(() => {
+            const len = input.value.length;
+            input.setSelectionRange(len, len);
+        });
```
Comment (fritzmg) [inline core-bundle/assets/controllers/scroll-offset-controller.js:132]: Why the usage of `window.requestAnimationFrame` here? Is this just to delay the execution? If yes, may be `window.queueMicroTask` is better suited?

**Review by aschempp — APPROVED** [review]
I can confirm this fixes the issue I noticed with drag&drop in the row wizard.

I think `requestAnimationFrame` is correct here, because we want to handle this when the browser is painting the next time, and not _somewhen when you're not busy_.

File: core-bundle/assets/controllers/scroll-offset-controller.js (hunk 1 above)
Comment (zoglo) [reply core-bundle/assets/controllers/scroll-offset-controller.js:132]: As explained: https://github.com/contao/contao/pull/9125#pullrequestreview-3577929753

**Comment by leofeyer** [comment]
Thank you @zoglo.
