### PR TITLE
Fix the page context when generating RSS feeds

### LINKED ISSUE #2556: News-Feed anlegen erzeugt "500 Internal Server Error"
**Affected version(s)**

4.9.9

Hallo,

wenn ich im Nachrichten-Modul einen News-Feed anlege, dann bekomme ich beim Speichern einen "500 Internal Server Error".
Ich werde zwar aus dem Backend geworfen, aber der News-Feed wird trotzdem angelegt und kann auch im Browser ausgegeben werden.
Die Exporteinstellung "Ganze Beiträge" wird ignoriert und es werden nur die Teasertexte angezeigt.
Habe ich mich nach erfolgten "Rauswurf" wieder ins Backend gehangelt und gehe ins Nachrichtenmodul, dann bekomme ich ebenfalls einen "500 Internal Server Error" und kann nichts weiter machen.

Im Debug-Modus wird mir ein
`Could not find template "ce_text_bild_mittig"`
angezeigt, wobei "ce_text_bild_mittig" ein eigenes abgeleitetes Template ist.

Gehe ich auf Systemwartung -> XML-Dateien neu schreiben -> Daten bereinigen dann werde ich ebenfalls mit einem "500 Internal Server Error" aus dem Backend entfernt.

Der Stack Trace
Exception:
Could not find template "ce_text_bild_mittig"

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:158
  at Contao\TemplateLoader::getDefaultPath('ce_text_bild_mittig', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:114)
  at Contao\TemplateLoader::getPath('ce_text_bild_mittig', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:76)
  at Contao\Controller::getTemplate('ce_text_bild_mittig')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:324)
  at Contao\Template->getTemplatePath('ce_text_bild_mittig', 'html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:87)
  at Contao\Template->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:292)
  at Contao\Template->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:44)
  at Contao\FrontendTemplate->parse()
     (vendor/contao/core-bundle/src/Resources/contao/elements/ContentElement.php:285)
  at Contao\ContentElement->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:575)
  at Contao\Controller::getContentElement(object(ContentModel))
     (vendor/contao/news-bundle/src/Resources/contao/classes/News.php:208)
  at Contao\News->generateFiles(array('id' => '6', 'tstamp' => '1607600977', 'title' => 'Aktuelles vom Landesverband Sachsen', 'alias' => 'news-sachsen-rss', 'language' => 'de', 'archives' => 'a:6:{i:0;s:1:"1";i:1;s:1:"2";i:2;s:1:"3";i:3;s:1:"4";i:4;s:1:"6";i:5;s:1:"7";}', 'format' => 'rss', 'source' => 'source_text', 'maxItems' => '40', 'feedBase' => 'https://pnp-gbs-sachsen.de/', 'description' => 'Aktuelle Nachrichten und Informationen der Deutsche Polyneuropathie Selbsthilfe e.V. Landesverband Sachsen', 'feedName' => 'news-sachsen-rss'))
     (vendor/contao/news-bundle/src/Resources/contao/classes/News.php:52)
  at Contao\News->generateFeed('6')
     (vendor/contao/news-bundle/src/Resources/contao/dca/tl_news_feed.php:455)
  at tl_news_feed->generateFeed(object(DC_Table))
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:202)
  at Contao\DC_Table->__construct('tl_news_feed', array('tables' => array('tl_news_archive', 'tl_news', 'tl_news_feed', 'tl_content'), 'table' => array('Contao\\TableWizard', 'importTable'), 'list' => array('Contao\\ListWizard', 'importList')))
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:411)
  at Contao\Backend->getBackendModule('news', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)

Der Pfad des Templates: `templates/pnp-gbs-sachsen/ce_text_bild_mittig.html5`

Der Error wird nur ausgelöst, wenn ich in den Exporteinstellungen "Ganze Beiträge" auswähle.

Grüsse

### PR DESCRIPTION
**Pull request by fritzmg**
This is a follow up to #2848.

### Reproduction of the problem

1. Create a page article with some content.
2. Create a news archive and a published news article.
3. Put `{{insert_article::*}}` into the teaser of the news article (replace `*` with the ID of the previously generated page article).
4. Create an RSS feed and select the created news archive.

Unter PHP 8.0, the following error will occur upon saving the RSS feed or when regenerating the XML files in the maintenance section:

```
ErrorException:
Warning: Attempt to read property "datimFormat" on null

  at vendor\contao\contao\core-bundle\src\Resources\contao\modules\ModuleArticle.php:124
```

Same basic reproduction with events as well.

Since the XML feeds are always generated without a proper front end context, we also need to set the global `$objPage` variable (not just the front end scope) according to the `jumpTo` page of the news archive (or calendar respectively).

### Notes

* This PR includes a behaviour change: if the configured `jumpTo` page of a news archive or calendar is deleted, the affected news and event entries will be skipped now. In my opinion this is fine, since the news archive or calendar is then in a misconfigured state. See also the original issue of the affected lines of code: https://github.com/contao/core/issues/5781
* This PR is based against **4.11**. While the original issue does not cause an error in Contao **4.9** I do consider it a bug that the global `$objPage` object is not set properly for the feed generation. Should I rebase it against **4.9** instead?

### CODE REVIEW

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 1]
```diff
@@ -215,6 +213,9 @@ protected function generateFiles($arrFeed)
 			$request->attributes->set('_scope', 'frontend');
 		}
 
+		global $objPage;
+		$origObjPage = $objPage;
```
Comment (ausi) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php]: Would `$objOrigPage` be more consistent with the old naming schema?
```suggestion
		$objOrigPage = $objPage;
```

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 2]
```diff
@@ -227,6 +228,9 @@ protected function generateFiles($arrFeed)
 						break 3;
 					}
 
+					// Override the global page object (#2946)
+					$objPage = CalendarModel::findByPk($event['pid'])->getRelated('jumpTo');
```
Comment (ausi) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php]: IMO using `$GLOBALS` instead of `global $objPage` would be better here for understanding the code. But not sure if there is a code style to follow here @leofeyer ?
```suggestion
					$GLOBALS['objPage'] = CalendarModel::findByPk($event['pid'])->getRelated('jumpTo');
```

**Comment by ausi** [comment]
> Should I rebase it against **4.9** instead?

IMO yes.

File: calendar-bundle/src/Resources/contao/classes/Calendar.php (hunk 1 above)
Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: I consider `$objPage` a special variable name in this context and thus find it more consistent to say "the original global objPage value". And it would be consistent with `$origScope` as well (though that variable lacks the type prefix of course).

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 3]
```diff
@@ -144,20 +144,18 @@ protected function generateFiles($arrFeed)
 					continue;
 				}
 
+				$objParent = PageModel::findWithDetails($jumpTo);
```
Comment (aschempp) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php]: looks like this is bypassing the `$arrUrls` cache?

Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: Yes, setting the global `$objPage` variable is unrelated to the URL cache and needs to be done for each record. We could implement a separate page cache, since `findWithDetails` cannot use the model registry (for the object with loaded details).

Comment (aschempp) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: pretty sure that will be a big performance penalty 😞

**Comment by fritzmg** [comment]
* `$GLOBALS['objPage']` is now used directly.
* A static cache for the page objects with loaded details is now in place.

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 4]
```diff
@@ -593,6 +604,22 @@ public function purgeOldFeeds()
...
+	 * @return PageModel|null
+	 */
+	private function getPageWithDetails($intPageId)
+	{
+		if (isset(self::$arrPageCache[$intPageId]))
+		{
+			return self::$arrPageCache[$intPageId];
+		}
+
+		return (self::$arrPageCache[$intPageId] = PageModel::findWithDetails($intPageId));
```
Comment (ausi) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php]: I think we do it the other way round most of the time. _(just a nitpick ☺️)_
```suggestion
		if (!isset(self::$arrPageCache[$intPageId]))
		{
			self::$arrPageCache[$intPageId] = PageModel::findWithDetails($intPageId)
		}

		return self::$arrPageCache[$intPageId];
```

**Review by ausi — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 5]
```diff
@@ -144,20 +150,18 @@ protected function generateFiles($arrFeed)
...
-						$arrUrls[$jumpTo] = false;
-					}
-					else
-					{
-						$arrUrls[$jumpTo] = $objParent->getAbsoluteUrl(Config::get('useAutoItem') ? '/%s' : '/events/%s');
-					}
+					$arrUrls[$jumpTo] = $objParent->getAbsoluteUrl(Config::get('useAutoItem') ? '/%s' : '/events/%s');
 				}
 
 				// Skip the event if it requires a jumpTo URL but there is none
```
Comment (aschempp) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php]: `$arrUrls[$jumpTo] === false` can no longer happen, right?

File: calendar-bundle/src/Resources/contao/classes/Calendar.php [hunk 6]
```diff
@@ -144,20 +150,18 @@ protected function generateFiles($arrFeed)
 					continue;
 				}
 
+				$objParent = $this->getPageWithDetails($jumpTo);
```
Comment (aschempp) [inline calendar-bundle/src/Resources/contao/classes/Calendar.php:153]: why is this done outside the `if (!isset($arrUrls[$jumpTo]))` call?

Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php:153]: The correct parent page always needs to be set, regardless of whether an URL to that parent page was already generated or not. Otherwise `$GLOBALS['objPage']` might be the parent page of a previous news item, rather than the current one.

File: calendar-bundle/src/Resources/contao/classes/Calendar.php (hunk 5 above)
Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: True, we can probably remove this altogether:

https://github.com/contao/contao/blob/8b7007185f3a82b637e42860b637d82641cb8a38/calendar-bundle/src/Resources/contao/classes/Calendar.php#L167-L171

Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: Done.

**Review by ausi — APPROVED** [review]

File: calendar-bundle/src/Resources/contao/classes/Calendar.php (hunk 3 above)
Comment (leofeyer) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: I am not sure about this, either. @contao/developers WDYT?

Comment (fritzmg) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: The performance penalty should be rectified now with the implemented static cache (https://github.com/contao/contao/pull/2946#issuecomment-824852392).

Comment (Toflar) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: I agree that should be okay.

Comment (leofeyer) [reply calendar-bundle/src/Resources/contao/classes/Calendar.php]: Ok. 😊

**Comment by leofeyer** [comment]
Thank you @fritzmg.
