### PR TITLE
Show errors for failed elements in the back end

### LINKED ISSUE #7544: Deleted file causes exception in back end for player element
### Affected version(s)

5.3.x

### Description

If the file (or one of the files) of a _Video/Audio_ content element gets deleted or renamed externally, an exception will be thrown in the back end. This also makes it impossible to rectify the issue by editing or deleting the content element.

**Reproduction**

1. Create a _Video/Audio_ content element.
2. Select a video, then _Save and close_.
3. Delete or rename the video outside of Contao.
4. Refresh within Contao.

The following error will occur:

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Unable to retrieve metadata from "files/videos/Pexels-20201107-1.mp4".").

  at C:/Users/fmg/www/c53/vendor/contao/contao/core-bundle/contao/templates/twig/content_element/player.html.twig:11
  […]
  at Twig\Template->render()
     (vendor\twig\twig\src\TemplateWrapper.php:35)
  at Twig\TemplateWrapper->render()
     (vendor\twig\twig\src\Environment.php:306)
  at Twig\Environment->render()
     (vendor\symfony\framework-bundle\Controller\AbstractController.php:448)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRenderView()
     (vendor\symfony\framework-bundle\Controller\AbstractController.php:453)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRender()
     (vendor\symfony\framework-bundle\Controller\AbstractController.php:253)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->render()
     (vendor\contao\contao\core-bundle\src\Controller\AbstractFragmentController.php:249)
  at Contao\CoreBundle\Controller\AbstractFragmentController->render()
     (vendor\contao\contao\core-bundle\src\Controller\AbstractFragmentController.php:126)
  at Contao\CoreBundle\Controller\AbstractFragmentController->Contao\CoreBundle\Controller\{closure}()
     (vendor\contao\contao\core-bundle\src\Twig\FragmentTemplate.php:130)
  at Contao\CoreBundle\Twig\FragmentTemplate->getResponse()
     (vendor\contao\contao\core-bundle\src\Controller\ContentElement\PlayerController.php:70)
  at Contao\CoreBundle\Controller\ContentElement\PlayerController->getResponse()
     (vendor\contao\contao\core-bundle\src\Controller\ContentElement\AbstractContentElementController.php:40)
  at Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController->__invoke()
     (vendor\symfony\http-kernel\HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor\symfony\http-kernel\HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor\symfony\http-kernel\HttpCache\SubRequestHandler.php:86)
  at Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle()
     (vendor\symfony\http-kernel\Fragment\InlineFragmentRenderer.php:78)
  at Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render()
     (vendor\symfony\http-kernel\Fragment\FragmentHandler.php:83)
  at Symfony\Component\HttpKernel\Fragment\FragmentHandler->render()
     (vendor\contao\contao\core-bundle\src\Fragment\FragmentHandler.php:66)
  at Contao\CoreBundle\Fragment\FragmentHandler->render()
     (vendor\contao\contao\core-bundle\contao\elements\ContentProxy.php:74)
  at Contao\ContentProxy->generate()
     (vendor\contao\contao\core-bundle\contao\library\Contao\Controller.php:601)
  at Contao\Controller::getContentElement()
     (vendor\contao\contao\core-bundle\contao\dca\tl_content.php:1007)
  at tl_content->addCteType()
     (vendor\contao\contao\core-bundle\contao\drivers\DC_Table.php:5014)
  at Contao\DC_Table->parentView()
     (vendor\contao\contao\core-bundle\contao\drivers\DC_Table.php:468)
  at Contao\DC_Table->showAll()
     (vendor\contao\contao\core-bundle\contao\classes\Backend.php:546)
  at Contao\Backend->getBackendModule()
     (vendor\contao\contao\core-bundle\contao\controllers\BackendMain.php:144)
  at Contao\BackendMain->run()
     (vendor\contao\contao\core-bundle\src\Controller\BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor\symfony\http-kernel\HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor\symfony\http-kernel\HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor\symfony\http-kernel\Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public\index.php:42)
```

### PR DESCRIPTION
**Pull request by ausi**
Fixes #7544 for the backend. 

Having a general try/catch for the content element preview makes sense IMO as this would always make it possible to edit the element and fix a potential misconfiguration.

The frontend is not affected for the audio/video element because the error only happens in the `editor_view` block. Image and download elements already failed gracefully in my test. We should not add a general try/catch for the frontend because only the content element itself can know if it should fail gracefully or not.

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

File: core-bundle/contao/dca/tl_content.php [hunk 1]
```diff
@@ -965,7 +965,15 @@ public function addCteType($arrRow)
 		$objModel->setRow($arrRow);
 
 		$class = 'cte_preview';
-		$preview = StringUtil::insertTagToSrc($this->getContentElement($objModel));
+
+		try
+		{
+			$preview = StringUtil::insertTagToSrc($this->getContentElement($objModel));
+		}
+		catch (Throwable $exception)
```
Comment (zoglo) [inline core-bundle/contao/dca/tl_content.php:973]:
```suggestion
		catch (\Throwable $exception)
```
Just a nit :)

**Review by zoglo — APPROVED** [review]

File: core-bundle/contao/dca/tl_content.php (hunk 1 above)
Comment (ausi) [reply core-bundle/contao/dca/tl_content.php:973]: This file has no namespace and our coding style is to not prefix the root-namespace classes in that case. (at least that is how the other root-namespace classes are referenced in this file already).

**Review by fritzmg — APPROVED** [review]
Just a thought: should we catch a rendering error even more generally in `Controller::getContentElement()`, if the scope is `backend`?

But otherwise I think this PR makes sense to me 👍

**Review by Toflar — APPROVED** [review]

**Comment by ausi** [comment]
> Just a thought: should we catch a rendering error even more generally in `Controller::getContentElement()`, if the scope is `backend`?

I don’t think that would be a great idea. Would you return the empty string then? Or a `<p class="tl_error">…</p>`? IMO it is perfectly fine for `Controller::getContentElement()` to throw an exception. The caller should decide how to handle it, as we know only there how to react to the error.

**Comment by leofeyer** [comment]
Thank you @ausi.
