### PR TITLE
Set the correct PIDs when copying folders recursively

### LINKED ISSUE #6186: Incorrect pid of nested subfiles when copying a folder
### Affected version(s)

4.13

### Description

I am building a frontend file browser that uses Contao's DBAFS. The current position in a file tree is determined by the UUID in the URL. This is basically how I found out there's something wrong with the DBAFS. Now, on to the details.

When copying a folder that contains subfolders, the files inside the subfolder will have a wrong `pid` in the database. Let's take a look at the official Contao demo files as an example. If I copy the `theme` folder and place it somewhere else, it will copy all the subfolders and files inside it – that's correct. All of those children will also get a new `pid` value, which will be the same as the new folder's UUID. But here's the catch: this new `pid` value is correct for the subfiles on the first level, but it's not for the subfiles on deeper levels. See the image below:

CleanShot 2023-07-03 at 13 32 04

I did a dump [below this line](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L373) that prints out the UUID and its new path. Here is the result:

CleanShot 2023-07-03 at 13 39 30

As you can see, the `pid` remains the same for all the files which is incorrect. It should get the `pid` of its direct parent folder model. The faulty line is exactly here:

https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L369

Would you like me to provide a pull request?

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6186

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Dbafs.php [hunk 1]
```diff
@@ -361,16 +361,20 @@ public static function copyResource($strSource, $strDestination)
...
 			{
+				$arrMapper = array();
+
 				while ($objFiles->next())
 				{
 					/** @var FilesModel $objNew */
 					$objNew = clone $objFiles->current();
 
-					$objNew->pid    = $objNewFile->uuid;
+					$objNew->pid    = $arrMapper[$objFiles->uuid] ?? $objNewFile->uuid;
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Dbafs.php]:
```suggestion
					$objNew->pid    = $arrMapper[$objFiles->pid] ?? $objNewFile->uuid;
```
we have to check for the old `pid` I guess?

**Review by ausi — APPROVED** [review]
