### PR TITLE
Do not decode entities in page names

### LINKED ISSUE #473: Entities are not decoded in news/event titles
**Affected version(s)**

Contao 4.4.39

**Description**

If the **news title** contains special characters, the corresponding HTML entities are written into the HTML `<title>` element.

**How to reproduce**

* Create a new news item
* Insert a news title with special characters (e.g. `Lorem ipsum (foobar)`)
* Save and close the news item
* Open the news item in the front end and check the `<title>` element in the HTML source code:
```html
<title>Lorem ipsum &#40;foobar&#41; - Contao Official Demo</title>
```

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #473 

Since insert tags are now removed recursively, we do not need the `StringUtil::stripInsertTags()` call in the `PageRegular` class anymore.

### CODE REVIEW

File: core-bundle/src/Resources/contao/pages/PageRegular.php [hunk 1]
```diff
@@ -210,7 +210,7 @@ protected function prepare($objPage)
 		}
 
 		// Assign the title and description
-		$this->Template->title = StringUtil::stripInsertTags($this->replaceInsertTags($objLayout->titleTag)); // see #7097
+		$this->Template->title = $this->replaceInsertTags($objLayout->titleTag);
```
Comment (Toflar) [inline core-bundle/src/Resources/contao/pages/PageRegular.php]: I wonder if we should `strip_tags()` though? What if I'm using the `{{br}}` insert tag? Or whatever insert tag that generates HTML?

**Review by aschempp — DISMISSED** [review]
The changes have been added in 2.6.3 (https://github.com/contao/core/commit/28f57b70ac6f02a47dab74e7257beb5ed9f9f6f1), unfortunately there's no note about why it was added.

I can already tell you there will be issues (like what @Toflar mentioned or the XML feed), but I think changing it is the correct approach and then we need to fix appearing issues in the long run.

**Comment by leofeyer** [comment]
I agree – even though the page title is never used in the XML sitemap.

File: core-bundle/src/Resources/contao/pages/PageRegular.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/pages/PageRegular.php]: We did not strip HTML tags before, but I guess it cannot hurt. Added in 31a24547dceb1ca23c1efe5595793535c70f29ee.

**Review by Toflar — APPROVED** [review]

**Review by aschempp — APPROVED** [review]
