### PR TITLE
Only create proxy templates for '@Contao' namespaced templates

### LINKED ISSUE #3199: Erroneous twig template proxy generation for Contao 3 templates
**Affected version(s)**

Contao 4.12-RC1

**Description**

If you create a `system/modules/test/templates/test.html5` file with the following content:

```php
<?php $foo = 'foo';
```

cache warmup will fail with the following error:

```
  In 2299977b4d0fce6c4a673ee3e186380c339e3173f384ff3835bd026d8ad04ba9.php line 30:

    [ParseError]
    syntax error, unexpected 'foo' (T_STRING), expecting ']'  

                                                                                                                                                                                                                          
  Exception trace:
    at var\cache\prod\twig\22\2299977b4d0fce6c4a673ee3e186380c339e3173f384ff3835bd026d8ad04ba9.php:30
   Twig\Cache\FilesystemCache->load() at vendor\twig\twig\src\Environment.php:410
   Twig\Environment->loadClass() at vendor\twig\twig\src\Environment.php:381
   Twig\Environment->loadTemplate() at vendor\twig\twig\src\Environment.php:359
   Twig\Environment->load() at vendor\symfony\twig-bundle\CacheWarmer\TemplateCacheWarmer.php:53
   Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer->warmUp() at vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php:98
   Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at vendor\symfony\framework-bundle\Command\CacheWarmupCommand.php:81
   Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand->execute() at vendor\symfony\console\Command\Command.php:256
   Symfony\Component\Console\Command\Command->run() at vendor\symfony\console\Application.php:989
   Symfony\Component\Console\Application->doRunCommand() at vendor\symfony\framework-bundle\Console\Application.php:96
   Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at vendor\symfony\console\Application.php:290
   Symfony\Component\Console\Application->doRun() at vendor\symfony\framework-bundle\Console\Application.php:82
   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\console\Application.php:166
   Symfony\Component\Console\Application->run() at vendor\contao\contao\manager-bundle\bin\contao-console:37
```

The cached template file will look like this:

```php
<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @test/test.html5 */
class __TwigTemplate_5ec61f350e59af06766a42fb452c86dcfdbe4d3206f3f35a1fdd929aaeff4348 extends \Twig\Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
            '<?php $foo = 'foo';' => [$this, 'block_<?php $foo = 'foo';'],
            '' => [$this, 'block_'],
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        echo $this->extensions["Contao\\CoreBundle\\Twig\\Extension\\ContaoExtension"]->renderLegacyTemplate(
            $this->getTemplateName(),
            array_map(
                function(callable $block) use ($context): string {
                    if ($this->env->isDebug()) { ob_start(); } else { ob_start(static function () { return ''; }); }
                    try { $block($context); return ob_get_contents(); } finally { ob_end_clean(); }
                }, $blocks
            ), $context
        );
    }

    public function block_<?php $foo = 'foo';($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo "[[TL_PARENT]]";
    }

    public function block_($context, array $blocks = [])
    {
        $macros = $this->macros;
        echo "[[TL_PARENT]]";
    }

    public function getTemplateName()
    {
        return "@test/test.html5";
    }

    public function getDebugInfo()
    {
        return array ();
    }

    public function getSourceContext()
    {
        return new Source("", "@test/test.html5", "…\\system\\modules\\test\\templates\\test.html5");
    }
}
```

It looks like blocks are detected erroneously, resulting in invalid PHP code for the generated template proxy class?

As far as I tested, this only happens for Contao 3 style extensions. I was unable to reproduce this in  `templates/`, `contao/templates/` or the `src/Resources/contao/templates/` folder of a bundle.

This can be reproduced by installing `codefog/contao-cookiebar` for example.

/cc @m-vo

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3199 
| Docs PR or issue | -

The `PhpTempalteProxyNodeVisitor` did only check if a template had a `.html5` file extension and not if it was actually from a `@Contao` or `@Contao_*` namespace. This is now fixed in 33ddca5097a0c34811b839e32fae911e799342d2 (guard + sanity check) - I also refactored the name parsing into a util class.

The error in #3199 happened because the `system/modules/test/templates` directory got registered as a bundle template folder by Symfony. And as everything can be a template, the `html5` files in there got parsed as well - which then caused our node visitor to generate nonsense.

/cc @fritzmg

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php [hunk 1]
```diff
@@ -73,12 +74,14 @@ private function handleContaoExtends(Node $expr, TokenStream $stream): void
         TokenParserHelper::traverseConstantExpressions(
             $expr,
             function (Node $node) use ($stream): void {
-                if (null === ($shortName = TokenParserHelper::getContaoTemplate($node->getAttribute('value')))) {
+                $parts = ContaoTwigUtil::parseContaoName($node->getAttribute('value'));
+
+                if ('Contao' !== ($parts[0] ?? null)) {
```
Comment (leofeyer) [inline core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php:79]: Why this check? If `$parts` is not `null`, `$parts[0]` will always be `Contao`, won't it?

File: core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php [hunk 2]
```diff
@@ -51,12 +52,14 @@ public function parse(Token $token): IncludeNode
      */
     public static function adjustTemplateName(string $name, TemplateHierarchyInterface $hierarchy): string
     {
-        if (null === ($shortNameOrIdentifier = TokenParserHelper::getContaoTemplate($name))) {
+        $parts = ContaoTwigUtil::parseContaoName($name);
+
+        if ('Contao' !== ($parts[0] ?? null)) {
```
Comment (leofeyer) [inline core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php:57]: Why this check? If `$parts` is not `null`, `$parts[0]` will always be `Contao`, won't it?

File: core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php [hunk 3]
```diff
@@ -367,34 +368,13 @@ public function buildInheritanceChains(): void
...
-    }
-
     /**
      * Returns the template name of a theme specific variant of the given name
      * or null if not applicable.
      */
     private function getThemeTemplateName(string $name): ?string
     {
-        if (null === ($parts = $this->parseContaoName($name)) || 'Contao' !== $parts[0]) {
+        if (null === ($parts = ContaoTwigUtil::parseContaoName($name)) || 'Contao' !== $parts[0]) {
```
Comment (leofeyer) [inline core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php]: Why this check? If `$parts` is not `null`, `$parts[0]` will always be `Contao`, won't it?

**Review by leofeyer — CHANGES_REQUESTED** [review]

File: core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php:79]: It could be `Contao` but also `Contao_Foo`, `Contao_App`, `Contao_Theme_foo_bar` and so on.

File: core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php (hunk 2 above)
Comment (m-vo) [reply core-bundle/src/Twig/Inheritance/DynamicIncludeTokenParser.php:57]: see https://github.com/contao/contao/pull/3201/files#r678459280

File: core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php (hunk 3 above)
Comment (m-vo) [reply core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php]: see https://github.com/contao/contao/pull/3201/files#r678459280

File: core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/src/Twig/Inheritance/DynamicExtendsTokenParser.php:79]: Should we need more name parsing in the future, we can refactor this to return an object with getters instead. I'd keep it as internal first anyway.

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.
