### PR TITLE
Fix error when using return => Array for models

### LINKED ISSUE #2897: Model::findMultipleByIds() fails when asked to return an array
**Affected version(s)**

Contao 4.9.12

**Description**

When called with the option `'return' => 'Array'`, findMultipleByIds throws an error:

> "Call to a member function next() on array" at contao/core-bundle/src/Resources/contao/library/Contao/Model.php line 872.

There's simply no logic in place to handle an array returned from the call to `find()` in line 868.

### PR DESCRIPTION
**Pull request by fritzmg**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2897
| Docs PR or issue | -

When using

```php
Model::findMultipleByIds([…], ['return' => 'Array']);
```

the following error occurs:

```
Error:
Call to a member function next() on array

  at vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:872
  at Contao\Model::findMultipleByIds()
```

This PR changes the affected code to always use `foreach` instead of `while` so that it does not matter whether `Array` or `Collection` is used for the `return` option.

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Resources/contao/library/Contao/Model.php [hunk 1]
```diff
@@ -869,10 +869,10 @@ public static function findMultipleByIds($arrIds, array $arrOptions=array())
 
 			if ($objMissing !== null)
 			{
-				while ($objMissing->next())
+				foreach ($objMissing as $objMissingRecord)
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Model.php]: Why did you choose `$objMissingRecord` instead of something short like `$model` or `$current` (or `$objModel` if you want to stick to the old naming schema)?

Comment (fritzmg) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: I wanted to stick to the old naming schema and use a descriptive variable name. Since `$objMissing` is the collection then iterating over the collection gives you a single record - hence the name `$objMissingRecord`. Otherwise I would go for `$objCurrent`.

**Review by leofeyer — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
