### PR TITLE
Handle null arguments in the ContentCompositionListener

### LINKED ISSUE #2787: Unable to setup a "Weiterleitungsseite" for (News, Forms, FAQ, Events,...)
**Affected version(s)**

Contao 4.10.1 - Contao 4.10.7?

**Description**

Hi, since today I'm not able to setup a "Weiterleitungsseite" for (News, Forms, FAQ, Events,...). If I press on the "Auswahl ändern" Button I'm getting the following server error:

```
TypeError:
preg_replace(): Argument #3 ($subject) must be of type array|string, null given

  at vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107
  at preg_replace()
     (vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107)
  at Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener->renderPageArticlesOperation()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:804)
  at Contao\DataContainer->generateButtons()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4028)
  at Contao\DC_Table->generateTree()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:3628)
  at Contao\DC_Table->treeView()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:353)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)  
```   
I have only installed the newest version (3.1.16) of "Sprachwechsler" modul and had until now no problems. Have someone an idea what is going wrong here?
Thxs...

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #2787 ([thread](https://community.contao.org/de/showthread.php?80310-Internal-Server-Error-beim-Dr%C3%BCcken-auf-quot-Auswahl-%C3%A4ndern-quot-bei-der-Weiterleitungsseite&p=540163&viewfull=1#post540163)):

```
TypeError:
preg_replace(): Argument #3 ($subject) must be of type array|string, null given

  at vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107
  at preg_replace()
     (vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107)
  at Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener->renderPageArticlesOperation()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:804)
  at Contao\DataContainer->generateButtons()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4028)
  at Contao\DC_Table->generateTree()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:3628)
  at Contao\DC_Table->treeView()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:353)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)
```

Since `$icon` can specifically be null. Not sure why it would be though in this specific instance, but apparently it can happen.

### CODE REVIEW

**Comment by leofeyer** [comment]
The PR is based on the wrong branch.

**Comment by m-vo** [comment]
In the picker `$href` and `$icon` is null every time. If `!$this->pageRegistry->supportsContentComposition($pageModel) || !$this->hasArticlesInLayout($pageModel)` evaluates to `false` an `a` tag without inner HTML is output. We should IMHO always return early in this case.

The original issue probably appears because the mentioned condition evaluates to `true` (legacy routing mode or something?).

**Comment by fritzmg** [comment]
> We should IMHO always return early in this case.

No, because you could still style the `<a>` otherwise.

// sorry, I meant we cannot return early, if only `$icon` is `null`. But we could if both `$href` and `$icon` are `null`, yes.

**Comment by m-vo** [comment]
I can reproduce #2787 as well with PHP8.0.

If you have a page that has no layout assigned `$this->hasArticlesInLayout($pageModel)` returns `false` which is why the failing code is executed. And `icon`/`href` can be `null` according to the DCA definition. 

This must IMHO also be taken into account in line 112 (`$href = null`) as well as line 114 (`$icon = null`).

Btw.: If both are `null` we could imo shortcut execution but maybe someone relies on the anchor with a title: `<a href="" title="foobar"></a>` that is still output. Giving this a second thought, I'd leave this out and focus on the PHP8 problem first.

**Comment by fritzmg** [comment]
Line 114 is ok, because there are no strict types. And `Image::getHtml` returns early with an empty string, if `$src` is falsey. Line 112 is ok too because concatenating a string together with `null` is allowed: https://3v4l.org/VCCr2

**Comment by m-vo** [comment]
> Line 114 is ok, because there are no strict types. And Image::getHtml returns early with an empty string

While true, at least this one looks a bit fragile to me. 🙃

**Comment by fritzmg** [comment]
I decided to include the return for when both the `$href` and `$icon` is `null` in this PR as well. I don't think it ever makes sense to output this HTML in the picker:

```html
<a href="contao?do=page&amp;popup=1&amp;picker=…&amp;pn=2&amp;rt=…&amp;ref=…" title=""></a>
```

This would be the link for the articles of a page within the page section of the picker - which should not be present anyway, but it's currently only not visible because it has not text or image content.

File: core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php [hunk 1]
```diff
@@ -95,7 +95,7 @@ public function __construct(ContaoFramework $framework, Security $security, Page
      */
     public function renderPageArticlesOperation(array $row, ?string $href, string $label, string $title, ?string $icon): string
     {
-        if (!$this->security->isGranted(ContaoCorePermissions::USER_CAN_ACCESS_MODULE, 'article')) {
+        if (null === $href && null === $icon || !$this->security->isGranted(ContaoCorePermissions::USER_CAN_ACCESS_MODULE, 'article')) {
```
Comment (leofeyer) [inline core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php]:
```suggestion
        if ((null === $href && null === $icon) || !$this->security->isGranted(ContaoCorePermissions::USER_CAN_ACCESS_MODULE, 'article')) {
```

**Review by leofeyer — CHANGES_REQUESTED** [review]

File: core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php [hunk 2]
```diff
@@ -104,7 +104,7 @@ public function renderPageArticlesOperation(array $row, ?string $href, string $l
         $pageModel->setRow($row);
 
         if (!$this->pageRegistry->supportsContentComposition($pageModel) || !$this->hasArticlesInLayout($pageModel)) {
-            return $this->image->getHtml(preg_replace('/\.svg$/i', '_.svg', $icon)).' ';
+            return null !== $icon ? $this->image->getHtml(preg_replace('/\.svg$/i', '_.svg', $icon)).' ' : '';
```
Comment (leofeyer) [inline core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107]: This check is not necessary, because if `$icon` is `null`, we are returning early in line 98, aren't we?

**Review by leofeyer — CHANGES_REQUESTED** [review]

File: core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php (hunk 2 above)
Comment (fritzmg) [reply core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107]: Line 98 only returns if both `$href` _and_ `$icon` are `null`. Granted, usually none or both will be null in this particular case, but we should employ defensive programming anyway, should we not?

Comment (leofeyer) [reply core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107]: You are right.

**Comment by leofeyer** [comment]
@fritzmg Can you please add a unit test that verifies the new behavior?

**Comment by fritzmg** [comment]
Yes, I'll do that right away.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
