### PR TITLE
Fix `isHidden()` for `ContentProxy`

### LINKED ISSUE #8013: bezogenes Inhaltselement mit zeitlicher Ansichtsbedingung
### Affected version(s)

5.3 ff.

### Description

ich habe auf Seite A ein Inhaltselement mit zeitlicher Begrenzung der Ansicht (Vergangenheit) - das habe ich auf Seite B als Include-Element eingebunden...

Auf Seite A wird das CE nicht angezeigt - auf Seite B aber dennoch

das war bis C 4.13 anders - konnte das in der Demo (5.4.12) nachstellen...

soll das so?!?

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #8013 

This fixes the aforementioned issue as discussed in #8976. Since `Contao\ContentProxy` does not load the model's data onto itself and has it's own `__get()` method which only accesses the `templateProperties` if present, `$this->invisible` (etc.) in the `ContentElement::isHidden()` method simply do not exist and thus fragments were always rendered when retrieved via `Controller::getContentElement()`.

This affects the `content_element()` Twig function, the `{{insert_content::*}}` Insert Tag as well as the `alias` content element.

This PR fixes this by populating `$this->arrData` of the `ContentProxy` instance (just as regular `ContentElement` instances would) and then allowing access to that data via `__get()`. If custom data is set via `templateProperties`, that data still has priority.

### CODE REVIEW

File: core-bundle/contao/elements/ContentProxy.php [hunk 1]
```diff
@@ -76,17 +84,17 @@ public function generate()
 
 	public function __set($strKey, $varValue)
 	{
-		$this->reference->attributes['templateProperties'][$strKey] = $varValue;
+		$this->reference->attributes['templateProperties'][$strKey] = $this->arrData[$strKey] = $varValue;
```
Comment (m-vo) [inline core-bundle/contao/elements/ContentProxy.php]: Shouldn't that leave the model data in `arrData` as is? The `templateProperties` have precedence anyways.

Comment (fritzmg) [reply core-bundle/contao/elements/ContentProxy.php]: I guess so 👍

**Review by m-vo — APPROVED** [review]
