### PR TITLE
Fix the remaining operation button callbacks

### LINKED ISSUE #8554: Old menu labels in the templates and form fields modules
### Affected version(s)

5.6

### Description

@aschempp Do we have to add voters to fix this or could we also just adjust the markup of the callbacks?

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/8554

### CODE REVIEW

File: core-bundle/contao/dca/tl_files.php [hunk 1]
```diff
@@ -753,7 +719,7 @@ public function cutFile($row, $href, $label, $title, $icon, $attributes)
 	 *
 	 * @return string
 	 */
-	public function uploadFile($row, $href, $label, $title, $icon, $attributes)
+	public function uploadFile(DataContainerOperation $operation)
```
Comment (leofeyer) [inline core-bundle/contao/dca/tl_files.php:714]: You either have to adjust the method body or revert this:

**Review by leofeyer — CHANGES_REQUESTED** [review]
Besides this, the changes work as expected.

File: core-bundle/contao/templates/twig/be_popup.html.twig [hunk 2]
```diff
@@ -71,7 +71,7 @@
                             <p>{{ languages[lang] }}</p>
                             {% for field, value in data %}
                                 {% if value|default %}
-                                    {{ value }} ({{ labels['aw_' ~ field] }})<br>
+                                    {{ value }} ({{ labels['aw_' ~ field]|default }})<br>
```
Comment (leofeyer) [inline core-bundle/contao/templates/twig/be_popup.html.twig:74]: This change seems unrelated because `aw_` refers to the meta wizard and not the operations menu.

Comment (aschempp) [reply core-bundle/contao/templates/twig/be_popup.html.twig:74]: yes, it is unrelated but the popup currently does not work due to Twig changes (and I tested it because the operation in the PR points to it).

File: core-bundle/contao/dca/tl_files.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/contao/dca/tl_files.php:714]: fixed in 63b001ff99792c1aebc6d845ee70f825ff4b4a2a

**Comment by leofeyer** [comment]
Thank you @aschempp.
