### PR TITLE
Fix rendering empty DC views

### LINKED ISSUE #9226: Article header is not rendered, if there are no content elements
### Affected version(s)

5.x-dev

### Description

When editing the content elements of an empty article (or when creating a new one), the article's header is currently not rendered:

\
This also makes it impossible to create new content elements, as there won't be a paste button to insert the new content element.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/9226
Alternative to https://github.com/contao/contao/pull/9235

Diff is best viewed without whitespaces 😉

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]
The changes work and make sense to me at first glance 👍. However, I still think @m-vo and/or @diekatrin should approve these.

**Review by zoglo — APPROVED** [review]

**Review by m-vo — CHANGES_REQUESTED** [review]
I think the fix can be a lot simpler, see https://github.com/contao/contao/pull/9244. 😉

File: core-bundle/contao/drivers/DC_Table.php [hunk 1]
```diff
@@ -4360,8 +4363,6 @@ protected function parentView()
 
 		$parameters['message'] = Message::generate();
 		$parameters['global_operations'] = $operations;
-		$parameters['has_clipboard_content'] = $blnClipboard;
-		$parameters['is_sortable'] = $blnIsSortable;
```
Comment (m-vo) [inline core-bundle/contao/drivers/DC_Table.php:4364]: Just to make sure: this is purely CS, not a change needed function-wise, correct? (I'm all for it anyways.)

(same for the other change in `DC_Table`)

**Review by m-vo — APPROVED** [review]
Let's go with this solution for now.

File: core-bundle/contao/drivers/DC_Table.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:4364]: Initially had `|default` because `has_clipboard_content` is currently not defined if there are no records.
