### PR TITLE
Fix various permission checks

### LINKED ISSUE #9352: Marking a DCA as `closed` breaks permission check
### Affected version(s)

 5.7.x-dev

### Description

In some of our extensions (e.g. https://github.com/numero2/contao-tags) we are using the `closed` option in the DCA.

We rely on this option because certain users should be able to view and edit existing records, but not create new ones, duplicate existing ones, or perform similar actions. This setup has been working reliably since Contao 4.13.

However, in `5.7.x-dev` we now encounter an `AccessDeniedHttpException` with the following message:

> Not enough permissions to update [Subject: Source: tl_tags; ID: 70].

This error occurs even when logged in as an **admin user**.

Image

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/9352

Here's the rules I followed:

### In the context of DC_Table:
 - `closed` means **cannot create and cannot copy record**, but can edit and delete
 - `notCreatable` means **cannot create new records** but can copy, edit and delete
 - `notCopyable` means **cannot copy records** but can create new, edit and delete
 - `notEditable` means **cannot edit records**. Beceause new records would need to be edited, it also means **cannot create new records**. However, can copy (without switching into edit mode).
 - `notDeletable` means **cannot delete records**

### In the context of DC_Folder:
- `closed` means **cannot upload files** and **cannot create folders**
- `notCreatable` means **cannot create folders**, but can upload new files
- `notMovable` means **cannot upload new files** but can create new folders (e.g. legacy template editor)
- `notEditable` means **cannot edit files and folders**. Because new folders need a name, it also means **cannot create folders**. But can upload files.
- `notDeletable` means **cannot delete files or folders**

Obviously all of them can be combined and will result in the least possible permissions.

### CODE REVIEW

**Review by leofeyer — CHANGES_REQUESTED** [review]
> > > * `notCreatable` means **cannot create new records** but can copy, edit and delete
> > 
> > 
> > That seems wrong. You shouldn't be able to copy records, either, otherwise you would create new records.
> 
> I'm just stating what is the current case already.

No, you're not?



The change shows that `$canCopy` was previously `false` if `notCreatable` was set.

File: core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php [hunk 1]
```diff
@@ -105,7 +105,7 @@ private function getDefaults(string $table): array
         $ctable = $GLOBALS['TL_DCA'][$table]['config']['ctable'][0] ?? null;
 
         $canEdit = !($GLOBALS['TL_DCA'][$table]['config']['notEditable'] ?? false);
-        $canCopy = !($GLOBALS['TL_DCA'][$table]['config']['closed'] ?? false) && !($GLOBALS['TL_DCA'][$table]['config']['notCreatable'] ?? false) && !($GLOBALS['TL_DCA'][$table]['config']['notCopyable'] ?? false);
+        $canCopy = !($GLOBALS['TL_DCA'][$table]['config']['closed'] ?? false) && !($GLOBALS['TL_DCA'][$table]['config']['notCopyable'] ?? false);
```
Comment (ausi) [inline core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php:108]: This reverts the changes to this file from https://github.com/contao/contao/pull/7712 on purpose?

Comment (aschempp) [reply core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php:108]: Interesting catch. It would set the permission checks consistent everywhere. But I'm happy to discuss what we prefer.

**Review by ausi — APPROVED** [review]
Changes look good to me, but I did not individually test all the combinations.

**Comment by leofeyer** [comment]
Thank you @aschempp.
