### PR TITLE
Fix the DCA loading performance in dev mode

### LINKED ISSUE #8474: Performance of DCA loading
### Affected version(s)

5.5+

### Description

It's not strictly a 5.5-only issue but it's now more apparent because e.g. in the search results, every search result loads the data container individually with the new `DcaUrlAnalyzer`.

See Blackfire profile: https://blackfire.io/profiles/dc554ddf-c834-452e-9c53-e957eb3e66ca/graph

It sure can be improved in the `DcaUrlAnalyzer` itself too but maybe it would also be great to actually build the DCA cache in `dev` mode as well and implement resource tracking so that it's rebuilt once a DCA file changes. This would make navigating in `dev` mode way faster in general.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #8474 until we implement a real solution using the symfony `ConfigCache`.

### CODE REVIEW

File: core-bundle/contao/library/Contao/DcaLoader.php [hunk 1]
```diff
@@ -164,7 +172,7 @@ private function loadDcaFiles()
 		$strCachePath = $strCacheDir . '/contao/dca/' . $this->strTable . '.php';
 
 		// Try to load from cache
-		if (file_exists($strCachePath) && !System::getContainer()->getParameter('kernel.debug'))
+		if (file_exists($strCachePath) && (!System::getContainer()->getParameter('kernel.debug') || isset(self::$freshPaths[$strCachePath])))
```
Comment (m-vo) [inline core-bundle/contao/library/Contao/DcaLoader.php]: Would make sense to swap the arguments of `&&` to short circuit the file exists check when in dev mode or cache miss, no?

**Review by m-vo — DISMISSED** [review]

File: core-bundle/contao/library/Contao/DcaLoader.php (hunk 1 above)
Comment (ausi) [reply core-bundle/contao/library/Contao/DcaLoader.php]:
```suggestion
		if ((!System::getContainer()->getParameter('kernel.debug') || isset(self::$freshPaths[$strCachePath])) && file_exists($strCachePath))
```

**Review by m-vo — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
