### PR TITLE
Fix 'Purge the preview cache' (path not found)

### LINKED ISSUE #4089: Systemwartung -> Vorschau-Cache leeren => Fehler in server error.log
### Affected version(s)

4.13.0-RC2

### Description

Die Ausführung der Funktion Systemwartung -> Vorschau-Cache leeren führt zu folgendem Fehler im error.log des Servers:

`2022/02/08 22:03:24 [error] 11108#11108: *20787 FastCGI sent in stderr: "PHP message: PHP Warning:  scandir(/var/www/client/web/assets/previews/): failed to open dir: No such file or directory in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588PHP message: PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588" while reading response header from upstream, client: 1.1.1.1, server: abc.tld, request: "POST /contao?do=maintenance&ref=Bm8E_5at HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web50.sock:", host: "abc.tld", referrer: "https://abc.tld"`

### PR DESCRIPTION
**Pull request by AlexanderWillner**
**Version:** 4.13-RC1 / PHP 7.4.27
**URL:** /contao?do=maintenance

**Steps that will reproduce the problem?**
1. Setup a new Contao instance from scratch
2. Go to System > Maintenance, select `Purge the preview cache`
3. Press `Purge data`

**What is the expected result?**

Purged preview cache.

**What happens instead?**

* Folder not found exception
* Class not found exception

Possible workaround:

See patches.

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Automator.php [hunk 1]
```diff
@@ -14,6 +14,7 @@
 use FOS\HttpCacheBundle\CacheManager;
 use Symfony\Component\Console\Input\ArgvInput;
 use Symfony\Component\Console\Output\NullOutput;
+use Contao\CoreBundle\Monolog\ContaoContext;
```
Comment (ausi) [inline core-bundle/src/Resources/contao/library/Contao/Automator.php]: Where in in this files gets the `ContaoContext` class used?

Comment (AlexanderWillner) [reply core-bundle/src/Resources/contao/library/Contao/Automator.php]: In RC1 the error ```Attempted to load class "ContaoContext" from namespace "Contao".
Did you forget a "use" statement for e.g. "Contao\CoreBundle\Asset\ContaoContext" or "Contao\CoreBundle\Monolog\ContaoContext"?``` will be thrown in line 152.

However, just saw it was fixed 20 day ago in https://github.com/contao/contao/commit/886fba0ff4925dc22698dc7abf9ba1b1eebdf761#diff-55b7dfefbb2703c2fb23f7d50a40ae3ac9a45d88fec605273593116a96e2969eR151

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Resources/contao/library/Contao/Folder.php [hunk 2]
```diff
@@ -585,16 +585,18 @@ public static function scan($strFolder, $blnUncached=false): array
...
-			}
+				if ($strFile == '.' || $strFile == '..')
+				{
+					continue;
+				}
 
-			$arrReturn[] = $strFile;
+				$arrReturn[] = $strFile;
+			}
 		}
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Folder.php:599]:
```suggestion
		}

```

I wasn‘t allowed to fix this myself, so now you have to merge this. 😄

**Review by leofeyer — CHANGES_REQUESTED** [review]

**Review by ausi — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

**Review by ausi — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @AlexanderWillner.
