### PR TITLE
Fix the "overwrite metadata fields" migration

### LINKED ISSUE #8037: Migrate overwrite metadata fields
### Affected version(s)

5.6

### Description

We'll need to add migrations for #8002, so that entries that were previously overwriting metadata using an empty string will now get the new `{{empty}}` insert tag.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #8037

### CODE REVIEW

**Review by m-vo — DISMISSED** [review]

File: calendar-bundle/src/Migration/OverwriteMetaMigration.php [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ * This file is part of Contao.
+ *
+ * (c) Leo Feyer
+ *
+ * @license LGPL-3.0-or-later
+ */
+
+namespace Contao\CalendarBundle\Migration;
+
+use Contao\CoreBundle\Migration\Version505\OverwriteMetaMigration as BaseMigration;
```
Comment (leofeyer) [inline calendar-bundle/src/Migration/OverwriteMetaMigration.php:15]: The base class is marked `@internal`, so technically we cannot use it here. Maybe we should provide a non-internal base class that can be used by everybody?

Comment (ausi) [reply calendar-bundle/src/Migration/OverwriteMetaMigration.php:15]: > The base class is marked `@internal`, so technically we cannot use it here.

Because we’re using `self.version` as our `core-bundle` requirement using `@internal` features in the other bundles should never be a problem.

Semantically I would interpret `@internal` on the root namespace level here, so every subnamespace of `\Contao` would be allowed to access/use it.

Comment (ausi) [reply calendar-bundle/src/Migration/OverwriteMetaMigration.php:15]: > Maybe we should provide a non-internal base class that can be used by everybody?

I don’t think that is nessecary.

Comment (leofeyer) [reply calendar-bundle/src/Migration/OverwriteMetaMigration.php:15]: So you think no extension but the default bundles uses the metadata overwrite mechanism?

Comment (ausi) [reply calendar-bundle/src/Migration/OverwriteMetaMigration.php:15]: They would have to use it in the exact same way. Our migration is too specific to be an abstract one I think. We skip the check for `varchar` to `text` for `imageUrl` for example because this is already a `text` column in `tl_content`. The Column names are fixed and are not configurable, etc..
If someone needs a similar migration, the can just copy it and adapt it to their needs.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
