### PR TITLE
Fix undefined array key access

### LINKED ISSUE #5509: Frontend User groups check first if array is empty.
### Affected version(s)

4.13.12

### Description

Contao 4.13.12
PHP: 8.1

Please check if the member groups array is empty before accessing its 0th element.

Screenshot 2022-11-15 at 17 47 45

### PR DESCRIPTION
**Pull request by bytehead**
Fixes #5509

### CODE REVIEW

File: core-bundle/src/Resources/contao/classes/FrontendUser.php [hunk 1]
```diff
@@ -237,7 +237,7 @@ protected function setUserFromDb()
 		}
 
 		// Get the group login page
-		if ($this->groups[0] > 0)
+		if (\count($this->groups) && $this->groups[0] > 0)
```
Comment (ausi) [inline core-bundle/src/Resources/contao/classes/FrontendUser.php]: Is `$this->groups` guaranteed to be indexed starting with zero? Otherwise I’d just use:
```suggestion
		if (($this->groups[0] ?? 0) > 0)
```

Comment (bytehead) [reply core-bundle/src/Resources/contao/classes/FrontendUser.php]: I've never seen any different - but who knows what's out there?

Comment (bytehead) [reply core-bundle/src/Resources/contao/classes/FrontendUser.php]: Adjusted in b367929334.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.
