### PR TITLE
Fix the front end preview

### LINKED ISSUE #1968: Preview link does not open FE preview
**Affected version(s)**

Contao 4.10

**Description**

- Back end home page → Preview → **no preview bar** (and no `preview.php` fragment)
- Site structure → edit page → Preview → preview bar is shown
- Articles → edit article → Preview → preview bar is shown
- Members → Preview front end as member → **no preview bar**

So it seems that the `/contao/preview` route with anything but `?page=` is broken?

@aschempp @richardhj /cc

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1968
| Docs PR or issue | -

### CODE REVIEW

**Review by m-vo — DISMISSED** [review]

File: core-bundle/src/Controller/BackendPreviewController.php [hunk 1]
```diff
@@ -90,6 +90,6 @@ public function __invoke(Request $request): Response
             return new RedirectResponse($targetUrl);
         }
 
-        return new RedirectResponse('/');
+        return new RedirectResponse($this->previewScript ?: '/');
```
Comment (aschempp) [inline core-bundle/src/Controller/BackendPreviewController.php]: This should probably use the request context's current root, right?

**Review by aschempp — CHANGES_REQUESTED** [review]

**Comment by aschempp** [comment]
`RequestContext::getBaseUrl()` is what I mean. That should include the script (regardless if preview or app_dev or whatever someone might create) and also a path.

**Comment by leofeyer** [comment]
I don't think this will work, because by the time the method is called, there is no `preview.php` fragment in the URL yet. The failing unit test seems to confirm this:

```php
return new RedirectResponse($request->getBaseUrl() ?: '/');
```

```
1) Contao\CoreBundle\Tests\Controller\BackendPreviewControllerTest::testRedirectsToRootPageWitPreviewScript
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'preview.php'
+'/'
```

I think the current fix is correct.

File: core-bundle/src/Controller/BackendPreviewController.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Controller/BackendPreviewController.php]: See 0c321e4f585856f587828ceaafed5db71ddca534.

**Review by aschempp — CHANGES_REQUESTED** [review]
the new test is wrong, it falls into the first if-condition in `BackendPreviewController`. Also, the request object does not have a `getBaseUrl()` mock.

**Review by aschempp — APPROVED** [review]
