### PR TITLE
Filter fallback routes if the accepted languages do not match

### LINKED ISSUE #430: Language redirect for regional codes ("de-at")
**Affected version(s)**
4.7.2 & 4.7.3

**Description**
Since ~ Contao 4.7, the language redirect to /de is not working anymore in Safari on Mac or iOS, if the browser language is "de-at" or "de-de".

**How to reproduce**  
Here are my headers according to https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending. No fancy alterations to my Safari headers, I tested this with several computers in Austria.
image

If I use these headers in a ` curl -s -i -H 'Accept-Language: de-at' https://themes.contao.org/`, I am redirected to https://themes.contao.org/en. Same with the 'de-de' header from my iOS Safari.

On a demo Site with Contao 4.4 it correctly redirects to /de.
Same on the Contao 3.x that terminal42 is running: `curl -s -i -H 'Accept-Language: de-at' https:/www.terminal42.ch/` redirects to /de

### PR DESCRIPTION
**Pull request by leofeyer**
This PR fixed #430 by filtering fallback routes if the accepted languages do not match.

- [x] Unit tests

I will add the unit tests as soon as we have agreed on the implementation. 😉

### CODE REVIEW

File: core-bundle/src/Routing/Matcher/DomainFilter.php [hunk 1]
```diff
@@ -42,7 +42,9 @@ public function filter(RouteCollection $collection, Request $request): RouteColl
 
         if ($hasDomainMatch) {
             foreach ($collection->all() as $name => $route) {
-                if (!$route->getHost()) {
+                $host = $route->getHost();
+
+                if (!$host || $host !== $httpHost) {
```
Comment (leofeyer) [inline core-bundle/src/Routing/Matcher/DomainFilter.php:47]: @aschempp I am not 100% sure if this is right, but filtering routes which have a domain that does not match the host (instead of just the ones that have no domain at all) does decrease the number of potential matches.

Comment (aschempp) [reply core-bundle/src/Routing/Matcher/DomainFilter.php:47]: Yeah, I think this makes sense. I just didn't add it because they would not match anyway. But this should theoretically result in a smaller number of route match tests.

**Review by aschempp — APPROVED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
However… should we not remove the expression language?

**Review by aschempp — APPROVED** [review]
O well… you already did 😂
