### PR TITLE
Fix loop when loading DCA and BackendUser

### LINKED ISSUE #5014: Field tl_(news|calendar_events).pid does not seem to be related
### Affected version(s)

5.0.x-dev, 5.0

### Description

When trying to edit a news article in the backend the following exception occurs:

```
Field tl_news.pid does not seem to be related

  at vendor/contao/core-bundle/contao/library/Contao/Model.php:651
  at Contao\Model->getRelated()
     (vendor/contao/news-bundle/contao/classes/News.php:351)
  at Contao\News::generateNewsUrl()
     (vendor/contao/news-bundle/contao/dca/tl_news.php:657)
  at tl_news->getSerpUrl()
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:159)
  at Contao\SerpPreview->getUrl()
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:51)
  at Contao\SerpPreview->generate()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:638)
  at Contao\Widget->generateWithError()
     (vendor/contao/core-bundle/contao/templates/backend/be_widget.html5:3)
  at include('/home/benny/www/contao5_php8/vendor/contao/core-bundle/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/contao/library/Contao/TemplateInheritance.php:109)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:585)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:729)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2014)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:544)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:149)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:44)    
```

and the same happens for the events:

```
Field tl_calendar_events.pid does not seem to be related

  at vendor/contao/core-bundle/contao/library/Contao/Model.php:651
  at Contao\Model->getRelated()
     (vendor/contao/calendar-bundle/contao/classes/Events.php:461)
  at Contao\Events::generateEventUrl()
     (vendor/contao/calendar-bundle/contao/dca/tl_calendar_events.php:725)
  at tl_calendar_events->getSerpUrl()
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:159)
  at Contao\SerpPreview->getUrl()
     (vendor/contao/core-bundle/contao/widgets/SerpPreview.php:51)
  at Contao\SerpPreview->generate()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:638)
  at Contao\Widget->generateWithError()
     (vendor/contao/core-bundle/contao/templates/backend/be_widget.html5:3)
  at include('/home/benny/www/contao5_php8/vendor/contao/core-bundle/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/contao/library/Contao/TemplateInheritance.php:109)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/contao/library/Contao/Widget.php:585)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/contao/classes/DataContainer.php:729)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:2014)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/contao/classes/Backend.php:544)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/contao/controllers/BackendMain.php:149)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:44)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:44)                
```

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5014

While analyzing the stack trace from https://github.com/contao/contao/issues/5014#issuecomment-1214395708 I saw that loading the `User` object caused a loop:

1. When loading the user the `Contao\Model::convertToPhpValue()` method gets executed
2. This needs the DcaExtractor so it gets loaded which itself loads all DCAs
3. Some DCA files directly call `BackendUser::getInstance()` which loads the user object
4. goto 1

I now created closures for the default values so that this only gets executed on the fly when needed.

### CODE REVIEW

File: core-bundle/contao/library/Contao/DcaLoader.php [hunk 1]
```diff
@@ -72,6 +72,11 @@ public function load()
 				throw static::$arrLoaded['dcaFiles'][$this->strTable];
 			}
 
+			if (!isset($GLOBALS['TL_DCA'][$this->strTable]))
+			{
+				trigger_deprecation('contao/core-bundle', '5.0', 'Loading a non-existent DCA has has been deprecated and will throw an exception in Contao 6.0.');
+			}
```
Comment (ausi) [inline core-bundle/contao/library/Contao/DcaLoader.php:78]: This would have helped debugging the issue IMO because it woud’ve detected DCA recursions.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
