### PR TITLE
Skip row size calculation for MyISAM

### LINKED ISSUE #4442: Handle non-InnoDB tables
### Affected version(s)

4.13.2

### Description

If there are both InnoDB and MyISAM tables, the migrations fail:

### PR DESCRIPTION
**Pull request by ausi**
Fixes #4442

### CODE REVIEW

File: core-bundle/src/Command/MigrateCommand.php [hunk 1]
```diff
@@ -485,6 +485,10 @@ private function compileTableWarnings(Table $table): array
     {
         $warnings = [];
 
+        if ($table->hasOption('engine') && 'innodb' !== strtolower($table->getOption('engine'))) {
```
Comment (m-vo) [inline core-bundle/src/Command/MigrateCommand.php:488]: Can the 'engine' option be empty and we're still dealing with anything else than innodb? 
If so should we turn the condition around?

```suggestion
        if (!$table->hasOption('engine') || 'innodb' === strtolower($table->getOption('engine'))) {
```

Comment (ausi) [reply core-bundle/src/Command/MigrateCommand.php:488]: AFAIK the engine defaults to `InnoDB`

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
