### PR TITLE
Fix the element count controller (again)

### LINKED ISSUE #9298: Error: Missing target element "parent" for "contao--element-count" controller
### Affected version(s)

5.7.x-dev

### Description

If you go to _Layout_ - _Templates_ the following error will appear in the browser console:

```
Error: Missing target element "parent" for "contao--element-count" controller
```

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #9298 _again_ because I accidentally removed [its fix](https://github.com/contao/contao/pull/9304) in #9258.

I have also made the `parent` target completely optional, so that this error cannot occur anymore.

### CODE REVIEW

**Review by zoglo — DISMISSED** [review]

**Review by zoglo — APPROVED** [review]

File: core-bundle/assets/controllers/element-count-controller.js [hunk 1]
```diff
@@ -5,7 +5,10 @@ export default class extends Controller {
     static values = { selector: String };
 
     connect() {
-        const count = this.parentTarget.querySelectorAll(this.selectorValue).length;
+        const count =
+            this.hasParentTarget && this.selectorValue
+                ? this.parentTarget.querySelectorAll(this.selectorValue).length
+                : 0;
```
Comment (leofeyer) [inline core-bundle/assets/controllers/element-count-controller.js:11]:
```suggestion
        const count = this.parentTarget?.querySelectorAll(this.selectorValue)?.length || 0;
```

Does this do the same?

Comment (fritzmg) [reply core-bundle/assets/controllers/element-count-controller.js:11]: No, `this.parentTarget` is not nullable, it will simply throw an error. You have to use `this.hasParentTarget`. 

https://stimulus.hotwired.dev/reference/targets#properties

And you also need to check for `this.selectorValue`, in case it was not added, otherwise you will get

> Element.querySelectorAll: '' is not a valid selector

Comment (leofeyer) [reply core-bundle/assets/controllers/element-count-controller.js:11]: Okay.
