### PR TITLE
Render the QR code margin directly in the image

### LINKED ISSUE #6773: 2FA - scanning of QR code in dark mode not working
### Affected version(s)

5.x

### Description

When running the Contao backend in “dark mode” the scanning of the QR code when enabling two factor authentication is not working. At least I didn’t get it to work.

Maybe we can introduce a catchy hint somewhere to switch to light mode for the scanning of the QR code or force the `<div class="two-factor">` to have a light background and dark elements.

PS: Thanks to the nice post man telling me this recently when I was trying to scan a QR code from my phone which is running on dark mode 😊.

### PR DESCRIPTION
**Pull request by Tastaturberuf**
Fixes #6773 and for Backend and Frontend. 

You need this margin in Frontend too and most of the designers never touch this.

before:
grafik

after:
grafik

### CODE REVIEW

**Comment by zoglo** [comment]
Wasn't this fixed by https://github.com/contao/contao/pull/6780 already?

**Comment by Tastaturberuf** [comment]
No because he fix this with CSS. And everyone has to fix this in every dark mode frontend. My with works for front- and backend because it renders the margin in the image.

**Comment by zoglo** [comment]
@Tastaturberuf could you remove the border that was introduced in #6870 within this PR?

**Comment by Tastaturberuf** [comment]
No, because i make this PR in the Browser 🙈 and cant build the assets.

File: core-bundle/src/Security/TwoFactor/Authenticator.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function getProvisionUri(User $user, Request $request): string
     public function getQrCode(User $user, Request $request): string
     {
         $renderer = new ImageRenderer(
-            new RendererStyle(180, 0),
+            new RendererStyle(180, 1),
```
Comment (fritzmg) [inline core-bundle/src/Security/TwoFactor/Authenticator.php:58]:
```suggestion
            new RendererStyle(180, 3),
```

In #6780 we introduced a 3px border.

May be this should be configurable though?

**Comment by zoglo** [comment]
> No, because i make this PR in the Browser 🙈 and cant build the assets.

Someone could do it for you ;)

File: core-bundle/src/Security/TwoFactor/Authenticator.php (hunk 1 above)
Comment (zoglo) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]:
```php
public function __construct(
        int $size,
        int $margin = 4,
        ?ModuleInterface $module = null,
        ?EyeInterface $eye = null,
        ?Fill $fill = null
    ) {
```

Having this set to 0 is already a bug to me, however, the margin is way bigger with 3 (I did test it out really quick)

Comment (zoglo) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: 1:
image

3:
image

Default (not passing the margin argument at all)
image

Comment (zoglo) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: > May be this should be configurable though?

Depends on what you would want to choose but if people want a bigger border in the frontend, they'd style it 🤔?
Maybe just winging with the default from the library itself would be better?

Comment (fritzmg) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: Ah, yes never mind, forgot that the margin setting is not related to pixels.

Comment (Tastaturberuf) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: I think we are fine with 3px for everyone. Android need this still.

Comment (Tastaturberuf) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: grafik

**Comment by Tastaturberuf** [comment]
Updated the CSS

File: core-bundle/src/Security/TwoFactor/Authenticator.php (hunk 1 above)
Comment (Tastaturberuf) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: Sorry i dint see the whole conversation. Better for configuration is to make this code bigger. The first parameter.

Comment (Tastaturberuf) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: The margin is related to one dot.

Comment (Tastaturberuf) [reply core-bundle/src/Security/TwoFactor/Authenticator.php:58]: I'am fine with `null`(4), `1` or `3` as default.

**Review by fritzmg — COMMENTED** [review]
Generally I am not sure we should change this in a bugfix PR, as this would result in a bigger border for anyone that already set a border in the front end. A feature PR for 5.6 could be so that you can change the render style in the config, e.g.:

```yaml
# config/config.yaml
contao:
    security:
        two_factor:
            qr_size: 180
            qr_margin: 3
```

**Comment by Tastaturberuf** [comment]
But the bigger border is much less a problem instead of a not working QR code (for Android users).

**Comment by Tastaturberuf** [comment]
Or we implement it with the default `0` now and change this to another value in the `5.6.`

**Comment by fritzmg** [comment]
> Or we implement it with the default `0` now and change this to another value in the `5.6.`

I would make it configurable with the above defaults in 5.6, yes 👍

**Comment by Tastaturberuf** [comment]
But we have this to fix for `5.3` as well. So apply lets call it bugfix instead of "feature".

File: core-bundle/src/Security/TwoFactor/Authenticator.php [hunk 2]
```diff
@@ -55,7 +55,7 @@ public function getProvisionUri(User $user, Request $request): string
     public function getQrCode(User $user, Request $request): string
     {
         $renderer = new ImageRenderer(
-            new RendererStyle(180, 0),
+            new RendererStyle(180, 3),
```
Comment (zoglo) [inline core-bundle/src/Security/TwoFactor/Authenticator.php]:
```suggestion
            new RendererStyle(180, 1),
```
I'd suggest using 1 for now as it's the closest to how it looked like before.

**Review by zoglo — CHANGES_REQUESTED** [review]

**Review by zoglo — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Tastaturberuf.
