### PR TITLE
Show infinitely repeating events only once if the list is open-ended

### LINKED ISSUE #8354: Recurring events cause 500 errors
### Affected version(s)

5.5.10

### Description

If you activate the Repeat Event option for the events and set the interval to once a day and the recurrences to 0, then a 500 server error occurs. I was also able to reproduce this in the Contao demo. 

Image

### PR DESCRIPTION
**Pull request by ausi**
Fixes #8354

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

File: calendar-bundle/src/Generator/CalendarEventsGenerator.php [hunk 1]
```diff
@@ -76,8 +76,13 @@ public function getAllEvents(array $calendars, \DateTimeInterface $rangeStart, \
                     $eventStartTime = (new \DateTime())->setTimestamp($eventModel->startTime);
                     $eventEndTime = (new \DateTime())->setTimestamp($eventModel->endTime);
                     $modifier = '+ '.$repeat['value'].' '.$repeat['unit'];
+                    $rangeCount = $eventEndTime < $rangeStart || $eventStartTime > $rangeEnd ? 0 : 1;
 
                     while ($eventEndTime < $rangeEnd) {
+                        if ($rangeCount > 0 && $rangeEnd->getTimestamp() >= min(4294967295, PHP_INT_MAX) && $eventModel->recurrences < 1) {
```
Comment (leofeyer) [inline calendar-bundle/src/Generator/CalendarEventsGenerator.php]:
```suggestion
                        if ($rangeCount > 0 && $rangeEnd->getTimestamp() >= min(4294967295, PHP_INT_MAX) && 0 === $eventModel->recurrences) {
```

Because a negative value does not mean "infinite recurrences".

**Comment by leofeyer** [comment]
And we should add a note in the `LIMITATIONS.md` file.

**Comment by ausi** [comment]
> And we should add a note in the `LIMITATIONS.md` file.

Done in the PR for 5.3: [f3b9502](https://github.com/contao/contao/pull/9730/changes/f3b95025212bafc3ed4436d44caf0719c5c2adba)

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
