### PR TITLE
Do not boot the Contao framework during cache warmup

### LINKED ISSUE #3567: Clearing the dev cache leads to "MemoryTokenStorage must not be accessed before it was initialized"
**Affected version(s)**

Contao 4.12.2

**Description**

If you clear the application cache while being logged into the back end and then refresh the back end again in your browser, the following exception occurs:

```
LogicException:
MemoryTokenStorage must not be accessed before it was initialized.

  at vendor\contao\core-bundle\src\Csrf\MemoryTokenStorage.php:101
  at Contao\CoreBundle\Csrf\MemoryTokenStorage->assertInitialized()
     (vendor\contao\core-bundle\src\Csrf\MemoryTokenStorage.php:54)
  at Contao\CoreBundle\Csrf\MemoryTokenStorage->hasToken('contao_csrf_token')
     (vendor\symfony\security-csrf\CsrfTokenManager.php:72)
  at Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('contao_csrf_token')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\RequestToken.php:57)
  at Contao\RequestToken::get()
     (vendor\contao\core-bundle\src\Framework\Adapter.php:44)
  at Contao\CoreBundle\Framework\Adapter->__call('get', array())
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:429)
  at Contao\CoreBundle\Framework\ContaoFramework->handleRequestToken()
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:311)
  at Contao\CoreBundle\Framework\ContaoFramework->initializeFramework()
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:158)
  at Contao\CoreBundle\Framework\ContaoFramework->initialize()
     (vendor\contao\core-bundle\src\Twig\Loader\TemplateLocator.php:67)
  at Contao\CoreBundle\Twig\Loader\TemplateLocator->findThemeDirectories()
     (vendor\contao\core-bundle\src\Twig\Loader\ContaoFilesystemLoaderWarmer.php:55)
  at Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoaderWarmer->warmUp('var/cache/dev')
     (vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php:98)
  at Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('var/cache/dev')
     (vendor\symfony\http-kernel\Kernel.php:584)
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:323)
  at Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()
     (vendor\symfony\http-kernel\Kernel.php:786)
  at Symfony\Component\HttpKernel\Kernel->preBoot()
     (vendor\symfony\http-kernel\Kernel.php:187)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\index.php:31)
  at require('web/index.php')
     (web\app.php:4)
```

**Reproduction**

1. Use `APP_ENV=dev` in your `.env.local`.
2. Log into the Contao back end.
3. Execute the following to clear the cache: `vendor/bin/contao-console cache:clear --no-warmup --env=dev`.
4. Refresh the Contao back end.

The aforementioned error will occur. However, the next request will be fine again.

Note: the same occurs when using `rm -rf var/cache/dev` - or a combination of both the `cache:clear` command an manually deleting the cache directory.

@m-vo since the `TemplateLocator` shows up in the stack trace, may be a somewhat related issue to #3557  ?

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3567
| Docs PR or issue | -

This PR exchanges the use of the Contao framework in `TemplateLocator#findThemeDirectories()` with a bare database connection. This way we do not need to boot the framework which unfortunately cannot be done in a non-request context.

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

File: core-bundle/src/Twig/Loader/TemplateLocator.php [hunk 1]
```diff
@@ -46,45 +45,44 @@ class TemplateLocator
...
         // table couldn't exist, yet.
         try {
-            $themes = $themeAdapter->findAll() ?? [];
+            // Note: we cannot use models or other parts of the Contao
+            //       framework here because this function will be called
+            //       during cache warmup (see #3567)
+            $themePaths = $this->connection->fetchFirstColumn('SELECT templates FROM tl_theme');
         } catch (TableNotFoundException $e) {
             return [];
         }
```
Comment (fritzmg) [inline core-bundle/src/Twig/Loader/TemplateLocator.php]: Since we have the database connection now, we could also use 

```php
$this->connection->getSchemaManager()->tablesExist(['tl_theme']);
```

instead of the try catch block which would make the code a little more self explanatory.

**Comment by aschempp** [comment]
Pretty sure we're already booting the framework on warmup to build the internal cache?

**Comment by fritzmg** [comment]
> Pretty sure we're already booting the framework on warmup to build the internal cache?

That only happens when you run `cache:warmup --env=prod`. The internal cache will not be built during a request.

**Comment by fritzmg** [comment]
Btw. booting the Contao Framework and then using a Model method will cause the `loadLanguageFile` Hook to be executed, which in turn can have other unintended consequences that may even cause `cache:warmup --env=prod` on the console to fail. For example if your Contao instance uses `madeyourday/contao-rocksolid-custom-elements` and the `system/` folder is missing (as it usually is during a deployment), the following error will occur:

```
$ vendor/bin/contao-console cache:warmup -vvv

In Files.php line 159:

  [ErrorException]
  Warning: fopen(system/tmp/7ba9a9e97772f43b365094323d38535d): failed to open stream: No such file or directory  


Exception trace:
  at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Files.php:159
 Contao\Files->fopen() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php:829
 Contao\File->fputs() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php:461
 Contao\File->write() at vendor\madeyourday\contao-rocksolid-custom-elements\src\CustomElements.php:1556
 MadeYourDay\RockSolidCustomElements\CustomElements::loadConfig() at vendor\madeyourday\contao-rocksolid-custom-elements\src\CustomElements.php:1633
 MadeYourDay\RockSolidCustomElements\CustomElements->loadLanguageFileHook() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\System.php:545
 Contao\System::loadLanguageFile() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:376
 Contao\DcaExtractor->createExtract() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:128        
 Contao\DcaExtractor->__construct() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php:150
 Contao\DcaExtractor::getInstance() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model\QueryBuilder.php:33     
 Contao\Model\QueryBuilder::find() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:1215
 Contao\Model::buildFindQuery() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:1053
 Contao\Model::find() at vendor\contao\core-bundle\src\Resources\contao\library\Contao\Model.php:967
 Contao\Model::findAll() at vendor\contao\core-bundle\src\Framework\Adapter.php:44
 Contao\CoreBundle\Framework\Adapter->__call() at vendor\contao\core-bundle\src\Twig\Loader\TemplateLocator.php:76
 Contao\CoreBundle\Twig\Loader\TemplateLocator->findThemeDirectories() at vendor\contao\core-bundle\src\Twig\Loader\ContaoFilesystemLoaderWarmer.php:55
 Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoaderWarmer->warmUp() at vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php:98
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at vendor\symfony\http-kernel\Kernel.php:584
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:323    
 Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() at vendor\symfony\http-kernel\Kernel.php:786
 Symfony\Component\HttpKernel\Kernel->preBoot() at vendor\symfony\http-kernel\Kernel.php:125
 Symfony\Component\HttpKernel\Kernel->boot() at vendor\symfony\framework-bundle\Console\Application.php:168
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at vendor\symfony\framework-bundle\Console\Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at vendor\bin\contao-console(21) : eval()'d code:36
 eval() at vendor\bin\contao-console:21
```

**Comment by aschempp** [comment]
> That only happens when you run `cache:warmup --env=prod`. The internal cache will not be built during a request.

`cache:warmup` means warming the cache to me. If you're talking about creating the container if its missing, that's not what I would call _cache warmup_. So I assume the later is a problem?

File: core-bundle/src/Twig/Loader/TemplateLocator.php [hunk 2]
```diff
@@ -46,45 +45,44 @@ class TemplateLocator
...
-        $themeAdapter = $this->framework->getAdapter(ThemeModel::class);
         $directories = [];
 
         // This code might run early during cache warmup where the 'tl_theme'
         // table couldn't exist, yet.
         try {
-            $themes = $themeAdapter->findAll() ?? [];
+            // Note: we cannot use models or other parts of the Contao
+            //       framework here because this function will be called
+            //       during cache warmup (see #3567)
```
Comment (aschempp) [inline core-bundle/src/Twig/Loader/TemplateLocator.php]: do you mean `when the container is built`?

**Comment by fritzmg** [comment]
@aschempp these errors happen during cache warmup, when the container is initialized (see stack traces).

File: core-bundle/src/Twig/Loader/TemplateLocator.php (hunk 1 above)
Comment (m-vo) [reply core-bundle/src/Twig/Loader/TemplateLocator.php]: True, but we must adjust which exceptions to catch anyway, see https://github.com/contao/contao/pull/3560/files

So I'd merge this as is and maybe reconsider this in the other PR.

**Review by leofeyer — APPROVED** [review]

File: core-bundle/src/Twig/Loader/TemplateLocator.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/src/Twig/Loader/TemplateLocator.php]: Wording adjusted in 9552d58efba07de12c887bae22068e35755c80a3.

**Comment by leofeyer** [comment]
Thank you @m-vo.
