### PR TITLE
Fix member registration issues

### LINKED ISSUE #5114: Registration with activation fails
### Affected version(s)

5.0.0-RC3

### Description

Trying to registrate as a member with an activation email (sent when registering) fails.

Steps to reproduce:
1. create a new front end module of type "Registration" (check all "Editable fields"; check the box "Send activation e-mail")
2. implement the new module in an article
3. fill in the data of the registration form in the frontend and send the form
4. click on link in activation email

result:
The contao error-screen is shown.
Error message in /var/logs:

```
[2022-08-10T18:08:00.181959+02:00] request.INFO: Matched route "tl_page.31". {"route":"tl_page.31","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.31","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.31","_route_object":{"Contao\\CoreBundle\\Routing\\Page\\PageRoute":[]}},"request_uri":"https://contao5.xyz.tld/page-registration?token=reg-9a37267d05d05e43dbf0","method":"GET"} []
[2022-08-10T18:08:00.197577+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens" at /var/www/contao5/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 119 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens at /var/www/contao5/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:119)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens at /var/www/contao5/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: HY093): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens at /var/www/contao5/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:136)"} []
```

### PR DESCRIPTION
**Pull request by fritzmg**
This PR fixes the following issues:

```
ErrorException:
Warning: Undefined array key "newsletter"

  at vendor\contao\contao\core-bundle\contao\modules\ModuleRegistration.php:467
  at Contao\ModuleRegistration->sendActivationMail(array('email' => 'foo@example.com', 'username' => 'foo@example.com', 'password' => '...', 'tstamp' => 1660153021, 'login' => true, 'dateAdded' => 1660153021, 'groups' => 'a:1:{i:0;s:1:"1";}', 'disable' => 1, 'id' => 4))
     (vendor\contao\contao\core-bundle\contao\modules\ModuleRegistration.php:380)
  at Contao\ModuleRegistration->createNewUser(array('email' => 'foo@example.com', 'username' => 'foo@example.com', 'password' => '...', 'tstamp' => 1660153021, 'login' => true, 'dateAdded' => 1660153021, 'groups' => 'a:1:{i:0;s:1:"1";}', 'disable' => 1, 'id' => 4))
     (vendor\contao\contao\core-bundle\contao\modules\ModuleRegistration.php:322)
  at Contao\ModuleRegistration->compile()
     (vendor\contao\contao\core-bundle\contao\modules\Module.php:213)
  at Contao\Module->generate()
     (vendor\contao\contao\core-bundle\contao\modules\ModuleRegistration.php:55)
```

(side note: we should probably move this to the `newsletter-bundle` at some point, if possible)

```
Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

  at vendor\doctrine\dbal\src\Driver\API\MySQL\ExceptionConverter.php:119
  at Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(object(Exception), object(Query))
     (vendor\doctrine\dbal\src\Connection.php:1822)
  at Doctrine\DBAL\Connection->handleDriverException(object(Exception), object(Query))
     (vendor\doctrine\dbal\src\Connection.php:1763)
  at Doctrine\DBAL\Connection->convertExceptionDuringQuery(object(Exception), 'SELECT * FROM tl_opt_in WHERE tl_opt_in.id IN (SELECT pid FROM tl_opt_in_related WHERE relTable=? AND relId IN(6)) ORDER BY tl_opt_in.createdOn DESC', array('tl_member', 'a:1:{i:0;i:6;}'), array())
     (vendor\doctrine\dbal\src\Connection.php:1034)
  at Doctrine\DBAL\Connection->executeQuery('SELECT * FROM tl_opt_in WHERE tl_opt_in.id IN (SELECT pid FROM tl_opt_in_related WHERE relTable=? AND relId IN(6)) ORDER BY tl_opt_in.createdOn DESC', array('tl_member', 'a:1:{i:0;i:6;}'), array())
     (vendor\contao\contao\core-bundle\contao\library\Contao\Database\Statement.php:268)
  at Contao\Database\Statement->query('', array('tl_member', 'a:1:{i:0;i:6;}'))
     (vendor\contao\contao\core-bundle\contao\library\Contao\Database\Statement.php:222)
  at Contao\Database\Statement->execute('tl_member', array(6))
     (vendor\contao\contao\core-bundle\contao\models\OptInModel.php:105)
  at Contao\OptInModel::findByRelatedTableAndIds('tl_member', array(6))
     (vendor\contao\contao\core-bundle\src\Framework\Adapter.php:40)
  at Contao\CoreBundle\Framework\Adapter->__call('findByRelatedTableAndIds', array('tl_member', array(6)))
     (vendor\contao\contao\core-bundle\src\OptIn\OptInToken.php:66)
  at Contao\CoreBundle\OptIn\OptInToken->confirm()
     (vendor\contao\contao\core-bundle\contao\modules\ModuleRegistration.php:534)
```

Fixes #5114

### CODE REVIEW

File: core-bundle/contao/modules/ModuleRegistration.php [hunk 1]
```diff
@@ -464,7 +464,7 @@ protected function sendActivationMail($arrData)
 			// Make sure newsletter is an array
 			if (!\is_array($arrData['newsletter'] ?? null))
 			{
-				if ($arrData['newsletter'])
+				if ($arrData['newsletter'] ?? null)
```
Comment (ausi) [inline core-bundle/contao/modules/ModuleRegistration.php]: Those 11 lines could probably be reduced to the following:

```php
// Make sure newsletter is an array
$arrData['newsletter'] = (array) ($arrData['newsletter'] ?? null);
```

**Review by ausi — DISMISSED** [review]

**Comment by fritzmg** [comment]
> (side note: we should probably move this to the `newsletter-bundle` at some point, if possible)

➡️ https://github.com/contao/contao/pull/5116

**Review by ausi — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
