### PR TITLE
Fix recursive paste permissions

### LINKED ISSUE #8264: `Paste into` operations do not work into the duplicated page
### Affected version(s)

5.5

### Description

If you try to duplicate a page in Contao 5.5 and want to insert it below the page to be duplicated, the button is disabled.

1.
Image

2.
Image

Edit: It works in 5.3.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/8264. The issue was is that `$blnCircularReference` is true for any clipboard mode (copy or paste), because it "represents" whether the current ID is a child of the current clipboard, not whether pasting it would "lead to a circular problem". As @zoglo noticed in the issue, the cut-check was missing.

This also fixes two cases of incorrectly checking the clipboard if multiple IDs are copied/moved. Both cases are easily reproducable in the online demo:

 1. when limiting the tree to a subnode, and using edit-all to move the root node, the paste buttons incorrectly enabled

    https://github.com/user-attachments/assets/377e496f-a9ac-477d-b06c-546dcdf56386

2. when copying multiple records and ajax-loading a sub-sub-part of the tree, the paste buttons are incorrectly enabled

    https://github.com/user-attachments/assets/b7fb354c-1f75-4a80-9449-db9342a24ba5

These bugs likely also happen in Contao 5.3, but the fix would be completely different and not sure they are worth it.

### CODE REVIEW

File: core-bundle/src/DataContainer/ClipboardManager.php [hunk 1]
```diff
@@ -113,6 +118,40 @@ public function clearAll(): void
         $session->set(self::SESSION_KEY, []);
     }
 
+    public function isCutMode(string $table): bool
```
Comment (leofeyer) [inline core-bundle/src/DataContainer/ClipboardManager.php:121]:
```suggestion
    public function isModeCut(string $table): bool
```

So it is consistent with the `MODE_CUT` constant. WDYT?

File: core-bundle/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -3802,10 +3802,11 @@ protected function treeView()
 		if (!empty($topMostRootIds))
 		{
 			static::preloadCurrentRecords($topMostRootIds, $table);
+			$clipboardManager = System::getContainer()->get('contao.data_container.clipboard_manager');
 
 			for ($i=0, $c=\count($topMostRootIds); $i<$c; $i++)
 			{
-				$tree .= $this->generateTree($table, $topMostRootIds[$i], array('p'=>($topMostRootIds[$i - 1] ?? null), 'n'=>($topMostRootIds[$i + 1] ?? null)), $blnHasSorting, -16, $blnClipboard ? $arrClipboard : false, ($GLOBALS['TL_DCA'][$this->strTable]['list']['sorting']['mode'] ?? null) == self::MODE_TREE && $blnClipboard && $topMostRootIds[$i] == $arrClipboard['id'], false, false, $arrFound);
+				$tree .= $this->generateTree($table, $topMostRootIds[$i], array('p'=>($topMostRootIds[$i - 1] ?? null), 'n'=>($topMostRootIds[$i + 1] ?? null)), $blnHasSorting, -16, $blnClipboard ? $arrClipboard : false, $clipboardManager->isCircularReference($table, $topMostRootIds[$i]), false, false, $arrFound);
```
Comment (leofeyer) [inline core-bundle/contao/drivers/DC_Table.php]: The original line uses `$this->strTable` but you use `$table` now. Is this intended?

File: core-bundle/contao/drivers/DC_Table.php [hunk 3]
```diff
@@ -3974,12 +3975,13 @@ public function ajaxTreeView($id, $level)
...
 
-		$arrClipboard = System::getContainer()->get('contao.data_container.clipboard_manager')->get($this->strTable);
+		$clipboardManager = System::getContainer()->get('contao.data_container.clipboard_manager');
+		$arrClipboard = $clipboardManager->get($this->strTable);
 		$blnClipboard = null !== $arrClipboard;
 
 		for ($i=0, $c=\count($arrIds); $i<$c; $i++)
 		{
-			$return .= ' ' . trim($this->generateTree($table, $arrIds[$i], array('p'=>($arrIds[$i - 1] ?? null), 'n'=>($arrIds[$i + 1] ?? null)), $hasSorting, $margin, $blnClipboard ? $arrClipboard : false, $arrClipboard !== null && ($id == $arrClipboard['id'] || (\is_array($arrClipboard['id']) && \in_array($id, $arrClipboard['id'])) || (!$blnPtable && !\is_array($arrClipboard['id']) && \in_array($id, $db->getChildRecords($arrClipboard['id'], $table)))), $blnProtected));
+			$return .= ' ' . trim($this->generateTree($table, $arrIds[$i], array('p'=>($arrIds[$i - 1] ?? null), 'n'=>($arrIds[$i + 1] ?? null)), $hasSorting, $margin, $blnClipboard ? $arrClipboard : false, $clipboardManager->isCircularReference($this->strTable, $arrIds[$i], !$blnPtable), $blnProtected));
```
Comment (leofeyer) [inline core-bundle/contao/drivers/DC_Table.php:3984]: Here the original line uses `$table` but you use `$this->strTable` now (also see my comment above).

File: core-bundle/contao/drivers/DC_Table.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php]: ~does not matter here. `$table = $this->strTable;` is the first line of this method. I would keep it like this since we use `$table` everywhere else.~

File: core-bundle/contao/drivers/DC_Table.php (hunk 3 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:3984]: Here it does matter, changed in a43cf98fb5bcea297098350592d6c6d69003275e

File: core-bundle/contao/drivers/DC_Table.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php]: I was wrong, it does matter actually. Fixed in 911f80111916be5444a20fbc19ddc5e3c3a3f11d

File: core-bundle/contao/drivers/DC_Table.php (hunk 3 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:3984]: Changed again in 22003365076c5ae768bc1f014697107d0415c591 😂 

- for `tl_article` (extended tree mode), `$table` contains `tl_page` and `$this->strTable` is `tl_article`. However, the clipboard always refers to the current table (`tl_article`), and checking for recursion on `tl_page` with the clipboard having an ID of `tl_article` makes little sense to me.

File: core-bundle/src/DataContainer/ClipboardManager.php (hunk 1 above)
Comment (aschempp) [reply core-bundle/src/DataContainer/ClipboardManager.php:121]: To me that is not fluent to read. The constants are grouped by prefix, therefore the "incorrect" wording, but for method names I try to keep them readable.

File: core-bundle/contao/drivers/DC_Table.php (hunk 3 above)
Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php:3984]: No, sorry, this cannot work. `$arrIds` also contains the IDs of `$table` and not of `$this->strTable`, so now you provide two arguments that refer to different tables.

**Review by leofeyer — CHANGES_REQUESTED** [review]
Besides the [one change](https://github.com/contao/contao/pull/8277/files#r2039281756) that is clearly wrong to me, there seems to be another problem with the `isCircularReference()` method:

### Contao 5.3





### This PR

**Comment by aschempp** [comment]
@leofeyer did you duplicate a record or move it?

**Comment by leofeyer** [comment]
Move. I clicked the cut icon.

File: core-bundle/contao/drivers/DC_Table.php (hunk 3 above)
Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:3984]: than's true in theory, but stupid in practice 😂 
- when rendering `tl_page` (a tree view), it does not matter since `$table === $this->strTable`
- when rendering `tl_article` (an extended tree), there can never be a circular reference because the clipboard IDs are not nested. Passing `$this->strTable` will cause the method to fail in checking for `MODE_TREE` and return false before actually checking the given ID

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php:3984]: > and return false before actually checking the given ID

Where exactly should this be? The method returns `string` and there is only one early return right at the beginning of the method.

Comment (aschempp) [reply core-bundle/contao/drivers/DC_Table.php:3984]: https://github.com/contao/contao/pull/8277/files#diff-3fd9ec2f732d3dbf6a03532469b98c26c49a1fa9a13ff4f2739d829b49f9dcddR132

Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php:3984]: As discussed in the call, the changes are correct 🎉

**Comment by leofeyer** [comment]
Thank you @aschempp.
