### PR TITLE
Fix login redirect and session usage

### LINKED ISSUE #7585: Session gets started when accessing /contao
### Affected version(s)

5.3, 4.13

### Description

Opening https://demo.contao.org/contao/ sets a Session Cookie and CSRF Cookie before the Login. We Night want to fix that?

/cc @fritzmg

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7585 

The first issue is fixed by checking whether the request is the `contao_backend` route _without_ any parameters. If that is the case, the `redirect` parameter will be ignored for the `contao_backend_login` route and no URL signing will take place - thus `/contao` will simply redirect to `/contao/login`.

The second issue is fixed by removing the "target path" session parameter, that Symfony always sets for non-stateless firewalls. However, since our `contao_backend_login` controller will simply redirect based on the `redirect` parameter this session variable can be removed - which in turn will not send a session cookie, as the session will then be empty again.

### CODE REVIEW

File: core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php [hunk 1]
```diff
@@ -50,13 +53,31 @@ public function start(Request $request, ?AuthenticationException $authException
...
+        // No URL signing required if we do not have any parameters
+        if ([] !== $loginParams) {
+            $location = $this->uriSigner->sign($location);
+        }
+
+        // Our back end login controller will redirect based on the 'redirect' parameter,
+        // ignoring Symfony's target path session value. Thus we remove the session variable
+        // here in order to not send an unnecessary session cookie.
+        if ($request->hasSession()) {
+            $this->removeTargetPath($request->getSession(), 'contao_backend');
```
Comment (aschempp) [inline core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php:79]: could you point to the place where this session value is added? I'd like to understand why would that be the case on this page but not "everywhere"?

Comment (fritzmg) [reply core-bundle/src/Security/Authentication/AuthenticationEntryPoint.php:79]: It is set [here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L206-L208) when accessing the `contao_backend` route without being logged in.

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
