### PR TITLE
Fix an "access array offset on value of type null" error in the help wizard

### LINKED ISSUE #5239: Help wizard of "Image size" dropdown doesn't take into account predefined image sizes
### Affected version(s)

4.13

### Description

This is 3 small issues in one:

1. The docs never mention that text for the wizard is fetched from `MSC` domain, not from `translations/image_sizes.en.yml`. This belongs probably in contao/docs, I just mention it here for completeness.

2. In `BackendHelp.php` controller, array of predefined options comes in structured differently, than core options, and the label is being used instead of key, here:

https://github.com/contao/contao/blob/4fb1c1555fcac428cb42e66a22c8236dd3356ad0/core-bundle/src/Resources/contao/controllers/BackendHelp.php#L104-L107

3. In the code above, `null` is being stored as a row, which makes `be_help.html5` throw a warning in php 8:

```
ErrorException:
Warning: Trying to access array offset on value of type null

  at vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_help.html5:42
```

In production or in php 7.4, it just outputs empty rows:

image

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5239

This fixes the `Trying to access array offset on value of type null` error when there is no translation for a predefined image size and it also allows using the the ID as translation key.

```php
// Using the generated name (status quo)
$GLOBALS['TL_LANG']['MSC']['video_placeholder (1280x)'] = ['Foo', 'Bar'];

// Using the ID of the predefined image size (new)
$GLOBALS['TL_LANG']['MSC']['_video_placeholder'] = ['Foo', 'Bar'];
```

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by aschempp** [comment]
Why would `BackendHelp` know about `image_sizes`???

**Comment by fritzmg** [comment]
@aschempp what do you mean? This is about the help overlay for image sizes.

**Comment by leofeyer** [comment]
How else am I supposed to add custom logic for predefined image sizes?

**Comment by aschempp** [comment]
> @aschempp what do you mean? This is about the help overlay for image sizes.

no, the `BackendHelp` class is generic to any help popup.

> How else am I supposed to add custom logic for predefined image sizes?

How would any extension solve the same problem?

There should be a generic approach. Maybe reformat the `references` using an (onload) callback to set the correct data. I haven't looked into the details of this case, but having a `image_sizes` handling in `BackendHelp` can't be correct.

**Comment by fritzmg** [comment]
> no, the `BackendHelp` class is generic to any help popup.

Yes, it is used for any help popup - including the one for image sizes.

**Comment by leofeyer** [comment]
Yes, we could maybe make it more generic, but then we would loose backwards compatibility. And I think the latter is more important.

File: core-bundle/src/Resources/contao/controllers/BackendHelp.php [hunk 1]
```diff
@@ -101,9 +101,18 @@ public function run()
...
+						if ($key == 'image_sizes')
+						{
+							// Allow using the ID (e.g. "_video_placeholder") as well as the generated
+							// name (e.g. "video_placeholder (1280x)") as key (see #5239)
+							$rows[] = $arrData['reference'][$opt] ?? $arrData['reference'][$id] ?? array($opt, '');
+						}
+						else
+						{
+							$rows[] = $arrData['reference'][$opt] ?? null;
+						}
```
Comment (aschempp) [inline core-bundle/src/Resources/contao/controllers/BackendHelp.php]:
```suggestion
						$rows[] = $arrData['reference'][$opt] ?? $arrData['reference'][$id] ?? array($opt, '');
```

**Review by aschempp — CHANGES_REQUESTED** [review]
I looked into this in detail. The problem is that we have a multidimensional array, where some of the values are translated already and some are not. I think this is a perfectly valid use case not limted to image sizes, so we should generally support this. I don't see any problem enabling that for any help wizard.

File: core-bundle/src/Resources/contao/controllers/BackendHelp.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: Except we need `null` as default for non image sizes and we only need `$arrData['reference'][$opt]` as BC layer for image sizes and not in general.

Comment (aschempp) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: why not in general? Why would it not show additional details for *my* help wizard if I have multidimensional options with keys and values?

Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: Because `$arrData['reference'][$id]` is what we want to use in general.

Comment (aschempp) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: Not sure what you mean. In the default `else` condition, `$arrData['reference'][$id]` would not be used at all?

---

## Here's an example

**References:**
```php
[
    'foo' => ['Foo Title', 'Foo explanation'],
    'bar' => ['Bar Headline', 'Bar explanation'],
]
```

**This `options` array is supported:**
```php
[
    'foo',
    'bar',
]
```

**This `options` does not work right now, but it would be with the changes:**
```php
[
    'foo' => 'Foo label',
    'bar' => 'Bar label',
]
```

Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: But this is not how the predefined images array looks like. 🤷‍♂️

Comment (aschempp) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: It does… at least to some extent. Here'swhat predefined images looks like for me (I'm sure you'll see the similarities):

```php
[
	'image_sizes' => [
		'_foo' => 'Foo label',
		'_bar' => 'Bar label',
	],
	'Contao Official Demo' => [
		1 => 'asdf (x)'
	],
	'relative' => [
		0 => 'proportional',
		1 => 'box'
	],
	'exact' => [
		0 => 'crop',
		1 => 'left_top',
		2 => 'center_top',
		3 => 'right_top',
		4 => 'left_center',
		5 => 'center_center',
		6 => 'right_center',
		7 => 'left_bottom',
		8 => 'center_bottom',
		9 => 'right_bottom',
	],
];
```

If you see a problem with the numeric keys, we could also check for `array_is_associative` or `is_number` on the `$id`.

Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: When we check for a translation, we only want to check `$arrData['reference']['_foo']` in the future. However, right now, we check for `$arrData['reference']['Foo label']`, which we cannot stop doing until Contao 6 (BC).

Therefore, if the key is `image_sizes`, we have to check

```php
$arrData['reference']['Foo label'] ?? $arrData['reference']['_foo'] ?? ['Foo label', '']
```

but in all other (generic) cases, we only want to check

```php
$arrData['reference']['_foo'] ?? ['Foo label', '']
```

And that is why the `BackendHelp` class must know about `image_sizes` as long as the BC layer remains in place.

Comment (ausi) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: So in the future the code should look like this?

```php
if (array_is_list($options))
{
	$rows[] = $arrData['reference'][$opt] ?? null;
}
else
{
	$rows[] = $arrData['reference'][$id] ?? array($opt, '');
}
```

As we IMO need the `array_is_list()` check to differentiate between `$arrData['reference']['Foo label']` and `$arrData['reference']['_foo']`

Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: Yes, but with the BC layer:

```php
if (array_is_list($options))
{
	$rows[] = $arrData['reference'][$opt] ?? null;
}
else
{
	if ($key == 'image_sizes' && isset($arrData['reference'][$opt]))
	{
		trigger_deprecation('contao/core-bundle', '5.3', 'Using … has been deprecated …');

		$rows[] = $arrData['reference'][$opt];
	}
	else
	{
		$rows[] = $arrData['reference'][$id] ?? array($opt, '');
	}
}
```

Of course that would also work without the `$key == 'image_sizes'` check, I‘m just not sure if there would be side-effects.

Comment (ausi) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: I’d use your version without the `image_sizes` check then (as others may already have used it that way for other options), but only if `$arrData['reference'][$id]` is not set (to make it the preferred one).

```php
if (array_is_list($option))
{
	$rows[] = $arrData['reference'][$opt] ?? null;
}
else
{
	if (isset($arrData['reference'][$opt]) && !isset($arrData['reference'][$id]))
	{
		trigger_deprecation('contao/core-bundle', '5.3', 'Using … has been deprecated …');

		$rows[] = $arrData['reference'][$opt];
	}
	else
	{
		$rows[] = $arrData['reference'][$id] ?? array($opt, '');
	}
}
```

Comment (leofeyer) [reply core-bundle/src/Resources/contao/controllers/BackendHelp.php]: I have decided to only fix the issue in Contao 4.13 because there is more that needs to be changed to properly handle image sizes. I will create a follow-up PR for Contao 5.3.

**Review by ausi — APPROVED** [review]
