### PR TITLE
Fix the base path for canonical URLs

### LINKED ISSUE #7606: Canonical URLs are incorrectly generated
### Affected version(s)

4.13.49

### Description

I have a multilingual website with several page trees. If I now manually select another page from another page tree in the page structure, the URL is generated incorrectly.
The prefix is also added to the URL. (See screenshot)

screen-20241007_sURaup2h

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7606

### CODE REVIEW

File: core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php [hunk 1]
```diff
@@ -94,7 +94,7 @@ public function createContaoWebpageResponseContext(PageModel $pageModel): Respon
                     throw new \RuntimeException('The request stack did not contain a request');
                 }
 
-                $url = UrlUtil::makeAbsolute($url, $request->getUri());
+                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().'/'.$request->getBasePath());
```
Comment (ausi) [inline core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php]:
```suggestion
                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().$request->getBasePath().'/');
```

**Review by ausi — CHANGES_REQUESTED** [review]

**Review by ausi — APPROVED** [review]

File: core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php [hunk 2]
```diff
@@ -94,7 +94,7 @@ public function createContaoWebpageResponseContext(PageModel $pageModel): Respon
                     throw new \RuntimeException('The request stack did not contain a request');
                 }
 
-                $url = UrlUtil::makeAbsolute($url, $request->getUri());
+                $url = UrlUtil::makeAbsolute($url, $request->getSchemeAndHttpHost().$request->getBasePath().'/');
```
Comment (aschempp) [inline core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]:
```suggestion
                $url = UrlUtil::makeAbsolute($url, $request->getUriForPath('/'));
```

**Review by aschempp — CHANGES_REQUESTED** [review]

File: core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php (hunk 2 above)
Comment (ausi) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: This is incorrect, we have to use the `basePath`, not the `baseUrl`

Comment (aschempp) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]:
```
public function getUriForPath(string $path): string
{
    return $this->getSchemeAndHttpHost().$this->getBaseUrl().$path;
}
```

Comment (aschempp) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: I don't think that's true. We don't want `getUri` because that contains the current path. But `getUriForPath` does not, and since these are page links we do want the entry point script (e.g. `preview.php`) to be in the links.

Comment (ausi) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: The entry point is already included in the provided `$url` so you would end up with `https://example.com/preview.php/preview.php/foo.html`

Comment (ausi) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: To give this more context: Non-deprecated sources for the `$url` always are at least path-absolute, so for them `basePath` vs `baseUrl` does not matter. But legacy or third party insert tags might return a URL that is relative to the `<base href` and so we must use the same base for these URLs as we use in the deprecated `<base href`. This is `Environment::get('base')` which internally uses `->getSchemeAndHttpHost().$request->getBasePath().'/'`

Comment (fritzmg) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: I can confirm that using `$request->getUriForPath('/')` for the base path would result in a canonical URL like

```
https://example.com/preview.php/preview.php/de/foobar
``` 

in case the stored `canonicalLink` (directly or indirectly via insert tag) is not at least path absolute.

Comment (aschempp) [reply core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php:97]: Thanks for the clarification 🙃

**Review by aschempp — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
