### PR TITLE
Nested content elements

### LINKED ISSUE #391: Nested content elements
Hello there,

I struggle with the possibilities to structure content in Contao once in a while. Pages, articles an content elements are already great and give us many possibilities to structure our content. However, many times I am missing another level of detail, namely grouping or nesting content elements. 

This is partly implemented with the wrapper content elements of course, but they feel more like a workaround rather than a decent solution (for some cases). So I am looking for a more versatile and editor-friendly way to have nested content elements. I fiddled with the online demo and dev tools to illustrate my ideas: 

sketch_dc_parent_view

sketch_dc_edit_view

Editing nested content elements (2nd screenshot) could then open in a modal window (issues ahead, see below).

[As I read in a fairly old issue](https://github.com/contao/core/issues/1247#issuecomment-374533143) the core team seems to have thought about this as well. I would like to hear what your ideas are?

I guess, wrapper elements were kind of a compromise to achieve element grouping within the constraints of the given Contao framework back when they where implemented. I also know that my sketched idea fails right away, when you would like to nest nested content elements, which is a Must requirement for a future solution in my opinion. 

 I am really looking forward to comments in any direction :-) Please treat the screenshots as what they were intended to be: As basic sketches that are totally not thought through ;-)

Cheerio

### PR DESCRIPTION
**Pull request by ausi**
Fixes https://github.com/contao/contao/issues/391
Alternative to https://github.com/contao/contao/pull/5814 (without the support for slots)

### CODE REVIEW

File: core-bundle/contao/dca/tl_content.php [hunk 1]
```diff
@@ -1480,6 +1487,23 @@ public function disableButton($row, $href, $label, $title, $icon, $attributes)
...
+	 * @param string $label
+	 * @param string $title
+	 * @param string $icon
+	 * @param string $attributes
+	 *
+	 * @return string
+	 */
+	public function editChildren($row, $href, $label, $title, $icon, $attributes)
+	{
+		return System::getContainer()->get('security.helper')->isGranted(ContaoCorePermissions::USER_CAN_ACCESS_ELEMENT_TYPE, $row['type']) ? '<a href="' . $this->addToUrl($href . '&amp;id=' . $row['id']) . '" title="' . StringUtil::specialchars($title) . '"' . $attributes . '>' . Image::getHtml($icon, $label) . '</a> ' : Image::getHtml(preg_replace('/\.svg$/i', '_.svg', $icon)) . ' ';
```
Comment (leofeyer) [inline core-bundle/contao/dca/tl_content.php]: We need to check if the content element supports nesting here. Any idea how to accomplish that?

Comment (ausi) [reply core-bundle/contao/dca/tl_content.php]: I guess we need to ask the fragment registry? But I’m not sure...

**Comment by leofeyer** [comment]
I hit the first hurdle.



The ID in the URL is now `1449`. It is the ID of the element I want to copy and paste inside the wrapper element.



But in order to get into the wrapper element, I have to click the "edit children" link, which sets the ID to `1450`.



And when I paste the element, it does not duplicate ID `1449` but ID `1450` (the wrapper element itself).

**Possible solutions**

1. Always use the clipboard (as we already do in "edit multiple" mode).
2. Add a third URL parameter besides `id=` and `pid=`, which stores the ID of the source element.

However, both solutions would be a behavior change. WDYT?

**Comment by ausi** [comment]
> Always use the clipboard (as we already do in "edit multiple" mode).

To me it looks like we are using the clipboard already, because I can paste the duplicated element into a different article.

I think it needs to work the same way for this case as I also want to paste into a different “parent”.

If I navigate to a different article the URL shows only the ID of the article: `?do=article&table=tl_content&id=1`.

So the „edit child elements“ button in your case should link to `?do=article&table=tl_content&ptable=tl_content&id=1450`. The rest would then work already I think.

**Comment by leofeyer** [comment]
I‘ll check this tomorrow. Thank you. 😊

File: core-bundle/contao/dca/tl_content.php (hunk 1 above)
Comment (leofeyer) [reply core-bundle/contao/dca/tl_content.php]: It would work like this: 1f4b3daa04b11968d0b2f9f3bf39a0c9d29b449e

But if that is correct, the method should not be called `isNested()` but `supportsNesting()` or something alike, shouldn‘t it?

Comment (ausi) [reply core-bundle/contao/dca/tl_content.php]: You are right, `supportsNesting()` is a way better name for that method 👍

**Comment by leofeyer** [comment]
This one is read for review I think. 🥳 

You can try it by converting the content slider of the official demo to the new slider element:

File: core-bundle/contao/drivers/DC_Table.php [hunk 2]
```diff
@@ -1063,7 +1063,7 @@ protected function copyChilds($table, $insertID, $id, $parentId)
 		$ctable = $GLOBALS['TL_DCA'][$table]['config']['ctable'] ?? array();
 		$db = Database::getInstance();
 
-		if (!($GLOBALS['TL_DCA'][$table]['config']['ptable'] ?? null) && Input::get('childs') && $db->fieldExists('pid', $table) && $db->fieldExists('sorting', $table))
+		if (Input::get('childs') && $db->fieldExists('pid', $table) && $db->fieldExists('sorting', $table))
```
Comment (ausi) [inline core-bundle/contao/drivers/DC_Table.php:1066]: Could it be, that instead of this change that we need to set `$GLOBALS['TL_DCA']['tl_content']['config']['ctable']` to `array('tl_content')` in *contao/dca/tl_content.php* ?

**Review by aschempp — COMMENTED** [review]
Things I noticed in my quick review:
 1. I'm missing the "save & go to children" button when editing the new slider element
 2. it appears a content elements can define its allowed children. I'm not sure this is a good idea, there seems to be no way to extend this. Hardcoding this would only make sense to me if there is a specific element for withing e.g. the slider, but then that element must not be available as a general content element. I think this concept needs to be re-thought, maybe something similar like picker scopes where one can add a picker to a scope but each field can define its custom scope if necessary.
 3. What is the reason the nested content elements are passed around in the `ContentElementReference`? Shouldn't the (abstract) content element controller be responsible for knowing, finding and rendering its child elements? Also keep in mind that our fragments can use differents renderers (e.g. ESI), so this must work if the slider uses ESI, or any of its children use ESI fragments).
 4. are we intentionally support nesting of front end modules? because our `RegisterFragmentsPass` allows this for both cases, and the fragment compositor will "have" nested modules then.
 5. also, why do we need the fragment compositor at all? Can't this be part of the fragment registry (where we already have a fragment config, and we can (potentially, at some point) ask our fragment e.g. if a subelement is allowed)?
 6. We agreed not to add new methods to the DCA classes, so `tl_content:copyElement()` should be a listener instead. It should also use the new button callback object to not have to generated the HTML on its own.

File: core-bundle/contao/drivers/DC_Table.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/contao/drivers/DC_Table.php:1066]: No, I think pointing both `ptable` and `ctable` to the same table is dangerous and will cause problems.

Can you explain why you think that we need the `!($GLOBALS['TL_DCA'][$table]['config']['ptable'] ?? null)` check? It seems like an unnecessary limitation to me. Any table with a `pid` and a `sorting` column can be copied with children, regardless of whether it has a parent table or not.

**Comment by leofeyer** [comment]
1. Good catch, I will add this.

2. This is optional and not meant to be extendable as far as I understood. General content elements such as the slider do not limit the types of content elements that can be nested.

3. IDK.

4. We most certainly do not.

5. IDK.

**Comment by ausi** [comment]
Switched from `{{ render() }}` to `{{ content_element() }}` in 83ffa1551f1c0e5a49fbbf0947dbe9afab592d67.

Added support for literal nested elements in c5574225d1395014951af21f1b31a5b0c863e9b7.  
You can now use something like this in Twig:

```twig
{{ content_element('slider', {
    headline: { value: 'Slider Überschrift', unit: 'h2' },
    nested_elements: [
        { type: 'text', text: 'Lorem Ipsum...' }
    ]
}) }}
```

File: core-bundle/contao/library/Contao/Controller.php [hunk 3]
```diff
@@ -514,13 +515,27 @@ public static function getArticle($varId, $blnMultiMode=false, $blnIsInsertTag=f
...
+		if ($intId instanceof ContentElementReference)
+		{
+			if (\func_num_args() > 1)
+			{
+				throw new \InvalidArgumentException('Passing a column name is not supported when using a ContentElementReference.');
+			}
+
+			$contentElementReference = $intId;
+			$strColumn = $contentElementReference->getSection();
+			$intId = $contentElementReference->getContentModel();
```
Comment (leofeyer) [inline core-bundle/contao/library/Contao/Controller.php:536]:
```suggestion
			$strColumn = $contentElementReference->attributes['section'];
			$intId = $contentElementReference->attributes['contentModel'];
```

`ControllerReference::$attributes` is a public property, so we could use it directly and remove the getters in our `ContentElementReference` class again. WDYT?

File: test-case/src/ContaoTestCase.php [hunk 4]
```diff
@@ -133,10 +133,15 @@ protected function mockContaoFramework(array $adapters = [], array $instances =
...
+        $instances = array_map(
+            static fn ($instance): \Closure => $instance instanceof \Closure ? $instance : static fn () => $instance,
+            $instances,
+        );
+
         if ($instances) {
             $framework
                 ->method('createInstance')
-                ->willReturnCallback(static fn (string $key): mixed => $instances[$key] ?? null)
+                ->willReturnCallback(static fn (string $key): mixed => ($instances[$key] ?? null)?->__invoke())
```
Comment (leofeyer) [inline test-case/src/ContaoTestCase.php]:
```suggestion
                ->willReturnCallback(
                    static function (string $key): mixed {
                        if (!isset($instances[$key])) {
                            return null;
                        }

                        if ($instances[$key] instanceof \Closure) {
                            return $instances[$key]();
                        }
                        
                        return $instances[$key];
                    }
                )
```

This is easier to understand and does not require to convert all instances to closures in lines 136–139.

Comment (leofeyer) [reply test-case/src/ContaoTestCase.php]: Changed in 9d625d5ab5c82c5bb1b9e24497d399abd86f19c9.

**Review by leofeyer — APPROVED** [review]

**Review by ausi — COMMENTED** [review]
✅

**Comment by leofeyer** [comment]
Thank you @ausi.

File: core-bundle/contao/drivers/DC_Table.php (hunk 2 above)
Comment (ausi) [reply core-bundle/contao/drivers/DC_Table.php:1066]: Looks like this caused a bug: #7422 
As we have `tl_content` as `ctable` now in https://github.com/contao/contao/blob/0b009b91b4186a32e91ca5f762df5b6a6e4ee375/core-bundle/contao/dca/tl_content.php#L37 should we revert this change?
