### PR TITLE
Fix relative redirects

### LINKED ISSUE #6179: Page Type "External Redirect" doesn't return correct url in folder like alias
### Affected version(s)

4.13

### Description

Hi,

I want to have a page with folder like alias such as "https://example.com/folder/page" redirected to another page like "https://example.com/news/news1".

So I create a new Page with type "External Redirect" with folder like alias "folder/page". Then select a "Link target" in "Page Picker" such as "{{news_url:1}}".

What we expect is:
https://example.com/folder/page  => https://example.com/news/news1

but this happens: 
https://example.com/folder/page => https://example.com/folder/news/news1

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #6179, replaces #3468

This PR fixes #6179 and also replaces #3468:

* Our `Controller::redirect` method already makes the URLs always absolute.
* I could not find any other instance of creating a `RedirectResponse` where a purely relative URL would be used. <sup>1</sup>

<sup>1</sup> except in some edge cases like `PageLogout` if the mandatory `jumpTo` page does not exist for example.

### CODE REVIEW

**Review by ausi — APPROVED** [review]

File: core-bundle/src/Resources/contao/pages/PageRedirect.php [hunk 1]
```diff
@@ -31,7 +32,9 @@ public function generate($objPage)
 
 		$this->prepare($objPage);
 
-		$this->redirect(System::getContainer()->get('contao.insert_tag.parser')->replaceInline($objPage->url), $this->getRedirectStatusCode($objPage));
+		$url = UrlUtil::makeAbsolute(System::getContainer()->get('contao.insert_tag.parser')->replaceInline($objPage->url), Environment::get('path'));
```
Comment (ausi) [inline core-bundle/src/Resources/contao/pages/PageRedirect.php]: I think this needs to be one of:
```suggestion
		$url = UrlUtil::makeAbsolute(System::getContainer()->get('contao.insert_tag.parser')->replaceInline($objPage->url), Environment::get('base'));
```

```suggestion
		$url = UrlUtil::makeAbsolute(System::getContainer()->get('contao.insert_tag.parser')->replaceInline($objPage->url), Environment::get('path') . '/');
```

**Review by ausi — CHANGES_REQUESTED** [review]

File: core-bundle/src/Resources/contao/pages/PageRedirect.php (hunk 1 above)
Comment (fritzmg) [reply core-bundle/src/Resources/contao/pages/PageRedirect.php]: You are right. While `UrlUtil::makeAbsolute` creates an absolute path anyway if `Environment::get('path')` is an empty string here:

https://github.com/contao/contao/blob/2082fff2c24229caf89dbfcd5afd89ffcb4fa33d/core-bundle/src/Util/UrlUtil.php#L38

the absolute URL will be wrong if `Environment::get('path')` is something like `/c413/public`.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
