### PR TITLE
Handle insert tag flags in the picker

### LINKED ISSUE #3366: |urlattr breaks the picker
**Affected version(s)**

Contao 4.9+

**Description**

TinyMCE → Insert/edit link → pick any page → `{{link_url::48}}`

Now save → the insert tag is converted to `{{link_url::48|urlattr}}`

Click "Insert/edit link" again → the page is no longer selected, because the picker fails to extract the ID from the insert tag.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3366
| Docs PR or issue | -

### CODE REVIEW

File: core-bundle/src/Picker/AbstractInsertTagPickerProvider.php [hunk 1]
```diff
@@ -44,7 +44,19 @@ protected function getInsertTagChunks(PickerConfig $config): array
...
     protected function getInsertTagValue(PickerConfig $config)
     {
-        return str_replace($this->getInsertTagChunks($config), '', $config->getValue());
+        return explode('|', str_replace($this->getInsertTagChunks($config), '', $config->getValue()), 2)[0];
+    }
+
+    /**
+     * Returns the insert tag flags.
+     */
+    protected function getInsertTagFlags(PickerConfig $config)
```
Comment (ausi) [inline core-bundle/src/Picker/AbstractInsertTagPickerProvider.php]:
```suggestion
    protected function getInsertTagFlags(PickerConfig $config): array
```

**Review by ausi — APPROVED** [review]
