### PR TITLE
Introduce `TemplateTrait` to fix missing method in `Widget`

### LINKED ISSUE #6722: CSP breaks the form fields
### Affected version(s)

5.3

### Description

The new CSP features seem to break form fields in the front end.

> Attempted to call an undefined method named "attr" of class "Contao\FormCaptcha".

https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/forms/form_captcha.html5#L25

This is probably because widget templates do not extend from `Template` but from `Widget`.

### PR DESCRIPTION
**Pull request by fritzmg**
This PR fixes the following things:

* Added the missing template methods to `Contao\Widget` (fixes #6722) by introducing a new `TemplateTrait` that contains all public member methods that are independent from the `Template` abstract class.
* Fixing that also revealed another issue: two of our (front end) templates use hard coded `style` attributes by default, which will cause a CSP violation. This is fixed by adding hashes for these inline styles. 

_Note:_ for CSP Level 3 capable browsers this also requires the `unsafe-hashes` source to be present in the directive, otherwise CSP hashes do not work for inline style _attributes_.

_Note:_ many of our PHP front end templates also still have

```php
<?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>
```

in them, but I deliberately disregarded those, as these are mostly there only for BC.

### CODE REVIEW

File: core-bundle/contao/library/Contao/TemplateTrait.php [hunk 1]
```diff
@@ -0,0 +1,266 @@
...
+
+use Contao\CoreBundle\Routing\ResponseContext\Csp\CspHandler;
+use Contao\CoreBundle\Routing\ResponseContext\JsonLd\JsonLdManager;
+use Contao\CoreBundle\String\HtmlAttributes;
+use Contao\Image\ImageInterface;
+use Contao\Image\PictureConfiguration;
+use Spatie\SchemaOrg\Graph;
+
+/**
+ * Provides template methods.
```
Comment (m-vo) [inline core-bundle/contao/library/Contao/TemplateTrait.php:21]: Changes to the legacy code should IMHO be internal if possible. 🙂

```suggestion
 * Provides template methods.
 *
 * @internal
```

File: core-bundle/contao/templates/modules/mod_two_factor.html5 [hunk 2]
```diff
@@ -20,6 +20,8 @@
         </div>
         <div class="widget">
           <p><?= $this->trans('MSC.twoFactorTextCode') ?></p>
+          <?php $this->addCspHash('style-src', 'word-break:break-all'); ?>
+          <?php $this->addCspSource('style-src', 'unsafe-hashes'); ?>
```
Comment (Toflar) [inline core-bundle/contao/templates/modules/mod_two_factor.html5:24]: Can't we automate this? It's always needed when adding a hash for inline styles, isn't it?

Comment (fritzmg) [reply core-bundle/contao/templates/modules/mod_two_factor.html5:24]: Only for inline style _attributes_, not for inline style _elements_.

Comment (fritzmg) [reply core-bundle/contao/templates/modules/mod_two_factor.html5:24]: To elaborate on this here as well - see https://content-security-policy.com/examples/allow-inline-style/

> CSP Level 3 (newest browsers) support a source list value: [`unsafe-hashes`](https://content-security-policy.com/unsafe-hashes/) which can be used to allow inline style attributes on HTML tags.

The `unsafe-hashes` source is only required for `style="…"` HTML attributes, not for `<style>` tags. Since I think we should not automatically allow any directive sources that are not necessary in general, I think we should not add `unsafe-hashes` automatically either when using `addHash`/`add_csp_hash`.

File: core-bundle/src/Twig/Runtime/CspRuntime.php [hunk 3]
```diff
@@ -51,4 +51,17 @@ public function addSource(string $directive, string $source): void
         $csp = $responseContext->get(CspHandler::class);
         $csp->addSource($directive, $source);
     }
+
+    public function addHash(string $directive, string $source, string $algorithm = 'sha384'): void
```
Comment (leofeyer) [inline core-bundle/src/Twig/Runtime/CspRuntime.php:55]: Is it really necessary to use `sha384` here? A faster algorithm would probably suffice and would be, well, faster. 😄

Comment (leofeyer) [reply core-bundle/src/Twig/Runtime/CspRuntime.php:55]: I‘m going to create separate issue for that.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.
