### PR TITLE
Fix the Choices.js quirks by isolating it in a shadow root

### LINKED ISSUE #8248: Choices.js error when navigating back/forward
### Affected version(s)

5.5.x

### Description

Currently the following error can happen in the back end:

```
Uncaught TypeError: this.containerOuter is undefined
    _removeEventListeners choices.min.js:4524
    destroy choices.min.js:3511
    _removeChoices choices-controller.js:72
    beforeCache choices-controller.js:64
    <anonymous> backend.js:81
    <anonymous> backend.js:79
    dispatch turbo.es2017-esm.js:350
    notifyApplicationBeforeCachingSnapshot turbo.es2017-esm.js:6060
    viewWillCacheSnapshot turbo.es2017-esm.js:5987
    cacheSnapshot turbo.es2017-esm.js:5552
    cacheSnapshot turbo.es2017-esm.js:4152
    node_modules backend.js:11776
    render turbo.es2017-esm.js:4163
    loadCachedSnapshot turbo.es2017-esm.js:3998
    visitStarted turbo.es2017-esm.js:4203
    start turbo.es2017-esm.js:3868
    startVisit turbo.es2017-esm.js:4749
    historyPoppedToLocationWithRestorationIdentifierAndDirection turbo.es2017-esm.js:5856
    onPopState turbo.es2017-esm.js:4528
    start turbo.es2017-esm.js:4454
    start turbo.es2017-esm.js:5715
    start turbo.es2017-esm.js:6182
    node_modules backend.js:14953
```

The Choices.js selects will not work properly anymore after that. The issue can be reproduced in the following way consistently:

1. Go to _Articles_.
2. Edit an article (its settings).
3. Click _Back_ in your browser.
4. Click _Forward_ in your browser.
5. Click _Back_ in your browser.
6. Click _Forward_ in your browser.

_Note:_ JavaScript stack trace is based on #8244 and the un-minified `choices.js`.

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #8248

### Overview
We had numerous attempts at integrating Choices with our mutation observer based handling of components (#7901, #8075, #8203, …). The main issue is, that Choices wraps/unwraps the underlying select element by removing and readding  it to the DOM, which is again triggering mutations. On top there are some global event-listeners. This all screams "race condition". 

This PR therefore goes down a completely different route. The strategy basically looks like this:
* On `connect`, create a sibling div element (the _host_) and hide the original element (add `.hidden` class)
* Create a separate DOM (shadow root) with a clone of the original select element inside the host and initialize Choices on that element
* When there are changes  (`change` event on Choices-owned select), update the original element.
* On `disconnect`/`beforeCache`, remove the host and show the original element again (remove `.hidden` class)

Now, no unwanted mutations occur anymore. In fact, the potentially hundreds of added Choices DOM nodes are also not part of the original DOM which should also make queries etc. on parent elements cheaper.

### Implementation details
Choices was a contao-component, now we install it as a npm package (88a718cefc658bb59076bfe663ce7d28e8e89f88). We therefore do not load the respective css/js files in `be_main` anymore.

Due to isolation, the shadow DOM styles cannot target classes on the parent (custom properties such as our color presets penetrate the boundary, though). There is the `:host` selector, however, that targets the host element. In order to allow styling depending on the current color scheme, I moved the color scheme controller to the `html` element and made a small change, so that you now can have multiple outlet targets where the classes are applied (d7f298ee3eb26746f913d958270b3e247d6a60ad). The host elements are now such targets.

Because global styles do not penetrate the boundary, we are only applying them to the shadow roots themselves. With webpack that can be done quite nicely: We use an annotated import to get the loader output and then create a `CssStyleSheet` object from it, that is shared across all controller instances (b076c53668358838e3fd68cb0a427f70f861cb3a).

Speaking of styles… There were the choices default styles, our adjustments from the contao-component and the base styles (`backend.css`) - all of them overwriting each other and sometimes only working with a very specific specificity (say that 3 times in a row). Now that styles are isolated, I moved them in one file (`assets/component/choices.pcss` importing `choices.js/public/assets/styles/choices.css`) and refactored them. Even with a lot of testing, it is very likely that I broke something while doing so. So please have a close look at this when reviewing.

### `contao--choices:create` event
Because the controller is now basically rewritten, I also added an event that lets you alter the config before the Choices instance is created. If we want to go with this one-line-addition, this PR will also supersede #8115 and #8154.

Usage:
```js
selectElement.addEventLister('contao--choices:init', (event) => {
    const config = event.details.config;
    config.foo = bar; // alter config

    // If you need to target the select node, the Choices
    // instance is created on, use `event.details.select`.
});
```

### CODE REVIEW

File: core-bundle/assets/controllers/choices-controller.js [hunk 1]
```diff
@@ -1,21 +1,27 @@
 import { Controller } from '@hotwired/stimulus';
+import Choices from 'choices.js';
+import css from '!!css-loader?{"url": false}!../styles/component/choices.pcss';
```
Comment (m-vo) [inline core-bundle/assets/controllers/choices-controller.js]: Side note: If we would fix the paths in our legacy css files to being file-relative, we could omit the `?{…}` notation here as well as the respective config in our `webpack.config.js`.

Comment (m-vo) [reply core-bundle/assets/controllers/choices-controller.js]: :thinking: In fact we can omit this here anyways, because I'm not importing the default backend styles, anymore. Adjusted in bd8097567b0aa6f28876687e28d4fc7c6f7b6f35.

Comment (zoglo) [reply core-bundle/assets/controllers/choices-controller.js]: > Side note: If we would fix the paths in our legacy css files to being file-relative, we could omit the ?{…} notation here as well as the respective config in our webpack.config.js.

IIRC right now, it is still needed due to the `system/themes/flexible` path, should we leave a note there?

Comment (m-vo) [reply core-bundle/assets/controllers/choices-controller.js]: At least here, the config is not needed. So let's do this in a separate issue/PR.

File: core-bundle/contao/themes/flexible/styles/main.css [hunk 2]
```diff
@@ -646,6 +646,7 @@ h2.sub_headline {
 
 .tl_filter > * {
 	margin: 0;
+	width: 100%;
```
Comment (leofeyer) [inline core-bundle/contao/themes/flexible/styles/main.css:651]: What does this do?

Comment (m-vo) [reply core-bundle/contao/themes/flexible/styles/main.css:651]: It makes sure the elements are displayed full width on smaller viewports. It's needed now that the child element (the host `div`) has not explicitly set `width: 100%` anymore.

File: core-bundle/contao/themes/flexible/styles/basic.css [hunk 3]
```diff
@@ -69,6 +69,9 @@
 	--serp-preview-title: #1a0dab;
 	--nested-bg: #fbfbfd;
 	--search-field-bg: rgba(255, 255, 255, .2);
+	--choices-highlighted: #3997fe;
+	--choices-bg: #eee;
+	--choices-border: #bbb;
```
Comment (leofeyer) [inline core-bundle/contao/themes/flexible/styles/basic.css]: I would prefer to have this in the .pcss file so there are no potential remnants if we remove Choices in the future. WDYT?

Comment (m-vo) [reply core-bundle/contao/themes/flexible/styles/basic.css]: Or should we maybe use generic names in the `basic.css` and reference/rename them in the `.pcss` file? So that all color definitions are still at one place.

**Comment by leofeyer** [comment]
As discussed in the call, we also want to include the changes from #8154 in this PR.

File: core-bundle/contao/themes/flexible/styles/basic.css (hunk 3 above)
Comment (m-vo) [reply core-bundle/contao/themes/flexible/styles/basic.css]: See [f810e21](https://github.com/contao/contao/pull/8261/commits/f810e21b238d8079cc7abf36f2d2d864d0bad0e1)

**Comment by m-vo** [comment]
> As discussed in the call, we also want to include the changes from #8154 in this PR.

See 798f69a3934d1b7d01e20c7d1ee93cf786cb1311

File: core-bundle/assets/styles/component/choices.pcss [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+    vertical-align: middle;
+    width: 100%;
+    height: 30px;
+    box-sizing: border-box;
+    border: 1px solid var(--form-border);
+    border-radius: 2px;
+    background: var(--form-bg) url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjNmE2YTZjIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIHN0cm9rZS13aWR0aD0iMS41IiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGQ9Im02IDkgNiA2IDYtNiIvPjwvc3ZnPgo=") right -16px top 3px no-repeat;
+    background-origin: content-box;
+    cursor: pointer;
+    text-align: left;
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss:15]:
```suggestion
    text-align: left;
        margin: 3px 0;

    /* Add the tl_select margin since the styles are applied in a a shadow dom */
    &:last-child {
        margin-bottom: 3px;
    }
```

Just this margin here:
image

File: core-bundle/assets/styles/component/choices.pcss [hunk 5]
```diff
@@ -0,0 +1,200 @@
...
+        &[data-placeholder]:before {
+            content: attr(data-placeholder);
+            display: block;
+            cursor: default;
+            opacity: .7;
+            padding: 3px 6px;
+            font-size: 13px;
+        }
+    }
+
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss]:
```suggestion
```

Moving this down due to selector specificity, see https://github.com/contao/contao/pull/8261#discussion_r2027836768

File: core-bundle/assets/styles/component/choices.pcss [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+    .choices__input {
+        background: transparent;
+        padding: 3px 6px;
+        margin: 0;
+        width: auto;
+    }
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss:51]:
```suggestion
        line-height: 17px;
    }
```

This adds the same input line height as all the other backend fields

File: core-bundle/assets/styles/component/choices.pcss [hunk 7]
```diff
@@ -0,0 +1,200 @@
...
+        font-size: revert;
+    }
+
+    .choices__button {
+        background-image: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjEiIGhlaWdodD0iMjEiIHZpZXdCb3g9IjAgMCAyMSAyMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSIjMjIyIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0yLjU5Mi4wNDRsMTguMzY0IDE4LjM2NC0yLjU0OCAyLjU0OEwuMDQ0IDIuNTkyeiIvPjxwYXRoIGQ9Ik0wIDE4LjM2NEwxOC4zNjQgMGwyLjU0OCAyLjU0OEwyLjU0OCAyMC45MTJ6Ii8+PC9nPjwvc3ZnPg==");
+        padding-bottom: 2px;
+        border-left-color: var(--select-border) !important;
+    }
+
+    .choices__list--dropdown, choices__list[aria-expanded] {
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss]:
```suggestion
    .choices__list--dropdown, .choices__list[aria-expanded] {
```

Forgot the class :D

File: core-bundle/assets/styles/component/choices.pcss [hunk 8]
```diff
@@ -0,0 +1,200 @@
...
+                color: #fff;
+            }
+        }
+
+        &.is-open {
+            border: 1px solid var(--form-border, #aaa);
+            z-index: 3;
+        }
+    }
+
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss]:
```suggestion
    }

    .is-open {
        .choices__list--dropdown, .choices__list[aria-expanded] {
            border: 1px solid var(--form-border, #aaa);
            z-index: 3;
        }
    }
```
The `is-open` class is on the outer element

File: core-bundle/assets/styles/component/choices.pcss [hunk 9]
```diff
@@ -0,0 +1,200 @@
...
+                    padding: 0 6px 0 22px;
+                }
+            }
+        }
+
+        .choices__input {
+            height: auto;
+            padding: 3px 6px;
+            border-bottom: 1px solid var(--form-border, #aaa);
+        }
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss:157]:
```suggestion
            background: transparent;
        }
```

The background needs to be reset for dark-mode, we did that in the reset for the contao-component as well

File: core-bundle/assets/styles/component/choices.pcss [hunk 10]
```diff
@@ -0,0 +1,200 @@
...
+            line-height: 16px;
+            padding: 2px 6px 2px 6px;
+            margin: 3px 0 3px 3px;
+            position: relative;
+            top: 0;
+            word-break: revert;
+            vertical-align: baseline;
+            font-weight: inherit;
+        }
+    }
```
Comment (zoglo) [inline core-bundle/assets/styles/component/choices.pcss:189]:
```suggestion
    }
    
    .choices__list {
        &:has(> .choices__group) > .choices__item {
            padding-left: 20px;
        }

        &[data-placeholder]:before {
            content: attr(data-placeholder);
            display: block;
            cursor: default;
            opacity: .7;
            padding: 3px 6px;
            font-size: 13px;
        }
    }
```

As explained above, this CSS is just moved to make sure to keep the previous specificity:

this PR:
image

previous:
image

**Review by zoglo — CHANGES_REQUESTED** [review]
The JS part for this PR works flawlessly ❤️ 
The CSS part still needs more adjustments, more in the requested changes.

There's still the CSS in tl_filter > tl_select that has to be changed, however that would need the choices-container to get the `tl_select` class and reset a lot of other stuff, e.g. here:

Before:

image

image


After:
image


___

Meaning we would most likely need to add the tl_select class within the choices-controller but also another one to reset the styles so we don't have something like this:

image

File: core-bundle/assets/styles/component/choices.pcss (hunk 10 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss:189]: Cannot confirm this. This must have maybe happened due to one of your changes?

File: core-bundle/assets/styles/component/choices.pcss (hunk 4 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss:15]: See f907a1d5280c85c044cfb02e2bb1808e613700fa

File: core-bundle/assets/styles/component/choices.pcss (hunk 6 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss:51]: See f367ac80bdd3d8d091bed72a10a47c542b3cbe65

File: core-bundle/assets/styles/component/choices.pcss (hunk 7 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss]: See 392cded7fb3c9f8987980031f97aa3d850f3057a

File: core-bundle/assets/styles/component/choices.pcss (hunk 10 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss:189]: A lol, its due to the fixed class name. Addressed in 9adfc31cfef0b9117c354b2f1c94fe39af9e1cb1

File: core-bundle/assets/styles/component/choices.pcss (hunk 9 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss:157]: See 9adfc31cfef0b9117c354b2f1c94fe39af9e1cb1

File: core-bundle/assets/styles/component/choices.pcss (hunk 8 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss]: Right. I don't think we need to set the border at all. I moved it up to where we fix the z-index for the focused state. IMO these can just be both set at 4 (correct me if I'm wrong).

See 087b59b91ae83fdeec79dc4714b07a6565a7c032

File: core-bundle/assets/styles/component/choices.pcss (hunk 5 above)
Comment (m-vo) [reply core-bundle/assets/styles/component/choices.pcss]: See https://github.com/contao/contao/pull/8261#discussion_r2028469631

**Comment by m-vo** [comment]
> There's still the CSS in tl_filter > tl_select that has to be changed, however that would need the choices-container to get the `tl_select` class and reset a lot of other stuff, e.g. here:

IMHO this can simply be fixed by switching to `.tl_search > :not(span, strong) {…}`.  
See d0fef2b41bb5ec364113e5f6d03e5e8941c46ddc.

**Comment by zoglo** [comment]
> IMHO this can simply be fixed by switching to `.tl_search > :not(span, strong) {…}`. See [d0fef2b](https://github.com/contao/contao/commit/d0fef2b41bb5ec364113e5f6d03e5e8941c46ddc).

Depending on how users were adapting this and adding new fields, this might break their layouts so I am unsure about it. Would adding a class for the new element + adding the styling not make it less prone to errors? Wdyt?

**Comment by m-vo** [comment]
> Depending on how users were adapting this and adding new fields, this might break their layouts so I am unsure about it. Would adding a class for the new element + adding the styling not make it less prone to errors? Wdyt?

We can also include all hosts, but I would rather do it the other way round and exclude any descriptions/labels. If targeting `span` and `strong` is too loose, we could give them a class. But IMHO overkill.

**Comment by m-vo** [comment]
@zoglo You requested changes - is there anything left we need to address?

**Comment by zoglo** [comment]
> @zoglo You requested changes - is there anything left we need to address?

The first quirk is the width that has been removed and will change the widths of options accordingly to the selected option within tl_filter.

- Readding the widths would fix this

The other one is somethint about the shadow-dom taking 32px height as briefly discussed on slack, something that causes a slight layout shift of 1px when focusing the select.

- Adding the same height as inputs to the container containing the shadow-root will fix this as well

Maybe the screencast shows it better :) (between demo and the current PR)

https://github.com/user-attachments/assets/8aed8c9e-220a-44ca-9ac3-811bba9dd26c

**Comment by zoglo** [comment]
@m-vo as discussed on Slack, I did make sure that the CSS does not change the layouting.

4df465b95ce7c008ae248be02654888bee6446ed ensures that the existing widths are preserved for `.tl_limit`, `.tl_sorting` and `.tl_subpanel`.

4ff6c23dfa4aaf4f0ff550d4d627d2828bccfa73 fixes a forgotten font-size for choices options

d1666095088470fd9b7ab986532d6d9797894669 is a bit trickier... I did remove the margin within the shadow DOM but only retain it for a specific case where the instance is not part of the subpanels or filters and where it's not an initialized choices within the shadow dom (Hence the comment).

**Review by zoglo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

File: core-bundle/assets/controllers/choices-controller.js [hunk 11]
```diff
@@ -1,21 +1,29 @@
 import { Controller } from '@hotwired/stimulus';
+import Choices from 'choices.js';
+import css from '!!css-loader!../styles/component/choices.pcss';
```
Comment (leofeyer) [inline core-bundle/assets/controllers/choices-controller.js:3]: Why don't we load the style sheet in the `backend.pcss` file where we load all other component style sheets?

```pcss
@import "component/color-picker.pcss";
@import "component/tabs.pcss";
@import "template-studio/layout.pcss";
@import "backend-search/layout.pcss";
```

Comment (zoglo) [reply core-bundle/assets/controllers/choices-controller.js:3]: We only ever apply those specific styles to the `shadow-root` in that case:
https://github.com/m-vo/contao/blob/7736f81a9b4fa96dfcc95ed530a0b9cea589f904/core-bundle/assets/controllers/choices-controller.js#L16

(basically the backend.pcss is never loaded in the `shadow dom`)

And (description)
> Choices was a contao-component, now we install it as a npm package (https://github.com/contao/contao/commit/88a718cefc658bb59076bfe663ce7d28e8e89f88). We therefore do not load the respective css/js files in be_main anymore.

Comment (leofeyer) [reply core-bundle/assets/controllers/choices-controller.js:3]: > We only ever apply those specific styles to the shadow-root in that case

That is probably why 👍 

> Choices was a contao-component, now we install it as a npm package (https://github.com/contao/contao/commit/88a718cefc658bb59076bfe663ce7d28e8e89f88). We therefore do not load the respective css/js files in be_main anymore.

I think that refers to something else.

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Comment by zoglo** [comment]
I reopened #8248 so we don't forget that this PR has been reverted in 18e970d6656fac2a158d74d8cc5eb22d7712b403 due to a race condition within the `onSubmitCallback` on the selects.

It's a race condition where the `Backend.autoSubmit` registered on the native `select` would fire the values earlier than the select being updated (Unsure right now what triggers the onchange because the value change should have done that)
