### PR TITLE
Set `globals $objPage` when building the layout template

### LINKED ISSUE #9369: Navigation Module causes exception in Twig frontend layout
### Affected version(s)

5.7

### Description

Looks like there is no `global $objPage` in the new Twig layout/content composition builder.

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #9369

### CODE REVIEW

File: core-bundle/src/ContentComposition/ContentCompositionBuilder.php [hunk 1]
```diff
@@ -261,6 +261,10 @@ private function setupFramework(PageModel $page): void
             $this->pictureFactory->setDefaultDensities($this->defaultImageDensities);
             $this->previewFactory->setDefaultDensities($this->defaultImageDensities);
         }
+
+        // Backwards compatibility: make global $objPage available
+        global $objPage;
```
Comment (Toflar) [inline core-bundle/src/ContentComposition/ContentCompositionBuilder.php]: Should we use `$GLOBALS['objPage']` like for the admin email?

Comment (m-vo) [reply core-bundle/src/ContentComposition/ContentCompositionBuilder.php]: Ah yes, of course. See 7661a7e7f9d5feefa087d732d37f27e2d49b6e79.

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/tests/ContentComposition/ContentCompositionBuilderTest.php [hunk 2]
```diff
@@ -136,6 +137,8 @@ public function testSetsUpFrameworkAndAddsDefaultDataToTemplate(): void
             translator: $translator,
         );
 
+        $this->assertNull($GLOBALS['objPage'], 'global $objPage is not set beforehand');
```
Comment (ausi) [inline core-bundle/tests/ContentComposition/ContentCompositionBuilderTest.php]:
```suggestion
        $this->assertNull($GLOBALS['objPage'] ?? null, 'global $objPage is not set beforehand');
```

Comment (m-vo) [reply core-bundle/tests/ContentComposition/ContentCompositionBuilderTest.php]: Made the change, although its already `null` there.

**Review by ausi — DISMISSED** [review]

**Review by ausi — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]
