### PR TITLE
Always show the 404 page

### LINKED ISSUE #4821: Custom 404 page is not shown for regular Symfony controllers
### Affected version(s)

4.13, probably 4.9

### Description

If a Symfony controller throws a `NotFoundHttpException` as we do for example in https://github.com/contao/contao/blob/29856d68eb3fc12db9e20dd43b54e5df716e8005/core-bundle/src/Controller/ImagesController.php#L53 the custom 404 page from the site structure is not shown, instead the default 404 page is sent to the user.

This can be reproduced easily:
- https://contao.org/assets/images/foo default 404 page
- https://contao.org/assets/image/foo correct 404 page

The reason for that is, that the pretty error screen listener requires a `pageModel` attribute on the request to be present in order to determine the correct root page from which the 404 page should get shown: https://github.com/contao/contao/blob/29856d68eb3fc12db9e20dd43b54e5df716e8005/core-bundle/src/EventListener/PrettyErrorScreenListener.php#L149

I think the correct solution would be, if the `pageModel` is not set on the current route, to get the root page from the routing by providing the hostname and accept-language header of the request.

A possibly related problem is, that many places in Contao get information from the `$GLOBALS['objPage']` for which some of it is only set in `PageRegular` like the theme folder from which to load templates from: https://github.com/contao/contao/blob/f536cf98b55fbaf9ff481b0ff96f7228a2542321/core-bundle/src/Resources/contao/pages/PageRegular.php#L96

So maybe there should be a way to tell the system to _“run in the context of page or root page X“_?

### PR DESCRIPTION
**Pull request by aschempp**
Fixes #4821

we might discuss what features the `PageFinder` should provide.

### CODE REVIEW

File: core-bundle/src/Routing/PageFinder.php [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+        $pageModel = $request->attributes->get('pageModel');
+
+        if (!$pageModel instanceof PageModel) {
+            return $this->findRootPageByHost($request->getHost(), $request->isSecure(), $request->headers->get('Accept-Language'));
+        }
+
+        return $this->framework->getAdapter(PageModel::class)->findPublishedById($pageModel->loadDetails()->rootId);
+    }
+
+    public function findFirstPageTypeByRequestHost(Request $request, string $type): ?PageModel
```
Comment (ausi) [inline core-bundle/src/Routing/PageFinder.php]:
```suggestion
    public function findFirstPageByTypeRequestHost(Request $request, string $type): ?PageModel
```
“find first page type by…” seems confusing to me :)

**Comment by leofeyer** [comment]
As discussed in the Contao call, the `PageFinder` should also be used to find the fallback pages in the sitemap controller, the robots.txt controller etc. We do not need to make it `@experimental`.

**Comment by aschempp** [comment]
I have updated the implementation. Here are two design-decisions I would like your feedback on @contao/developers 

1. `RobotsTxtController` and `FaviconController` only need the fallback root page for the current host, so they now use `PageFinder` to match the fallback root. `SitemapController` however requires all root pages of the current domain. To be consistent (and after discussing with @Toflar) I decided to go the same way: match the fallback root page for the current domain, and then search the DB for all root pages with the given DNS.

2. The existing controllers previously returned an empty response with status 404 if no root page was found or e.g. the favicon was not configured. I now changed this to throwing a `NotFoundHttpException`, since the whole point of this PR is to render the Contao `error_404` page in such cases.

**Comment by ausi** [comment]
> Here are two design-decisions I would like your feedback on

Agree with both decisions 👍

**Comment by Toflar** [comment]
Same here, in case that wasn't clear from @aschempp's comment.

File: core-bundle/src/EventListener/RobotsTxtListener.php [hunk 2]
```diff
@@ -62,14 +62,7 @@ public function __invoke(RobotsTxtEvent $event): void
...
 
-        $pageModel = $this->contaoFramework->getAdapter(PageModel::class);
-
-        // Only fetch the fallback page because there can only be one sitemap per host
-        $rootPage = $pageModel->findPublishedFallbackByHostname($event->getRootPage()->dns);
-
-        if (null === $rootPage) {
-            return;
-        }
+        $rootPage = $event->getRootPage();
```
Comment (ausi) [inline core-bundle/src/EventListener/RobotsTxtListener.php:59]: Do I understand it correctly, that the deleted code is (and already was) superfluous?

File: core-bundle/src/Routing/PageFinder.php [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+        return $this->matchRootPageForRequest($request);
+    }
+
+    /**
+     * Finds all root pages matching the given host name. It will first look for a matching
+     * root page through routing and then find all root pages with the same tl_page.dns value.
+     *
+     * @return array<PageModel>
+     */
+    public function findAllRootPagesForHost(string $hostname): array
```
Comment (ausi) [inline core-bundle/src/Routing/PageFinder.php]:
```suggestion
    public function findRootPagesForHost(string $hostname): array
```
I think the word “all” is not needed here, and may be confusing because you only get published ones, not all.

File: core-bundle/src/Routing/PageFinder.php [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+
+    /**
+     * Finds all root pages matching the host of the given request. It will first look for a matching
+     * root page through routing and then find all root pages with the same tl_page.dns value.
+     *
+     * @return array<PageModel>
+     */
+    public function findAllRootPagesForRequest(Request $request): array
+    {
+        return $this->findAllRootPagesForHost($request->getHost());
```
Comment (ausi) [inline core-bundle/src/Routing/PageFinder.php]:
```suggestion
    public function findRootPagesForRequest(Request $request): array
    {
        return $this->findRootPagesForHost($request->getHost());
```
Same here

File: core-bundle/src/EventListener/RobotsTxtListener.php (hunk 2 above)
Comment (aschempp) [reply core-bundle/src/EventListener/RobotsTxtListener.php:59]: yes exactly. I noticed this while reworking the controller.

**Comment by aschempp** [comment]
I have found a new issue regarding this implementation. Any route that does not have a Contao `frontend` or `backend` scope will not have a firewall (by default). This applies to the image request for example. Not having a firewall means checking for permissions (`Security::isGranted()`) will throw an exception by default in Contao 4. Unfortunately, rendering a 404 page will likely throw such an exception, because a lot of front end modules (e.g. the navigation) will check for user permissions.

There are two possible solution, of which I would prefer the first one:
 1. only implement this change for Contao 5(.2). Would also have the advantage of not adding a new `PageFinder` class in a patch release of Contao 4.13. Since Contao 5 uses Symfony Security 6, a "default firewall" (`NullToken`) is always present.
 2. Patch Symfony security to not throw an exception on Contao 4, basically by faking behaviour of Symfony Security 6 (`NullToken`) but not fully enable the new authentication manager system. Not sure this is really possible or what other side effects that would have on the system 😕

**Comment by Toflar** [comment]
I guess introducing this as a new feature is the safer way then. We cannot afford to fiddle around with security in a patch release of the current (and thus most widely adopted and used) LTS version.

File: core-bundle/src/Routing/PageFinder.php (hunk 3 above)
Comment (Toflar) [reply core-bundle/src/Routing/PageFinder.php]: @aschempp this is unresolved so the review makes no sense.

File: core-bundle/src/Routing/Enhancer/InputEnhancer.php [hunk 5]
```diff
@@ -37,6 +38,12 @@ public function enhance(array $defaults, Request $request): array
             return $defaults;
         }
 
+        $mainRequest = $this->requestStack->getMainRequest();
```
Comment (Toflar) [inline core-bundle/src/Routing/Enhancer/InputEnhancer.php]: Can you explain this change? What's this doing? (comment in code would make sense then maybe)

Comment (aschempp) [reply core-bundle/src/Routing/Enhancer/InputEnhancer.php]: The goal is to not set input parameters for additional route matching. But I'm not sure this fix is entirely correct, we might need to discuss this problem 😕

Comment (aschempp) [reply core-bundle/src/Routing/Enhancer/InputEnhancer.php]: As discussed at the Contao Call on May 4th, we agreed only the main request should modify Input parameters. I added a comment in 684858bf9e164235821571cd0e0a34c13b024c1e

File: core-bundle/src/Routing/PageFinder.php (hunk 3 above)
Comment (aschempp) [reply core-bundle/src/Routing/PageFinder.php]: changed in 1e2f600e0a4df54a41b195f4a2ed436df394182f

File: core-bundle/src/Routing/PageFinder.php (hunk 4 above)
Comment (aschempp) [reply core-bundle/src/Routing/PageFinder.php]: changed in 1e2f600e0a4df54a41b195f4a2ed436df394182f

File: core-bundle/src/Routing/PageFinder.php [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+        $rootPages = $this->framework->getAdapter(PageModel::class)->findPublishedRootPages(['dns' => $pageModel->dns]);
+
+        /** @var array<PageModel> */
+        return $rootPages ? $rootPages->getModels() : [];
+    }
+
+    /**
+     * Finds the first sub-page of a given page for a request host and Accept-Language.
+     * This is mainly useful to retrieve an error page for the current host,
+     * or any other page type that only exists once per root page.
```
Comment (ausi) [inline core-bundle/src/Routing/PageFinder.php]:
```suggestion
     * Finds the first sub-page of a given type for a request host and Accept-Language.
     * This is mainly useful to retrieve an error page for the current host,
     * or any other page type that only exists once per root page.
```
typo?

**Review by ausi — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.
