### PR TITLE
Fix the priority of the web worker and improve memory handling

### LINKED ISSUE #7310: The dump() function is no longer displayed in the Symfony debug bar
### Affected version(s)

5.3.10

### Description

The dump() function is no longer displayed in the Symfony debug bar in 5.3.10.
It works in 5.3.9. 
I was also able to reproduce it in the demo installation.

Thanks for checking.

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/contao/issues/7310

### CODE REVIEW

File: core-bundle/src/Messenger/WebWorker.php [hunk 1]
```diff
@@ -115,11 +115,21 @@ private function processTransport(string $transportName): void
 
         $this->webWorkerRunning = true;
 
-        $input = new ArrayInput([
+        $inputParameters = [
             'receivers' => [$transportName],
             '--time-limit' => 30,
             '--sleep' => 0,
-        ]);
+            '--no-reset' => true, // Do not reset the container between every message (otherwise web profiler profiles etc. would all be gone)
```
Comment (ausi) [inline core-bundle/src/Messenger/WebWorker.php]: I’d prefer to keep the reset and instead move the prio of the terminate listener below `-1024`

**Review by ausi — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.
