### PR TITLE
Show a warning if ALTCHA is used with an insecure connection

### LINKED ISSUE #7369: ALTCHA captcha not working in unsafe environments within chromium based browsers
### Affected version(s)

5.4.0-RC1

### Description

The newly introduced ALTCHA captcha uses parts of the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) / https://www.chromium.org/blink/webcrypto/ that do not work within unsafe origins (e.g. `http://`)

Here is a list of safe origins:
| [Safe origins](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/security/faq.md#which-origins-are-secure) |
| -- |
| (https, *, *) |
| (wss, *, *) |
| (*, localhost, *) |
| (*, 127/8, *) |
| (*, ::1/128, *) |
| (file, *, —) |
| (chrome-extension, *, —) |

More information here as well:
https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

### Proposal

This could be considered as a known limitation within LIMITATIONS.md

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #7369

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/contao/forms/FormAltcha.php [hunk 1]
```diff
@@ -73,6 +73,8 @@ public function parse($arrAttributes = null): string
 			return $objTemplate->parse();
 		}
 
+		$this->isSecure = $request->isSecure();
```
Comment (ausi) [inline core-bundle/contao/forms/FormAltcha.php]: Should we check for `127.0.0.1`, `localhost` and `*.localhost` here too? Otherwise many local dev setups would not be able to test the captcha even though it would technically work on localhost.

Comment (leofeyer) [reply core-bundle/contao/forms/FormAltcha.php]: <del>Changed in 96cdebdff6935558780661e8ff4ee60af07c384c. I‘ve also added `::1`.</del>

**EDIT**: See 2c931f66d9f8073175f0c03ddf66226a7d86e110 for the correct implementation.

Comment (fritzmg) [reply core-bundle/contao/forms/FormAltcha.php]: The IP does not matter, only the domains `localhost` and `*.localhost` are supported, are they not? i.e.

```php
$this->canUseAltcha = $request->isSecure() || preg_match('/^(.+\.)?localhost$/', $request->getHost());
```

Comment (Toflar) [reply core-bundle/contao/forms/FormAltcha.php]: Best would be probably to use JS to detect anyway (in case other constraints are added/removed in the future). But that's probably a bit more work.

Comment (leofeyer) [reply core-bundle/contao/forms/FormAltcha.php]: No, `http://127.0.0.1:8000` is also supported and considered secure context.

**Review by ausi — APPROVED** [review]
