### PR TITLE
Restore backwards compatiblilty for DB Statement

### LINKED ISSUE #3642: Prepared statement fails in Contao\Versions
```An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens```

After pulling in 3cadec7dfd444eefced20da70d5ca21408b3ec82 I get the error message mentioned above after logging into the backend. It originates in the Versions class, when counting versions:

https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/classes/Versions.php#L655-L656

I logged in as Admin, hence the ` AND userid=?` part was not added to the prepared statement. The user id however is always passed to `execute()`.

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3642

### CODE REVIEW

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php [hunk 1]
```diff
@@ -284,18 +284,19 @@ static function ($varParam)
 		{
 			$this->statement = $this->resConnection->executeQuery($this->strQuery, $arrParams);
 		}
-		catch (DriverException $exception)
+		catch (DriverException|\ArgumentCountError $exception)
 		{
-			if ($arrParams !== array(null))
+			if (!$arrParams || \count($arrParams) <= ($intTokenCount = $this->countQueryTokens()))
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: How about moving this logic into the `countQueryTokens()` method as well and renaming it to `isTokenCountMismatch()` or something else? Then we could simplify this condition:

```suggestion
			if ($this->isTokenCountMismatch($arrParams))
```

File: core-bundle/src/Resources/contao/library/Contao/Model.php [hunk 2]
```diff
@@ -750,6 +750,13 @@ public function preventSaving($blnKeepClone=true)
 	 */
 	public static function findByPk($varValue, array $arrOptions=array())
 	{
+		if ($varValue === null)
+		{
+			trigger_deprecation('contao/core-bundle', '4.13', 'Using "%s::findByPk(null)" has been deprecated and will no longer work in Contao 5.0.', __CLASS__);
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Model.php]: Not sure if this is good. What if I want to pass `null` as argument to e.g. get `SELECT * FROM table WHERE field=null`?

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php (hunk 1 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: Not possible because `$intTokenCount` is reused in the code below.

File: core-bundle/src/Resources/contao/library/Contao/Model.php (hunk 2 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: That’s why I only added it for `findByPk`, AFAIK we don’t support nullable primary key columns.

Comment (m-vo) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: IMHO nullable primary keys never make sense as it's semantically the same as deleting the row. :smile:

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php [hunk 3]
```diff
@@ -308,6 +309,15 @@ static function ($varParam)
 		return new Result($this->statement, $this->strQuery);
 	}
 
+	/**
+	 * @return int
+	 */
+	private function countQueryTokens()
+	{
+		// Backwards compatibility
```
Comment (leofeyer) [inline core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: How is this a BC layer?

File: core-bundle/src/Resources/contao/library/Contao/Model.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: But we also have `findById()` and `findByIdOrAlias()`. 🙈

File: core-bundle/src/Routing/RouteProvider.php [hunk 4]
```diff
@@ -301,7 +301,7 @@ private function findRootPages(string $httpHost): array
             $rootPages = $pages->getModels();
         }
 
-        $pages = $pageModel->findBy(["tl_page.alias='index' OR tl_page.alias='/'"], null);
+        $pages = $pageModel->findAll(['column' => ["tl_page.alias='index' OR tl_page.alias='/'"]]);
```
Comment (leofeyer) [inline core-bundle/src/Routing/RouteProvider.php]: I like the original syntax more. Can't we preserve this kind of usage?

File: core-bundle/src/Resources/contao/library/Contao/Model.php (hunk 2 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: Yes, but `findByIdOrAlias()` could potentially allow `null` so we cannot disallow that I think.

Calling `findByPk(null)` is most certainly wrong, but for all other columns we cannot assume that.

File: core-bundle/src/Routing/RouteProvider.php (hunk 4 above)
Comment (ausi) [reply core-bundle/src/Routing/RouteProvider.php]: I don’t think so because `null` can be an actual value that gets used by a `?` in the query.

How about the following?
```suggestion
        $pages = $pageModel->findBy(["tl_page.alias=? OR tl_page.alias=?"], ['index', '/']);
```

Comment (ausi) [reply core-bundle/src/Routing/RouteProvider.php]:
```suggestion
        $pages = $pageModel->findBy(["tl_page.alias='index' OR tl_page.alias='/'"], []);
```
This could also work maybe (need to test :)

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php (hunk 3 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: It counts the tokens the way the old implementation did which is error-prone and only needed for deprecated calls with too many arguments.

File: core-bundle/src/Resources/contao/library/Contao/Model.php (hunk 2 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: Not even for `findById()`? `findByPk()` is actually just an alias for `findById()`.

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php (hunk 3 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: How will we count the tokens in the new implementation?

File: core-bundle/src/Routing/RouteProvider.php (hunk 4 above)
Comment (leofeyer) [reply core-bundle/src/Routing/RouteProvider.php]: The first one is a good compromise. 👍

File: core-bundle/src/Resources/contao/library/Contao/Model.php (hunk 2 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Model.php]: Added deprecation for `findById()` in 325ad84cfa783bbe8f95c006f785da1db02f41b3

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php (hunk 3 above)
Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: We will not. Once the deprecation layer is removed, for a mismatch between the number of tokens and arguments the database will throw an exception.

File: core-bundle/src/Routing/RouteProvider.php (hunk 4 above)
Comment (ausi) [reply core-bundle/src/Routing/RouteProvider.php]: Fixed in 8d303adc813138d747225458a9633c7678d819eb

File: core-bundle/src/Resources/contao/library/Contao/Database/Statement.php (hunk 3 above)
Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: What do you think about https://github.com/ausi/contao-contao/pull/1? I find it more clear this way.

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: Both exceptions handle the same case. One is for pdo, the other for mysqli. So we cannot split them up.

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: But I should probably add a comment that clarifies this.

Comment (ausi) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: Added a comment in e7d12adb8ebdabbc55563001c8e5278bb63ad98f

Comment (leofeyer) [reply core-bundle/src/Resources/contao/library/Contao/Database/Statement.php]: WDYT about https://github.com/ausi/contao-contao/pull/2?

**Review by m-vo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
