### PR TITLE
Fix setting integer properties on models to invalid types

### LINKED ISSUE #9781: Unsupported operand types: string * int at Model.php line 498
### Affected version(s)

5.3.46

### Description

Got this error immediately after updating to Contao v5.3.46:

```
[2026-04-25T11:22:14.716060+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Unsupported operand types: string * int" at Model.php line 498 {"exception":"[object] (TypeError(code: 0): Unsupported operand types: string * int at [...]/www/vendor/contao/core-bundle/contao/library/Contao/Model.php:498)"} {"request_uri":"https://www.example.com/","request_method":"GET"}
[2026-04-25T11:22:14.750599+02:00] messenger.INFO: Stopping worker. {"transport_names":["contao_prio_high"]} {"request_uri":"https://www.example.com/","request_method":"GET"}
[2026-04-25T11:25:23.232323+02:00] request.INFO: Matched route "tl_page.3.root". {"route":"tl_page.3.root","route_parameters":{"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","_format":"html","_canonical_route":"tl_page.3","parameters":"","pageModel":{"Contao\\PageModel":[]},"_route":"tl_page.3.root","_route_object":{"Symfony\\Component\\Routing\\Route":[]}},"request_uri":"https://www.example.com/","method":"GET"} {"request_uri":"https://www.example.com/","request_method":"GET"}
```
PHP version: 8.4.20
Database version: MariaDB 10.11.14

### PR DESCRIPTION
**Pull request by ausi**
Fixes #9781

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

File: core-bundle/tests/Contao/ModelTest.php [hunk 1]
```diff
@@ -122,6 +125,42 @@ public function __construct()
...
 
+    /**
+     * @group legacy
+     *
+     * @dataProvider getDatabaseValues
+     */
+    public function testMagicSetterTypesDeprecation(string $key, mixed $value, mixed $expected): void
+    {
+        if (\PHP_VERSION_ID < 80200) {
+            $this->markTestSkipped('Deprecation messages do not work correctly in PHP 8.1 in this case');
```
Comment (ausi) [inline core-bundle/tests/Contao/ModelTest.php:136]: Is this acceptable? PHP 8.1 has a weird bug with the class name in the deprecation message, see https://github.com/contao/contao/actions/runs/24941944357/job/73037014452?pr=9783

Comment (leofeyer) [reply core-bundle/tests/Contao/ModelTest.php:136]: I guess so. Will this also fix the prefer lowest and reverse order tests?

Comment (ausi) [reply core-bundle/tests/Contao/ModelTest.php:136]: Yes, all green.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.
