### PR TITLE
Adjust the `service_unavailable` namespace for the maintenance mode

### LINKED ISSUE #8194: service_unavailable.html.twig is not defined
### Affected version(s)

5.5.4

### Description

https://github.com/contao/contao/pull/8185 might have created another bug:

I just tried to upgrade my local test installation from Contao 5.5.3 to 5.5.4. The Update with the Contao Manager finishes, but once it is done I cannot recreate the PROD-Cache and it is not possible to activate the Maintenance Mode within the Contao Manager.

In /var/logs/prod-2025-03-12.log there are error messages like this:

`[2025-03-12T20:15:22.593154+01:00] console.CRITICAL: Error thrown while running command ""contao:maintenance" enable --format=json --no-interaction". Message: "Template "@ContaoCore/Error/service_unavailable.html.twig" is not defined."
{"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Template \"@ContaoCore/Error/service_unavailable.html.twig\" is not defined. at C:\\xampp\\htdocs\projectfolder\\vendor\\twig\\twig\\src\\Loader\\ChainLoader.php:111)","command":"\"contao:maintenance\" enable --format=json --no-interaction","message":"Template \"@ContaoCore/Error/service_unavailable.html.twig\" is not defined."} []`

I suspect "dropping the existing templates" in the PR created this bug?

I tried it multipe times (from 5.5.3 backups) with different variations:
1) Removed self-created error-overwrites in Template Studio (so it should be compareable to a "clean" installation), then upgrade to 5.5.4 -> still error
2) Remove all "error" folders and files from my /templates/ folder, then upgrade -> still error
3) Add custom (empty) overwrites for all error template in the Template Studio, then upgrade -> still error

EDIT: I also tried it with a new/"fresh" installation of 5.5.4

Once the installation is done, it is not possible to
- install or upgrade anything with the Contao Manager (because it fails in the step "activate Maintenance Mode")
- rebuild the PROD cache
- manually activate the Maintenance Mode

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #8194

Regression from #8185 that did change the namespaces for the error templates.

/cc @m-vo

### CODE REVIEW

File: manager-bundle/src/Command/MaintenanceModeCommand.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ protected function configure(): void
     {
         $this
             ->addArgument('state', InputArgument::OPTIONAL, 'Use "enable" to enable and "disable" to disable the maintenance mode. If the state is already the desired one, nothing happens. You can also use "on" and "off".')
-            ->addOption('template', 't', InputOption::VALUE_REQUIRED, 'Allows to take a different Twig template name when enabling the maintenance mode.', '@ContaoCore/Error/service_unavailable.html.twig')
```
Comment (m-vo) [inline manager-bundle/src/Command/MaintenanceModeCommand.php]: IMHO we must keep the old namespace there, test for its existence (BC) and only render the new one else. Similar to the changes in the `PrettyErrorScreenListener`. Otherwise an "overwritten" bundle template would not be used anymore.

**Review by m-vo — CHANGES_REQUESTED** [review]

File: manager-bundle/src/Command/MaintenanceModeCommand.php (hunk 1 above)
Comment (zoglo) [reply manager-bundle/src/Command/MaintenanceModeCommand.php]: See 0a5386806c1f23021df503e1c339b3c2a6390985

File: manager-bundle/tests/Command/MaintenanceModeCommandTest.php [hunk 2]
```diff
@@ -207,6 +211,26 @@ public static function enableProvider(): iterable
...
+    private function mockTwigLoader(Environment&MockObject $twig, string $expectedTemplateName): void
+    {
+        $serviceUnavailable = '@ContaoCore/Error/service_unavailable.html.twig';
+
+        if ($expectedTemplateName === $serviceUnavailable) {
+            $loader = $this->createMock(LoaderInterface::class);
+            $loader
+                ->expects($this->once())
+                ->method('exists')
+                ->with('@ContaoCore/Error/service_unavailable.html.twig')
```
Comment (leofeyer) [inline manager-bundle/tests/Command/MaintenanceModeCommandTest.php]:
```suggestion
                ->with($serviceUnavailable)
```

File: manager-bundle/tests/Command/MaintenanceModeCommandTest.php [hunk 3]
```diff
@@ -37,6 +38,9 @@ protected function tearDown(): void
     public function testEnable(string $expectedTemplateName, array $expectedTemplateVars, string|null $customTemplateName = null, string|null $customTemplateVars = null): void
     {
         $twig = $this->mockEnvironment();
+
+        $this->mockTwigLoader($twig, $expectedTemplateName);
```
Comment (leofeyer) [inline manager-bundle/tests/Command/MaintenanceModeCommandTest.php]: Why does this have to be a separate method? It is not used anywhere else.

Comment (zoglo) [reply manager-bundle/tests/Command/MaintenanceModeCommandTest.php]: I originally tested it differently, thus moved it away.

fixed in 82709a53162bee39efef0c6708c42867e632db24

File: manager-bundle/tests/Command/MaintenanceModeCommandTest.php (hunk 2 above)
Comment (zoglo) [reply manager-bundle/tests/Command/MaintenanceModeCommandTest.php]: See https://github.com/contao/contao/pull/8195#discussion_r1992942529 82709a53162bee39efef0c6708c42867e632db24

File: manager-bundle/src/Command/MaintenanceModeCommand.php [hunk 4]
```diff
@@ -77,6 +77,11 @@ protected function execute(InputInterface $input, OutputInterface $output): int
 
     private function enable(string $templateName, string $templateVars): void
     {
+        // Change the error template namespace (see #8195)
+        if (str_starts_with($templateName, '@ContaoCore/Error') && !$this->twig->getLoader()->exists($templateName)) {
+            $templateName = str_replace('@ContaoCore/Error', '@Contao/error', $templateName);
```
Comment (m-vo) [inline manager-bundle/src/Command/MaintenanceModeCommand.php]: Does this need to be dynamic? I would use the hardcoded template name:

```suggestion
        if ($templateName === '@ContaoCore/Error/service_unavailable.html.twig' && !$this->twig->getLoader()->exists($templateName)) {
            $templateName = '@Contao/error/service_unavailable.html.twig';
```

Alternatively, I would at least add a slash:
```suggestion
        if (str_starts_with($templateName, '@ContaoCore/Error/') && !$this->twig->getLoader()->exists($templateName)) {
            $templateName = str_replace('@ContaoCore/Error/', '@Contao/error', $templateName);
```

Comment (zoglo) [reply manager-bundle/src/Command/MaintenanceModeCommand.php]: >Does this need to be dynamic? I would use the hardcoded template name:

Had it like that in the first place in case you would use the maintenance mode template with the --template prefix in your systems since people may have had their own commands built but could revert it. Wdyt would be best here @m-vo ?

Comment (m-vo) [reply manager-bundle/src/Command/MaintenanceModeCommand.php]: If you had specified a custom template using `--template`, this would not have been affected by the changes anyway. You are free to use whatever namespace you like and it should not be altered.

Comment (zoglo) [reply manager-bundle/src/Command/MaintenanceModeCommand.php]: Guessing peoples templates would not have changed so it's 1, yeah.

**Review by m-vo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.
