### PR TITLE
Increase the blob size for `tl_user.session`

### LINKED ISSUE #7295: Change field type for `session` in `tl_user`
### Affected version(s)

4.x | 5.x

### Description

One of our customers is working in a pretty big installation and managed to fill the `session` in `tl_user` which resulted in

```
An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session' at row 1
```

Maybe the field should be changed to a `MEDIUMBLOB` (16MB) instead of `BLOB` (64KB).

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7295

### CODE REVIEW

**Review by ausi — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

File: core-bundle/contao/dca/tl_user.php [hunk 1]
```diff
@@ -351,7 +352,7 @@
 		(
 			'input_field_callback'    => array('tl_user', 'sessionField'),
 			'eval'                    => array('doNotShow'=>true, 'doNotCopy'=>true),
-			'sql'                     => "blob NULL"
+			'sql'                     => array('type' => 'blob', 'length' => MySQLPlatform::LENGTH_LIMIT_MEDIUMBLOB, 'notnull' => false)
```
Comment (leofeyer) [inline core-bundle/contao/dca/tl_user.php:355]: Why not just this?

```suggestion
			'sql'                     => "mediumblob NULL"
```

Comment (fritzmg) [reply core-bundle/contao/dca/tl_user.php:355]: We should always use the array notation. We are already using the array notation in other places as well.

Comment (leofeyer) [reply core-bundle/contao/dca/tl_user.php:355]: Yes, for boolean fields that cannot be configured with simple strings. But certainly not for everything? `mediumblob NULL` is much shorter and easier to understand than `array('type' => 'blob', 'length' => MySQLPlatform::LENGTH_LIMIT_MEDIUMBLOB, 'notnull' => false)`, don't you think?

Comment (fritzmg) [reply core-bundle/contao/dca/tl_user.php:355]: > Yes, for boolean fields that cannot be configured with simple strings.

Why can they not configured with simple strings? Instead of writing `['type' => 'boolean', 'default' => false]` you can also write `'tinyint DEFAULT 0'`.

> mediumblob NULL is much shorter and easier to understand than array('type' => 'blob', 'length' => MySQLPlatform::LENGTH_LIMIT_MEDIUMBLOB, 'notnull' => false), don't you think?

The array notation is more descriptive and can be parsed more easily. Plus you can then rely on DBAL to create the correct notation for your platform.

Comment (leofeyer) [reply core-bundle/contao/dca/tl_user.php:355]: > Instead of writing `['type' => 'boolean', 'default' => false]` you can also write `'tinyint DEFAULT 0'`.

Yes, but then our parser (or maybe their parser?) does not handle the field correctly anymore, which is why we have to use the array notation for boolean fields.

Comment (fritzmg) [reply core-bundle/contao/dca/tl_user.php:355]: > Yes, but then our parser (or maybe their parser?) does not handle the field correctly anymore, which is why we have to use the array notation for boolean fields.

I cannot confirm that. Using `tinyint DEFAULT 0` works just as well.

In my original PR introducing the boolean fields I used the array notation for the same reasons I outlined here and consider it best practice.

**Comment by leofeyer** [comment]
Thank you @fritzmg.
